# Game-wide strings: title, disclosure, names, stats, actions, items, skills, generic
# rooms/hotspots/events, and the core keys this game overrides (the core says "Night" and
# "Suspicion"; this is a date). (key: (EN, JA)). New RPG writing follows the fork's voice:
# second person, present tense, warm and close.
S = {
"title": ("VESPER", "VESPER"),
"t_subtitle": ("An otome dating sim RPG. Six men, one evening star — plan the date, win him over.", "乙女恋愛シミュレーションRPG。六人の男、ひとつの宵の明星 — デートを計画し、彼の心をほどく。"),
"t_note": ("18+ · Otome · All characters are adults · AI-generated work (see 'About this work')", "18歳以上対象 · 乙女向け · 登場人物は全員成人です · AI生成作品（「作品について」参照）"),
"n_you": ("You", "あなた"), "n_narrator": ("", ""),
"ds_adult": ("This game is for adults (18+). Every character is an adult and is stated as one; every intimate scene is consensual and asked for on the page. Contains sexual content (no explicit genitals).",
             "本作品は成人向け（18歳以上）です。登場人物はすべて成人で、作中でもそう明記されています。親密な場面はすべて合意のうえで、その意思が作中で確かめられます。性的な表現を含みます（性器の描写はありません）。"),
"about_ai": ("AI disclosure: Generative AI is used as a production tool in this work, which was made through intensive collaboration between the developer and AI over several hundred hours. Images (sprites, backgrounds, CGs) are output by an image-generation model and the voice by a speech-synthesis model. The concept, world, story structure, direction, character design, the selection and compositing of every image, voice direction, game-system design and balancing, and testing are the developer's work; the script text and the program were written and edited jointly by AI language models and the developer.",
             "【AI使用について】本作は生成AIを制作ツールとして活用し、開発者とAIの集中的な共同作業で制作しました。画像（立ち絵・背景・CG）は画像生成AIで出力し、音声は音声合成AIで生成しています。企画・世界観・ストーリー構成・演出・キャラクター設計、すべての画像の選定と合成、音声の演技指示、ゲームシステムの設計とバランス調整、テストは開発者が行い、シナリオ文とプログラムはAI（大規模言語モデル）と開発者が共同で執筆・編集しています。制作には数百時間を費やしています。"),
"lang_note": ("All seven languages cover the interface, the RPG text, every standoff and the six routes' story; voice is in English.",
              "七言語すべてで、インターフェース、RPG部分の文章、すべての対峙、六つのルートの本編を収録しています。ボイスは英語です。"),
# core overrides
"ev_trust": ("Trust +%d", "信頼 +%d"),
"toast_trust": ("Trust %d — he has let you a little further in", "信頼 %d — 彼はあなたを少し内側へ入れた"),
"m_gift": ("Give it to him", "彼に贈る"),
"lose_standoff_t": ("He stepped back", "彼は一歩引いた"),
"lose_standoff": ("The distance won: the moment closed. Nothing is lost but the last few minutes — you are back at the last save, just before it.",
                  "距離が勝ち、その瞬間は閉じてしまった。失ったのは数分だけ — 直前のセーブに戻る。"),
"lose_dawn_t": ("The last train", "終電"),
"lose_dawn": ("The last train goes without you and the night closes without him. You are back at the last save.", "終電はあなたを置いて出て、夜は彼のいないまま閉じた。最後のセーブに戻る。"),
"end_t": ("Chapter cleared", "章クリア"),
"t_trial": ("Trial version — Gu Yan, chapters 1–2", "体験版 — 顧言 第1〜2章"),
"fin_body": ("Level %d · Trust %d. Thank you for playing. Your last save is in slot 1. Five more men are waiting at the title: every route has three endings.",
             "レベル %d · 信頼 %d。プレイしていただきありがとうございました。最後のセーブはスロット1に。タイトルではあと五人が待っています — どのルートにも三つのエンディングがあります。"),
"nc_budget": ("%d turns until the last train. Moving, searching and standoffs all cost time.", "終電まで %d 手。移動・調べる・対峙はすべて時間を使う。"),
"h_clock": ("%s   ·   %d turns to the last train   ·   Lv %d", "%s　·　終電まで %d 手　·　Lv %d"),
"h_trust": ("Trust %d  (next scene at %d)", "信頼 %d（次の場面は %d）"),
"b_intro": ("A standoff.", "対峙。"),
"b_dmg": ("Guard −%d.", "心の壁 −%d。"),
"b_susp": ("Distance %s.", "距離 %s。"),
"b_weak_hit": ("It lands — that is one of his tells.", "届いた — それは彼の弱いところ。"),
"b_resist_hit": ("It slides off. He sees it coming.", "かわされた。見抜かれている。"),
"b_threat_mark": ("You pushed. He will remember it: the distance grows faster for the rest of this.", "押しすぎた。彼は忘れない：この先、距離は速く広がる。"),
"b_enemy_turn": ("%s holds back. Distance %+d. %s loses %d composure.", "%s は身を引く。距離 %+d。%s の平静 −%d。"),
"b_win": ("The guard comes down.", "心の壁がほどけた。"),
"b_lose": ("It is over. He has closed the door.", "終わった。彼は扉を閉じた。"),
"b_resolve": ("Guard %d / %d", "心の壁 %d / %d"),
"b_suspicion": ("Distance %d / 100", "距離 %d / 100"),
"b_marked": ("[pushed]", "［押しすぎ］"),
"b_known": ("Tells:", "弱いところ："),
"r_needs_keepsake": ("Needs a keepsake — something to remember together.", "思い出の品が必要。"),
"r_needs_treat": ("Needs something sweet from the café.", "カフェの甘いものが必要。"),
"lv_title": ("%s — level %d", "%s — レベル %d"),
"b_won": ("He let you in", "彼は心を開いた"),
"b_lost": ("He stepped back", "彼は一歩引いた"),
"tr_end_title": ("This is where the trial ends.", "体験版はここまで"),
"tr_end_body": ("Gu Yan's chapters 3–5 and all three of his endings, five more men with five chapters and three endings each, every date and rival standoff, all 18 CGs and growth to level 20 are in the full version. Your trial save carries over.",
                "顧言の第3〜5章と三つのエンディング、それぞれ五章・三エンディングを持つほか五人のルート、すべてのデートとライバルとの対峙、全18枚のCG、レベル20までの成長は製品版に収録されています。体験版のセーブデータは製品版に引き継げます。"),
"tr_open_store": ("Open the product page", "製品版のページを開く"), "tr_back": ("Back to the title", "タイトルに戻る"),
"credits_1": ("VESPER — the RPG edition. Flat 404.", "VESPER — RPG版。Flat 404。"),
# stats
"s_wit": ("Wit", "機知"), "s_cha": ("Charm", "魅力"), "s_grt": ("Poise", "落ち着き"), "s_stl": ("Patience", "辛抱"),
"sd_wit": ("Banter, remembering, saying it plainly; your nerve pool.", "軽口・思い出す・率直に言う。胆力の上限。"),
"sd_cha": ("Teasing, something sweet, a look that lingers.", "からかう・甘いもの・見つめる。"),
"sd_grt": ("Composure; how much the distance can cost you.", "平静の上限。距離に耐える力。"),
"sd_stl": ("Breathing brings the distance down further.", "「深呼吸」で距離を大きく縮める。"),
# actions
"a_deflect": ("Hold back", "引く"), "a_observe": ("Read him", "彼を読む"), "a_banter": ("Banter", "軽口"),
"a_tease": ("Tease", "からかう"), "a_remember": ("Remember", "思い出す"), "a_sweet": ("Something sweet", "甘いもの"),
"a_push": ("Push him", "押す"), "a_stall": ("Breathe", "深呼吸"), "a_item": ("Use item", "アイテム"),
"a_plain": ("Say it plainly", "率直に言う"), "a_linger": ("A look that lingers", "長いまなざし"),
"ad_deflect": ("Give him room: soften his next move and close the distance a little.", "彼に余白を：次の一手を和らげ、距離を少し縮める。"),
"ad_observe": ("Watch him: reveals his tells (what reaches him).", "彼を見る：弱いところ（彼に届くもの）が分かる。"),
"ad_banter": ("Quick and light. Wit.", "軽やかに切り返す。機知。"),
"ad_tease": ("Warmth with a smile in it. Charm.", "笑みを含んだ温かさ。魅力。"),
"ad_remember": ("Bring up something only the two of you know. Closes the distance. Needs a keepsake.", "二人だけが知っていることを持ち出す。距離が縮む。思い出の品が必要。"),
"ad_sweet": ("Share something from the café. Charm. Needs a treat.", "カフェの甘いものを分ける。魅力。お菓子が必要。"),
"ad_push": ("Ask for more than he is offering. Hits hard — and he remembers: the distance grows faster for the rest of the date.", "彼が差し出す以上を求める。強く響くが、彼は忘れない：この先、距離は速く広がる。"),
"ad_stall": ("Slow down and let the quiet work. The distance falls; a little composure back.", "ゆっくりと、沈黙に任せる。距離が縮み、平静が少し戻る。"),
"ad_item": ("Use something from your bag.", "バッグの中のものを使う。"),
"ad_plain": ("Say the true thing, without decoration. Closes the distance.", "飾らずに本当のことを言う。距離が縮む。"),
"ad_linger": ("Hold his eyes a beat longer than you should. Closes the distance.", "少しだけ長く、彼の目を見つめる。距離が縮む。"),
# skills
"br_sharp": ("Sharp", "鋭さ"), "br_sweet": ("Sweet", "甘さ"),
"sk_quick": ("Quick tongue", "回る舌"), "skd_quick": ("Banter +30%.", "軽口 +30%。"),
"sk_steady": ("Steady heart", "揺れない心"), "skd_steady": ("Composure +10.", "平静 +10。"),
"sk_noticing": ("Noticing", "気づく人"), "skd_noticing": ("Wit +2, Remember +20%.", "機知 +2、思い出す +20%。"),
"sk_plain_sk": ("Plain words", "率直な言葉"), "skd_plain_sk": ("Learn 'Say it plainly'.", "「率直に言う」を覚える。"),
"sk_candour": ("Candour", "まっすぐさ"), "skd_candour": ("Say it plainly +40%, Remember +20%.", "率直に言う +40%、思い出す +20%。"),
"sk_warm": ("Warm smile", "温かい笑み"), "skd_warm": ("Tease +30%.", "からかう +30%。"),
"sk_linger_sk": ("Eye contact", "目を合わせる"), "skd_linger_sk": ("Learn 'A look that lingers'.", "「長いまなざし」を覚える。"),
"sk_poise_sk": ("Grace", "しなやかさ"), "skd_poise_sk": ("Charm +2.", "魅力 +2。"),
"sk_unhurried": ("Unhurried", "急がない人"), "skd_unhurried": ("Breathe +40%, A look that lingers +20%.", "深呼吸 +40%、長いまなざし +20%。"),
"sk_glow": ("Glow", "輝き"), "skd_glow": ("Tease +40%, A look that lingers +30%.", "からかう +40%、長いまなざし +30%。"),
# items
"i_coffee": ("Café latte", "カフェラテ"), "id_coffee": ("Restores 16 composure.", "平静を16回復。"),
"i_cake": ("Slice of cake", "ケーキひと切れ"), "id_cake": ("Restores 28 composure.", "平静を28回復。"),
"i_tea": ("Mint tea", "ミントティー"), "id_tea": ("Restores 8 nerve.", "胆力を8回復。"),
"i_wine": ("A glass of wine", "グラスワイン"), "id_wine": ("Restores 14 nerve.", "胆力を14回復。"),
"i_macarons": ("Macarons", "マカロン"), "id_macarons": ("A box from the café. For 'Something sweet'.", "カフェの箱入り。「甘いもの」に使う。"),
"i_transit": ("Night-bus pass", "深夜バスの定期"), "id_transit": ("Gets you across the city after dark.", "夜の街を渡るための定期。"),
"i_blouse": ("Silk blouse", "シルクのブラウス"), "id_blouse": ("Office-to-evening. Wit +1.", "仕事帰りにも。機知 +1。"),
"i_trench": ("Trench coat", "トレンチコート"), "id_trench": ("For rain and long walks. Poise +1, Patience +1, Breathe +20%.", "雨と長い散歩に。落ち着き +1、辛抱 +1、深呼吸 +20%。"),
"i_dress": ("Little black dress", "黒のワンピース"), "id_dress": ("Charm +2, Tease +20%.", "魅力 +2、からかう +20%。"),
"i_slip": ("Wine-red slip dress", "ワインレッドのスリップドレス"), "id_slip": ("Charm +3, Tease +30%, A look that lingers +20%.", "魅力 +3、からかう +30%、長いまなざし +20%。"),
"i_his_shirt": ("His shirt", "彼のシャツ"), "id_his_shirt": ("Too big, and yours now. Charm +2, Poise +2, A look that lingers +30%, Say it plainly +20%.", "大きすぎて、もうあなたのもの。魅力 +2、落ち着き +2、長いまなざし +30%、率直に言う +20%。"),
"i_earrings": ("Pearl earrings", "パールのイヤリング"), "id_earrings": ("Charm +1.", "魅力 +1。"),
"i_scarf": ("Silk scarf", "シルクのスカーフ"), "id_scarf": ("Poise +1, Breathe +20%.", "落ち着き +1、深呼吸 +20%。"),
"i_perfume": ("Evening perfume", "夜の香水"), "id_perfume": ("Charm +1, Tease +20%, A look that lingers +20%.", "魅力 +1、からかう +20%、長いまなざし +20%。"),
"i_phone": ("Your phone", "スマートフォン"), "id_phone": ("Wit +1.", "機知 +1。"),
"i_notebook": ("Pocket notebook", "手帳"), "id_notebook": ("You write down what he says. Wit +1, Remember +30%.", "彼の言葉を書き留める。機知 +1、思い出す +30%。"),
"i_umbrella": ("Umbrella", "傘"), "id_umbrella": ("Patience +1, Breathe +20%.", "辛抱 +1、深呼吸 +20%。"),
"hs_plan": ("Plan the evening", "今夜の計画を立てる"),
"pl_day_1": ("Monday. You have the evening, and a plan to make.", "月曜日。夜は空いている。計画を立てよう。"),
"pl_day_2": ("Tuesday. You already know a little more about him than last time.", "火曜日。前より少しだけ、彼のことを知っている。"),
"pl_day_3": ("Wednesday. Halfway through the week, and he is on your mind more than halfway.", "水曜日。週の半ば。彼のことは半分以上、頭にある。"),
"pl_day_4": ("Thursday. Something is pressing on him; plan for that.", "木曜日。何かが彼にのしかかっている。それを踏まえて計画を。"),
"pl_day_5": ("Friday. The last evening of the week. Make it the right one.", "金曜日。週の最後の夜。正しい夜にしよう。"),
"pl_hint_guyan": ("Gu Yan closes the shop at nine and likes the quiet hour after. Something warm before you go; no rush; dress for rain.", "顧言は九時に店を閉め、その後の静かな時間が好き。行く前に温かいものを。急がずに。雨に備えた装いで。"),
"pl_hint_ethan": ("Ethan works until the building empties. He respects people who don't waste his time: go straight to him, say what you mean, and dress like you work on the top floor.", "イーサンはビルが空になるまで働く。時間を無駄にしない人を尊重する：まっすぐ彼のもとへ、思ったことを言い、最上階で働く人のような装いで。"),
"pl_hint_luxingye": ("Lu Xingye can't be seen in public as himself. Take the long way through the city, keep it light and teasing, and wear something that feels like a night out.", "陸星野は素顔で人前に出られない。遠回りして街を歩き、軽やかにからかって、夜遊びらしい装いで。"),
"pl_hint_liam": ("Liam is off shift at seven and hates fuss. A walk first, a joke or two, and what you'd wear to a neighbour's porch.", "リアムは七時に非番になり、大げさなことが苦手。まず散歩、冗談をひとつふたつ、そしてお隣のポーチに行くような服で。"),
"pl_hint_adrian": ("Adrian is bored of people who perform. Go straight to him, mean every word, and wear something with an edge.", "エイドリアンは演じる人に飽きている。まっすぐ彼のもとへ、言葉はすべて本気で、少し尖った装いで。"),
"pl_hint_fushen": ("Fu Shen notices everything and says nothing. Somewhere quiet first, take your time, and dress like the room you're walking into.", "傅深はすべてに気づき、何も言わない。まず静かな場所へ、時間をかけて、向かう部屋にふさわしい装いで。"),
"pl_q_stop": ("Where do you go first?", "まずどこへ？"),
"pl_q_way": ("How do you want to be with him tonight?", "今夜、彼とどう過ごしたい？"),
"pl_fit": ("That suits him.", "それは彼に合っている。"),
"pl_miss": ("Not quite him — but it's your evening too.", "彼らしくはない — でも、あなたの夜でもある。"),
"pl_wear_ok": ("And what you're wearing is exactly his kind of evening.", "そしてその装いは、まさに彼好みの夜だ。"),
"pl_wear_no": ("You catch yourself in the mirror: lovely — but not quite his evening. (Change in the Party menu; the wardrobe is here.)", "鏡に映る自分：素敵だけど、彼の好みとは少し違う。（着替えは「パーティ」メニューから。クローゼットはここ）"),
"pl_good": ("The plan fits him (2 of 3 or better): Trust +1, and his guard starts lower tonight.", "計画は彼にぴったり（3つ中2つ以上）：信頼 +1、今夜は心の壁が低いところから始まる。"),
"pl_bad": ("The plan doesn't quite fit him (fewer than 2 of 3): the date starts at his full guard.", "計画は彼に合わなかった（3つ中2つ未満）：デートは心の壁が高いまま始まる。"),
"m_party": ("Me", "わたし"),
# rooms (shared) and generic hotspots
"r_home": ("Your flat", "あなたの部屋"), "r_street": ("The city at night", "夜の街"), "r_cafe": ("The late café", "深夜のカフェ"),
"hs_wardrobe": ("the wardrobe", "クローゼット"), "hs_desk": ("your desk", "机"), "hs_mirror": ("the mirror", "鏡"),
"hs_counter": ("the counter", "カウンター"), "hs_corner": ("the window seat", "窓際の席"), "hs_board": ("the noticeboard", "掲示板"),
"hs_stall": ("the flower stall", "花屋の屋台"), "hs_kiosk": ("the kiosk", "キオスク"),
"hs_b1": ("Go to him", "彼のもとへ"), "hs_b2": ("Stay a little longer", "もう少しだけ"), "hs_b3": ("One more thing", "もうひとつだけ"),
"hs_end": ("Before the night ends", "夜が終わる前に"),
"ev_wardrobe": ("You open the wardrobe and stand there longer than you need to, deciding who you are going to be tonight.", "クローゼットを開け、必要以上に長く立ち尽くす。今夜の自分を決めるために。"),
"ev_wardrobe_n": ("Nothing new in here — but the mirror says you look like someone who is expected somewhere.", "新しいものはない — でも鏡の中のあなたは、どこかで待たれている人の顔をしている。"),
"ev_desk": ("Your desk, the half-finished things on it, and the one thing you came back for.", "机の上の、やりかけのものたち。そして取りに戻ったひとつ。"),
"ev_counter": ("The barista knows your order by now, and adds something you didn't ask for. \"You've got a look,\" she says. \"Go on.\"", "バリスタはもうあなたの注文を覚えていて、頼んでいないものをひとつ添える。「いい顔してる。行っておいで」"),
"ev_corner": ("You sit by the window for a minute and let the evening rearrange itself. Something in your bag has his name on it now.", "窓際に一分だけ座り、夜が形を変えるのを待つ。バッグの中のあるものは、もう彼の名前がついている。"),
"ev_board": ("Flyers, lost cats, a poem someone pinned up and never claimed. You take what you need and leave the poem.", "チラシ、迷い猫、誰かが貼って取りに来なかった詩。必要なものだけ取って、詩は残していく。"),
"ev_stall": ("The flower seller wraps a single stem for you without asking who it is for.", "花売りは誰に贈るのかも聞かずに、一輪だけ包んでくれる。"),
"ev_kiosk": ("A late paper, a bus pass top-up, a mint. The city keeps its small promises.", "遅い新聞、バス定期のチャージ、ミントひとつ。街は小さな約束を守る。"),
"ev_heat_gate": ("Whatever happens next is a question, and he asks it out loud. You can say yes. You can say not tonight. Both are allowed.", "次に起きることは問いかけで、彼はそれを声に出して尋ねる。はいと言ってもいい。今夜はやめておくと言ってもいい。どちらも許されている。"),
"ev_heat_locked": ("(Trust is not high enough yet for this — the scene stays closed, and so does nothing else. You can still say not tonight.)", "（まだ信頼が足りない — この場面は閉じたまま。他に失うものはない。「今夜はやめておく」はいつでも選べる。）"),
"ev_trust_missed": ("He let you in — but you got there the long way round, and the distance is still in the room. (Win a date with Distance under 60 for Trust.)", "彼は心を開いた — でも遠回りだった。距離はまだ部屋に残っている。（距離60未満で勝つと信頼が上がる）"),
"ev_chapter_cg": ("You will keep this one.", "これは、ずっと覚えている。"),
"ev_ending": ("— Ending —", "— エンディング —"),
# night card for the prologue
"nt_prologue": ("VESPER", "VESPER"),
"ns_prologue": ("The evening star is up. Six doors in the city are still lit.", "宵の明星が昇った。街にはまだ灯りのついた扉が六つある。"),
"ev_pro_1": ("Evening. The city switches its lights on one window at a time, and somewhere in it six men are still awake for reasons they have not told anyone.",
             "夜。街は窓ひとつずつ灯りを点けていく。そのどこかで、六人の男が誰にも言っていない理由で、まだ起きている。"),
"ev_pro_2": ("Everyone you will meet tonight is an adult, and so are you. Nothing happens here that is not asked for and answered yes.",
             "今夜出会う人はみな大人で、あなたもそう。ここでは、尋ねられ「はい」と答えられたこと以外は何も起きない。"),
"ev_pro_3": ("Whose night do you walk into?", "誰の夜に歩み入る？"),
"ev_route_joined": ("You step out into the evening. He doesn't know yet that you are on your way.", "あなたは夜へ踏み出す。彼はまだ、あなたが向かっていることを知らない。"),
# stranger standoffs (shared across routes): pre / after / barks
"pre_doorman": ("A doorman with an earpiece and a clipboard steps into your path. \"Name? You're not on the list.\"", "イヤーピースとクリップボードのドアマンが行く手を塞ぐ。「お名前は？ リストにありませんね」"),
"post_doorman": ("He checks the list again, finds a reason to have made a mistake, and holds the door. \"Have a good night, miss.\"", "彼はリストを見直し、自分の間違いだった理由を見つけて、扉を押さえる。「良い夜を」"),
"pre_paparazzo": ("A flash goes off in your face. A man with a long lens grins. \"Who are you to him? Give me a name and I'll make you famous.\"", "目の前でフラッシュが光る。望遠レンズの男がにやりと笑う。「彼とはどういう関係？ 名前をくれたら有名にしてやるよ」"),
"post_paparazzo": ("He lowers the camera, deletes the frame in front of you, and goes to stand somewhere else.", "彼はカメラを下ろし、あなたの目の前でその一枚を消して、別の場所へ立ち去る。"),
"pre_columnist": ("A woman in a trench coat falls into step beside you, phone already recording. \"Off the record — how long has this been going on?\"", "トレンチコートの女があなたの横に並ぶ。スマホはもう録音中。「オフレコで — いつから続いてるの？」"),
"post_columnist": ("She stops the recording, looks at you for a long second, and laughs. \"Fine. Keep it. Some things are better not printed.\"", "彼女は録音を止め、しばらくあなたを見て、笑う。「いいわ。取っておきなさい。書かないほうがいいこともある」"),
"bark_doorman_1": ("\"I don't make the list. I just read it.\"", "「リストを作るのは俺じゃない。読むだけだ」"), "bark_doorman_2": ("He taps the clipboard, slowly.", "彼はゆっくりとクリップボードを叩く。"), "bark_doorman_3": ("\"Lot of people say they know him.\"", "「彼の知り合いだって言う人は多いんですよ」"),
"bark_paparazzo_1": ("\"Just one smile. For the readers.\"", "「一枚だけ笑って。読者のために」"), "bark_paparazzo_2": ("The shutter clicks three times, fast.", "シャッターが三度、素早く鳴る。"), "bark_paparazzo_3": ("\"Everyone's for sale, sweetheart. What's your price?\"", "「誰にだって値段はあるさ。あんたのは？」"),
"bark_columnist_1": ("\"I'll find out anyway. Better from you.\"", "「どうせ調べはつくの。あなたから聞いたほうがいい」"), "bark_columnist_2": ("She smiles like she has already written the headline.", "彼女はもう見出しを書き終えたような顔で微笑む。"), "bark_columnist_3": ("\"Does he know you're this interesting?\"", "「あなたがこんなに面白い人だって、彼は知ってるの？」"),
"e_doorman": ("The doorman", "ドアマン"), "e_paparazzo": ("A paparazzo", "パパラッチ"), "e_columnist": ("The gossip columnist", "ゴシップ記者"),
# heroine (narrator) barks: the fork's rendered voice lines, verbatim
"hb_open_1": ("He left the thread open. He was hoping.", "彼は話の糸を切らずにおいた。期待していたのだ。"),
"hb_open_2": ("You're back, and it's late, and he noticed both.", "あなたは戻ってきた。夜も遅い。彼はその両方に気づいている。"),
"hb_read_1": ("One more word and he says it out loud.", "あとひと言で、彼はそれを口にする。"),
"hb_read_2": ("He's right at the edge of asking.", "彼は今にも尋ねそうだ。"),
"hb_win_1": ("He'll think about that all night.", "彼は一晩中、そのことを考えるだろう。"),
"hb_win_2": ("That landed. You can feel him go still.", "届いた。彼が静かになるのが分かる。"),
"hb_win_3": ("Something just shifted, and you both felt it.", "何かが動いた。二人ともそれを感じた。"),
"vb_stage_1": ("Something in him just gave way.", "彼の中で何かがほどけた。"),
"vb_stage_2": ("He stopped pretending he wasn't waiting.", "彼は待っていないふりをやめた。"),
"vb_stage_3": ("He's telling you the thing he doesn't tell anyone.", "彼は誰にも言わないことを、あなたに話している。"),
"vb_stage_4": ("You're not being careful any more. Neither is he.", "あなたはもう慎重じゃない。彼もそう。"),
"vb_win_big_1": ("He kept every word you ever gave him. All of them.", "彼はあなたがくれた言葉を全部取っておいた。ひとつ残らず。"),
"vb_win_big_2": ("You reached the end of him, and he stayed.", "あなたは彼のいちばん奥まで辿り着き、彼はそこに留まった。"),
"vb_unlock_1": ("A new chapter just opened for you.", "新しい章があなたのために開いた。"),
"vb_unlock_2": ("Someone else has been waiting his turn.", "別の誰かが、自分の番を待っていた。"),
"vb_streak_1": ("Three in a row. You know exactly what he needs.", "三連続。彼に何が必要か、あなたはもう分かっている。"),
"vb_streak_2": ("You're reading him like you wrote him.", "まるで自分で書いた人物のように、彼を読めている。"),
"vb_fail_1": ("He's gone quiet. Let him have the moment.", "彼は黙り込んだ。その時間を彼にあげて。"),
"vb_fail_2": ("That one missed. Say it another way.", "今のは外れ。別の言い方で。"),
"vb_idle_1": ("He's still on the other end of this.", "彼はまだ、この向こう側にいる。"),
"vb_idle_2": ("Still awake? So is he.", "まだ起きてる？ 彼もよ。"),
# gallery
"g_locked": ("Locked — Trust %d", "未開放 — 信頼 %d"),
}
