#!/usr/bin/env python3
"""Write assets/cg/installed.json — which plate files are real renders, not placeholders.

    python3 play/floor-13-x/tools/plate_manifest.py [--check]

Why this exists. tools/make_placeholder_plates.py drops a labelled PIL card at every slot
path at the right size and format, so that the hooks, gates, gallery and tests can all be
built before a GPU second is spent. That is the right call, and it has exactly one sharp
edge: the *game* cannot tell a placeholder from a render. ResourceLoader.exists() is true
for both, load() returns a valid texture for both, and tests/fork_cg.gd's "every earned
slot resolves to a file that exists" passes while a player on the NEW_MANAGER ending is
looking at a grey card with the words CG_DESK_X on it.

So the distinction is made here, at build time, and written down. The discriminator is the
unique-colour count, which separates the two classes by more than an order of magnitude and
is not a close call on any file we have:

    placeholders   cg_withheld 4,388   cg_desk_x 8,844
    renders        89,406 .. 279,412

A slot that is not installed falls back to its `_locked` partner (and then to the withheld
card) at runtime, via CgGate.installed(). Re-run this after every ops/install_plates.py.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
CG = ROOT / "assets" / "cg"
OUT = CG / "installed.json"

# Comfortably between the two populations above. A render has never come in under 80k and
# a placeholder has never come in over 10k; anything in between should be looked at by a
# person, and is reported rather than silently classified.
REAL = 40_000
SUSPECT_LOW, SUSPECT_HIGH = 10_000, 80_000


def colours(path: pathlib.Path) -> int:
    im = Image.open(path).convert("RGB")
    return len(im.getcolors(maxcolors=20_000_000) or [])


def build() -> dict:
    installed, placeholder, suspect = [], [], []
    for p in sorted(CG.glob("*.png")):
        stem = p.stem
        if stem == "cg_withheld" or stem.startswith("bg_"):
            continue
        n = colours(p)
        (installed if n >= REAL else placeholder).append(stem)
        if SUSPECT_LOW < n < SUSPECT_HIGH:
            suspect.append(f"{stem} ({n} colours)")
    return {
        "installed": installed,
        "placeholder": placeholder,
        "suspect": suspect,
        "note": "generated by tools/plate_manifest.py; slots not in `installed` fall back "
                "to their _locked partner at runtime (CgGate.installed()).",
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if installed.json is missing or out of date")
    args = ap.parse_args()
    data = build()
    if args.check:
        if not OUT.is_file():
            print("!! %s does not exist" % OUT)
            return 1
        have = json.loads(OUT.read_text())
        if have.get("installed") != data["installed"] or have.get("placeholder") != data["placeholder"]:
            print("!! installed.json is stale\n   on disk: %s\n   actual : %s"
                  % (have.get("installed"), data["installed"]))
            return 1
        print("  ok   installed.json matches the files (%d installed, %d placeholder)"
              % (len(data["installed"]), len(data["placeholder"])))
        return 0
    OUT.write_text(json.dumps(data, indent=2) + "\n")
    print("installed  (%d): %s" % (len(data["installed"]), ", ".join(data["installed"])))
    print("placeholder(%d): %s" % (len(data["placeholder"]), ", ".join(data["placeholder"])))
    if data["suspect"]:
        print("!! look at these by eye: %s" % ", ".join(data["suspect"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
