# System strings, names, actions, items, skills and the office screen for OCCUPANCY. (key: (EN, JA))
# Keys that also exist in the core's strings_core.json override it. The standoff is re-skinned
# as a RENT NEGOTIATION: the other side's Resolve, each staffer's Composure and Focus, and the
# other side's PRESSURE on the floor -- at 100 the floor is served notice (a loss, reload).
# Voice: close second person on the night manager, present tense, warm and a little dry.
S = {
"title": ("OCCUPANCY", "OCCUPANCY ―オキュパンシー―"),
"t_subtitle": ("RPG × office management × staff recruiting — five nights to make the rent", "RPG × オフィス経営 × スタッフ採用ガチャ ― 家賃を払いきる五夜"),
"t_note": ("18+ · All characters are adults · AI-generated work (see 'About this work')", "18歳以上対象 · 登場人物は全員成人です · AI生成作品（「作品について」参照）"),
"t_trial": ("Trial version — Night one: the open plan", "体験版 — 第一夜：オープンフロア"),
# ops/dlsite/AI_DISCLOSURE.md, voiced variant (Mirei's 21 voiced lines ship), verbatim
"about_ai": ("This is an adults-only work. Every character depicted is an adult. Recruiting uses the in-game rent fund only: there are no real-money purchases of any kind.\n\nAI disclosure: Generative AI is used as a production tool in this work, which was made through intensive collaboration between the developer and AI over several hundred hours. Images (sprites, backgrounds, CGs) are output by an image-generation model and the voice by a speech-synthesis model. The concept, world, story structure, direction, character design, the selection and compositing of every image, voice direction, game-system design and balancing, and testing are the developer's work; the script text and the program were written and edited jointly by AI language models and the developer.",
             "本作は18歳以上を対象とした作品です。登場人物は全員成人です。スタッフ採用（ガチャ）はゲーム内の家賃資金のみで行い、現実のお金による課金は一切ありません。\n\n【AI使用について】本作は生成AIを制作ツールとして活用し、開発者とAIの集中的な共同作業で制作しました。画像（立ち絵・背景・CG）は画像生成AIで出力し、音声は音声合成AIで生成しています。企画・世界観・ストーリー構成・演出・キャラクター設計、すべての画像の選定と合成、音声の演技指示、ゲームシステムの設計とバランス調整、テストは開発者が行い、シナリオ文とプログラムはAI（大規模言語モデル）と開発者が共同で執筆・編集しています。制作には数百時間を費やしています。"),
"ds_adult": ("18+. Everyone in this game is an adult. It contains partial nudity and sexual themes between consenting adults (nothing explicit), office politics and debt.", "18歳以上対象。登場人物は全員成人です。成人同士の合意のうえでの部分的な裸体と性的な主題（露骨な描写はありません）、職場の駆け引き、借金を扱います。"),
# names
"n_you": ("You", "あなた"),
"n_mara": ("Mara", "マーラ"),
"n_priya": ("Priya", "プリヤ"),
"n_nia": ("Nia", "ニア"),
"n_sol": ("Sol", "ソル"),
"n_mirei": ("Mirei", "ミレイ"),
"n_dan": ("Dan", "ダン"),
"n_wes": ("Wes", "ウェス"),
"n_pryce": ("Pryce", "プライス"),
"n_courier": ("The courier", "配達人"),
"n_cleaner": ("The supervisor", "主任"),
"n_varga": ("Ms. Varga", "ヴァルガ"),
"n_ames": ("Ms. Ames", "エイムズ"),
"n_bailiff": ("The Bailiff", "執行官"),
"n_sallow": ("Mr. Sallow", "サロウ"),
"n_halvard": ("Corinne", "コリンヌ"),
"n_tenant": ("Tenant", "入居者"),
"n_foreman": ("The foreman", "班長"),
# HUD / menus
"h_clock": ("%s   ·   %d moves before dawn   ·   Lv %d", "%s   ·   夜明けまであと%d手   ·   Lv %d"),
"h_counter": ("Rent fund $%d", "家賃資金 $%d"),
"nc_budget": ("%d moves before dawn. Walking, searching, negotiating and the shift all cost time.", "夜明けまであと%d手。移動・調査・交渉・シフト、すべてに時間がかかります。"),
"m_party": ("Staff", "スタッフ"),
"m_map": ("The building", "ビルの案内図"),
"ms_level": ("Office level %d   XP %d / %d   Best trust %d", "オフィスレベル %d   経験値 %d / %d   最高信頼 %d"),
"ev_trust_track": ("%s's trust +%d", "%sの信頼 +%d"),
"toast_trust_track": ("%s: Trust %d — something after hours is open", "%s：信頼%d — 終業後の時間が解放されました"),
"g_locked": ("Locked — Trust %d", "未解放 — 信頼%d"),
"g_unseen": ("Not seen yet", "まだ見ていない"),
"end_t": ("Lights down on the floor", "フロアの消灯"),
"end_body": ("Office level %d · best Trust %d. Your progress is saved in slot 1.", "オフィスレベル %d · 最高信頼 %d。進行状況はスロット1に保存されています。"),
"fin_t": ("Occupancy", "オキュパンシー"),
"fin_body": ("Office level %d · best Trust %d. Thank you for playing. Your last save is in slot 1: build the floors differently, hire differently, stay late with someone else, and the dawn changes.", "オフィスレベル %d · 最高信頼 %d。遊んでいただきありがとうございました。最後のセーブはスロット1にあります。フロアの組み方、採用、残業の相手を変えれば、夜明けが変わります。"),
"lose_standoff_t": ("Served notice", "通告"),
"lose_standoff": ("The pressure on the floor reached a hundred, and the notice went up on the door. Nothing is lost but the last few minutes: you are back at the last save.", "フロアへの圧力が100に達し、扉に通告が貼られた。失ったのは直前の数分だけ。最後のセーブに戻ります。"),
"lose_dawn_t": ("Dawn", "夜明け"),
"lose_dawn": ("The cleaners arrive, the lifts wake, and the night is gone with the floor still unsettled. You are back at the last save.", "清掃員が来て、エレベーターが目を覚まし、フロアが片づかないまま夜が終わった。最後のセーブに戻ります。"),
# the standoff, re-skinned
"b_intro": ("Across the desk.", "机を挟んで。"),
"b_resolve": ("Resolve %d / %d", "意地 %d / %d"),
"b_suspicion": ("Pressure %d / 100", "圧力 %d / 100"),
"b_comp_nerve": ("Composure %d/%d  Focus %d/%d", "平静 %d/%d  集中 %d/%d"),
"b_dmg": ("Resolve −%d.", "意地 −%d。"),
"b_susp": ("Pressure %s.", "圧力 %s。"),
"b_weak_hit": ("It lands — a soft spot.", "効いた — 弱みだ。"),
"b_resist_hit": ("It slides off. They were ready for that.", "受け流された。その手は読まれていた。"),
"b_enemy_turn": ("%s leans on the desk. Pressure %+d. %s's composure −%d.", "%sが机に身を乗り出す。圧力 %+d。%sの平静 −%d。"),
"b_threat_mark": ("Security has been called and cannot be uncalled: the pressure climbs faster for the rest of this.", "警備を呼んだら取り消せない。この先、圧力の上がり方が速くなる。"),
"b_win": ("They sign off.", "相手が引き下がった。"),
"b_lose": ("The notice goes up on the door.", "扉に通告が貼られる。"),
"b_marked": ("[security called]", "[警備を呼んだ]"),
"b_won": ("Settled", "交渉成立"),
"b_lost": ("Served notice", "通告"),
"r_needs_cash": ("Needs a parking pass or a voucher to comp.", "渡す駐車券かバウチャーが要る。"),
"r_needs_evidence": ("Needs a document to show.", "見せる書類が要る。"),
"r_nerve": ("Not enough focus.", "集中が足りない。"),
"r_rattled": ("Too rattled to act.", "動揺して動けない。"),
"ev_trust_missed": ("You won, but too close to the line: Mirei noticed how close.", "勝ったが、際どすぎた。ミレイはその際どさに気づいた。"),
# stats
"s_wit": ("Sharp", "切れ者"),
"s_cha": ("Charm", "魅力"),
"s_grt": ("Nerve", "度胸"),
"s_stl": ("Calm", "冷静"),
"sd_wit": ("Paperwork, spin, keys and audits. Also the focus pool.", "書類・言いくるめ・鍵・監査。集中の上限も決まる。"),
"sd_cha": ("Charm, perks and headlines.", "愛嬌・特典・見出し。"),
"sd_grt": ("How much a staffer can take across a desk, and how hard security lands.", "机越しに耐えられる量と、警備の効き目。"),
"sd_stl": ("A coffee break lowers the pressure further.", "「コーヒー休憩」で圧力を大きく下げる。"),
# actions
"a_deflect": ("Hold the line", "一線を守る"),
"a_observe": ("Read them", "相手を読む"),
"a_bluff": ("Spin it", "言いくるめる"),
"a_evidence": ("Show the paperwork", "書類を見せる"),
"a_bribe": ("Comp a perk", "特典を渡す"),
"a_flirt": ("Charm", "愛嬌"),
"a_threaten": ("Call security", "警備を呼ぶ"),
"a_stall": ("Coffee break", "コーヒー休憩"),
"a_item": ("Use item", "道具を使う"),
"a_keys": ("Master keys", "マスターキー"),
"a_fix": ("Fix it on the spot", "その場で直す"),
"a_audit": ("Audit them", "監査する"),
"a_headline": ("Headline", "見出し"),
"ad_deflect": ("Feet planted. Take the next push and cool the room a little.", "足を踏ん張る。次の圧を受け止め、場を少し冷やす。"),
"ad_observe": ("Watch what they reach for: reveals their soft spots.", "相手が何に手を伸ばすか見る。弱みがわかる。"),
"ad_bluff": ("Tell it the way it should have happened. Sharp.", "そうあるべきだった形で話す。切れ者。"),
"ad_evidence": ("A lease, a sign-in sheet, a ledger: lowers the pressure. Needs one.", "契約書、入館記録、台帳。圧力が下がる。一枚必要。"),
"ad_bribe": ("A parking pass, a voucher, a favour. Charm. Spends one.", "駐車券、バウチャー、ちょっとした恩。魅力。一つ消費。"),
"ad_flirt": ("Warmly, until they forget the number. Charm.", "温かく、相手が数字を忘れるまで。魅力。"),
"ad_threaten": ("Hits hard — and they remember. Pressure climbs faster for the rest of this.", "強烈に効く。だが相手は覚えている。この先、圧力が上がりやすくなる。"),
"ad_stall": ("Two coffees and a silence. Pressure falls; a little composure comes back.", "コーヒー二杯と沈黙。圧力が下がり、平静が少し戻る。"),
"ad_item": ("Something from the desk drawer.", "机の引き出しから何かを。"),
"ad_keys": ("Mara opens the door they were sure was locked. Hard, and it lowers the pressure.", "マーラが、閉まっていると思われていた扉を開ける。強力で、圧力も下がる。"),
"ad_fix": ("Priya fixes the thing they were complaining about while they are still complaining. Nerve.", "プリヤは相手が文句を言っている最中に、その原因を直してしまう。度胸。"),
"ad_audit": ("Nia reads their numbers back to them. Very hard, and the pressure drops.", "ニアが相手の数字を読み返す。非常に強力で、圧力が下がる。"),
"ad_headline": ("Sol tells them how this will read in print. Charm.", "ソルが、これが記事になったらどう読めるかを告げる。魅力。"),
# items
"i_coin": ("Rent fund", "家賃資金"), "id_coin": ("The building's float, in dollars. In-game money only.", "ビルの運転資金（ドル）。ゲーム内通貨のみ。"),
"i_voucher": ("Parking pass", "駐車券"), "id_voucher": ("A free month in the garage. Comp a perk spends one.", "駐車場一か月無料。「特典を渡す」で一つ消費。"),
"i_espresso": ("Double espresso", "ダブルエスプレッソ"), "id_espresso": ("Restores 16 composure.", "平静を16回復。"),
"i_energy": ("Energy drink", "エナジードリンク"), "id_energy": ("Restores 8 focus.", "集中を8回復。"),
"i_pastry": ("Night-shift pastry", "夜勤のペストリー"), "id_pastry": ("Restores 28 composure.", "平静を28回復。"),
"i_mints": ("Strong mints", "強いミント"), "id_mints": ("Restores 14 focus.", "集中を14回復。"),
"i_lease_copy": ("Floor two's lease", "二階の賃貸契約書"), "id_lease_copy": ("Paperwork. Signed, dated, paid.", "書類。署名、日付、支払済。"),
"i_sign_in_sheet": ("The night sign-in sheet", "夜間入館記録"), "id_sign_in_sheet": ("Paperwork. Who was where, in Mara's hand.", "書類。誰がどこにいたか、マーラの字で。"),
"i_sublet_ledger": ("Wes's ledger", "ウェスの台帳"), "id_sublet_ledger": ("Paperwork. Every desk he rented that he did not have.", "書類。持っていない机を貸した記録すべて。"),
"i_audit_trail": ("An audit trail", "監査証跡"), "id_audit_trail": ("Paperwork. Six years, stamped RETURNED.", "書類。六年分、『返却』の判。"),
"i_court_error": ("The order's wrong date", "命令書の日付誤り"), "id_court_error": ("Paperwork. The court typed 2025.", "書類。裁判所が2025と打った。"),
"i_trust_deed": ("The 1974 trust deed", "1974年の信託証書"), "id_trust_deed": ("Paperwork. Clause nine, which nobody has read since 1974.", "書類。1974年以来誰も読んでいない第九条。"),
"i_mara_work": ("Mara — shirt and lanyard", "マーラ — シャツと名札"), "id_mara_work": ("Outfit. Nerve +1. The keys to every floor.", "服装。度胸+1。全フロアの鍵。"),
"i_mara_after": ("Mara — black dress", "マーラ — 黒いドレス"), "id_mara_after": ("Outfit. Charm +2, charm stronger. She kept the lanyard on.", "服装。魅力+2、愛嬌が強くなる。名札はつけたまま。"),
"i_priya_work": ("Priya — hi-vis", "プリヤ — 反射ジャケット"), "id_priya_work": ("Outfit. Nerve +1.", "服装。度胸+1。"),
"i_priya_after": ("Priya — red sweater", "プリヤ — 赤いセーター"), "id_priya_after": ("Outfit. Charm +2, charm stronger.", "服装。魅力+2、愛嬌が強くなる。"),
"i_nia_work": ("Nia — navy blazer", "ニア — 紺のブレザー"), "id_nia_work": ("Outfit. Sharp +1.", "服装。切れ者+1。"),
"i_nia_after": ("Nia — emerald satin", "ニア — エメラルドのサテン"), "id_nia_after": ("Outfit. Charm +2, spin stronger.", "服装。魅力+2、言いくるめが強くなる。"),
"i_sol_work": ("Sol — cardigan", "ソル — カーディガン"), "id_sol_work": ("Outfit. Calm +1.", "服装。冷静+1。"),
"i_sol_after": ("Sol — burgundy wrap", "ソル — ワインのラップドレス"), "id_sol_after": ("Outfit. Charm +2, charm stronger.", "服装。魅力+2、愛嬌が強くなる。"),
"i_keyring": ("Mara's keyring", "マーラの鍵束"), "id_keyring": ("Accessory (Mara). Sharp +1.", "装飾品（マーラ）。切れ者+1。"),
"i_gold_lanyard": ("Gold lanyard", "金の名札紐"), "id_gold_lanyard": ("Accessory. Charm +1, Sharp +1.", "装飾品。魅力+1、切れ者+1。"),
"i_earpiece": ("Earpiece", "イヤーピース"), "id_earpiece": ("Accessory. Calm +2.", "装飾品。冷静+2。"),
"i_safety_glasses": ("Safety glasses", "保護メガネ"), "id_safety_glasses": ("Accessory (Priya). Nerve +1.", "装飾品（プリヤ）。度胸+1。"),
"i_fountain_pen": ("Varga's fountain pen", "ヴァルガの万年筆"), "id_fountain_pen": ("Accessory. Sharp +2, paperwork stronger.", "装飾品。切れ者+2、書類が強くなる。"),
"i_press_pass": ("An old press pass", "古い記者証"), "id_press_pass": ("Accessory. Charm +2.", "装飾品。魅力+2。"),
"i_clipboard": ("Clipboard", "クリップボード"), "id_clipboard": ("Tool. Sharp +1, spin stronger.", "道具。切れ者+1、言いくるめが強くなる。"),
"i_tablet": ("Building tablet", "ビル管理タブレット"), "id_tablet": ("Tool. Calm +1, coffee breaks stronger.", "道具。冷静+1、コーヒー休憩が強くなる。"),
"i_thermos": ("Steel thermos", "スチールの魔法瓶"), "id_thermos": ("Tool. Nerve +2.", "道具。度胸+2。"),
"i_toolbelt": ("Priya's toolbelt", "プリヤの工具ベルト"), "id_toolbelt": ("Tool (Priya). Nerve +1, fixes stronger.", "道具（プリヤ）。度胸+1、修理が強くなる。"),
"i_orchid": ("A white orchid", "白い蘭"), "id_orchid": ("A gift for Mirei. +1 trust.", "ミレイへの贈り物。信頼+1。"),
"i_whisky": ("A good single malt", "上等なシングルモルト"), "id_whisky": ("A gift for Mara. +1 trust.", "マーラへの贈り物。信頼+1。"),
"i_craft_beer": ("A four-pack of sour beer", "サワービール四本"), "id_craft_beer": ("A gift for Priya. +1 trust.", "プリヤへの贈り物。信頼+1。"),
"i_ink": ("A bottle of green ink", "緑のインク瓶"), "id_ink": ("A gift for Nia. +1 trust.", "ニアへの贈り物。信頼+1。"),
"i_first_edition": ("A first edition", "初版本"), "id_first_edition": ("A gift for Sol. +1 trust.", "ソルへの贈り物。信頼+1。"),
# skill branches and skills
"br_keys": ("Keys", "鍵"), "br_steel": ("Steel", "鋼"), "br_tools": ("Tools", "工具"), "br_banter": ("Banter", "軽口"),
"br_ledger": ("Ledger", "帳簿"), "br_poise": ("Poise", "品位"), "br_press": ("Press", "報道"), "br_warmth": ("Warmth", "温もり"),
"sk_m_ring": ("Every key on one ring", "鍵はひとつの輪に"), "skd_m_ring": ("Paperwork +30%.", "書類+30%。"),
"sk_m_plan": ("Floor plans by heart", "図面は頭の中"), "skd_m_plan": ("Sharp +2.", "切れ者+2。"),
"sk_m_master": ("The master key", "マスターキー"), "skd_m_master": ("Grants Master keys.", "「マスターキー」を習得。"),
"sk_m_lockdown": ("Lockdown", "封鎖"), "skd_m_lockdown": ("Master keys +40%.", "マスターキー+40%。"),
"sk_m_steady": ("Night-shift steady", "夜勤の落ち着き"), "skd_m_steady": ("Composure +10.", "平静+10。"),
"sk_m_glare": ("The eyebrow", "眉ひとつ"), "skd_m_glare": ("Call security +30%.", "警備を呼ぶ+30%。"),
"sk_m_spine": ("Spine", "背骨"), "skd_m_spine": ("Nerve +2.", "度胸+2。"),
"sk_p_wrench": ("Heavy wrench", "重いレンチ"), "skd_p_wrench": ("Nerve +2.", "度胸+2。"),
"sk_p_fix": ("Fix it now", "今すぐ直す"), "skd_p_fix": ("Grants Fix it on the spot.", "「その場で直す」を習得。"),
"sk_p_overtime": ("On the clock", "時間外手当"), "skd_p_overtime": ("Fix it on the spot +40%.", "その場で直す+40%。"),
"sk_p_grin": ("The grin", "あの笑顔"), "skd_p_grin": ("Charm +30%.", "愛嬌+30%。"),
"sk_p_tease": ("Teasing", "からかい"), "skd_p_tease": ("Charm stat +2.", "魅力+2。"),
"sk_p_wink": ("A wink", "ウインク"), "skd_p_wink": ("Spin it +30%.", "言いくるめ+30%。"),
"sk_n_columns": ("Columns", "列"), "skd_n_columns": ("Paperwork +30%.", "書類+30%。"),
"sk_n_audit": ("Forensic eye", "鑑識の目"), "skd_n_audit": ("Grants Audit them.", "「監査する」を習得。"),
"sk_n_forensic": ("Six years in an hour", "六年を一時間で"), "skd_n_forensic": ("Audit them +40%.", "監査+40%。"),
"sk_n_glasses": ("Over the glasses", "眼鏡越し"), "skd_n_glasses": ("Sharp +2.", "切れ者+2。"),
"sk_n_dry": ("Dry", "辛口"), "skd_n_dry": ("Spin it +30%.", "言いくるめ+30%。"),
"sk_n_cold": ("Cold read", "冷たい読み"), "skd_n_cold": ("Composure +12.", "平静+12。"),
"sk_s_lede": ("The lede", "リード文"), "skd_s_lede": ("Charm +30%.", "愛嬌+30%。"),
"sk_s_headline": ("Front page", "一面"), "skd_s_headline": ("Grants Headline.", "「見出し」を習得。"),
"sk_s_front": ("Stop the presses", "輪転機を止めろ"), "skd_s_front": ("Headline +40%.", "見出し+40%。"),
"sk_s_tea": ("Kettle on", "やかんを火に"), "skd_s_tea": ("Coffee break +30%.", "コーヒー休憩+30%。"),
"sk_s_warm": ("Warm voice", "温かい声"), "skd_s_warm": ("Charm stat +2.", "魅力+2。"),
"sk_s_late": ("Files at four", "四時に入稿"), "skd_s_late": ("Composure +12.", "平静+12。"),
# the office (scripts/office.gd): the board, the shift, recruiting, supplies
"of_title": ("The office — %s", "オフィス — %s"),
"of_fund": ("Rent fund $%d", "家賃資金 $%d"),
"of_rent": ("Rent due tonight: $%d", "今夜の家賃：$%d"),
"of_preview": ("This layout: $%d a shift × %d shifts = $%d tonight", "この配置：1シフト$%d × %dシフト = 今夜$%d"),
"of_chain": ("Links %d · chain ×%.2f", "連鎖 %d · 倍率×%.2f"),
"of_ran": ("Shift run: +$%d to the rent fund.", "シフト完了：家賃資金 +$%d。"),
"of_ran_short": ("Tonight's shift is done (+$%d).", "今夜のシフトは完了（+$%d）。"),
"of_run": ("Run the night shift", "夜勤シフトを回す"),
"of_run_hint": ("Place staff and objects on the floor, then run the shift once. Links between neighbours multiply the whole floor.", "スタッフと備品をフロアに置いてから、シフトを一度だけ回す。隣同士の連携がフロア全体を倍増させる。"),
"of_pieces": ("Staff and objects — pick one, then a desk", "スタッフと備品 — 選んでから机へ"),
"of_clear": ("Clear the floor", "フロアを空にする"),
"of_auto": ("Suggest a layout", "配置を提案"),
"of_recruit": ("Recruit ($%d)", "採用（$%d）"),
"of_recruit10": ("Recruit ×10 ($%d)", "10連採用（$%d）"),
"of_pity": ("An epic recruit is guaranteed within %d more.", "あと%d回以内にエピック確定。"),
"of_got": ("Recruited: %s (%s)", "採用：%s（%s）"),
"of_dupe": ("%s again — overtime bonus +5%%, and %s +1.", "%sが再び — 残業ボーナス+5%%、%s+1。"),
"of_dupe_board": ("%s again — overtime bonus +5%%.", "%sが再び — 残業ボーナス+5%%。"),
"of_joined": ("%s joins the staff — and the party.", "%sがスタッフに — そしてパーティに加わった。"),
"of_supplies": ("Supplies", "備品・購買"),
"of_buy": ("%s — $%d", "%s — $%d"),
"of_owned": ("owned %d", "所持 %d"),
"of_done": ("Back to the floor", "フロアに戻る"),
"of_broke": ("Not enough in the rent fund.", "家賃資金が足りない。"),
"of_rarity_common": ("common", "コモン"), "of_rarity_rare": ("rare", "レア"), "of_rarity_epic": ("epic", "エピック"),
"of_events": ("On this floor: %s", "このフロアで：%s"),
"of_none": ("nothing linked yet", "まだ連携なし"),
"of_trust": ("%s worked the floor you built (+1 trust).", "%sがあなたの組んだフロアで働いた（信頼+1）。"),
"of_rule": ("%s — %s", "%s — %s"),
"of_tab_floor": ("Floor", "フロア"), "of_tab_recruit": ("Recruit", "採用"), "of_tab_supplies": ("Supplies", "購買"),
"of_no_money_note": ("Recruiting uses the in-game rent fund only.", "採用はゲーム内の家賃資金のみで行います。"),
# board pieces (the rule text is the committed Overtime design's, unchanged)
"pc_coffee": ("Coffee", "コーヒー"), "pr_coffee": ("Pays 2. Beside Dan: ×3.", "2を生む。ダンの隣で×3。"),
"pc_mute": ("Headphones", "ヘッドホン"), "pr_mute": ("Pays 4. Shields Dan, Priya, Mara beside them from Wes.", "4を生む。隣のダン・プリヤ・マーラをウェスから守る。"),
"pc_printer": ("Printer", "プリンター"), "pr_printer": ("Pays 2, +1 for every other piece in its row.", "2を生む。同じ列の他の駒1つごとに+1。"),
"pc_corner": ("Corner plant", "角の観葉植物"), "pr_corner": ("Pays 3, but only in a corner.", "3を生む。ただし角でのみ。"),
"pc_dan": ("Dan", "ダン"), "pr_dan": ("Pays 3. Coffee beside him triples. Headphones beside him +2.", "3を生む。隣のコーヒーは3倍。隣のヘッドホンで+2。"),
"pc_priya": ("Priya", "プリヤ"), "pr_priya": ("Copies the best base beside her.", "隣で一番高い基本値をコピーする。"),
"pc_mara": ("Mara", "マーラ"), "pr_mara": ("Every neighbour +1.", "隣すべて+1。"),
"pc_wes": ("Wes", "ウェス"), "pr_wes": ("Pays 2. Taxes unshielded Dan and Priya beside him. Tag: noise.", "2を生む。守られていない隣のダンとプリヤから徴収。騒音タグ。"),
"pc_nia": ("Nia", "ニア"), "pr_nia": ("Audits Wes: each Wes beside her pays her his 2.", "ウェスを監査：隣のウェス1人ごとに2を受け取る。"),
"pc_sol": ("Sol", "ソル"), "pr_sol": ("Coffee beside her +2 to her. Floor: every other staff +1.", "隣のコーヒーで+2。フロア全体：他のスタッフ全員+1。"),
"ev_coffee-dan": ("coffee × Dan", "コーヒー×ダン"), "ev_dan-mute": ("Dan in headphones", "ヘッドホンのダン"),
"ev_mute-shield": ("headphones shield", "ヘッドホンの防壁"), "ev_priya-copy": ("Priya covers", "プリヤの代役"),
"ev_print-job": ("print run", "印刷"), "ev_mara-boost": ("Mara lifts", "マーラの底上げ"),
"ev_wes-tax": ("Wes's tax", "ウェスの徴収"), "ev_nia-audit": ("Nia audits Wes", "ニアの監査"),
"ev_sol-late": ("Sol's late coffee", "ソルの夜更けのコーヒー"), "ev_sol-floor": ("Sol keeps the floor late", "ソルが残るフロア"),
"ev_tag-staff": ("staff together", "スタッフの連携"), "ev_tag-fuel": ("fuel together", "燃料の連携"),
"ev_tag-noise": ("noise together", "騒音の連携"), "ev_tag-infra": ("infrastructure", "設備の連携"),
# trial end (bilingual screen)
"tr_end_title": ("The trial ends here.", "体験版はここまでです。"),
"tr_end_body": ("Floor two is paid. The full game keeps the building running — the sublet on seven, the audit on six, the bailiff in the newsroom, the heir in the penthouse — with Nia and Sol to recruit, two outfits for every woman on staff, and after-hours scenes for each of them and for Mirei.", "二階は払い終えた。製品版ではビルの経営が続く — 七階の又貸し、六階の監査、新聞部の執行官、ペントハウスの相続人。ニアとソルの採用、女性スタッフ全員の二着の衣装、そして彼女たちとミレイそれぞれの終業後の場面。"),
"tr_back": ("Back to title", "タイトルへ戻る"),
}
