#!/usr/bin/env bash
# Regenerate scripts/gc_strings_data.gd from the prototype's i18n.js (en + zh + ja packs).
#
# ja was added on 2026-09-21. It was not a translation job: the prototype's i18n.js has
# carried a complete Japanese pack all along (and es + pt, which stay out), and the port
# simply never pulled it. Audited before wiring -- 130 of 130 leaves present, no key
# falling through to English, nothing shared with the zh pack but the game's own name --
# because the failure to avoid here is Floor 13's: ja offered in the menu, Chinese prose
# underneath. See memory/renpy-translation-blind-spots + the STANDARD, item 7.
cd "$(dirname "$0")/.." && node -e '
const fs=require("fs"),vm=require("vm");
const sb={window:{},localStorage:{getItem:()=>null,setItem:()=>{}},navigator:{language:"en"},document:{documentElement:{},querySelector:()=>null,querySelectorAll:()=>[]}};
sb.window=sb; vm.createContext(sb);
const src=fs.readFileSync("../ghost-channel/i18n.js","utf8").replace("root.GCi18n = {","root.__T = T; root.GCi18n = {");
vm.runInContext(src,sb);
const T={en:sb.__T.en, zh:sb.__T.zh, ja:sb.__T.ja};
fs.writeFileSync("scripts/gc_strings_data.gd","## GCStringsData — the en, zh and ja packs of play/ghost-channel/i18n.js, verbatim.\n## Generated by tools/gen_strings.sh (node over the prototype file); do not edit by hand.\nclass_name GCStringsData\n\nconst T := "+JSON.stringify(T,null,1)+"\n");
'
