#!/usr/bin/env bash
# Regenerate scripts/gc_strings_data.gd from the prototype's i18n.js (en + zh packs).
cd "$(dirname "$0")/.." && node -e '
const fs=require("fs"),vm=require("vm");
const sb={window:{},localStorage:{getItem:()=>null,setItem:()=>{}},navigator:{language:"en"},document:{documentElement:{},querySelector:()=>null,querySelectorAll:()=>[]}};
sb.window=sb; vm.createContext(sb);
const src=fs.readFileSync("../ghost-channel/i18n.js","utf8").replace("root.GCi18n = {","root.__T = T; root.GCi18n = {");
vm.runInContext(src,sb);
const T={en:sb.__T.en, zh:sb.__T.zh};
fs.writeFileSync("scripts/gc_strings_data.gd","## GCStringsData — the en and zh packs of play/ghost-channel/i18n.js, verbatim.\n## Generated by tools/gen_strings.sh (node over the prototype file); do not edit by hand.\nclass_name GCStringsData\n\nconst T := "+JSON.stringify(T,null,1)+"\n");
'
