# Game-wide strings: names, stats, actions, items, skills, enemies, barks, rooms, hotspots,
# and the core keys this game overrides (the core says "Night"/"Dean"; this is a hotel).
# (key: (EN, JA)). New RPG writing follows the VN's voice: short declaratives, present
# tense, second person.
S = {
"title": ("Room 704", "ルーム704"),
"t_subtitle": ("One night. One floor. Nobody in the book.", "ひと晩。ひとつの階。帳簿には誰もいない。"),
"t_note": ("18+ · All characters are adults · AI-generated work (see 'About this work')", "18歳以上対象 · 登場人物は全員成人です · AI生成作品（「作品について」参照）"),
"n_protagonist": ("You", "あなた"), "n_auditor": ("Night auditor", "夜間監査人"), "n_mira": ("Mira", "ミラ"),
"n_man": ("???", "？？？"), "n_gale": ("Gale", "ゲイル"), "n_haskell": ("Haskell", "ハスケル"), "n_penhallow": ("Penhallow", "ペンハロウ"),
"n_dace": ("Mrs Dace", "デイス夫人"), "n_guest212": ("The guest in 212", "212号室の客"), "n_constable": ("Constable", "巡査"),
"n_porter": ("Lenny", "レニー"),
# core overrides
"ev_trust": ("Mira's trust +%d", "ミラの信頼 +%d"),
"lose_standoff_t": ("The shift ends early", "シフトは早く終わった"),
"lose_standoff": ("Suspicion boiled over: somebody picked up a phone. Nothing is lost but the last few minutes — you are back at the last save, just before the standoff.", "疑念が限界を超え、誰かが受話器を取った。失ったのは数分だけ — 対峙の直前のセーブに戻る。"),
"lose_dawn_t": ("Seven o'clock", "七時"),
"lose_dawn": ("The day porter comes on and the night is over without you. You are back at the last save.", "昼番のポーターが出勤し、夜はあなたを置いて終わった。最後のセーブに戻る。"),
"end_t": ("Shift cleared", "シフトを乗り切った"),
"t_trial": ("Trial version — Shift 1", "体験版 — 第一シフト"),
"fin_body": ("Level %d · Trust %d. Thank you for playing. Your last save is in slot 1: replay the last shift for another ending.", "レベル %d · 信頼 %d。プレイしていただきありがとうございました。最後のセーブはスロット1に。最終シフトをやり直すと別のエンディングが見られます。"),
"nc_budget": ("%d turns until the shift ends. Moving, searching and standoffs all cost time.", "シフト終了まで %d 手。移動・調査・対峙はすべて時間を使う。"),
"h_clock": ("%s   ·   %d turns left   ·   Lv %d", "%s　·　残り %d 手　·　Lv %d"),
"ds_adult": ("This game is for adults (18+). All characters are adults. Contains sexual content.", "本作品は成人向け（18歳以上）です。登場人物はすべて成人です。性的な表現を含みます。"),
"about_ai": ("AI disclosure: This work uses generative AI. All character art, backgrounds and event CGs were generated with Animagine XL (an image model) and then selected and composited by the developer. The spoken lines are synthesised with CosyVoice (a text-to-speech model). The story, dialogue and game code were written with the help of AI language models and edited, directed and tested by the developer.",
             "AI使用について：本作は生成AIを使用しています。キャラクター立ち絵・背景・イベントCGは画像生成AI「Animagine⁠ ⁠XL」で生成し、開発者が選定・合成しています。ボイスは音声合成AI「CosyVoice」による合成音声です。シナリオ・テキストおよびプログラムもAI（大規模言語モデル）の支援を受けて作成し、開発者が編集・監修・テストしています。"),
"tr_end_title": ("This is where the trial ends.", "体験版はここまで"),
"tr_end_body": ("Shifts 2 and 3 and the epilogue, Mira in the party, all three routes and three endings, every standoff and boss, the full gallery and growth to level 20 are in the full version. Your trial save carries over.",
                "第二・第三シフトとエピローグ、仲間になるミラ、3つのルートと3種のエンディング、すべての対峙とボス、ギャラリー、レベル20までの成長は製品版に収録されています。体験版のセーブデータは製品版に引き継げます。"),
"tr_open_store": ("Open the product page", "製品版のページを開く"), "tr_back": ("Back to the title", "タイトルに戻る"),
"credits_1": ("ROOM 704 — the RPG edition. Writing, art direction and code: Flat 404. Art: Animagine XL. Voice: CosyVoice.", "ROOM 704 — RPG版。脚本・アートディレクション・プログラム：Flat 404。画像：Animagine XL。音声：CosyVoice。"),
"credits_2": ("Thank you for staying the night.", "ご宿泊ありがとうございました。"),
# stats
"s_wit": ("Wits", "機転"), "s_cha": ("Charm", "魅力"), "s_grt": ("Grit", "根性"), "s_stl": ("Discretion", "口の堅さ"),
"sd_wit": ("Bluffs, evidence, nerve pool.", "はったり・証拠・胆力の上限。"), "sd_cha": ("Bribes and charm.", "買収と魅了。"),
"sd_grt": ("Composure, and how hard a threat lands.", "平静の上限と、脅しの重さ。"), "sd_stl": ("Stalling brings suspicion down further.", "時間稼ぎで疑念を大きく下げる。"),
# actions
"a_deflect": ("Deflect", "受け流す"), "a_observe": ("Read him", "相手を読む"), "a_bluff": ("Bluff", "はったり"),
"a_evidence": ("Show the book", "帳簿を示す"), "a_bribe": ("Bribe", "買収"), "a_flirt": ("Flirt", "誘惑"),
"a_threaten": ("Threaten", "脅す"), "a_stall": ("Stall", "時間稼ぎ"), "a_item": ("Use item", "アイテム"),
"a_houseline": ("The house line", "ホテルの決まり文句"), "a_confide": ("Tell him the truth", "本当のことを話す"),
"ad_deflect": ("Halve the next blow and cool the room a little.", "次の一撃を和らげ、疑念を少し下げる。"),
"ad_observe": ("Mira reads them: reveals their weaknesses.", "ミラが相手を読む：弱点が分かる。"),
"ad_bluff": ("A confident lie. Wits.", "自信たっぷりの嘘。機転。"),
"ad_evidence": ("Put a page in front of them. Lowers suspicion. Needs evidence.", "書類を突きつける。疑念が下がる。証拠品が必要。"),
"ad_bribe": ("Folded notes. Charm. Uses one cash.", "折った紙幣。魅力。現金を一つ使う。"),
"ad_flirt": ("Warmth where they did not expect it. Charm.", "思いがけない温かさ。魅力。"),
"ad_threaten": ("Hits hard — and they remember. Suspicion climbs faster for the rest of the standoff.", "強烈だが、相手は忘れない。以後この対峙では疑念が速く上がる。"),
"ad_stall": ("Talk about the rain. Suspicion falls; a little composure back.", "雨の話でもする。疑念が下がり、平静が少し戻る。"),
"ad_item": ("Use something from behind the desk.", "持ち物を使う。"),
"ad_houseline": ("'The hotel doesn't discuss guests.' Said with twenty years behind it. Lowers suspicion.", "「当ホテルはお客様についてお話ししません」。二十年分の重みで言う。疑念が下がる。"),
"ad_confide": ("Mira tells one true thing, plainly. Nobody is ready for that. Lowers suspicion.", "ミラが本当のことをひとつ、淡々と話す。誰も身構えていない。疑念が下がる。"),
# items
"i_cash": ("Her banknotes", "彼女の紙幣"), "id_cash": ("From the stack she put on the counter. For bribes.", "彼女がカウンターに置いた札束から。買収用。"),
"i_coffee": ("Desk coffee", "デスクのコーヒー"), "id_coffee": ("Restores 16 composure.", "平静を16回復。"),
"i_whisky": ("Tooth-glass whisky", "歯磨きコップのウイスキー"), "id_whisky": ("Restores 8 nerve.", "胆力を8回復。"),
"i_minibar": ("Minibar chocolate", "ミニバーのチョコ"), "id_minibar": ("Restores 28 composure. Billed to nobody.", "平静を28回復。請求先はなし。"),
"i_aspirin": ("Aspirin", "アスピリン"), "id_aspirin": ("Restores 14 nerve.", "胆力を14回復。"),
"i_passkey": ("Pass key", "マスターキー"), "id_passkey": ("Opens every door in the Marbeck except the ones that matter.", "マーベックのどの扉も開く。肝心な扉を除いて。"),
"i_basement_key": ("Basement key", "地下の鍵"), "id_basement_key": ("Mrs Dace keeps it on a nail. Now it is in your pocket.", "デイス夫人が釘に掛けていたもの。今はあなたのポケットに。"),
"i_card_gale": ("His card", "彼の名刺"), "id_card_gale": ("Evidence. A number, no name. He left it on the counter.", "証拠。番号だけで名前はない。彼がカウンターに置いていった。"),
"i_register_page": ("Register page", "宿帳のページ"), "id_register_page": ("Evidence. The fourth floor, fourth row: a clean line.", "証拠。四階の四行目：きれいな空白。"),
"i_cctv_tape": ("CCTV tape", "防犯カメラのテープ"), "id_cctv_tape": ("Evidence. The lobby camera has not recorded since March. Nobody knows that but you.", "証拠。ロビーのカメラは三月から録画していない。知っているのはあなただけ。"),
"i_ledger704": ("The quarterly ledger", "四半期の帳簿"), "id_ledger704": ("Evidence. Room 704 has been 'out of order' on paper for two years. It was let every week.", "証拠。704号室は書類上、二年間「故障中」。毎週貸し出されていた。"),
"i_train_ticket": ("Her train ticket", "彼女の列車の切符"), "id_train_ticket": ("Six-forty. Nine days old. Give it back to her, or don't.", "六時四十分発。九日前のもの。返すか、返さないか。"),
"i_umbrella": ("Hotel umbrella", "ホテルの傘"), "id_umbrella": ("Accessory. Wits +1. Nobody ever brings them back.", "アクセサリー。機転+1。誰も返しに来ない。"),
"i_lighter": ("His lighter", "彼のライター"), "id_lighter": ("Tool. Discretion +1, Stall stronger. Gale's. He will want it back.", "道具。口の堅さ+1、時間稼ぎ強化。ゲイルのもの。取り戻しに来るだろう。"),
"i_torch": ("Rubber torch", "ゴム製の懐中電灯"), "id_torch": ("Tool. Discretion +1.", "道具。口の堅さ+1。"),
"i_revolver": ("The drawer revolver", "引き出しの回転式拳銃"), "id_revolver": ("Tool. Grit +2, Threaten stronger. It has never been fired. It will not be tonight.", "道具。根性+2、脅し強化。一度も撃たれたことはない。今夜も撃たれない。"),
"i_waistcoat": ("Hotel waistcoat", "ホテルのベスト"), "id_waistcoat": ("Outfit. Grit +1.", "衣装。根性+1。"),
"i_namebadge": ("Name badge", "名札"), "id_namebadge": ("Accessory. Charm +1. People trust a name they can read.", "アクセサリー。魅力+1。読める名前は信用される。"),
"i_coat": ("Her long coat", "彼女のロングコート"), "id_coat": ("Outfit. Grit +1. Still wet at the hem.", "衣装。根性+1。裾がまだ濡れている。"),
"i_slip": ("The black slip", "黒のスリップドレス"), "id_slip": ("Outfit. Charm +1, Flirt stronger. Not chosen for the rain.", "衣装。魅力+1、誘惑強化。雨の夜向きではない。"),
"i_shirt": ("Your spare shirt", "あなたの替えのシャツ"), "id_shirt": ("Outfit. Charm +2, Flirt stronger. Too big for her. That is the point.", "衣装。魅力+2、誘惑強化。彼女には大きすぎる。それがいい。"),
"i_robe": ("Hotel bathrobe", "ホテルのバスローブ"), "id_robe": ("Outfit. Wits +1, Stall stronger. The Marbeck's one luxury.", "衣装。機転+1、時間稼ぎ強化。マーベック唯一の贅沢。"),
"i_lace": ("What was under the dress", "ドレスの下にあったもの"), "id_lace": ("Outfit. Charm +3, Flirt much stronger. Not for corridors.", "衣装。魅力+3、誘惑大幅強化。廊下向きではない。"),
# skill branches
"br_clerk": ("Clerk", "番台"), "br_fixer": ("Fixer", "始末屋"), "br_ghost": ("Ghost", "幽霊"), "br_flame": ("Flame", "灯火"),
"sk_ledger": ("The ledger", "帳簿"), "skd_ledger": ("Show the book +30%.", "帳簿を示す +30%。"),
"sk_nightshift": ("Night shift", "夜勤"), "skd_nightshift": ("Composure +10.", "平静の上限 +10。"),
"sk_arithmetic": ("Mental arithmetic", "暗算"), "skd_arithmetic": ("Wits +2.", "機転 +2。"),
"sk_houseline_sk": ("Twenty years at a desk", "番台二十年"), "skd_houseline_sk": ("Learn The house line.", "「ホテルの決まり文句」を習得。"),
"sk_auditor": ("Auditor", "監査人"), "skd_auditor": ("House line +40%, book +20%.", "決まり文句 +40%、帳簿 +20%。"),
"sk_tip": ("The tip", "チップ"), "skd_tip": ("Bribe +30%.", "買収 +30%。"),
"sk_deadpan": ("Deadpan", "無表情"), "skd_deadpan": ("Bluff +30%.", "はったり +30%。"),
"sk_thickskin": ("Thick skin", "面の皮"), "skd_thickskin": ("Grit +2.", "根性 +2。"),
"sk_backdoor": ("Back door", "裏口"), "skd_backdoor": ("Stall +40%.", "時間稼ぎ +40%。"),
"sk_quietword": ("A quiet word", "静かな一言"), "skd_quietword": ("Threaten +40%, bluff +20%.", "脅し +40%、はったり +20%。"),
"sk_unseen": ("Unseen", "見えない女"), "skd_unseen": ("Discretion +2.", "口の堅さ +2。"),
"sk_coolhead": ("Cool head", "冷静"), "skd_coolhead": ("Composure +10.", "平静の上限 +10。"),
"sk_straightface": ("Straight face", "真顔の嘘"), "skd_straightface": ("Bluff +40%.", "はったり +40%。"),
"sk_vanish": ("Vanish", "消える"), "skd_vanish": ("Stall +40%.", "時間稼ぎ +40%。"),
"sk_nobody": ("Nobody", "誰でもない"), "skd_nobody": ("Bluff +30%, stall +20%.", "はったり +30%、時間稼ぎ +20%。"),
"sk_smile": ("That laugh", "あの笑い声"), "skd_smile": ("Flirt +30%.", "誘惑 +30%。"),
"sk_confide_sk": ("Plain answers", "率直な答え"), "skd_confide_sk": ("Learn Tell him the truth.", "「本当のことを話す」を習得。"),
"sk_poise": ("Poise", "落ち着き"), "skd_poise": ("Charm +2.", "魅力 +2。"),
"sk_candle": ("Candle", "蝋燭"), "skd_candle": ("Tell him the truth +40%.", "本当のことを話す +40%。"),
"sk_ember": ("Ember", "熾火"), "skd_ember": ("Flirt +40%, truth +20%.", "誘惑 +40%、本当のこと +20%。"),
# enemies
"e_guest212": ("The guest in 212, drunk", "212号室の客、酔っている"), "e_guest212_2": ("The guest in 212, in the lift", "エレベーターの中の212号室の客"),
"e_haskell": ("Haskell, the house detective", "ホテル探偵ハスケル"), "e_haskell_2": ("Haskell, on the fourth floor", "四階のハスケル"), "e_haskell_3": ("Haskell, with the register", "宿帳を持ったハスケル"),
"e_dace_phone": ("Mrs Dace, on the internal line", "内線のデイス夫人"), "e_dace": ("Mrs Dace, the night manager", "夜間支配人デイス夫人"), "e_dace_2": ("Mrs Dace, in the laundry", "洗濯室のデイス夫人"),
"e_gale": ("The man from the car", "車の男"), "e_gale_2": ("Gale, on the fourth floor", "四階のゲイル"),
"e_constable": ("A constable, at the roof door", "屋上の扉の巡査"), "e_constable_2": ("The constable, in the alley", "路地の巡査"),
"e_penhallow": ("Mr Penhallow, the owner's man", "オーナーの代理人ペンハロウ氏"), "e_porter": ("Lenny, the day porter", "昼番のポーター、レニー"),
"ei_guest212": ("The guest from 212 has found his way to the bar and wants it open. He has the keys to nothing and the confidence of a man who has paid.", "212号室の客がバーまで降りてきて、開けろと言う。鍵はひとつも持っていないが、金を払った男の自信がある。"),
"ew_guest212": ("He goes back up with a glass of water he thinks is gin.", "彼はジンだと思っている水のグラスを持って上がっていった。"),
"ei_guest212_2": ("The lift has stopped between floors with the guest from 212 inside it, and he has decided this is your fault.", "エレベーターが階の途中で止まり、中には212号室の客。彼はこれがあなたのせいだと決めた。"),
"ew_guest212_2": ("The lift remembers how to move. He forgets what he was angry about.", "エレベーターは動き方を思い出し、彼は何に怒っていたかを忘れた。"),
"ei_haskell": ("Haskell does the floors at three. He has done them for eleven years and he has never once found nothing.", "ハスケルは三時に各階を回る。十一年続けて、一度も「何もなし」で終わったことがない。"),
"ew_haskell": ("Haskell writes 'quiet' in his notebook, and underlines it, and does not believe it.", "ハスケルは手帳に「異常なし」と書き、下線を引き、それを信じていない。"),
"ei_haskell_2": ("Haskell, on the fourth floor, with a complaint from 702 about voices and a torch he does not need.", "四階のハスケル。702号室から声がするとの苦情と、必要のない懐中電灯を携えて。"),
"ew_haskell_2": ("He turns the torch off. 'Voices. In a hotel. I'll write it up as the pipes.'", "彼は懐中電灯を消す。「声ね。ホテルで。配管の音ってことにしとく」"),
"ei_haskell_3": ("Haskell has the register open at the fourth floor. He is not reading it. He is waiting for you to.", "ハスケルは宿帳の四階のページを開いている。読んではいない。あなたが読むのを待っている。"),
"ew_haskell_3": ("He closes the book. 'Eleven years. I know what a quiet night looks like. This wasn't one. Goodnight.'", "彼は帳簿を閉じる。「十一年だ。静かな夜がどんなものかは知ってる。今夜は違った。おやすみ」"),
"ei_dace_phone": ("The internal line. Mrs Dace, from the sixth floor, who heard the lift and wants to know who is in her hotel.", "内線。六階のデイス夫人。エレベーターの音を聞いて、自分のホテルに誰がいるのか知りたがっている。"),
"ew_dace_phone": ("'Well. Keep it quiet.' The line clicks. The sixth floor goes back to sleep.", "「そう。静かにね」回線が切れる。六階はまた眠りにつく。"),
"ei_dace": ("Mrs Dace on the landing in a quilted dressing gown, with a cordless phone and the expression of a woman who owns the building.", "踊り場のデイス夫人。キルトのガウン、コードレス電話、そしてこの建物の所有者の顔。"),
"ew_dace": ("'I did not see her. I did not see you. I saw a draught.' She goes back up.", "「彼女は見なかった。あなたも見なかった。見たのは隙間風」彼女は上へ戻った。"),
"ei_dace_2": ("Mrs Dace is in the laundry at half past six, folding sheets that are not hers to fold, because she could not sleep either.", "六時半の洗濯室にデイス夫人。自分の仕事ではないシーツを畳んでいる。彼女も眠れなかったのだ。"),
"ew_dace_2": ("She hands you a folded sheet. 'For the room. It'll want making up before nine.'", "彼女は畳んだシーツを渡す。「部屋の分。九時までに整えておきなさい」"),
"ei_gale": ("He is not a policeman. A policeman would have led with being a policeman. He is waiting, and the register is on the counter between you.", "彼は警察ではない。警察なら、まず警察だと名乗る。彼は待っている。宿帳はあなたと彼の間のカウンターの上だ。"),
"ew_gale": ("He puts a card on the counter. You leave it there. He goes. The rain takes him.", "彼はカウンターに名刺を置く。あなたはそのままにする。彼は出て行く。雨が彼を連れ去る。"),
"ei_gale_2": ("Gale, on the fourth floor. He came up the service stair. He has her name now, and the number of the room, and still he knocks.", "四階のゲイル。業務用階段を上ってきた。今や彼女の名前も部屋番号も知っている。それでもノックする。"),
"ew_gale_2": ("He looks at the door of 704 for a long time, and then he goes down the way he came.", "彼は704号室の扉を長いこと見つめ、来た道を戻っていった。"),
"ei_constable": ("A constable at the roof door, called out for a welfare check on a woman he has never met by a man who would not give his name.", "屋上の扉に巡査。名乗らない男からの、会ったこともない女性の安否確認の通報で来た。"),
"ew_constable": ("'Welfare's fine, then.' He radios it in as a hoax and goes to find his car.", "「じゃあ安否は問題なし」彼は無線で悪戯だと報告し、車を探しに行った。"),
"ei_constable_2": ("The constable again, in the alley, with a different question: whose car was that, and why has it gone.", "路地にまた巡査。今度の質問は違う。あの車は誰のもので、なぜ消えたのか。"),
"ew_constable_2": ("He writes down the registration you give him, which is wrong, and thanks you for it.", "彼はあなたが教えた偽のナンバーを書き留め、礼を言った。"),
"ei_penhallow": ("Mr Penhallow, for the owner, at a quarter to seven, with a briefcase and a cheque with Gale's handwriting on it. He would like to see the fourth floor's row.", "六時四十五分、オーナーの代理でペンハロウ氏。鞄と、ゲイルの筆跡の小切手を携えて。四階の行を見たいという。"),
"ew_penhallow": ("He puts the cheque back in the briefcase, unsigned. 'A quiet hotel. The owner will be pleased.'", "彼は未署名の小切手を鞄に戻す。「静かなホテルだ。オーナーも喜ぶだろう」"),
"ei_porter": ("Lenny comes on at seven and asks if anything happened. Lenny always asks.", "七時にレニーが出勤し、何かあったかと聞く。レニーはいつも聞く。"),
"ew_porter": ("'Quiet night, then.' He takes the paper and the register and does not look at either.", "「静かな夜だったんだな」彼は新聞と宿帳を受け取り、どちらも見なかった。"),
"bark_guest212_1": ("\"I'm a guest. I'm a paying guest.\"", "「俺は客だぞ。金払ってる客だ」"),
"bark_guest212_2": ("\"There's a woman upstairs who isn't in the book. I heard.\"", "「上に帳簿に載ってない女がいるんだろ。聞いたぞ」"),
"bark_guest212_3": ("\"One drink. Then I'll go up. Then you'll never know I was here.\"", "「一杯だけ。そしたら上に戻る。俺がいたことも忘れるさ」"),
"bark_haskell_1": ("\"Eleven years on nights. I've seen every kind of quiet.\"", "「夜勤十一年だ。あらゆる種類の静けさを見てきた」"),
"bark_haskell_2": ("\"Fourth floor hook's empty. Fourth floor's closed. Explain that to me slowly.\"", "「四階の鍵が一本ない。四階は閉鎖中だ。ゆっくり説明してくれ」"),
"bark_haskell_3": ("\"I don't need the police. I need you to stop looking at the stairs.\"", "「警察はいらん。階段を見るのをやめてくれればいい」"),
"bark_dace_1": ("\"This is my hotel. I hear every door in it.\"", "「ここは私のホテルよ。扉の音はすべて聞こえる」"),
"bark_dace_2": ("\"Forty rooms, eleven guests. I can count. Can you?\"", "「四十室に十一人。数えられるわ。あなたは？」"),
"bark_dace_3": ("\"If the owner's man asks, I was asleep. Was I?\"", "「オーナーの人に聞かれたら、私は寝てたことにする。寝てたのよね？」"),
"bark_gale_1": ("\"Woman, late twenties, pale hair. These last two hours.\"", "「女だ。二十代後半、淡い髪。この二時間のうちに来た」"),
"bark_gale_2": ("\"I pay for the account. I'm entitled to know where it sleeps.\"", "「口座の金は俺が払ってる。どこで寝てるか知る権利がある」"),
"bark_gale_3": ("\"There's one gap on the fourth row.\"", "「四行目に空きがひとつある」"),
"bark_gale_4": ("\"I can wait. I've a car and a full tank.\"", "「待てるさ。車はあるし、ガソリンも満タンだ」"),
"bark_constable_1": ("\"Welfare check, sir. A caller was concerned.\"", "「安否確認です。通報者が心配していまして」"),
"bark_constable_2": ("\"I'll need to see the register. Procedure.\"", "「宿帳を見せてもらいます。手続きですので」"),
"bark_constable_3": ("\"Nobody gives their name at four in the morning. I've noticed that.\"", "「朝四時に名乗る人はいませんね。そういうものだと気づきました」"),
"bark_penhallow_1": ("\"The owner is a patient man. I am paid to be less so.\"", "「オーナーは辛抱強い。私は辛抱しないために雇われている」"),
"bark_penhallow_2": ("\"Room 704 is out of order. It has been for two years. Who is in it?\"", "「704号室は故障中だ。二年前からね。誰が泊まっている？」"),
"bark_penhallow_3": ("\"A night auditor audits. He does not editorialise.\"", "「夜間監査人は監査をするものだ。論評はしない」"),
"bark_penhallow_4": ("\"I know what a clean line in a register costs. I have paid for several.\"", "「宿帳のきれいな空白にいくらかかるかは知っている。何度も払ってきた」"),
"bark_porter_1": ("\"Anything happen?\"", "「何かあった？」"),
"bark_porter_2": ("\"The fourth floor's hook. I only ask because I'll be the one asked.\"", "「四階の鍵。聞くのは、俺が聞かれる側になるからさ」"),
"bark_porter_3": ("\"Quiet night, you'll say. You always say.\"", "「静かな夜だった、って言うんだろ。いつもそうだ」"),
# rooms
"r_lobby": ("Lobby", "ロビー"), "r_back_office": ("Back office", "事務室"), "r_bar": ("The Marbeck Bar", "マーベック・バー"),
"r_kitchen": ("Service kitchen", "業務用厨房"), "r_lift": ("Lift lobby", "エレベーターホール"), "r_service_stair": ("Service stair", "業務用階段"),
"r_corridor_2": ("Second-floor corridor", "二階の廊下"), "r_room_212": ("Room 212", "212号室"), "r_corridor4": ("Fourth-floor corridor", "四階の廊下"),
"r_room704": ("Room 704", "704号室"), "r_room_702": ("Room 702", "702号室"), "r_linen": ("Linen room", "リネン室"),
"r_roof": ("The roof", "屋上"), "r_manager_flat": ("Mrs Dace's flat", "デイス夫人の部屋"), "r_boiler": ("Boiler room", "ボイラー室"),
"r_laundry": ("Laundry", "洗濯室"), "r_loading_bay": ("Loading bay", "搬入口"), "r_street": ("The street", "通り"),
# hotspots
"hs_register": ("The register", "宿帳"), "hs_keysafe": ("Key safe", "鍵の金庫"), "hs_kettle": ("Kettle", "やかん"), "hs_cctv": ("CCTV monitor", "防犯カメラのモニター"),
"hs_drawer": ("Desk drawer", "デスクの引き出し"), "hs_till": ("The till", "レジ"), "hs_bottles": ("Bottle shelf", "酒棚"), "hs_mirror": ("Bar mirror", "バーの鏡"),
"hs_fridge": ("Walk-in fridge", "業務用冷蔵庫"), "hs_service_door": ("Service door", "業務用ドア"), "hs_pans": ("Hanging pans", "吊るした鍋"),
"hs_dial": ("Floor dial", "階数表示"), "hs_gate": ("Lift gate", "エレベーターの格子扉"), "hs_landing": ("Landing", "踊り場"), "hs_footprints": ("Wet footprints", "濡れた足跡"),
"hs_sconce": ("Dying sconce", "消えかけの壁灯"), "hs_extinguisher": ("Fire extinguisher", "消火器"), "hs_dustsheet": ("Dust sheets", "家具のカバー"), "hs_window212": ("Window", "窓"),
"hs_doors": ("The glass doors", "ガラスのドア"), "hs_phone": ("Desk phone", "デスクの電話"), "hs_car": ("The car", "車"), "hs_noodle": ("Noodle place", "麺屋"),
"hs_newspapers": ("Newspapers", "新聞"), "hs_ashtray": ("Ashtray", "灰皿"), "hs_suitcase": ("Open suitcase", "開いたスーツケース"),
"hs_towels": ("Towel shelves", "タオルの棚"), "hs_chute": ("Laundry chute", "洗濯物シュート"), "hs_ladder": ("Roof ladder", "屋上へのはしご"),
"hs_tank": ("Water tank", "給水タンク"), "hs_sign": ("Back of the sign", "看板の裏"), "hs_parapet": ("Parapet", "パラペット"),
"hs_cat": ("The cat", "猫"), "hs_photos": ("Framed photographs", "写真立て"), "hs_nail": ("Key on a nail", "釘に掛かった鍵"),
"hs_gauges": ("Pressure gauges", "圧力計"), "hs_pipes": ("Pipes", "配管"), "hs_washers": ("Washing machines", "洗濯機"), "hs_sheets": ("Hanging sheets", "干したシーツ"),
"hs_shutter": ("Roller shutter", "シャッター"), "hs_bins": ("Bins", "ゴミ箱"), "hs_puddle": ("Puddle", "水たまり"),
"hs_bed704": ("The bed", "ベッド"), "hs_window704": ("The window", "窓"), "hs_bathroom": ("Bathroom", "バスルーム"), "hs_bag": ("Her canvas bag", "彼女のキャンバスバッグ"),
"hs_corner": ("The corner", "角"), "hs_board": ("Key board", "鍵のボード"),
# shift cards
"n1_title": ("Shift One — The Front Desk", "第一シフト — フロント"),
"n1_sub": ("The Marbeck Residential Hotel. 2:14 AM. Rain.", "マーベック・レジデンシャル・ホテル。午前2時14分。雨。"),
"n2_title": ("Shift Two — The Fourth Floor", "第二シフト — 四階"),
"n2_sub": ("Room 704. 4:10 AM. A car across the road.", "704号室。午前4時10分。通りの向かいに車。"),
"n3_title": ("Shift Three — Six-Forty", "第三シフト — 六時四十分"),
"n3_sub": ("The window is grey. The sign is off.", "窓は灰色。看板は消えた。"),
"n4_title": ("Epilogue — Seven O'Clock", "エピローグ — 七時"),
"n4_sub": ("The day porter comes on.", "昼番のポーターが出勤する。"),
# gallery
"g_cg_checkin": ("Check-in", "チェックイン"), "g_cg_door": ("The door", "扉"), "g_cg_morning": ("Morning", "朝"),
"g_cg_bed": ("The bed", "ベッド"), "g_cg_window": ("The window", "窓"),
"g_cg_rpg_doors": ("Out of the rain", "雨の中から"), "g_cg_rpg_car": ("The car", "車"), "g_cg_rpg_register": ("The fourth row", "四行目"),
"g_cg_rpg_roof_city": ("The roof", "屋上"), "g_cg_rpg_corner": ("The corner", "角"),
"g_cg_trust3_stair": ("The service stair", "業務用階段"), "g_cg_trust5_bath": ("Steam", "湯気"), "g_cg_trust7_sheets": ("Sheets", "シーツ"), "g_cg_trust9_morning": ("Coffee", "コーヒー"),
}
