# Shift 1 — the front desk (EN, JA). The VN's act 1 is kept by line reference; this is the
# room writing around it.
S = {
"n1_open_1": ("The desk is yours until seven. Between now and then: the rounds, the register, and whatever walks in off the street.", "七時まで、このデスクはあなたのものだ。それまでに：見回り、宿帳、そして通りから入ってくる何か。"),
"n1_open_2": ("You have until the shift ends before the day porter asks what happened. Every door, every search and every conversation costs minutes.", "昼番のポーターに「何かあったか」と聞かれるまでが、持ち時間だ。扉も、調べ物も、会話も、すべて数分ずつ食う。"),
"n1_open_3": ("Start with the back office. The pass key is in the safe, and the fourth floor is a long way up without it.", "まずは事務室から。マスターキーは金庫の中。それなしでは四階は遠い。"),
"n1_register_1": ("The register. Forty rooms, eleven names, and on the fourth floor's row, a line as clean as the day it was ruled.", "宿帳。四十室、十一の名前。そして四階の行には、罫線を引いた日のままの空白。"),
"n1_register_2": ("You tear the carbon from under it, carefully, so the page above shows nothing. Paper has a way of becoming useful after midnight.", "下のカーボン紙を慎重に剥がす。上のページには何も残らないように。真夜中を過ぎると、紙切れは役に立つものに化ける。"),
"n1_board_1": ("The key board. Seven-oh-four's hook is empty. So are nineteen others, and nobody can tell which empty hook is the one.", "鍵のボード。704の鉤は空。他にも十九本空いていて、どの空の鉤がそれなのか、誰にも分からない。"),
"n1_board_2": ("You move two keys from the fourth row to the second. Now it is twenty-one, and the pattern is gone.", "四段目の鍵を二本、二段目へ移す。これで二十一本。並びは消えた。"),
"n1_office_1": ("The back office: a key safe, a kettle, a television that has shown the same lobby since March, and the owner's accountant's chair, which nobody sits in.", "事務室。鍵の金庫、やかん、三月から同じロビーを映しているテレビ、そして誰も座らないオーナーの会計士の椅子。"),
"n1_keysafe_1": ("The pass key hangs on the inside of the safe door, where the night manager keeps it so she never has to come down.", "マスターキーは金庫の扉の内側に掛かっている。夜間支配人が降りてこなくて済むように、そこに置いているのだ。"),
"n1_cctv_1": ("The monitor shows the lobby, the doors, the rain. The recorder under it shows a tape that ran out in March. You take it out. Now it never happened.", "モニターにはロビー、ドア、雨。その下のレコーダーには、三月に使い切ったテープ。取り出す。これで、何も起きなかったことになる。"),
"n1_kettle_1": ("The kettle is warm. Someone was down here before you. You make a coffee anyway; it is going to be that kind of night.", "やかんが温かい。あなたより前に誰かが降りてきていた。構わずコーヒーを淹れる。そういう夜になりそうだ。"),
"n1_drawer_1": ("The drawer under the till: a revolver the owner bought in 1983 and a note that says NEVER. It has never been fired. You put it in your pocket to keep it that way.", "レジの下の引き出し。オーナーが1983年に買った回転式拳銃と、「絶対に」とだけ書かれたメモ。一度も撃たれたことはない。そのままにしておくために、ポケットに入れる。"),
"n1_ledger_1": ("The quarterly ledger. Room 704: OUT OF ORDER, for two years, in the accountant's hand. Under it, in pencil, a weekly figure that an out-of-order room does not earn.", "四半期の帳簿。704号室：故障中、二年間、会計士の筆跡で。その下に鉛筆で、故障中の部屋が稼ぐはずのない週ごとの数字。"),
"n1_ledger_2": ("Somebody has been letting a room that does not exist. Somebody with a key. You put the page in your pocket.", "誰かが存在しない部屋を貸している。鍵を持った誰かが。そのページをポケットに入れる。"),
"n1_bar_1": ("The Marbeck Bar, closed since eleven. Stools on the counter, one lamp left on for the mirror's benefit.", "マーベック・バー。十一時から閉店。カウンターに上げた椅子、鏡のためだけに点けたままのランプ。"),
"n1_g212_1": ("A man in an undershirt is behind the bar, looking for the gin with the confidence of a man who has paid for a room.", "下着姿の男がカウンターの奥で、部屋代を払った男の自信でジンを探している。"),
"n1_g212_2": ("\"Two-twelve. Paying guest. I'd like the bar open and I'd like it not to be a conversation.\"", "「212だ。金払ってる客だ。バーを開けてくれ。話し合いはなしで」"),
"n1_g212_3": ("He is not dangerous. He is loud, and loud is the one thing this hotel cannot afford tonight.", "危険な男ではない。ただ声が大きい。そして今夜のこのホテルに、一番困るのが大声だ。"),
"n1_tutorial_1": ("A standoff. Bring his Resolve to zero before his Suspicion reaches 100 — at 100, somebody picks up a phone.", "対峙だ。相手の「疑念」が100に達する前に「決意」を0にする。100になれば、誰かが受話器を取る。"),
"n1_tutorial_2": ("Every person has weaknesses. A drunk wants a drink and a reason to go back to bed. Threats are remembered.", "人には必ず弱点がある。酔っ払いが欲しいのは一杯と、ベッドに戻る口実。脅しは記憶に残る。"),
"n1_g212_4": ("\"Water. Fine. It's gin where I come from.\" He goes up by the stairs, which is the quietest thing he has done all night.", "「水か。いいさ。俺の国じゃこれがジンだ」彼は階段で上がっていく。今夜彼がした一番静かな行いだ。"),
"n1_bottles_1": ("Behind the bottles, a half bottle that is nobody's. You pour two inches into a tooth glass, for later.", "酒瓶の裏に、誰のものでもない半分の瓶。後のために、歯磨きコップに二インチ注ぐ。"),
"n1_till_1": ("The till has forty in it and a note from the barman: TAKE IT, THEY NEVER COUNT. You take it. For bribes, you tell yourself.", "レジには四十ポンドと、バーテンダーのメモ。「持ってけ、どうせ誰も数えない」。持っていく。買収用だ、と自分に言い聞かせる。"),
"n1_mirror_1": ("In the mirror behind the bar, the glass doors, and through them the street, and across the street a car with its lights off that was not there at midnight.", "バーの鏡に、ガラスのドアが映っている。その向こうの通り、通りの向かいに、ライトを消した車。真夜中にはなかった車だ。"),
"n1_kitchen_1": ("The service kitchen. Steel, tile, one fluorescent tube that has never been off. The door to the basement is at the far end.", "業務用厨房。鋼鉄、タイル、一度も消えたことのない蛍光灯が一本。地下への扉は突き当たりだ。"),
"n1_fridge_1": ("The walk-in fridge has a shelf labelled MINIBAR. Chocolate, mostly. It is billed to the rooms; it will not be billed to 704.", "業務用冷蔵庫に「ミニバー」と書かれた棚。ほとんどチョコレートだ。各部屋に請求される。704には請求されない。"),
"n1_pans_1": ("Somebody has hung the pans in order of size. It is the only orderly thing in the building and it makes you unreasonably happy.", "誰かが鍋を大きさ順に吊るしている。この建物でただひとつ秩序だったもので、なぜか無性に嬉しくなる。"),
"n1_service_locked": ("The basement door is locked from the other side. Mrs Dace keeps that key, and Mrs Dace is asleep.", "地下の扉は向こう側から施錠されている。鍵はデイス夫人が持っていて、デイス夫人は眠っている。"),
"n1_lift_1": ("The lift. Brass gate, floor dial, and a noise on the way up that wakes the sixth floor. Mrs Dace lives on the sixth floor.", "エレベーター。真鍮の格子扉、階数表示、そして上りの途中で六階を起こす音。六階にはデイス夫人が住んでいる。"),
"n1_lift_2": ("You press the button anyway, to hear it. Somewhere above, a door opens, and a telephone starts to ring at the desk you just left.", "それでもボタンを押す。音を聞くために。どこか上で扉が開き、たった今離れたデスクで電話が鳴り始める。"),
"n1_dial_1": ("The dial says four. The lift is on the ground floor. The dial has said four since the owner stopped paying for repairs.", "階数表示は「4」。エレベーターは一階にある。オーナーが修理代を払わなくなってから、表示はずっと「4」だ。"),
"n1_gate_1": ("Inside the gate, a cigarette end, still faintly warm. Not a brand this hotel sells.", "格子扉の内側に煙草の吸殻。まだかすかに温かい。このホテルで売っている銘柄ではない。"),
"n1_phone_1": ("The internal line. Mrs Dace, who has lived on the sixth floor since her husband owned the place, and hears every door in it.", "内線。デイス夫人だ。夫がこのホテルを所有していた頃から六階に住み、建物じゅうの扉の音を聞き分ける。"),
"n1_phone_2": ("\"The lift. At this hour. Who is in my hotel?\"", "「エレベーター。この時間に。私のホテルに誰がいるの？」"),
"n1_phone_3": ("\"Keep it quiet, then. And if anyone asks, I was asleep.\" The line clicks.", "「じゃあ静かにね。誰かに聞かれたら、私は寝てたことにして」回線が切れる。"),
"n1_stair_1": ("The service stair: concrete, a caged bulb on every landing, and the floor numbers painted by someone who gave up at four.", "業務用階段。コンクリート、踊り場ごとの金網付き電球、そして四階で投げ出した誰かが塗った階数の数字。"),
"n1_footprints_1": ("Wet footprints, small, going up. One pair. She took the stairs, as you told her to. Nobody else has.", "濡れた足跡。小さく、上へ向かっている。ひと組だけ。あなたが言った通り、彼女は階段を使った。他には誰も。"),
"n1_landing_1": ("From the second landing you can see the street through a wired-glass window. The car is still there. It has not moved since you noticed it.", "二階の踊り場から、網入りガラスの窓越しに通りが見える。車はまだそこにいる。気づいてから一度も動いていない。"),
"n1_corr2_1": ("The second-floor corridor: green carpet, a radiator that bangs, and at the far end a torch beam that is not yours.", "二階の廊下。緑の絨毯、音を立てるラジエーター、そして突き当たりに、あなたのものではない懐中電灯の光。"),
"n1_haskell_1": ("Haskell. The house detective, which in a forty-room hotel means a retired policeman with a notebook and nowhere to be.", "ハスケル。ホテル探偵。四十室のホテルでは、手帳を持った引退警官で、他に行き場のない男を指す。"),
"n1_haskell_2": ("\"Fourth floor's closed. Fourth floor's hook is empty. I've been doing this eleven years, son. Tell me a story.\"", "「四階は閉鎖中。四階の鍵が一本ない。十一年この仕事をしてるんだ、坊や。話を聞かせてくれ」"),
"n1_haskell_3": ("He sees through a bluff the way a window sees through rain. But he is a man who respects paper. He always has been.", "彼は窓が雨を透かすように、はったりを見抜く。だが紙を敬う男だ。昔からそうだった。"),
"n1_haskell_4": ("\"Quiet. I'll write 'quiet'.\" He writes it. He underlines it. He does not believe it, and he goes.", "「異常なし。『異常なし』と書く」彼は書く。下線を引く。信じていないまま、去っていく。"),
"n1_haskell_5": ("He leaves the torch on the radiator. Rubber, heavy, the kind that is also a reason to stop talking.", "彼はラジエーターの上に懐中電灯を置いていく。ゴム製で重く、話を終わらせる口実にもなる類いのものだ。"),
"n1_sconce_1": ("The sconce outside 208 is dying. You tap it and it comes back, which is more than can be said for most things in this building.", "208号室の前の壁灯が消えかけている。叩くと点き直る。この建物では珍しいことだ。"),
"n1_extinguisher_1": ("Behind the extinguisher, Haskell's spare torch. He hides one on every floor. You take this one. He has eleven.", "消火器の裏に、ハスケルの予備の懐中電灯。彼は各階にひとつ隠している。これをもらう。彼には十一本ある。"),
"n1_212_1": ("Room 212, vacant since the spring. Dust sheets, a stripped mattress, and a window that looks straight across at the noodle place.", "212号室。春から空室。家具のカバー、剥がされたマットレス、そして麺屋を真正面に見る窓。"),
"n1_dustsheet_1": ("Under the dust sheet, a bedside drawer with a packet of aspirin and a bible someone has used as a coaster.", "カバーの下に、アスピリンの箱と、誰かがコースター代わりにした聖書の入ったベッドサイドの引き出し。"),
"n1_window_1": ("From up here you can see into the car. A man, mid-forties, doing nothing, which takes a particular kind of patience.", "ここからなら車の中が見える。四十代半ばの男が、何もせずにいる。それには特別な種類の忍耐がいる。"),
"n1_window_2": ("He is looking at the doors. He is not looking up. Nobody looks up.", "彼はドアを見ている。上は見ていない。誰も上を見ない。"),
"n1_street_1": ("The street. Rain, the noodle place's red neon, and the car at the kerb with a man in it who does not look at you.", "通り。雨、麺屋の赤いネオン、そして縁石の車と、あなたを見ない中の男。"),
"n1_noodle_1": ("The noodle place is shut, but the cook knows you. He hands a paper cup through the side door and does not ask why you are out in this.", "麺屋は閉まっているが、料理人はあなたを知っている。横の扉から紙コップを差し出し、なぜこんな雨の中にいるのかとは聞かない。"),
"n1_car_1": ("You walk past the car as if you were going somewhere. The window is down an inch. He is listening to the hotel's doors, not to the rain.", "どこかへ行くふりをして車の横を歩く。窓が一インチ開いている。彼は雨ではなく、ホテルのドアの音を聞いている。"),
"n1_gale_1": ("He does not go. He puts both hands on the counter, flat, the way a man does when he has decided to stay until he hears what he came for.", "彼は帰らない。両手をカウンターに平らに置く。聞きに来たことを聞くまで居座ると決めた男のやり方で。"),
"n1_gale_2": ("Whatever you told him, he is going to make you say it again, slower, until one of you is wrong.", "何を言ったにせよ、彼はもう一度、ゆっくり言わせるつもりだ。どちらかが間違うまで。"),
"n1_end_1": ("You take the pass key from your pocket and look at the stairs. Four floors. One window. A car across the road.", "ポケットからマスターキーを出し、階段を見る。四階分。窓ひとつ。通りの向かいの車。"),
"hs_ask": ("Pick up", "受話器を取る"),
}
