# Shift 2 — the fourth floor (EN, JA). Mira joins. The VN's act 2 is kept by line reference.
S = {
"n2_join_1": ("She wants to know who he is talking to. The roof looks down on the car. Mrs Dace keeps a call log on the sixth floor. The man in 702 keeps nothing, and that is useful too.", "彼女は彼が誰と話しているのか知りたがっている。屋上からは車が見下ろせる。六階のデイス夫人は通話記録をつけている。702の男は何も記録しない。それもまた役に立つ。"),
"n2_join_2": ("Mira joins you. In a standoff she acts after you, with her own skills — and she can Read him, which shows you what a person is afraid of.", "ミラが仲間になった。対峙では彼女もあなたの後に、自分のスキルで行動する。「相手を読む」で、その人が何を恐れているかが分かる。"),
"n2_join_3": ("\"I'm good at people. I had eleven months of practice being looked at. Let me do the looking.\"", "「人を見るのは得意なの。十一ヶ月、見られる練習をしたから。見るのは私に任せて」"),
"n2_join_4": ("Her coat is on the chair, still wet at the hem. The dress underneath was not chosen for corridors either.", "彼女のコートは椅子の上。裾はまだ濡れている。その下のドレスも、廊下向きに選ばれたものではない。"),
"n2_bag_1": ("Her canvas bag, open on the bed. A toothbrush, a paperback with the cover torn off, and a train ticket for six-forty, nine days old.", "ベッドの上に開いたキャンバスバッグ。歯ブラシ、表紙の破れた文庫本、そして九日前の六時四十分発の列車の切符。"),
"n2_bag_2": ("\"You can hold on to that. I keep almost getting on it.\"", "「持ってていいわ。乗りそうになるのを、何度も繰り返してるから」"),
"n2_window704_1": ("The car is still there. From the window you can make out the shape of a man doing nothing. The sign across the street cycles red, then off, then red.", "車はまだそこにいる。窓から、何もしていない男の影が見える。通りの向かいの看板が赤く点き、消え、また赤く点く。"),
"n2_bath_1": ("The bathroom. A tooth glass with two inches of something in it, and a towel folded by someone who meant to leave early.", "バスルーム。何かが二インチ入った歯磨きコップと、早朝に発つつもりだった誰かが畳んだタオル。"),
"n2_coat_1": ("You hang her coat on the radiator and turn it so the wet side faces the heat. She watches you do it.", "彼女のコートをラジエーターに掛け、濡れた側を熱に向ける。彼女はそれを見ている。"),
"n2_coat_2": ("\"...Nobody does that.\"", "「……そんなことする人、いないわ」"),
"n2_corr_1": ("The fourth-floor corridor. The sconce outside 702 flickers, and under it a torch beam that is not yours. Haskell is early.", "四階の廊下。702号室の前の壁灯が明滅し、その下にあなたのものではない懐中電灯の光。ハスケルが早い。"),
"n2_haskell_1": ("\"Voices. Seven-oh-two rang down about voices on a closed floor. And here's two of them.\"", "「声がするってな。閉鎖中の階で声がすると、702から電話があった。で、ここに二人分の声がある」"),
"n2_haskell_2": ("He looks at Mira the way he looks at everything: as if it were already in his notebook.", "彼はミラを見る。他のすべてを見るのと同じように。もう手帳に書いてあるとでも言うように。"),
"n2_haskell_3": ("\"Pipes. I'll write it up as the pipes.\" He turns the torch off, which for Haskell is an apology.", "「配管の音だな。配管ってことにしとく」彼は懐中電灯を消す。ハスケルにとっては、それが謝罪だ。"),
"n2_sconce4_1": ("The sconce outside 702 has been dying for a year. Tonight it holds. Even the building is on your side.", "702号室の前の壁灯は一年前から消えかけている。今夜は持ちこたえた。建物まであなたの味方だ。"),
"n2_702_1": ("Room 702. The guest is a salesman who is never in it. Newspapers, an ashtray, an open suitcase, and a smell of a cigarette finished three hours ago.", "702号室。客は部屋にいたためしのないセールスマン。新聞、灰皿、開いたスーツケース、そして三時間前に吸い終えた煙草の匂い。"),
"n2_newspapers_1": ("Between the papers, two twenties and a racing slip. He will not miss the twenties. He has not been back since Tuesday.", "新聞の間に二十ポンド札が二枚と競馬の投票券。彼は札を惜しまないだろう。火曜日から戻っていない。"),
"n2_ashtray_1": ("In the ashtray, a cigarette end of the brand you found in the lift. The man in the car has been up here. Recently.", "灰皿に、エレベーターで見つけたのと同じ銘柄の吸殻。車の男はここまで上がってきていた。最近。"),
"n2_suitcase_1": ("A laundered shirt on top of the suitcase, two sizes too big for her. Mira looks at it, and at you, and takes it anyway.", "スーツケースの上に、洗濯済みのシャツ。彼女には二回り大きい。ミラはそれを見て、あなたを見て、それでも手に取る。"),
"n2_linen_1": ("The linen room. Towels to the ceiling, a chute to the laundry, and a ladder to a hatch somebody painted shut and somebody else unpainted.", "リネン室。天井までのタオル、洗濯室へのシュート、そして誰かがペンキで塞ぎ、別の誰かが剥がした天井ハッチへのはしご。"),
"n2_towels_1": ("Behind the towels, the Marbeck's one bathrobe. The night manager's. Mira puts it over the dress and looks, for the first time tonight, warm.", "タオルの奥に、マーベック唯一のバスローブ。夜間支配人のものだ。ミラはドレスの上に羽織り、今夜はじめて暖かそうに見える。"),
"n2_chute_1": ("Down the chute, far below, someone is running a washing machine at half past four. Mrs Dace does not sleep either.", "シュートの奥、はるか下で、誰かが四時半に洗濯機を回している。デイス夫人も眠れないのだ。"),
"n2_roof_1": ("The roof. The back of the sign, the water tank, and the whole wet city laid out like a thing that owes nobody anything.", "屋上。看板の裏、給水タンク、そして誰にも何の借りもないように広がる、濡れた街のすべて。"),
"n2_roof_2": ("Mira stands at the parapet in your coat and looks at the city for a long time, the way people look at a thing they are about to leave.", "ミラはあなたのコートを着てパラペットに立ち、長いこと街を眺める。これから去る場所を見る人の目で。"),
"n2_roof_3": ("\"From up here he's just a car.\"", "「ここからだと、彼はただの車ね」"),
"n2_constable_1": ("A torch at the roof door. Hi-vis, a radio, a face that is twenty-eight and has not decided what to think yet.", "屋上の扉に懐中電灯。蛍光ベスト、無線機、そしてまだ何も決めていない二十八歳の顔。"),
"n2_constable_2": ("\"Welfare check, sir. A caller was concerned about a woman at this address. He wouldn't give his name.\"", "「安否確認です。この住所の女性について心配する通報がありまして。通報者は名乗りませんでした」"),
"n2_constable_3": ("Mira does not hide. She stands in the open and lets him see that she is, in every sense, fine.", "ミラは隠れない。開けた場所に立ち、あらゆる意味で自分が無事であることを彼に見せる。"),
"n2_constable_4": ("\"Hoax, then.\" He radios it in. He looks at Mira once more, kindly, and goes to find his car.", "「じゃあ悪戯ですね」彼は無線で報告する。もう一度、優しくミラを見て、車を探しに行った。"),
"n2_tank_1": ("The water tank hums. Somebody has written a name and a year on it in paint. It is not a name you know.", "給水タンクが唸る。誰かがペンキで名前と年号を書いている。知らない名前だ。"),
"n2_sign_1": ("The back of the sign, where the neon is just wire and dust. From the front it is the most beautiful thing on the street.", "看板の裏。ネオンはただの針金と埃だ。表から見れば、通りで一番美しいもの。"),
"n2_parapet_1": ("From the parapet, the car. He has the interior light on now. He is writing something down.", "パラペットから、車。今は室内灯が点いている。何かを書き留めている。"),
"n2_lift_1": ("The lift has stopped between the third and fourth floors with the guest from 212 inside it, and he has decided this is your fault.", "エレベーターが三階と四階の間で止まった。中には212号室の客。彼はこれがあなたのせいだと決めた。"),
"n2_g212_1": ("\"I've paid! I've paid for a room with a lift that works!\"", "「金は払ったぞ！ 動くエレベーター付きの部屋に払ったんだ！」"),
"n2_g212_2": ("The lift remembers how to move. He forgets what he was angry about, and goes down, and does not come back.", "エレベーターは動き方を思い出し、彼は何に怒っていたかを忘れ、降りていき、戻ってこない。"),
"n2_dial4_1": ("The dial on this floor says two. Nothing in this building agrees with anything else in it.", "この階の階数表示は「2」。この建物の中で、互いに一致するものは何ひとつない。"),
"n2_stair_1": ("The service stair again. The caged bulbs, the painted numbers, and her hand on the rail just ahead of yours.", "また業務用階段。金網の電球、ペンキの数字、そしてあなたの手のすぐ先で手すりに添えられた彼女の手。"),
"n2_t3_1": ("On the fifth landing she stops, and turns, and does not say anything, and the strap of the dress has slipped off her shoulder and she does not fix it.", "五階の踊り場で彼女は立ち止まり、振り返り、何も言わない。ドレスの肩紐が肩から落ちていて、彼女はそれを直さない。"),
"n2_t3_2": ("You kiss her under a caged bulb on a concrete stair, which is not where either of you imagined it, and is exactly right.", "金網の電球の下、コンクリートの階段で、彼女にキスをする。どちらも思い描いていた場所ではない。そして、それで完全に正しい。"),
"n2_t3_3": ("\"Later,\" she says, and means it, and goes up ahead of you not hurrying.", "「あとで」と彼女は言う。本気で。そして急がずに、あなたの先を上がっていく。"),
"n2_trust_hint": ("(Her trust is not there yet. At Trust 3, this stair goes somewhere.)", "（まだ彼女の信頼が足りない。信頼3で、この階段は別の場所へ続く）"),
"n2_dace_1": ("Mrs Dace, on the sixth landing, in a quilted dressing gown, with a cordless phone in one hand and the other on the rail like a woman who owns the rail.", "六階の踊り場にデイス夫人。キルトのガウン、片手にコードレス電話、もう片方の手は手すりを所有する女のように手すりに。"),
"n2_dace_2": ("\"Forty rooms. Eleven guests. I can count, young man. And I can count her.\"", "「四十室。十一人。数えられるのよ、お若いの。彼女も数えられる」"),
"n2_dace_3": ("She looks at Mira for a long moment, and something in her face that was a landlady becomes, briefly, a woman.", "彼女は長いことミラを見る。女主人だった顔の何かが、ほんの一瞬、ひとりの女になる。"),
"n2_dace_4": ("\"I did not see her. I did not see you. I saw a draught. Keep the lift still.\" She goes up.", "「彼女は見なかった。あなたも見なかった。見たのは隙間風。エレベーターは動かさないで」彼女は上がっていく。"),
"n2_flat_1": ("Mrs Dace's flat: an armchair, a blanket, a cat on the cushion, a television with the sound off, and the Marbeck's whole history in photographs along one wall.", "デイス夫人の部屋。肘掛け椅子、毛布、クッションの上の猫、音を消したテレビ、そして壁一面の写真に収まったマーベックの歴史。"),
"n2_cat_1": ("The cat looks at Mira, decides something, and gets into her lap. Mira sits very still, as if she had been given something breakable.", "猫はミラを見て、何かを決め、彼女の膝に乗る。ミラは壊れ物を渡されたように、じっと動かない。"),
"n2_cat_2": ("\"Nobody's chosen me in a while. Not even a cat.\"", "「しばらく誰にも選ばれてなかった。猫にすら」"),
"n2_photos_1": ("The photographs: the Marbeck in 1962, the Marbeck on fire in 1979, Mr Dace shaking hands with a man in a good coat. The man is younger. The coat is the same. Penhallow.", "写真。1962年のマーベック、1979年の火事のマーベック、上等なコートの男と握手するデイス氏。男は若い。コートは同じだ。ペンハロウ。"),
"n2_photos_2": ("Under the frame, a call log in Mrs Dace's hand. Tonight, 3:52: 'Man asking after the fourth floor. Told him we're closed. He didn't believe me.'", "写真立ての下に、デイス夫人の筆跡の通話記録。今夜3時52分：「四階について尋ねる男。閉鎖中と伝えた。信じなかった」"),
"n2_nail_1": ("The basement key, on a nail by the door, where a woman who never goes down keeps it. You take it. She will know. She will not say.", "扉のそばの釘に地下の鍵。決して下へ行かない女が置いておく場所だ。あなたはそれを取る。彼女は気づく。何も言わない。"),
"n2_gale_1": ("Footsteps on the service stair. Not hurrying. He comes round the corner of the fourth-floor corridor with his coat open and his hands empty, and looks at the door of 704.", "業務用階段に足音。急いでいない。彼はコートの前を開け、手には何も持たず、四階の廊下の角を曲がってきて、704号室の扉を見る。"),
"n2_gale_2": ("\"Mira.\" Not a question. \"Nine days. I'd have let you have the ticket. I only wanted to know where.\"", "「ミラ」問いかけではない。「九日間。切符なら持たせてやった。どこなのか、知りたかっただけだ」"),
"n2_gale_3": ("She does not step behind you. She steps beside you. That is the whole of what she has decided tonight.", "彼女はあなたの後ろに下がらない。隣に立つ。それが今夜、彼女が決めたことのすべてだ。"),
"n2_gale_4": ("He looks at the door for a long time. Then he puts his lighter on the radiator, like a man leaving a card, and goes down the way he came.", "彼は長いこと扉を見る。それから名刺を置く男のように、ラジエーターの上にライターを置き、来た道を戻っていく。"),
"n2_gale_5": ("\"He'll go to the station. He'll wait there. He's good at waiting.\" She says it without looking at the stairs.", "「駅に行くわ。そこで待つ。待つのは得意だから」階段を見ずに、彼女は言う。"),
"n2_back_1": ("Back in 704. The bed, the chair, the window. She pours two inches of something into the tooth glass and hands it to you.", "704号室に戻る。ベッド、椅子、窓。彼女は歯磨きコップに何かを二インチ注ぎ、あなたに渡す。"),
"n2_after_1": ("Four floors down, a car starts, and idles, and does not leave. The window goes from black to a colour that is not yet grey.", "四階下で車のエンジンがかかり、アイドリングし、去らない。窓は黒から、まだ灰色ではない色に変わる。"),
"n2_trust5_hint": ("(She asked plainly. At Trust 5 you could answer plainly. Tonight you say the sensible thing.)", "（彼女は率直に尋ねた。信頼5なら率直に答えられた。今夜は、分別のあることを言う）"),
}
