# Shift 3 — six-forty — and the epilogue (EN, JA). The VN's act 3 is kept by line reference.
S = {
"n3_t7_1": ("Before the stockings, before the car's gone and the sign is off: she is on her front on the sheets with her chin on her arms, watching you not get up.", "ストッキングの前、車が消えて看板が消える前。彼女はシーツの上にうつ伏せで、腕に顎を乗せ、起き上がらないあなたを見ている。"),
"n3_t7_2": ("\"Don't look at the window yet. Look at this. This is the part I'll keep.\"", "「まだ窓を見ないで。こっちを見て。これが、私が持っていく部分だから」"),
"n3_t7_3": ("The neon crosses her back one last time and goes out for the day.", "ネオンが最後にもう一度、彼女の背中を横切り、昼のために消える。"),
"n3_t5_1": ("The bathroom door stays open. Steam, the tap, and Mira on the edge of the bath with a towel round her hips and nothing else, laughing at something you said.", "バスルームの扉は開いたまま。湯気、蛇口、そして腰にタオルだけを巻いたミラが、バスタブの縁に腰かけ、あなたの言ったことに笑っている。"),
"n3_t5_2": ("\"The Marbeck has hot water. I take back half of what I said about it.\"", "「マーベックにはお湯が出るのね。言ったことの半分は撤回するわ」"),
"n3_plan_1": ("The car's gone. The sign is off. In an hour the day porter comes on, and before that, at a quarter to seven, the owner's man comes for the book.", "車は消えた。看板は消えた。一時間後に昼番のポーターが出勤し、その前の六時四十五分に、オーナーの代理人が帳簿を取りに来る。"),
"n3_plan_2": ("The basement key is in your pocket. The fourth row of the fourth floor is a clean line. Keep it that way until seven.", "地下の鍵はポケットの中。四階の四行目はきれいな空白。七時までそのままにしておこう。"),
"n3_plan_3": ("\"I'm not getting on the six-forty. I've decided that much. The rest I'll decide at the door.\"", "「六時四十分には乗らない。それだけは決めた。残りは、ドアのところで決める」"),
"n3_corr_1": ("The fourth-floor corridor by daylight is only a corridor. The sconce outside 702 is off because somebody, finally, has turned it off.", "昼の光の中の四階の廊下は、ただの廊下だ。702の前の壁灯は、ついに誰かが消したから消えている。"),
"n3_stair_1": ("Down the service stair, past the landing where she stopped. Neither of you mentions it. Both of you look at it.", "業務用階段を降り、彼女が立ち止まった踊り場を過ぎる。どちらもそれには触れない。どちらもそこを見る。"),
"n3_boiler_1": ("The boiler room. Gauges, pipes, a lamp in a cage, and the one place in the Marbeck that is warm by design.", "ボイラー室。計器、配管、金網の中のランプ。マーベックで唯一、意図して暖かい場所。"),
"n3_gauges_1": ("The gauges read what they read in 1979. Mr Dace painted the needles on. It has not blown up yet.", "計器は1979年と同じ値を示している。デイス氏が針をペンキで描いたのだ。まだ爆発していない。"),
"n3_pipes_1": ("Behind the pipes, a bottle with Mrs Dace's name on it in biro and a glass that has been washed. You pour her a measure back and take the rest.", "配管の裏に、ボールペンでデイス夫人の名前を書いた瓶と、洗ってあるグラス。彼女の分を一杯注ぎ戻し、残りをもらう。"),
"n3_laundry_1": ("The laundry. Sheets on lines, steam, two machines running, and Mrs Dace at the folding table at half past six because she could not sleep either.", "洗濯室。ロープに干したシーツ、湯気、回っている洗濯機が二台、そして六時半に畳み台に向かうデイス夫人。彼女も眠れなかったのだ。"),
"n3_dace_1": ("\"You took my key.\" Not a question. \"And the owner's man is coming for the book, and I am a woman who was asleep.\"", "「鍵を持っていったわね」問いではない。「オーナーの代理人が帳簿を取りに来る。そして私は、寝ていた女」"),
"n3_dace_2": ("Mira takes the other end of the sheet without being asked, and the two of them fold it between them like women who have done this before.", "ミラは言われもせずにシーツの反対側を持ち、二人は昔からそうしてきた女たちのように、間でシーツを畳む。"),
"n3_dace_3": ("\"For the room. It'll want making up before nine. And put my key back on its nail, young man.\"", "「部屋の分。九時までに整えておきなさい。それと鍵は釘に戻しておいて、お若いの」"),
"n3_washers_1": ("On the second machine, a tray of minibar chocolate someone has been drying out. It is the Marbeck. Nothing is thrown away.", "二台目の洗濯機の上に、誰かが乾かしていたミニバーのチョコレートのトレー。マーベックだ。何も捨てられない。"),
"n3_sheets_1": ("Between two hanging sheets, Mira stops, and the light comes through the cotton onto her face, and for a second nobody is looking for anyone.", "干したシーツの間でミラが立ち止まる。木綿越しの光が顔に落ち、一瞬、誰も誰かを探していない。"),
"n3_bay_1": ("The loading bay. The shutter up a foot, rain blowing under it, bins, puddles, and on the cobbles a dry rectangle where a car was parked until twenty past six.", "搬入口。一フィート上がったシャッター、その下から吹き込む雨、ゴミ箱、水たまり。そして石畳に、六時二十分まで車が停まっていた乾いた長方形。"),
"n3_constable_1": ("The constable again, in the alley, with a notebook and a different question.", "路地にまた巡査。手帳と、違う質問を携えて。"),
"n3_constable_2": ("\"The car. Dark saloon, kerbside, there since three. Whose was it, sir, and why has it gone?\"", "「あの車です。黒っぽいセダン、縁石脇、三時からいました。誰の車で、なぜいなくなったんですか？」"),
"n3_constable_3": ("You give him a registration. It is wrong by one letter. He writes it down and thanks you, and that is the end of the car.", "ナンバーを教える。一文字だけ違う。彼は書き留めて礼を言い、それで車の話は終わりだ。"),
"n3_shutter_1": ("The shutter has been forced from outside, a foot and no more. A man came in this way at four and went out this way at six.", "シャッターは外からこじ開けられている。一フィートだけ。四時に男がここから入り、六時にここから出た。"),
"n3_bins_1": ("In the bin, torn in half, his card. The number he left on the counter. He does not want it back.", "ゴミ箱の中に、半分に破られた彼の名刺。カウンターに置いていった番号だ。もう要らないらしい。"),
"n3_street_1": ("The street at twenty to seven. The rain has stopped. The pavement has started to steam. The kerb where the car was is only a kerb.", "六時四十分の通り。雨は止んだ。歩道から湯気が立ち始めている。車のあった縁石は、ただの縁石だ。"),
"n3_car_gone_1": ("A dry rectangle on the road, already shrinking. In an hour there will be no sign he was ever here, which is what he would have wanted.", "路面に乾いた長方形。もう縮み始めている。一時間後には彼がいた痕跡もなくなる。彼もそれを望んだだろう。"),
"n3_noodle_1": ("The noodle place is opening. The cook puts two paper cups on the sill without being asked. He has seen the two of you from across the road.", "麺屋が開く。料理人は頼まれもせずに窓の桟に紙コップを二つ置く。通りの向こうから、二人を見ていたのだ。"),
"n3_office_1": ("The back office. The register is open on the desk, and Haskell is sitting in the accountant's chair, which nobody sits in.", "事務室。デスクの上に開かれた宿帳。そして会計士の椅子に、誰も座らないその椅子に、ハスケルが座っている。"),
"n3_haskell_1": ("\"Fourth floor. Fourth row. Clean as the day it was ruled.\" He turns the book round. \"Eleven years, son. Tell me a story I can write down.\"", "「四階。四行目。罫線を引いた日のままだ」彼は宿帳をこちらに向ける。「十一年だ、坊や。書き留められる話を聞かせてくれ」"),
"n3_haskell_2": ("He closes the book. \"This wasn't a quiet night. I'll write 'quiet'. Goodnight.\" He leaves the chair exactly as he found it.", "彼は帳簿を閉じる。「静かな夜じゃなかった。『異常なし』と書く。おやすみ」椅子は見つけたときのままに戻していった。"),
"n3_register3_1": ("The fourth row. You run your thumb along it. Nothing comes off. It is the cleanest thing you have done all year.", "四行目。親指でなぞる。何もつかない。この一年であなたがした、一番きれいな仕事だ。"),
"n3_lobby_1": ("The lobby at a quarter to seven: grey light, wet tiles, and a man in a camel coat at the doors with a briefcase, who has not pressed the bell because he does not need to.", "六時四十五分のロビー。灰色の光、濡れたタイル、そしてドアのところに鞄を持ったキャメルコートの男。ベルは押さない。押す必要がないからだ。"),
"n3_pen_1": ("\"Penhallow. For the owner. The quarterly audit is early this quarter, because the owner had a telephone call at four this morning from a man with a full tank.\"", "「ペンハロウだ。オーナーの代理でね。今期の四半期監査は早めだ。今朝四時に、オーナーのところへガソリン満タンの男から電話があったものでね」"),
"n3_pen_2": ("He puts a cheque on the counter, unsigned, with Gale's handwriting on the payee line. \"The fourth floor's row, please. I am told it is empty. I would like to be told it by the book.\"", "彼はカウンターに未署名の小切手を置く。受取人の欄にはゲイルの筆跡。「四階の行を見せてくれ。空だと聞いている。帳簿にそう言ってもらいたい」"),
"n3_pen_3": ("Mira, beside you, in your spare shirt, looks at the cheque and then at him, and he looks at her for the first time, and understands that she is not for sale either.", "隣のミラは、あなたの替えのシャツを着て、小切手を見て、それから彼を見る。彼ははじめて彼女を見て、彼女も売り物ではないと理解する。"),
"n3_pen_4": ("He puts the cheque back in the briefcase. \"A quiet hotel. The owner will be pleased. Mrs Dace will be relieved.\" He goes out into a street that is only a street.", "彼は小切手を鞄に戻す。「静かなホテルだ。オーナーも喜ぶだろう。デイス夫人も安心する」彼はただの通りに出ていく。"),
"n3_pen_5": ("On the counter where the cheque was: her train ticket. He found it in the car. He does not say so. He does not need to.", "小切手のあった場所に、彼女の列車の切符。彼は車の中で見つけたのだ。そうとは言わない。言う必要がない。"),
"n3_end_pre": ("She walks back up four flights for her coat and her bag, and comes down them again without hurrying, and stops at the desk.", "彼女はコートとバッグを取りに四階分を上がり、急がずにまた降りてきて、デスクのところで立ち止まる。"),
# epilogue
"n4_open_1": ("Lenny. Twenty-three, bicycle clips, a paper under his arm, and a question he asks every morning because one day the answer will be yes.", "レニー。二十三歳、自転車用のズボン留め、小脇に新聞。そして、いつか答えが「ああ」になる日のために毎朝する質問。"),
"n4_porter_1": ("\"Anything happen?\" He asks it at the door, before his coat is off. He asks it the way other people say good morning.", "「何かあった？」コートを脱ぐ前に、ドアのところで聞く。他の人が「おはよう」と言うのと同じ調子で。"),
"n4_porter_2": ("\"Only — the fourth floor's hook. I'll be the one asked, see, if anyone asks.\"", "「ただ、四階の鍵なんだけど。誰かに聞かれたら、聞かれるのは俺だからさ」"),
"n4_porter_3": ("He takes the paper and the register and does not look at either, and goes to put the kettle on, and that is the Marbeck's whole security review for the quarter.", "彼は新聞と宿帳を受け取り、どちらも見ず、やかんを火にかけに行く。それが今四半期のマーベックの保安監査のすべてだ。"),
"n4_board_1": ("Seven-oh-four goes back on its hook. Twenty empty hooks. Nobody will ever know which one.", "704が鉤に戻る。空の鉤は二十本。どれがそれなのか、誰にも分からない。"),
"n4_corner_1": ("The corner, at seven. The pavement steaming. She goes left, the wrong way for the station, and that is the point.", "七時の角。湯気を立てる歩道。彼女は左へ行く。駅とは逆の方へ。それが肝心なところだ。"),
"n4_corner_2": ("At the corner she looks back once. You are standing in the doorway you have watched all night from the wrong side.", "角で彼女は一度だけ振り返る。あなたは、一晩じゅう内側から見ていた戸口に立っている。"),
"n4_train_1": ("The bus from the corner at seven goes the wrong way for an hour. She gets on it with the key in her pocket, which she will post back, which she does.", "七時に角から出るバスは、一時間ほど逆方向へ行く。彼女はポケットに鍵を入れたまま乗る。郵便で返すと言って、本当に返してきた。"),
"n4_train_2": ("The hotel gets three letters a year. That winter it gets four.", "ホテルには年に三通の手紙が届く。その冬は四通だった。"),
"n4_alone_1": ("The station, then. She walks to it the way she walked in: without hurrying. She does not look back at the doors.", "では駅へ。彼女は入ってきたときと同じように歩いていく。急がずに。ドアを振り返りはしない。"),
"n4_alone_2": ("You go back inside and put the tooth glass in the sink, and the key on the board, and the night in the place where you keep the others.", "中に戻り、歯磨きコップを流しに置き、鍵をボードに掛け、今夜を、他の夜をしまってある場所にしまう。"),
"n4_t9_1": ("At nine, with the room already made up, the desk phone rings. Internal line. Seven-oh-four.", "九時、部屋はもう整えてある。デスクの電話が鳴る。内線。704号室。"),
"n4_t9_2": ("\"It's Mira. From the book you didn't write in. I never went to the corner. I've been sitting here in your shirt drinking the noodle man's coffee, deciding.\"", "「ミラよ。あなたが書かなかった帳簿の。角には行かなかった。ずっとここで、あなたのシャツを着て麺屋のコーヒーを飲みながら、決めてたの」"),
"n4_t9_3": ("\"Bring the pass key. I've decided.\"", "「マスターキーを持ってきて。決めたから」"),
"n4_t9_4": ("You take the key off the board, and you do not write anything in the book, and you go up the stairs not hurrying either.", "ボードから鍵を取り、帳簿には何も書かず、あなたもまた急がずに階段を上がっていく。"),
"hs_ticket": ("The ticket", "切符"),
}
