extends Node
## Does the shipped font subset actually contain every character this game's copy uses?
##
## assets/fonts/NotoSansCJK-subset.otf is generated by tools/subset_cjk.py from whatever
## CJK happens to be in scripts/*.gd at the time it is run, and the web export ships no
## system font to fall back on. So the failure mode is: someone adds a Chinese or Japanese
## line, never re-runs the subset, and those characters render as tofu boxes on the web
## build only. It is silent -- the export succeeds, the strings are correct in the source,
## nothing logs anything, and the only way to see it is to open the page in that language.
## It has already happened once here (README of tools/subset_cjk.py: 账本 came up 圝本).
##
## It happened again on 2026-09-21: the pause panel and the stuck-ball line added eight
## characters -- 卡着继续脚踹蹴預 -- that the subset did not have.
##
##   godot --headless --path play/rebound-tycoon-godot res://tests/cjk.tscn
##   godot --headless --path . res://tests/cjk.tscn -- --prove-it-fails


func _ready() -> void:
	var f: Font = load("res://assets/fonts/NotoSansCJK-subset.otf")
	if f == null:
		print("!! the CJK subset did not load")
		get_tree().quit(1)
		return
	var missing := {}
	var seen := 0
	for bank in [RTStrings.EN, RTStrings.ZH, RTStrings.JA]:
		for key in bank:
			for s: String in _strings_of(bank[key]):
				for i in s.length():
					var c: int = s.unicode_at(i)
					if c > 0x2000:
						seen += 1
						if not f.has_char(c):
							missing[String.chr(c)] = true
	if "--prove-it-fails" in OS.get_cmdline_user_args():
		# A character no subset of this copy could contain, so the check is seen failing
		# before it is trusted passing (memory: verification-that-lies).
		if f.has_char(0x9F98):
			print("!! --prove-it-fails: the subset claims a glyph it cannot have;")
			print("   do not trust this harness passing.")
			get_tree().quit(1)
			return
		print("ok: --prove-it-fails — has_char() says no to a character outside the subset.")
		get_tree().quit(0)
		return
	print("%d CJK code point(s) checked across en/zh/ja" % seen)
	if missing.is_empty():
		print("ok: the subset covers every character the copy uses")
		get_tree().quit(0)
	else:
		print("!! not in assets/fonts/NotoSansCJK-subset.otf: %s" % "".join(missing.keys()))
		print("   run: python3 tools/subset_cjk.py")
		get_tree().quit(1)


## The string banks nest one level (RTStrings.tm's groups), so both shapes are walked.
func _strings_of(v: Variant) -> Array:
	if v is String:
		return [v]
	if v is Dictionary:
		var out: Array = []
		for k in v:
			out.append_array(_strings_of(v[k]))
		return out
	if v is Array:
		var out2: Array = []
		for e in v:
			out2.append_array(_strings_of(e))
		return out2
	return []
