# System strings, names, actions, items, skills, enemies for LIEN. (key: (EN, JA))
# Keys that also exist in the core's strings_core.json override it. The standoff is
# re-skinned as a HAGGLE (or, against an object's memory, a READING): the other side's
# Resolve, Nara's Composure and Focus, and their CLAIM on her -- at 100 she is written into
# their book (a loss, reload). New writing keeps the fork's voice: close third person on
# Nara, present tense, dry.
S = {
"title": ("LIEN", "LIEN ―リーエン―"),
"t_subtitle": ("RPG × pawn-shop management — one night at the counter and under it", "RPG × 質屋経営・鑑定 ― カウンターと、その下の一夜"),
"t_note": ("18+ · All characters are adults · AI-generated work (see 'About this work')", "18歳以上対象 · 登場人物は全員成人です · AI生成作品（「作品について」参照）"),
"t_trial": ("Trial version — Midnight: the finial and the first landing", "体験版 — 午前零時：真鍮の飾りと最初の踊り場"),
# ops/dlsite/AI_DISCLOSURE.md, voiced variant (Nara's 21 voiced lines ship), verbatim
"about_ai": ("This is an adults-only work. Every character depicted is an adult.\n\nAI disclosure: Generative AI is used as a production tool in this work, which was made through intensive collaboration between the developer and AI over several hundred hours. Images (sprites, backgrounds, CGs) are output by an image-generation model and the voice by a speech-synthesis model. The concept, world, story structure, direction, character design, the selection and compositing of every image, voice direction, game-system design and balancing, and testing are the developer's work; the script text and the program were written and edited jointly by AI language models and the developer.",
             "本作は18歳以上を対象とした作品です。登場人物は全員成人です。\n\n【AI使用について】本作は生成AIを制作ツールとして活用し、開発者とAIの集中的な共同作業で制作しました。画像（立ち絵・背景・CG）は画像生成AIで出力し、音声は音声合成AIで生成しています。企画・世界観・ストーリー構成・演出・キャラクター設計、すべての画像の選定と合成、音声の演技指示、ゲームシステムの設計とバランス調整、テストは開発者が行い、シナリオ文とプログラムはAI（大規模言語モデル）と開発者が共同で執筆・編集しています。制作には数百時間を費やしています。"),
"ds_adult": ("18+. Everyone in this game is an adult. It contains nudity and sexual themes (seen in readings of other people's private hours; nothing explicit), grief, and debt.", "18歳以上対象。登場人物は全員成人です。裸体と性的な主題（他人の私的な時間を「読む」場面として。露骨な描写はありません）、喪失、借金を扱います。"),
# names
"n_nara": ("Nara", "ナラ"),
"n_tam": ("Tamsin", "タムシン"),
"n_ivo": ("Ivo", "アイヴォ"),
"n_mara": ("Mara", "マーラ"),
"n_cal": ("Calder", "カルダー"),
"n_shop": ("The shop", "店"),
"n_tamsin": ("Tamsin", "タムシン"),
"n_clerk": ("The Stair Clerk", "階段の書記"),
"n_keeper": ("The Toll-Keeper", "通行税の番人"),
"n_haggler": ("Old Ossian", "オシアン爺"),
"n_broker": ("The Hollow Broker", "虚ろな仲買人"),
"n_moth": ("The Moth Widow", "蛾の未亡人"),
"n_archivist": ("Miss Penrose", "ペンローズ嬢"),
"n_bailiff": ("The Bailiff", "執達吏"),
"n_auditor": ("The Auditor", "監査人"),
"n_glass": ("Nara, in the glass", "鏡の中のナラ"),
# HUD / menus
"h_clock": ("%s   ·   %d moves before the hour turns   ·   Lv %d", "%s   ·   この刻が過ぎるまであと%d手   ·   Lv %d"),
"h_counter": ("Till £%d", "金庫 £%d"),
"nc_budget": ("%d moves before the hour turns. Walking, searching, haggling and reading all cost time.", "この刻が過ぎるまであと%d手。移動・調べる・値切り・読み取り、すべてに時間がかかります。"),
"m_party": ("Nara", "ナラ"),
"m_map": ("The ledger map", "台帳の地図"),
"ms_level": ("Level %d   XP %d / %d   Best trust %d", "レベル %d   経験値 %d / %d   最高信頼 %d"),
"ev_trust_track": ("%s's trust +%d", "%sの信頼 +%d"),
"toast_trust_track": ("%s: Trust %d — a deeper reading is open", "%s：信頼%d — より深い読み取りが解放されました"),
"g_locked": ("Locked — Trust %d", "未解放 — 信頼%d"),
"g_unseen": ("Not read yet", "まだ読んでいない"),
"end_t": ("The hour turns", "刻が移る"),
"end_body": ("Level %d · best Trust %d. Your progress is saved in slot 1.", "レベル %d · 最高信頼 %d。進行状況はスロット1に保存されています。"),
"fin_t": ("Thirty days on the ticket", "質札は三十日"),
"fin_body": ("Level %d · best Trust %d. Thank you for playing. Your last save is in slot 1: price someone differently, or keep your hands to yourself, and the dawn changes.", "レベル %d · 最高信頼 %d。遊んでいただきありがとうございました。最後のセーブはスロット1にあります。値付けを変えるか、手を触れずにおけば、夜明けが変わります。"),
"lose_standoff_t": ("Written in", "書き込まれた"),
"lose_standoff": ("Their claim on you reached a hundred, and your name went into their book. Nothing is lost but the last few minutes: you are back at the last save.", "相手の請求が100に達し、あなたの名前が向こうの帳簿に書き込まれた。失ったのは直前の数分だけ。最後のセーブに戻ります。"),
"lose_dawn_t": ("The hour turns", "刻が移る"),
"lose_dawn": ("The shelves shuffle and the hour is gone. You are back at the last save.", "棚が入れ替わり、この刻は過ぎ去った。最後のセーブに戻ります。"),
# the standoff, re-skinned
"b_intro": ("Across the counter.", "カウンターを挟んで。"),
"b_resolve": ("Resolve %d / %d", "意地 %d / %d"),
"b_suspicion": ("Claim %d / 100", "請求 %d / 100"),
"b_comp_nerve": ("Composure %d/%d  Focus %d/%d", "平静 %d/%d  集中 %d/%d"),
"b_dmg": ("Resolve −%d.", "意地 −%d。"),
"b_susp": ("Claim %s.", "請求 %s。"),
"b_weak_hit": ("It lands — a soft spot.", "効いた — 弱みだ。"),
"b_resist_hit": ("It slides off. They have priced that before.", "受け流された。その手はもう値踏み済みだ。"),
"b_enemy_turn": ("%s leans on the counter. Claim %+d. %s's composure −%d.", "%sがカウンターに身を乗り出す。請求 %+d。%sの平静 −%d。"),
"b_threat_mark": ("A debt called cannot be uncalled: their claim climbs faster for the rest of this.", "取り立てた借りは取り消せない。この先、相手の請求は速く膨らむ。"),
"b_win": ("They let go of it.", "相手が手を離した。"),
"b_lose": ("Your name goes into their book.", "あなたの名前が相手の帳簿に書き込まれる。"),
"b_marked": ("[debt called]", "[取り立て済み]"),
"b_won": ("Haggle won", "交渉成立"),
"b_lost": ("Written in", "書き込まれた"),
"r_needs_cash": ("Needs a bone charm to trade.", "取引には骨の護符が要る。"),
"r_needs_evidence": ("Needs a ticket or a receipt to show.", "見せる質札か受領証が要る。"),
"r_nerve": ("Not enough focus.", "集中が足りない。"),
"r_rattled": ("Too shaken to act.", "動揺して動けない。"),
"ev_trust_missed": ("You won, but too close to the line: it did not trust you for it.", "勝ったが、際どすぎた。それで信頼は得られなかった。"),
# stats
"s_wit": ("Eye", "目利き"),
"s_cha": ("Patter", "話術"),
"s_grt": ("Steel", "胆力"),
"s_stl": ("Tact", "気配り"),
"sd_wit": ("Appraisal: lowballs, tickets, the touch. Also your focus pool.", "鑑定。値切り・質札・手触り。集中の上限も決まる。"),
"sd_cha": ("Talk: patter and trading in kind.", "話。口上と物々交換。"),
"sd_grt": ("How much you can take across a counter, and how hard you call a debt.", "カウンター越しに耐えられる量と、取り立ての強さ。"),
"sd_stl": ("Letting it sit lowers their claim further.", "「寝かせる」で相手の請求を大きく下げる。"),
# actions
"a_deflect": ("Hold the counter", "カウンターを守る"),
"a_observe": ("Appraise", "鑑定する"),
"a_bluff": ("Lowball", "安く言い値"),
"a_evidence": ("Show the ticket", "質札を見せる"),
"a_bribe": ("Pay in kind", "現物で払う"),
"a_flirt": ("Patter", "口上"),
"a_threaten": ("Call the debt", "借りを取り立てる"),
"a_stall": ("Let it sit", "寝かせる"),
"a_item": ("Use item", "道具を使う"),
"a_touch": ("Lay a hand", "手を置く"),
"a_elsa": ("Elsa's rule", "エルサの決まり"),
"ad_deflect": ("Hands flat on the glass. Take the next push and cool the room a little.", "両手をガラスに置く。次の圧を受け止め、場を少し冷ます。"),
"ad_observe": ("Look at them the way you look at a hallmark: reveals their soft spots.", "刻印を見るように相手を見る。弱みがわかる。"),
"ad_bluff": ("Name a number lower than you mean. Eye.", "本気より低い数字を言う。目利き。"),
"ad_evidence": ("Put a ticket or a receipt on the glass. Lowers their claim. Needs one.", "質札か受領証をガラスに置く。請求が下がる。一枚必要。"),
"ad_bribe": ("Trade a bone charm across. Patter. Spends one.", "骨の護符を差し出す。話術。一つ消費。"),
"ad_flirt": ("Keep them talking, warmly, until they forget the price. Patter.", "温かく話し続け、値段を忘れさせる。話術。"),
"ad_threaten": ("Hits hard — and they remember. Their claim climbs faster for the rest of this.", "強烈に効く。だが相手は覚えている。この後、請求が速く膨らむ。"),
"ad_stall": ("Say nothing. Let the clock do it. Their claim falls; a little composure comes back.", "黙って時計に任せる。請求が下がり、平静が少し戻る。"),
"ad_item": ("Something from your apron.", "エプロンから何かを。"),
"ad_touch": ("Palm flat on the thing between you. It tells you what they are really selling.", "二人の間の品に掌を当てる。相手が本当に売っているものがわかる。"),
"ad_elsa": ("The shop pays first and looks second. Said in Elsa's voice, it ends arguments.", "店が先に払い、見るのはそのあと。エルサの声で言えば、議論は終わる。"),
# items
"i_coin": ("Till", "金庫"), "id_coin": ("The shop's drawer, in pounds.", "店の引き出しの中身（ポンド）。"),
"i_fees": ("Fourth column", "第四の欄"), "id_fees": ("Spent on knowing.", "知るために払った額。"),
"i_stock": ("Stock", "在庫"), "id_stock": ("On the shelf.", "棚の上。"),
"i_n_read": ("Readings", "読み取り"), "id_n_read": ("Taken.", "済み。"),
"i_n_refused": ("Refusals", "見送り"), "id_n_refused": ("Priced blind.", "見ずに値付け。"),
"i_bone_charm": ("Bone charm", "骨の護符"), "id_bone_charm": ("Market money. Pay in kind spends one.", "市場の通貨。「現物で払う」で一つ消費。"),
"i_tea": ("Strong tea", "濃い紅茶"), "id_tea": ("Restores 16 composure.", "平静を16回復。"),
"i_salts": ("Smelling salts", "気付け塩"), "id_salts": ("Restores 8 focus.", "集中を8回復。"),
"i_brandy": ("Elsa's brandy", "エルサのブランデー"), "id_brandy": ("Restores 28 composure.", "平静を28回復。"),
"i_peppermint": ("Peppermints", "ハッカ飴"), "id_peppermint": ("Restores 14 focus.", "集中を14回復。"),
"i_receipt": ("A stamped receipt", "判の押された受領証"), "id_receipt": ("Proof. The Stair Clerk's stamp, still wet.", "証拠。階段の書記の判、まだ乾いていない。"),
"i_ticket_tamsin": ("Tamsin's ticket", "タムシンの質札"), "id_ticket_tamsin": ("Proof. One brass finial, priced.", "証拠。真鍮の飾り一つ、値付け済み。"),
"i_ticket_ivo": ("Ivo's ticket", "アイヴォの質札"), "id_ticket_ivo": ("Proof. One gold band, priced.", "証拠。金の指輪一つ、値付け済み。"),
"i_ticket_mara": ("Mara's ticket", "マーラの質札"), "id_ticket_mara": ("Proof. One mourning veil, priced.", "証拠。喪のヴェール一枚、値付け済み。"),
"i_elsa_note": ("Elsa's note", "エルサのメモ"), "id_elsa_note": ("Proof. 'Never pay the Bailiff in coin.' In pencil.", "証拠。「執達吏に硬貨で払うな」。鉛筆書き。"),
"i_calder_card": ("Calder's card", "カルダーの名刺"), "id_calder_card": ("Proof. 'Factor. Readings bought.'", "証拠。「仲買。読み取り買います」。"),
"i_ledger_page": ("A torn ledger page", "破れた台帳の頁"), "id_ledger_page": ("Proof. Your own name, in a hand that is not yet yours.", "証拠。自分の名前。まだ自分のものではない筆跡で。"),
"i_vault_key": ("A key with no door", "扉のない鍵"), "id_vault_key": ("Old Ossian swears he never sold it to you.", "オシアン爺は売っていないと誓っている。"),
"i_waistcoat": ("Charcoal waistcoat", "炭色のベスト"), "id_waistcoat": ("Outfit. Steel +1.", "服装。胆力+1。"),
"i_oilskin": ("Elsa's oilskin", "エルサの油布コート"), "id_oilskin": ("Outfit. Steel +2. Smells of the stair.", "服装。胆力+2。階段の匂いがする。"),
"i_velvet": ("Velvet jacket", "ベルベットの上着"), "id_velvet": ("Outfit. Patter +2, patter stronger.", "服装。話術+2、口上が強くなる。"),
"i_monocle": ("Monocle on a chain", "鎖つきの片眼鏡"), "id_monocle": ("Accessory. Eye +1.", "装飾品。目利き+1。"),
"i_loupe": ("Jeweller's loupe", "宝石鑑定ルーペ"), "id_loupe": ("Accessory. Eye +2, tickets stronger.", "装飾品。目利き+2、質札が強くなる。"),
"i_brooch": ("Jet brooch", "黒玉のブローチ"), "id_brooch": ("Accessory. Patter +1. Mara's kind of brooch.", "装飾品。話術+1。マーラが着けていた類のもの。"),
"i_lantern": ("Stair lantern", "階段のランタン"), "id_lantern": ("Tool. Tact +1, letting it sit stronger.", "道具。気配り+1、「寝かせる」が強くなる。"),
"i_scales": ("Pocket scales", "携帯天秤"), "id_scales": ("Tool. Eye +1, lowballs stronger.", "道具。目利き+1、値切りが強くなる。"),
"i_gloves": ("Cotton gloves", "木綿の手袋"), "id_gloves": ("Tool. Steel +2. Elsa wore them for the things she did not want to read.", "道具。胆力+2。エルサが読みたくない品に触れるとき嵌めていた。"),
# skill branches
"br_broker": ("Broker", "仲買"),
"br_reader": ("Reader", "読み手"),
"sk_tally": ("Quick tally", "早勘定"), "skd_tally": ("Lowball +30%.", "値切り+30%。"),
"sk_patter": ("Shop patter", "店の口上"), "skd_patter": ("Patter +30%.", "口上+30%。"),
"sk_ledger_mind": ("Ledger mind", "帳簿頭"), "skd_ledger_mind": ("Eye +2.", "目利き+2。"),
"sk_elsa_sk": ("Elsa's voice", "エルサの声"), "skd_elsa_sk": ("Grants Elsa's rule.", "「エルサの決まり」を習得。"),
"sk_house": ("The house always", "店はいつも"), "skd_house": ("Elsa's rule +40%, pay in kind +30%.", "「エルサの決まり」+40%、現物払い+30%。"),
"sk_steady": ("Steady hands", "動じない手"), "skd_steady": ("Composure +10.", "平静+10。"),
"sk_open_hand": ("Open hand", "開いた手"), "skd_open_hand": ("Tact +2.", "気配り+2。"),
"sk_fingertips": ("Fingertips", "指先"), "skd_fingertips": ("Show the ticket +30%.", "質札を見せる+30%。"),
"sk_touch_sk": ("The touch", "手触り"), "skd_touch_sk": ("Grants Lay a hand.", "「手を置く」を習得。"),
"sk_deep": ("All the way in", "奥まで"), "skd_deep": ("Lay a hand +40%, let it sit +20%.", "「手を置く」+40%、「寝かせる」+20%。"),
# the counter (scripts/counter.gd)
"sh_ledger": ("The book", "帳簿"),
"sh_till": ("Till: £%d", "金庫：£%d"),
"sh_rep": ("Reputation %d  %s", "評判 %d  %s"),
"sh_pledges": ("Pledges out", "預かり中の質草"),
"sh_pledge_row": ("%s — lent £%d, due %s", "%s — 貸付£%d、期限 %s"),
"sh_stock": ("Stock", "在庫"),
"sh_open": ("The counter — %s", "カウンター — %s"),
"sh_redeemed": ("%s: redeemed. £%d back across the glass, interest and all.", "%s：請け出し。利息込みで£%dがガラス越しに戻る。"),
"sh_forfeit": ("%s: nobody came. Thirty days are thirty days; it is stock now.", "%s：誰も来なかった。三十日は三十日。もう在庫だ。"),
"sh_looks": ("Looks like £%d.", "見た目は£%d。"),
"sh_worth": ("Under your hand: worth £%d.", "手の下で：値打ち£%d。"),
"sh_fake": ("Under your hand: a fake. Worth next to nothing.", "手の下で：偽物。ほとんど無価値。"),
"sh_touch": ("Lay a hand on it (3 moves)", "手を置く（3手）"),
"sh_lend": ("Lend £%d against it (%d%%) — they may come back with interest", "£%dを貸す（%d%%）— 利息つきで戻るかもしれない"),
"sh_buy": ("Buy it outright: £%d (%d%%)", "買い取る：£%d（%d%%）"),
"sh_away": ("Send them away", "断る"),
"sh_away_line": ("The bell. The rain. Not every door is a sale.", "ベル。雨。扉がいつも商いとは限らない。"),
"sh_refused": ("£%d? They pick it up again. Not for that.", "£%d？ 品を拾い上げる。その額じゃ無理だ。"),
"sh_lent": ("£%d out of the drawer, a ticket across. Due %s.", "引き出しから£%d、質札を渡す。期限は%s。"),
"sh_bought": ("£%d, and it goes on the shelf.", "£%dで、棚に並ぶ。"),
"sh_sell_to": ("Sell %s for £%d", "%sを£%dで売る"),
"sh_nothing": ("Nothing on the shelf for them", "渡せるものはない"),
"sh_sold_buyer": ("£%d, paid gladly. Word gets round.", "£%d、気持ちよく支払われた。噂は広まる。"),
"sh_buyer_gone": ("They leave a card. Come back with one, it says.", "名刺を置いていく。手に入ったら、と書いてある。"),
"sh_closed": ("Lamp down", "灯りを落とす"),
"sh_closed_body": ("The counter is closed for this hour.", "この刻のカウンターは閉店。"),
"sh_market": ("The stalls", "屋台"),
"sh_market_body": ("The Market buys what the shop could not keep, and sells what the stair will cost you.", "市場は店が抱えきれなかったものを買い、階段で要るものを売る。"),
"sh_sell": ("Sell %s — £%d", "%sを売る — £%d"),
"sh_buy_good": ("Buy %s — £%d", "%sを買う — £%d"),
"sh_leave": ("Done here", "ここまで"),
# trial end (bilingual screen)
"tr_end_title": ("The trial ends here.", "体験版はここまでです。"),
"tr_end_body": ("Midnight is priced. The full game keeps the counter running — loans coming due, stock for the Market, curios from below — through four more hours of the same night: Ivo's ring, Mara's veil, the Ossuary Market and Calder's offer, and the last object on the counter. Twenty-one standoffs, sixteen CGs, three endings, about two and a half hours. The full version is the one on DLsite.", "午前零時の値付けは終わりました。製品版ではカウンター経営（期限の来る質草、市場へ売る在庫、地下の骨董）を回しながら、同じ夜がさらに四つの刻へ続きます。アイヴォの指輪、マーラのヴェール、骨の市場とカルダーの申し出、そしてカウンターに置かれる最後の品。対決21戦、CG16枚、エンディング3種、約2時間半。製品版はDLsiteで販売中です。"),
"tr_back": ("Back to title", "タイトルへ戻る"),
}
