class_name Rebound
## Port of play/rebound-tycoon/frontend/js/kernel.js — the table, the ledger, the eras,
## the prestige. Pure state (a Dictionary shaped exactly like the JS state object) and
## static functions; nothing here touches the scene tree. Every constant and formula is
## the JS one; tests/run_tests.gd replays tests/conformance.json (generated by running
## the real kernel.js in node) and asserts bit-identical positions, scores and events.
##
## Rounding traps (see tests/run_tests.gd "libm parity"): JS Math.hypot is Kahan-summed
## and scaled in V8 and is NOT sqrt(x*x+y*y) — hypot() below is V8's algorithm, which
## reproduces it bit for bit. pow/sin/cos go to the C library and are checked for parity
## on the inputs the table actually uses.

const SAVE_VERSION := 2
const GRAVITY := 1.35
const DAMP := 0.996
const MAX_SPEED := 2.6
const BALL_R := 0.017
const FLIP_LEN := 0.155
const FLIP_R := 0.016
const BALLS := 3
const COMBO_WINDOW_S := 2.2
const COMBO_CAP := 8
const COMBO_STEP := 0.12
const PRESTIGE_MIN_ERA := 1
const PRESTIGE_COIN_DIV := 4000
const SUBSTEPS := 4

const TABLE := {"left": 0.075, "right": 0.855, "top": 0.055, "bottom": 0.965,
	"laneL": 0.875, "laneR": 0.955, "drainL": 0.40, "drainR": 0.60}

const LEFT_PIVOT := Vector2(0.255, 0.865)
const RIGHT_PIVOT := Vector2(0.675, 0.865)
const LEFT_REST := 0.42
const LEFT_UP := -0.70
const RIGHT_REST := PI - 0.42
const RIGHT_UP := PI + 0.70

const BUMPERS := [
	{"id": "courier", "x": 0.34, "y": 0.30, "r": 0.048, "score": 90},
	{"id": "party", "x": 0.58, "y": 0.30, "r": 0.048, "score": 90},
	{"id": "raccoon", "x": 0.46, "y": 0.44, "r": 0.052, "score": 120},
]
const TARGETS := [
	{"id": "booth", "x": 0.28, "y": 0.155, "w": 0.07, "h": 0.028, "score": 180},
	{"id": "lobby", "x": 0.46, "y": 0.125, "w": 0.07, "h": 0.028, "score": 180},
	{"id": "tower", "x": 0.64, "y": 0.155, "w": 0.07, "h": 0.028, "score": 180},
]
const SAUCER := {"x": 0.46, "y": 0.58, "r": 0.028, "score": 500}
const WALLS := [
	[0.075, 0.16, 0.075, 0.78],
	[0.075, 0.16, 0.38, 0.055],
	[0.38, 0.055, 0.70, 0.055],
	[0.70, 0.055, 0.82, 0.12],
	[0.855, 0.28, 0.855, 0.70],
	[0.075, 0.78, 0.230, 0.875],
	[0.700, 0.875, 0.855, 0.70],
	[0.875, 0.30, 0.875, 0.90],
	[0.955, 0.05, 0.955, 0.90],
	[0.855, 0.90, 0.955, 0.90],
	[0.82, 0.12, 0.70, 0.055],
	[0.18, 0.62, 0.075, 0.52],
	[0.75, 0.62, 0.855, 0.52],
]
const SLINGS := [
	{"ax": 0.16, "ay": 0.70, "bx": 0.27, "by": 0.80, "kick": 1.15},
	{"ax": 0.77, "ay": 0.70, "bx": 0.66, "by": 0.80, "kick": 1.15},
]
const ERAS := [
	{"id": "booth", "minScore": 0, "mult": 1.0},
	{"id": "lobby", "minScore": 4, "mult": 1.15},
	{"id": "towers", "minScore": 14, "mult": 1.35},
	{"id": "neon", "minScore": 32, "mult": 1.6},
]
const UPGRADES := [
	{"id": "springs", "group": "table", "baseCost": 40, "growth": 1.22, "skyline": 0},
	{"id": "flippers", "group": "table", "baseCost": 55, "growth": 1.24, "skyline": 0},
	{"id": "bumpers", "group": "table", "baseCost": 70, "growth": 1.23, "skyline": 0},
	{"id": "slings", "group": "table", "baseCost": 45, "growth": 1.22, "skyline": 0},
	{"id": "doorman", "group": "staff", "baseCost": 80, "growth": 1.2, "skyline": 0},
	{"id": "concierge", "group": "staff", "baseCost": 110, "growth": 1.22, "skyline": 0},
	{"id": "manager", "group": "staff", "baseCost": 160, "growth": 1.25, "skyline": 1},
	{"id": "studio", "group": "property", "baseCost": 90, "growth": 1.18, "skyline": 2},
	{"id": "loft", "group": "property", "baseCost": 180, "growth": 1.2, "skyline": 4},
	{"id": "penthouse", "group": "property", "baseCost": 320, "growth": 1.22, "skyline": 8},
	{"id": "cannon", "group": "table", "baseCost": 140, "growth": 1.26, "skyline": 1},
	{"id": "neon", "group": "amenity", "baseCost": 240, "growth": 1.24, "skyline": 3},
]
const PERKS := [
	{"id": "uniform", "tokenBase": 1, "tokenGrowth": 1.6, "income": 0.08},
	{"id": "legend", "tokenBase": 1, "tokenGrowth": 1.7, "cannon": 0.12},
	{"id": "switchboard", "tokenBase": 1, "tokenGrowth": 1.65, "spawn": 0.08},
	{"id": "empire", "tokenBase": 1, "tokenGrowth": 1.75, "idle": 0.12},
]


static func upgrade_by_id(id: String) -> Dictionary:
	for u in UPGRADES:
		if u["id"] == id:
			return u
	return {}


static func perk_by_id(id: String) -> Dictionary:
	for p in PERKS:
		if p["id"] == id:
			return p
	return {}


## V8's Math.hypot: scale by the largest magnitude, Kahan-sum the squares, sqrt, rescale.
static func hypot(a: float, b: float) -> float:
	var aa: float = abs(a)
	var bb: float = abs(b)
	var mx: float = aa if aa > bb else bb
	if mx == 0.0:
		return 0.0
	var sum := 0.0
	var comp := 0.0
	for v in [aa, bb]:
		var n: float = v / mx
		var s: float = n * n - comp
		var p: float = sum + s
		comp = (p - sum) - s
		sum = p
	return sqrt(sum) * mx


static func empty_owned() -> Dictionary:
	var o := {}
	for u in UPGRADES:
		o[u["id"]] = 0
	return o


static func empty_perks() -> Dictionary:
	var p := {}
	for k in PERKS:
		p[k["id"]] = 0
	return p


static func fresh_ball() -> Dictionary:
	return {"x": 0.915, "y": 0.82, "vx": 0.0, "vy": 0.0}


static func new_state() -> Dictionary:
	return {
		"version": SAVE_VERSION, "coins": 0.0, "score": 0.0, "owned": empty_owned(), "perks": empty_perks(),
		"tokens": 0, "combo": 0, "comboLeft": 0.0, "balls": BALLS, "night": 1, "prestiges": 0,
		"lifetime": 0.0, "runCoins": 0.0, "rebounds": 0, "buys": 0, "mode": "plunge", "plunge": 0.0,
		"flipL": LEFT_REST, "flipR": RIGHT_REST, "flipLv": 0.0, "flipRv": 0.0, "ball": fresh_ball(),
		"bumperFlash": [0.0, 0.0, 0.0], "targetDown": [false, false, false], "saucerHold": 0.0,
		"ballSave": 0.0, "inPlay": false, "savedAt": 0,
	}


static func _num(v) -> float:
	match typeof(v):
		TYPE_FLOAT, TYPE_INT: return float(v)
		TYPE_BOOL: return 1.0 if v else 0.0
		TYPE_STRING: return float(v) if (v as String).is_valid_float() else 0.0
	return 0.0


static func hydrate(raw) -> Dictionary:
	var state := new_state()
	if typeof(raw) != TYPE_DICTIONARY or int(_num(raw.get("version", 0))) != SAVE_VERSION:
		return state
	state["coins"] = max(0.0, _num(raw.get("coins")))
	state["score"] = max(0.0, _num(raw.get("score")))
	state["tokens"] = int(max(0.0, _num(raw.get("tokens"))))
	state["combo"] = int(max(0.0, _num(raw.get("combo"))))
	state["comboLeft"] = max(0.0, _num(raw.get("comboLeft")))
	state["balls"] = int(max(0.0, _num(raw.get("balls"))))
	state["night"] = int(max(1.0, _num(raw.get("night", 1))))
	if state["night"] < 1:
		state["night"] = 1
	state["prestiges"] = int(max(0.0, _num(raw.get("prestiges"))))
	state["lifetime"] = max(0.0, _num(raw.get("lifetime")))
	state["runCoins"] = max(0.0, _num(raw.get("runCoins")))
	state["rebounds"] = int(max(0.0, _num(raw.get("rebounds"))))
	state["buys"] = int(max(0.0, _num(raw.get("buys"))))
	var mode = raw.get("mode", "")
	state["mode"] = mode if (mode == "live" or mode == "nightover") else "plunge"
	state["plunge"] = min(1.0, max(0.0, _num(raw.get("plunge"))))
	state["inPlay"] = bool(raw.get("inPlay", false))
	var owned = raw.get("owned")
	for u in UPGRADES:
		var v := 0
		if typeof(owned) == TYPE_DICTIONARY:
			v = int(_num(owned.get(u["id"], 0)))
		state["owned"][u["id"]] = max(0, v)
	var perks = raw.get("perks")
	for p in PERKS:
		var v := 0
		if typeof(perks) == TYPE_DICTIONARY:
			v = int(_num(perks.get(p["id"], 0)))
		state["perks"][p["id"]] = max(0, v)
	var ball = raw.get("ball")
	if typeof(ball) == TYPE_DICTIONARY:
		var bx := _num(ball.get("x"))
		var by := _num(ball.get("y"))
		state["ball"] = {"x": bx if bx != 0.0 else 0.915, "y": by if by != 0.0 else 0.82,
			"vx": _num(ball.get("vx")), "vy": _num(ball.get("vy"))}
	if state["mode"] == "live" and state["ball"] != null and not state["inPlay"] and float(state["ball"]["x"]) > 0.86:
		state["mode"] = "plunge"
		state["plunge"] = 0.0
		state["ball"] = fresh_ball()
	if state["mode"] == "nightover":
		state["ball"] = null
	return state


static func snapshot(state: Dictionary, now_ms: int) -> Dictionary:
	var out: Dictionary = state.duplicate(true)
	out["version"] = SAVE_VERSION
	out["savedAt"] = now_ms
	return out


static func level_of(state: Dictionary, id: String) -> int:
	return int(state.get("owned", {}).get(id, 0))


static func perk_of(state: Dictionary, id: String) -> int:
	return int(state.get("perks", {}).get(id, 0))


static func scale_cost(base: float, growth: float, level: int) -> int:
	return int(floor(base * pow(growth, max(0, level))))


static func upgrade_cost(id: String, level: int) -> int:
	var u := upgrade_by_id(id)
	return scale_cost(float(u["baseCost"]), float(u["growth"]), level) if not u.is_empty() else 0x7fffffff


static func perk_cost(id: String, level: int) -> int:
	var p := perk_by_id(id)
	if p.is_empty():
		return 0x7fffffff
	return max(1, int(floor(float(p["tokenBase"]) * pow(float(p["tokenGrowth"]), max(0, level)))))


static func skyline_score(state: Dictionary) -> int:
	var score := 0
	for u in UPGRADES:
		score += level_of(state, u["id"]) * int(u["skyline"])
	return score


static func era_index(state: Dictionary) -> int:
	var score := skyline_score(state)
	var idx := 0
	for i in range(ERAS.size()):
		if score >= int(ERAS[i]["minScore"]):
			idx = i
	return idx


static func era_id(state: Dictionary) -> String:
	return ERAS[era_index(state)]["id"]


static func era_mult(state: Dictionary) -> float:
	return float(ERAS[era_index(state)]["mult"])


static func prestige_mult(state: Dictionary) -> float:
	return 1.0 + perk_of(state, "uniform") * 0.08 + perk_of(state, "empire") * 0.12


static func score_mult(state: Dictionary) -> float:
	var studio := 1.0 + level_of(state, "studio") * 0.08
	var loft := 1.0 + level_of(state, "loft") * 0.1
	var pent := 1.0 + level_of(state, "penthouse") * 0.12
	var neon := 1.0 + level_of(state, "neon") * 0.1
	var concierge := 1.0 + level_of(state, "concierge") * 0.06
	return studio * loft * pent * neon * concierge * era_mult(state) * prestige_mult(state)


static func combo_mult(combo: int) -> float:
	return 1.0 + min(COMBO_CAP, max(0, combo)) * COMBO_STEP


static func flip_power(state: Dictionary) -> float:
	return 10.0 + level_of(state, "flippers") * 2.2


static func bumper_kick(state: Dictionary) -> float:
	return 0.55 + level_of(state, "bumpers") * 0.12


static func sling_kick(state: Dictionary) -> float:
	return 0.85 + level_of(state, "slings") * 0.15


static func plunge_power(state: Dictionary) -> float:
	return 1.7 + level_of(state, "springs") * 0.22


static func cannon_kick(state: Dictionary) -> float:
	return 1.5 + level_of(state, "cannon") * 0.25 + perk_of(state, "legend") * 0.2


static func start_balls(state: Dictionary) -> int:
	return BALLS + (1 if level_of(state, "manager") > 0 else 0)


static func save_time(state: Dictionary) -> float:
	return level_of(state, "doorman") * 1.4


static func award(state: Dictionary, base: float) -> int:
	var pts := int(floor(base * score_mult(state) * combo_mult(int(state["combo"]))))
	state["score"] = float(state["score"]) + pts
	var coins := max(1, int(floor(float(pts) / 12.0)))
	state["coins"] = float(state["coins"]) + coins
	state["lifetime"] = float(state["lifetime"]) + coins
	state["runCoins"] = float(state["runCoins"]) + coins
	state["combo"] = min(COMBO_CAP, int(state["combo"]) + 1)
	state["comboLeft"] = COMBO_WINDOW_S
	state["rebounds"] = int(state["rebounds"]) + 1
	return pts


static func clamp_ball(ball: Dictionary) -> void:
	var sp := hypot(ball["vx"], ball["vy"])
	if sp > MAX_SPEED:
		ball["vx"] = float(ball["vx"]) * (MAX_SPEED / sp)
		ball["vy"] = float(ball["vy"]) * (MAX_SPEED / sp)


static func hit_wall(ball: Dictionary, ax: float, ay: float, bx: float, by: float, bounce: float) -> bool:
	var abx := bx - ax
	var aby := by - ay
	var apx := float(ball["x"]) - ax
	var apy := float(ball["y"]) - ay
	var ab2 := abx * abx + aby * aby
	if ab2 == 0.0:
		ab2 = 1.0
	var t := (apx * abx + apy * aby) / ab2
	t = max(0.0, min(1.0, t))
	var cx := ax + abx * t
	var cy := ay + aby * t
	var dx := float(ball["x"]) - cx
	var dy := float(ball["y"]) - cy
	var dist := hypot(dx, dy)
	if dist >= BALL_R or dist < 1e-8:
		return false
	var nx := dx / dist
	var ny := dy / dist
	ball["x"] = cx + nx * BALL_R
	ball["y"] = cy + ny * BALL_R
	var vn := float(ball["vx"]) * nx + float(ball["vy"]) * ny
	if vn < 0.0:
		ball["vx"] = float(ball["vx"]) - (1.0 + bounce) * vn * nx
		ball["vy"] = float(ball["vy"]) - (1.0 + bounce) * vn * ny
	return true


static func hit_circle(ball: Dictionary, cx: float, cy: float, cr: float, kick: float) -> bool:
	var dx := float(ball["x"]) - cx
	var dy := float(ball["y"]) - cy
	var dist := hypot(dx, dy)
	var mn := BALL_R + cr
	if dist >= mn:
		return false
	var nx := 0.0 if dist < 1e-8 else dx / dist
	var ny := -1.0 if dist < 1e-8 else dy / dist
	ball["x"] = cx + nx * mn
	ball["y"] = cy + ny * mn
	var vn := float(ball["vx"]) * nx + float(ball["vy"]) * ny
	if vn < 0.0:
		ball["vx"] = float(ball["vx"]) - 1.85 * vn * nx
		ball["vy"] = float(ball["vy"]) - 1.85 * vn * ny
	ball["vx"] = float(ball["vx"]) + nx * kick
	ball["vy"] = float(ball["vy"]) + ny * kick
	return true


static func flipper_end(pivot: Vector2, angle: float) -> Vector2:
	return Vector2(pivot.x + cos(angle) * FLIP_LEN, pivot.y + sin(angle) * FLIP_LEN)


static func hit_flipper(ball: Dictionary, pivot: Vector2, angle: float, omega: float, power: float) -> bool:
	var tip := flipper_end(pivot, angle)
	var hit := hit_wall(ball, pivot.x, pivot.y, tip.x, tip.y, 0.25)
	if not hit:
		return false
	var rx := float(ball["x"]) - pivot.x
	var ry := float(ball["y"]) - pivot.y
	var fx := -omega * ry
	var fy := omega * rx
	ball["vx"] = float(ball["vx"]) + fx * 0.35 + cos(angle - PI / 2.0) * max(0.0, omega) * power * 0.012
	ball["vy"] = float(ball["vy"]) + fy * 0.35 + sin(angle - PI / 2.0) * max(0.0, -omega) * power * 0.012
	if omega != 0.0:
		var nx := cos(angle - PI / 2.0)
		var ny := sin(angle - PI / 2.0)
		var sign := -1.0 if pivot.x < 0.5 else 1.0
		ball["vx"] = float(ball["vx"]) + nx * abs(omega) * 0.08 * sign
		ball["vy"] = float(ball["vy"]) + ny * abs(omega) * 0.08
	return true


static func hit_target(ball: Dictionary, t: Dictionary) -> bool:
	var x: float = max(float(t["x"]), min(float(t["x"]) + float(t["w"]), float(ball["x"])))
	var y: float = max(float(t["y"]), min(float(t["y"]) + float(t["h"]), float(ball["y"])))
	return hypot(float(ball["x"]) - x, float(ball["y"]) - y) < BALL_R


## charge_override < 0 means "none" (JS null).
static func launch_ball(state: Dictionary, charge_override: float = -1.0) -> float:
	if state["mode"] != "plunge" or state["ball"] == null:
		return 0.0
	var charge: float = max(0.55, charge_override if charge_override >= 0.0 else float(state["plunge"]))
	var min_vy := 1.48
	state["ball"]["x"] = 0.915
	state["ball"]["y"] = 0.78
	state["ball"]["vx"] = 0.04
	state["ball"]["vy"] = -max(min_vy, plunge_power(state) * charge)
	state["mode"] = "live"
	state["plunge"] = 0.0
	state["inPlay"] = false
	state["ballSave"] = save_time(state)
	return charge


static func drain_ball(state: Dictionary) -> String:
	if float(state["ballSave"]) > 0.0 and state["ball"] != null:
		state["ball"]["x"] = 0.46
		state["ball"]["y"] = 0.72
		state["ball"]["vx"] = 0.0
		state["ball"]["vy"] = -0.9
		state["ballSave"] = 0.0
		return "save"
	state["balls"] = int(state["balls"]) - 1
	state["combo"] = 0
	state["comboLeft"] = 0.0
	state["targetDown"] = [false, false, false]
	if int(state["balls"]) <= 0:
		state["mode"] = "nightover"
		state["ball"] = null
		return "nightover"
	state["mode"] = "plunge"
	state["ball"] = fresh_ball()
	state["plunge"] = 0.0
	state["inPlay"] = false
	return "drain"


static func new_night(state: Dictionary) -> Dictionary:
	var next: Dictionary = state.duplicate(true)
	next["mode"] = "plunge"
	next["balls"] = start_balls(next)
	next["score"] = 0.0
	next["combo"] = 0
	next["comboLeft"] = 0.0
	next["plunge"] = 0.0
	next["ball"] = fresh_ball()
	next["inPlay"] = false
	next["targetDown"] = [false, false, false]
	next["saucerHold"] = 0.0
	next["night"] = int(next["night"]) + 1
	return next


## step(state, input, dt, rng) -> {state, events}. input: {left, right, plunge, fire}.
## rng is a Callable returning [0,1) — the one place the JS calls Math.random (the
## cannon's sideways kick); the conformance test hands in the same LCG as the JS run.
static func step(state: Dictionary, input: Dictionary, dt: float, rng: Callable = Callable()) -> Dictionary:
	var next: Dictionary = state.duplicate(true)
	var events: Array = []
	var seconds: float = max(0.0, min(0.05, dt))
	if float(next["comboLeft"]) > 0.0:
		next["comboLeft"] = max(0.0, float(next["comboLeft"]) - seconds)
		if float(next["comboLeft"]) == 0.0:
			next["combo"] = 0
	var flash: Array = []
	for v in next["bumperFlash"]:
		flash.append(max(0.0, float(v) - seconds * 4.0))
	next["bumperFlash"] = flash
	if float(next["ballSave"]) > 0.0:
		next["ballSave"] = max(0.0, float(next["ballSave"]) - seconds)

	var speed := flip_power(next)
	var target_l: float = LEFT_UP if input.get("left", false) else LEFT_REST
	var target_r: float = RIGHT_UP if input.get("right", false) else RIGHT_REST
	var prev_l: float = next["flipL"]
	var prev_r: float = next["flipR"]
	next["flipL"] = float(next["flipL"]) + (target_l - float(next["flipL"])) * min(1.0, seconds * speed)
	next["flipR"] = float(next["flipR"]) + (target_r - float(next["flipR"])) * min(1.0, seconds * speed)
	next["flipLv"] = ((float(next["flipL"]) - prev_l) / seconds) if seconds != 0.0 else 0.0
	next["flipRv"] = ((float(next["flipR"]) - prev_r) / seconds) if seconds != 0.0 else 0.0

	if next["mode"] == "plunge":
		if next["ball"] == null:
			next["ball"] = fresh_ball()
		next["ball"]["x"] = 0.915
		next["ball"]["y"] = 0.82 - float(next["plunge"]) * 0.08
		next["ball"]["vx"] = 0.0
		next["ball"]["vy"] = 0.0
		if input.get("fire", false):
			var charge := launch_ball(next, max(float(next["plunge"]), 0.78))
			events.append({"type": "launch", "charge": charge})
			return {"state": next, "events": events}
		if input.get("plunge", false):
			next["plunge"] = min(1.0, float(next["plunge"]) + seconds * 2.4)
			if float(next["plunge"]) >= 1.0:
				events.append({"type": "launch", "charge": launch_ball(next, 1.0)})
		elif float(next["plunge"]) > 0.08:
			events.append({"type": "launch", "charge": launch_ball(next)})
		else:
			next["plunge"] = 0.0
		return {"state": next, "events": events}

	if next["mode"] != "live" or next["ball"] == null:
		return {"state": next, "events": events}

	var ball: Dictionary = next["ball"]
	if float(next["saucerHold"]) > 0.0:
		next["saucerHold"] = max(0.0, float(next["saucerHold"]) - seconds)
		ball["x"] = float(SAUCER["x"])
		ball["y"] = float(SAUCER["y"])
		ball["vx"] = 0.0
		ball["vy"] = 0.0
		if float(next["saucerHold"]) == 0.0:
			ball["vy"] = -cannon_kick(next)
			var r: float = rng.call() if rng.is_valid() else randf()
			ball["vx"] = (r - 0.5) * 0.3
			events.append({"type": "cannon"})
		return {"state": next, "events": events}

	var h := seconds / float(SUBSTEPS)
	for i in range(SUBSTEPS):
		ball["vy"] = float(ball["vy"]) + GRAVITY * h
		ball["vx"] = float(ball["vx"]) * pow(DAMP, h * 60.0)
		ball["vy"] = float(ball["vy"]) * pow(DAMP, h * 60.0)
		ball["x"] = float(ball["x"]) + float(ball["vx"]) * h
		ball["y"] = float(ball["y"]) + float(ball["vy"]) * h
		if not next["inPlay"] and float(ball["x"]) > 0.86 and float(ball["y"]) < 0.40:
			ball["vx"] = -1.7
			ball["vy"] = min(float(ball["vy"]), -0.2)
		if not next["inPlay"] and float(ball["x"]) < 0.84 and float(ball["y"]) < 0.50:
			next["inPlay"] = true
			ball["vx"] = min(float(ball["vx"]), -0.85)
			if float(ball["vy"]) > 0.7:
				ball["vy"] = 0.55
		if not next["inPlay"] and float(ball["x"]) > 0.86 and float(ball["y"]) > 0.86 and float(ball["vy"]) >= 0.0:
			next["mode"] = "plunge"
			next["plunge"] = 0.0
			next["ball"] = fresh_ball()
			events.append({"type": "reload"})
			break
		if next["inPlay"]:
			hit_wall(ball, 0.86, 0.05, 0.86, 0.32, 0.2)
		clamp_ball(ball)

		for w in WALLS:
			hit_wall(ball, w[0], w[1], w[2], w[3], 0.42)

		for idx in range(BUMPERS.size()):
			var b: Dictionary = BUMPERS[idx]
			if hit_circle(ball, b["x"], b["y"], b["r"], bumper_kick(next)):
				next["bumperFlash"][idx] = 1.0
				var pts := award(next, float(b["score"]))
				events.append({"type": "bumper", "i": idx, "id": b["id"], "pts": pts})

		for s in SLINGS:
			if hit_wall(ball, s["ax"], s["ay"], s["bx"], s["by"], 0.1):
				var nx: float = float(s["bx"]) - float(s["ax"])
				var ny: float = float(s["by"]) - float(s["ay"])
				var len := hypot(nx, ny)
				if len == 0.0:
					len = 1.0
				var px := -ny / len
				var kick := sling_kick(next)
				ball["vx"] = float(ball["vx"]) + px * kick * (1.0 if float(s["ax"]) < 0.5 else -1.0)
				ball["vy"] = float(ball["vy"]) - kick * 0.35
				var pts := award(next, 25.0)
				events.append({"type": "sling", "pts": pts})

		for idx in range(TARGETS.size()):
			var t: Dictionary = TARGETS[idx]
			if not next["targetDown"][idx] and hit_target(ball, t):
				next["targetDown"][idx] = true
				ball["vy"] = abs(float(ball["vy"])) * 0.4 + 0.2
				var pts := award(next, float(t["score"]))
				events.append({"type": "target", "i": idx, "id": t["id"], "pts": pts})
		if next["targetDown"][0] and next["targetDown"][1] and next["targetDown"][2]:
			next["targetDown"] = [false, false, false]
			var pts := award(next, 800.0)
			events.append({"type": "gate", "pts": pts})

		if hit_circle(ball, SAUCER["x"], SAUCER["y"], SAUCER["r"], 0.0) and hypot(float(ball["vx"]), float(ball["vy"])) < 1.4:
			next["saucerHold"] = 0.35
			var pts := award(next, float(SAUCER["score"]))
			events.append({"type": "saucer", "pts": pts})

		hit_flipper(ball, LEFT_PIVOT, next["flipL"], next["flipLv"], flip_power(next))
		hit_flipper(ball, RIGHT_PIVOT, next["flipR"], next["flipRv"], flip_power(next))

		if float(ball["y"]) > float(TABLE["bottom"]) and float(ball["x"]) > float(TABLE["drainL"]) and float(ball["x"]) < float(TABLE["drainR"]):
			var kind := drain_ball(next)
			events.append({"type": kind})
			break
		if float(ball["y"]) > 1.08 or float(ball["x"]) < -0.05 or float(ball["x"]) > 1.05:
			var kind := drain_ball(next)
			events.append({"type": kind})
			break

	return {"state": next, "events": events}


static func can_buy(state: Dictionary, id: String) -> bool:
	return not upgrade_by_id(id).is_empty() and float(state["coins"]) + 1e-9 >= upgrade_cost(id, level_of(state, id))


static func buy(state: Dictionary, id: String) -> Dictionary:
	if not can_buy(state, id):
		return {"ok": false, "state": state.duplicate(true), "spent": 0}
	var cost := upgrade_cost(id, level_of(state, id))
	var next: Dictionary = state.duplicate(true)
	next["coins"] = float(next["coins"]) - cost
	next["owned"][id] = level_of(state, id) + 1
	next["buys"] = int(next["buys"]) + 1
	return {"ok": true, "state": next, "spent": cost}


static func can_buy_perk(state: Dictionary, id: String) -> bool:
	return not perk_by_id(id).is_empty() and int(state["tokens"]) >= perk_cost(id, perk_of(state, id))


static func buy_perk(state: Dictionary, id: String) -> Dictionary:
	if not can_buy_perk(state, id):
		return {"ok": false, "state": state.duplicate(true), "spent": 0}
	var cost := perk_cost(id, perk_of(state, id))
	var next: Dictionary = state.duplicate(true)
	next["tokens"] = int(next["tokens"]) - cost
	next["perks"][id] = perk_of(state, id) + 1
	return {"ok": true, "state": next, "spent": cost}


static func prestige_tokens_for(state: Dictionary) -> int:
	if era_index(state) < PRESTIGE_MIN_ERA:
		return 0
	return int(floor(sqrt(max(0.0, float(state["runCoins"])) / float(PRESTIGE_COIN_DIV))))


static func can_prestige(state: Dictionary) -> bool:
	return prestige_tokens_for(state) >= 1


static func do_prestige(state: Dictionary) -> Dictionary:
	var tokens := prestige_tokens_for(state)
	if tokens < 1:
		return {"ok": false, "state": state.duplicate(true), "tokens": 0}
	var next := new_state()
	next["perks"] = state["perks"].duplicate(true)
	next["tokens"] = int(state["tokens"]) + tokens
	next["prestiges"] = int(state["prestiges"]) + 1
	next["lifetime"] = state["lifetime"]
	next["night"] = int(state["night"]) + 1
	next["rebounds"] = state["rebounds"]
	next["buys"] = state["buys"]
	next["balls"] = start_balls(next)
	return {"ok": true, "state": next, "tokens": tokens}


## JS (v/1e9).toFixed(2): ties round half away from zero in V8's dtoa; C's %.2f rounds
## to even. Done by hand on the scaled integer so the two agree.
static func _fixed(v: float, digits: int) -> String:
	var scale := pow(10.0, digits)
	var scaled := v * scale
	var n: float = floor(scaled)
	if scaled - n >= 0.5:
		n += 1.0
	var s := str(int(n))
	while s.length() <= digits:
		s = "0" + s
	return s.substr(0, s.length() - digits) + "." + s.substr(s.length() - digits)


static func format_coins(n: float) -> String:
	var v := n
	if v >= 1e9:
		return _fixed(v / 1e9, 2) + "B"
	if v >= 1e6:
		return _fixed(v / 1e6, 2) + "M"
	if v >= 10000:
		return _fixed(v / 1000.0, 1) + "K"
	return str(int(floor(v)))
