# Night 1 strings and the game-wide names/actions/items. (key: (EN, JA))
# New RPG writing follows the VN's voice: short declaratives, present tense, second person.
S = {
"title": ("Elena: Crimson Archives", "エレナ：深紅の書庫"),
"t_subtitle": ("Five nights in the Blackwood wing", "ブラックウッド棟の五夜"),
"t_note": ("18+ · All characters are adults · AI-generated work (see Settings → About)", "18歳以上対象 · 登場人物は全員成人です · AI生成作品（設定 → 作品について）"),
"n_protagonist": ("Vance", "ヴァンス"), "n_vance": ("Vance", "ヴァンス"), "n_elena": ("Elena", "エレナ"),
"n_cobb": ("Cobb", "コブ"), "n_penhallow": ("Penhallow", "ペンハロウ"), "n_dean": ("Dean Holloway", "ホロウェイ学部長"),
# stats
"s_wit": ("Wit", "知力"), "s_cha": ("Charm", "魅力"), "s_grt": ("Grit", "根性"), "s_stl": ("Stealth", "隠密"),
"sd_wit": ("Bluffs, evidence, nerve pool.", "はったり・証拠・胆力の上限。"), "sd_cha": ("Bribes and charm.", "買収と魅了。"),
"sd_grt": ("Composure, and how hard a threat lands.", "平静の上限と、脅しの重さ。"), "sd_stl": ("Stalling brings suspicion down further.", "時間稼ぎで疑念を大きく下げる。"),
# actions
"a_deflect": ("Deflect", "受け流す"), "a_observe": ("Read the room", "空気を読む"), "a_bluff": ("Bluff", "はったり"),
"a_evidence": ("Show evidence", "証拠を示す"), "a_bribe": ("Bribe", "買収"), "a_flirt": ("Flirt", "誘惑"),
"a_threaten": ("Threaten", "脅す"), "a_stall": ("Stall", "時間稼ぎ"), "a_item": ("Use item", "アイテム"),
"a_lecture": ("Lecture", "講義"), "a_recite": ("Recite in Latin", "ラテン語で暗誦"),
"ad_deflect": ("Halve the next blow and cool the room a little.", "次の一撃を和らげ、疑念を少し下げる。"),
"ad_observe": ("Elena reads them: reveals their weaknesses.", "エレナが相手を読む：弱点が分かる。"),
"ad_bluff": ("A confident lie. Wit.", "自信たっぷりの嘘。知力。"),
"ad_evidence": ("Put a document in front of them. Lowers suspicion. Needs evidence.", "書類を突きつける。疑念が下がる。証拠品が必要。"),
"ad_bribe": ("Folded notes. Charm. Uses one cash.", "折った紙幣。魅力。現金を一つ使う。"),
"ad_flirt": ("Warmth where they did not expect it. Charm.", "思いがけない温かさ。魅力。"),
"ad_threaten": ("Hits hard — and they remember. Suspicion climbs faster for the rest of the standoff.", "強烈だが、相手は忘れない。以後この対峙では疑念が速く上がる。"),
"ad_stall": ("Talk about the weather. Suspicion falls; a little composure back.", "天気の話でもする。疑念が下がり、平静が少し戻る。"),
"ad_item": ("Use something from your pockets.", "持ち物を使う。"),
"ad_lecture": ("Twenty minutes on provenance. Nobody interrupts a professor.", "来歴について二十分。教授の話を遮る者はいない。"),
"ad_recite": ("Elena quotes the statutes at them, in the original.", "エレナが原文のまま学則を読み上げる。"),
# items
"i_cash": ("Petty cash", "小口現金"), "id_cash": ("Twenties from the department tin. For bribes.", "学科の缶から取った二十ポンド札。買収用。"),
"i_tea": ("Flask of tea", "紅茶の水筒"), "id_tea": ("Restores 16 composure.", "平静を16回復。"),
"i_sherry": ("College sherry", "学寮のシェリー"), "id_sherry": ("Restores 8 nerve.", "胆力を8回復。"),
"i_hip_flask": ("Silver hip flask", "銀のスキットル"), "id_hip_flask": ("Hers, engraved E.A. — give it back to her.", "E.A.と刻まれた彼女の物。返してあげよう。"),
"i_override_key": ("Override key", "オーバーライドキー"), "id_override_key": ("Opens the Blackwood vault after eleven.", "十一時以降のブラックウッド書庫を開ける。"),
"i_deaccession": ("Deaccession notice", "除籍通知"), "id_deaccession": ("Evidence. The crate is listed for burning tomorrow.", "証拠。木箱は明日焼却予定と記されている。"),
"i_porter_rota": ("Porter's rota", "守衛の当番表"), "id_porter_rota": ("Evidence. Cobb signed for a round he never walked.", "証拠。コブは歩いていない巡回に署名している。"),
"i_ledger": ("The donor ledger", "寄付者台帳"), "id_ledger": ("Evidence. 1994–1996. Page fourteen.", "証拠。1994〜1996年。14ページ。"),
"i_torch": ("Brass torch", "真鍮の懐中電灯"), "id_torch": ("Tool. Stealth +1, Stall stronger.", "道具。隠密+1、時間稼ぎ強化。"),
"i_tweed": ("Tweed jacket", "ツイードの上着"), "id_tweed": ("Outfit. Grit +1.", "衣装。根性+1。"),
"i_signet": ("The Dean's signet", "学部長の印章指輪"), "id_signet": ("Accessory. Charm +1. She dropped it. Or left it.", "アクセサリー。魅力+1。落としたのか、置いていったのか。"),
"i_raincoat": ("Wet raincoat", "濡れたレインコート"), "id_raincoat": ("Outfit. Grit +1.", "衣装。根性+1。"),
"i_cardigan": ("Lost-property cardigan", "落とし物のカーディガン"), "id_cardigan": ("Outfit. Charm +1, Flirt stronger. Dry, at least.", "衣装。魅力+1、誘惑強化。少なくとも乾いている。"),
"i_spectacles": ("Spare spectacles", "予備の眼鏡"), "id_spectacles": ("Accessory. Wit +1.", "アクセサリー。知力+1。"),
# skills
"br_scholar": ("Scholar", "学究"), "br_rogue": ("Rogue", "悪漢"), "br_archivist": ("Archivist", "書庫番"), "br_accomplice": ("Accomplice", "共犯者"),
"sk_footnote": ("Footnotes", "脚注"), "skd_footnote": ("Show evidence +30%.", "証拠を示す +30%。"),
"sk_tenure": ("Tenure", "終身在職"), "skd_tenure": ("Composure +10.", "平静の上限 +10。"),
"sk_recall": ("Total recall", "完全記憶"), "skd_recall": ("Wit +2.", "知力 +2。"),
"sk_lectern": ("The lectern", "講壇"), "skd_lectern": ("Learn Lecture.", "「講義」を習得。"),
"sk_emeritus": ("Emeritus", "名誉教授"), "skd_emeritus": ("Lecture +40%, evidence +20%.", "講義 +40%、証拠 +20%。"),
"sk_palm": ("Greased palm", "袖の下"), "skd_palm": ("Bribe +30%.", "買収 +30%。"),
"sk_poker": ("Poker face", "ポーカーフェイス"), "skd_poker": ("Bluff +30%.", "はったり +30%。"),
"sk_cold": ("Cold blood", "冷血"), "skd_cold": ("Grit +2.", "根性 +2。"),
"sk_backstair": ("Back stairs", "裏階段"), "skd_backstair": ("Stall +40%.", "時間稼ぎ +40%。"),
"sk_iron": ("Iron voice", "鉄の声"), "skd_iron": ("Threaten +40%, bluff +20%.", "脅し +40%、はったり +20%。"),
"sk_index": ("Card index", "索引カード"), "skd_index": ("Show evidence +30%.", "証拠を示す +30%。"),
"sk_memory": ("Archive memory", "書庫の記憶"), "skd_memory": ("Wit +2.", "知力 +2。"),
"sk_tongues": ("Dead tongues", "死語"), "skd_tongues": ("Learn Recite in Latin.", "「ラテン語で暗誦」を習得。"),
"sk_lockwork": ("Lockwork", "錠前術"), "skd_lockwork": ("Stealth +2.", "隠密 +2。"),
"sk_provenance": ("Provenance", "来歴"), "skd_provenance": ("Evidence +40%, recite +30%.", "証拠 +40%、暗誦 +30%。"),
"sk_smile": ("That smile", "あの微笑み"), "skd_smile": ("Flirt +30%.", "誘惑 +30%。"),
"sk_poise": ("Poise", "落ち着き"), "skd_poise": ("Composure +10.", "平静の上限 +10。"),
"sk_lie": ("Straight face", "真顔の嘘"), "skd_lie": ("Bluff +40%.", "はったり +40%。"),
"sk_steady": ("Steady hands", "震えない手"), "skd_steady": ("Grit +2.", "根性 +2。"),
"sk_alibi": ("Alibi", "アリバイ"), "skd_alibi": ("Stall +40%, flirt +20%.", "時間稼ぎ +40%、誘惑 +20%。"),
# enemies
"e_cobb": ("Cobb, the night porter", "夜間守衛コブ"), "e_cobb_return": ("Cobb, with a torch", "懐中電灯を持ったコブ"),
"e_penhallow": ("Julian Penhallow, trustee", "理事ジュリアン・ペンハロウ"), "e_dean": ("Dean Holloway", "ホロウェイ学部長"),
"ei_cobb": ("Cobb wants to know why the vault alarm is your business.", "コブは、なぜ書庫の警報があなたの用事なのか知りたがっている。"),
"ew_cobb": ("Cobb decides he never saw you.", "コブは何も見なかったことにした。"),
"ei_penhallow": ("Penhallow smiles like a man who owns the shelves.", "ペンハロウは書棚の持ち主のように微笑む。"),
"ew_penhallow": ("Penhallow closes his book and goes to bed.", "ペンハロウは本を閉じ、寝に行った。"),
"ei_cobb_return": ("Cobb is back, and this time he has a torch and a question.", "コブが戻ってきた。今度は懐中電灯と疑問を携えて。"),
"ew_cobb_return": ("Cobb goes back to his kettle.", "コブはやかんのもとへ戻っていった。"),
"ei_dean": ("Dean Holloway, at dawn, in the one room nobody should be in.", "夜明けの学部長。誰もいるはずのない部屋に。"),
"ew_dean": ("The Dean goes back up the stair. She does not look at the crate.", "学部長は階段を上っていく。木箱には目もくれない。"),
"bark_cobb_1": ("\"Rules are rules, Professor.\"", "「規則は規則ですよ、教授」"),
"bark_cobb_2": ("\"I've a phone in the lodge, you know.\"", "「詰所には電話があるんですがね」"),
"bark_cobb_3": ("\"Thirty years on nights. I know a lie when I hear one.\"", "「夜勤三十年。嘘は聞けば分かる」"),
"bark_penhallow_1": ("\"The Academy is generous to its friends.\"", "「学園は友人には寛大でね」"),
"bark_penhallow_2": ("\"Do you know what a trustee is for, Professor?\"", "「理事が何のためにいるか、ご存じかな、教授」"),
"bark_penhallow_3": ("\"Miss Ashcombe. Your father's daughter.\"", "「アシュコム君。お父上によく似ている」"),
"bark_cobb_return_1": ("\"The vault seal reset itself twice. Seals don't do that.\"", "「封印が二度も勝手に戻った。封印はそんなことしない」"),
"bark_cobb_return_2": ("\"Whose coat is that?\"", "「そのコートは誰のです？」"),
"bark_cobb_return_3": ("\"Money's not going to do it twice, sir.\"", "「金で二度は通りませんよ」"),
"bark_dean_dawn_1": ("\"Professor. You are early. Or late.\"", "「教授。お早いのね。それとも遅いのかしら」"),
"bark_dean_dawn_2": ("\"That crate is on my list.\"", "「その木箱は私のリストにあるわ」"),
"bark_dean_dawn_3": ("\"Miss Ashcombe has no business in this wing.\"", "「アシュコムさんがこの棟に用はないはずよ」"),
"bark_dean_dawn_4": ("\"I can wait. I am very good at waiting.\"", "「待てるわ。待つのは得意なの」"),
# rooms / night
"n1_title": ("Night One — The Vault Alarm", "第一夜 — 書庫の警報"),
"n1_sub": ("Saint Jude Academy, Blackwood wing. Rain.", "聖ジュード学園、ブラックウッド棟。雨。"),
"r_study": ("Faculty study", "教員研究室"), "r_corridor": ("Antiquities corridor", "古美術学部の廊下"),
"r_stair": ("Blackwood stair", "ブラックウッド階段"), "r_vault": ("Blackwood vault", "ブラックウッド書庫"),
"r_stacks": ("Lower stacks", "下層書架"), "r_cellar": ("Service passage", "業務用通路"),
"r_muniment": ("Muniment room", "古文書室"),
"n1_vault_locked": ("The iron door does not move. The override key is still upstairs in your desk.", "鉄の扉はびくともしない。オーバーライドキーは上の机の中だ。"),
# events
"n1_open_1": ("The console blinks: SEAL ENGAGED, SENSOR TRIPPED. Somebody is inside a room that locks itself.", "コンソールが点滅する。封鎖作動、センサー反応。自ら施錠する部屋の中に、誰かがいる。"),
"n1_open_2": ("You have until dawn before the building wakes. Take what you need from the study first.", "建物が目を覚ます夜明けまでに片を付けたい。まずは研究室で必要な物を揃えよう。"),
"n1_desk_1": ("Under the key: your own note from September. 'Do not lend this to anyone.' You lent it to Elena once.", "鍵の下に九月の自分のメモ。「誰にも貸すな」。一度だけエレナに貸したことがある。"),
"n1_essays_1": ("Forty-one essays on Byzantine seals. The forty-second argues that every archive is a confession.", "ビザンツの印章についてのレポートが四十一本。四十二本目は、すべての書庫は告白だと論じている。"),
"n1_essays_2": ("Ashcombe. Of course it is.", "アシュコム。やはりそうか。"),
"n1_essays_3": ("You read her last paragraph twice. It is the best thing on the desk.", "最後の段落を二度読む。机の上で一番いい文章だ。"),
"n1_tin_1": ("The department's petty-cash tin. Forty pounds and a button.", "学科の小口現金の缶。四十ポンドとボタンが一つ。"),
"n1_tin_2": ("You leave an IOU. You are, after all, a professor.", "借用書を残しておく。教授なのだから。"),
"n1_cabinet_1": ("A brass torch from the war-games society, and behind it a silver hip flask engraved E.A.", "戦史研究会の真鍮の懐中電灯。その奥に、E.A.と刻まれた銀のスキットル。"),
"n1_cabinet_2": ("She left it here in October. You never gave it back. You never asked yourself why.", "十月に彼女が置き忘れたものだ。返さないままでいた。理由は考えないことにしていた。"),
"n1_corr_1": ("A shadow moves at the far end, where the porter's lodge spills light across the tiles.", "廊下の奥で影が動く。守衛詰所の明かりがタイルにこぼれている。"),
"n1_cobb_1": ("Cobb, the night porter. Thirty years on nights and a kettle that never goes cold.", "夜間守衛のコブ。夜勤三十年、冷めることのないやかん。"),
"n1_cobb_2": ("\"Blackwood alarm went at eleven-thirty-seven, Professor. That's a Dean's-office matter.\"", "「ブラックウッドの警報が十一時三十七分に鳴りました、教授。学部長室の案件ですよ」"),
"n1_cobb_3": ("I hold the override key, Cobb. That makes it my matter.", "オーバーライドキーを持っているのは私だ、コブ。だから私の案件だ。"),
"n1_cobb_4": ("\"Then you won't mind me ringing the Dean to say so.\"", "「なら、学部長にそうお伝えしても構いませんね」"),
"n1_tutorial_1": ("A standoff. Bring his Resolve to zero before his Suspicion reaches 100 — at 100 he picks up the phone.", "対峙だ。相手の「疑念」が100に達する前に「決意」を0にする。100になれば彼は電話を取る。"),
"n1_tutorial_2": ("Every person has weaknesses. A porter on a porter's wage, for instance. Threats are remembered.", "人には必ず弱点がある。たとえば、守衛の給料で暮らす守衛。脅しは記憶に残る。"),
"n1_cobb_5": ("\"Kettle's on, Professor. I'll be in the lodge if anybody asks. Which they won't.\"", "「やかんを火にかけてあります、教授。誰かに聞かれたら詰所にいますよ。聞かれやしませんがね」"),
"n1_cobb_6": ("He drops a clipboard as he goes. The night rota, with his signature on a round he did not walk.", "彼は去り際にクリップボードを落とす。歩いてもいない巡回に彼の署名がある当番表だ。"),
"n1_board_1": ("The noticeboard: a lost cat, a sherry evening, and a thermos left 'for whoever needs it'. You need it.", "掲示板。迷い猫、シェリーの会、「必要な人へ」と置かれた水筒。今は必要だ。"),
"n1_stair_1": ("The Blackwood stair goes down further than the building should allow. The air gets colder by the step.", "ブラックウッド階段は建物が許すより深く降りていく。一段ごとに空気が冷える。"),
"n1_notice_1": ("A typed notice pinned to the vault door: DEACCESSION — WATER-DAMAGED LOT — INCINERATE 09:00.", "書庫の扉に留められたタイプ打ちの通知：除籍 — 水濡れ品 — 午前9時焼却。"),
"n1_notice_2": ("The stamp is the Dean's. The handwriting underneath is not. You take it.", "印は学部長のもの。その下の筆跡は違う。あなたはそれを外して持っていく。"),
"n1_join_1": ("There was someone in the lower stacks when I came down. A man, reading by a lamp. He saw the seal light.", "降りてくるとき、下層書架に誰かいました。男の人がランプで本を読んでいた。封印の灯りを見られたわ。"),
"n1_join_2": ("And Cobb walks the service passage at two. He'll find the seal reset and come looking.", "それにコブは二時に業務用通路を回る。封印が戻っているのに気付いて、探しに来るはず。"),
"n1_join_3": ("Then we deal with both before anyone rings the Dean. Together.", "なら、誰かが学部長に電話する前に、両方片付ける。二人で。"),
"n1_join_4": ("Together. I can read people, Professor. Let me do the reading.", "二人で。人を読むのは得意です、教授。読むのは私に任せて。"),
"n1_join_5": ("Elena joins you. In a standoff she acts after you, with her own skills — and she can Read the room.", "エレナが仲間になった。対峙では彼女も自分のスキルで行動する。「空気を読む」で相手の弱点が分かる。"),
"n1_join_6": ("The ledger stays in the crate for now. The way out is through the stacks, then the service passage.", "台帳はひとまず木箱の中に。出口は下層書架から業務用通路へ抜ける道だ。"),
"n1_crate_1": ("Under the straw, a thermos somebody else forgot. The Blackwood wing is full of people who leave things.", "藁の下に、誰かが忘れた水筒。ブラックウッド棟は物を置いていく人間ばかりだ。"),
"n1_coat_1": ("Her coat is steaming on the radiator. You turn it so the wet side faces the heat.", "彼女のコートがラジエーターの上で湯気を立てている。濡れた側を熱に向けてやる。"),
"n1_coat_2": ("...Thank you. Nobody does that.", "……ありがとう。そんなことしてくれる人、いないわ。"),
"n1_stacks_1": ("The lower stacks. One green lamp is still lit, and under it, a man in a good coat turning pages slowly.", "下層書架。緑のランプがひとつだけ灯り、その下で上等なコートの男がゆっくりと頁をめくっている。"),
"n1_pen_1": ("Julian Penhallow. Trustee, benefactor, the name over the fireplace in the annex.", "ジュリアン・ペンハロウ。理事、後援者、別館の暖炉の上に名が刻まれた男。"),
"n1_pen_2": ("\"Professor Vance. And Miss Ashcombe. The Blackwood wing is very popular tonight.\"", "「ヴァンス教授。それにアシュコム君。今夜のブラックウッド棟は大人気だね」"),
"n1_pen_3": ("We could say the same of you, Mr Penhallow.", "同じことをあなたにも言えますわ、ペンハロウさん。"),
"n1_pen_4": ("\"I am a trustee. Trustees may read where they like. What is your excuse?\"", "「私は理事だ。理事はどこで本を読もうと自由だ。君たちの言い訳は？」"),
"n1_pen_5": ("\"Goodnight, then. Do give my regards to the Dean. She keeps such careful lists.\"", "「では、おやすみ。学部長によろしく。彼女はとても丁寧にリストを作るからね」"),
"n1_pen_6": ("He takes his book with him. The space it leaves on the shelf is exactly the width of a ledger.", "彼は本を持って去る。棚に残った隙間は、ちょうど台帳一冊分の幅だった。"),
"n1_pen_7": ("He knew my name. He has never met me.", "私の名前を知っていた。会ったこともないのに。"),
"n1_cart_1": ("A returns cart. On top, a pair of tortoiseshell spectacles with a lost-property tag from 2019.", "返却カート。一番上に、2019年の遺失物札が付いたべっ甲の眼鏡。"),
"n1_cart_2": ("Mine are fogged. These will do. Don't tell anyone I stole from lost property.", "私のは曇ってるの。これで十分。遺失物を盗んだって誰にも言わないでね。"),
"n1_cellar_1": ("The service passage smells of coal and wet stone. A boiler grumbles somewhere to the left.", "業務用通路は石炭と濡れた石の匂いがする。左のどこかでボイラーが唸っている。"),
"n1_cellar_2": ("He'll come this way. He always does the boiler at two.", "彼はこっちに来るわ。二時には必ずボイラーを見に来るの。"),
"n1_cobb2_1": ("A torch beam swings across the coal and stops on Elena's face.", "懐中電灯の光が石炭の上を走り、エレナの顔で止まる。"),
"n1_cobb2_2": ("\"Miss Ashcombe. Now that's two people who aren't here.\"", "「アシュコムさん。これで、ここにいないはずの人間が二人になった」"),
"n1_cobb2_3": ("\"And the money won't do it twice, Professor. I've a pension to think of.\"", "「金も二度は通じませんよ、教授。年金のことも考えないと」"),
"n1_cobb2_4": ("He signed for a round he didn't walk. Let me talk to him.", "彼は歩いてない巡回に署名した。私に話させて。"),
"n1_cobb2_5": ("\"Fine. Fine. Nobody saw nobody. I'm going back to my kettle.\"", "「分かりました、分かりましたよ。誰も誰も見なかった。やかんのとこへ戻ります」"),
"n1_cobb2_6": ("Behind him, in a lost-property box by the boiler, a dry cardigan. Elena takes it without asking.", "彼の後ろ、ボイラー脇の遺失物箱に乾いたカーディガン。エレナは何も聞かずに手に取る。"),
"n1_cobb2_7": ("The way is clear. The service door opens back into the vault. The ledger is waiting.", "道は開けた。業務用の扉は書庫へと通じている。台帳が待っている。"),
"n1_boiler_1": ("A bottle of college sherry hidden behind the boiler pipes. Cobb's, probably. Medicinal, certainly.", "ボイラーの配管の裏に学寮のシェリーが一本。たぶんコブのものだ。薬用には違いない。"),
"n1_back_1": ("Back in the vault. The crate, the lamp, the rain. Nobody else knows you are here now.", "書庫に戻った。木箱、ランプ、雨。今ここにいることを知る者は、もういない。"),
"n1_ctrl_cut_1": ("She deletes the photographs herself, one by one, and does not look at you while she does it.", "彼女は自分で写真を一枚ずつ消す。その間、一度もあなたを見ない。"),
"n1_trust_hint": ("(Her trust is not there yet. At Trust 3 this scene goes further.)", "（まだ彼女の信頼が足りない。信頼3でこの場面は先へ進む）"),
"n1_dean_1": ("Footsteps on the stair. Heels. Unhurried. Dean Marguerite Holloway, coat buttoned to the throat.", "階段に足音。ヒール。急がない足取り。喉元までコートのボタンを留めたマルグリット・ホロウェイ学部長。"),
"n1_dean_2": ("\"Professor Vance. The incinerator is at nine. I came to make sure of the list.\"", "「ヴァンス教授。焼却は九時よ。リストを確かめに来たの」"),
"n1_dean_3": ("Then you are early, Dean. The list is in order.", "なら早すぎますよ、学部長。リストは問題ありません。"),
"n1_dean_4": ("\"I will be the judge of that.\"", "「それを判断するのは私よ」"),
"n1_dean_5": ("\"Very well. Nine o'clock, Professor. Do not be in this room at nine.\"", "「いいでしょう。九時よ、教授。九時にこの部屋にいないこと」"),
"n1_dean_6": ("On the floor where she stood: a signet ring. The Dean does not drop things.", "彼女が立っていた床に、印章指輪がひとつ。学部長は物を落とす人ではない。"),
"n1_end_1": ("The crate goes to the incinerator at nine. The ledger does not. Forty-eight hours later, the Dean sends for you.", "九時、木箱は焼却炉へ運ばれる。台帳は運ばれない。四十八時間後、学部長があなたを呼び出す。"),
# toasts / gallery
"g_cg_confrontation": ("The vault", "書庫にて"), "g_cg_climax_pact": ("Page fourteen", "14ページ"),
"g_cg_climax_control": ("The arrangement", "取り決め"), "g_cg_aftermath": ("Dawn", "夜明け"),
"g_cg_coal_store": ("The coal store", "石炭庫"), "g_cg_ch2_office": ("After hours", "時間外"),
}
