# Night 1, additional room writing (EN, JA).
S = {
"n1_open_3": ("You think of Elena, who asked last week whether the Blackwood wing was ever really empty. You said yes.", "先週エレナに、ブラックウッド棟は本当に無人になるのかと聞かれた。あなたは「なる」と答えた。"),
"n1_open_4": ("The rain gets heavier. Whatever is in that vault, it has been waiting for a night like this.", "雨脚が強まる。あの書庫に何があるにせよ、それはこんな夜を待っていたのだ。"),
"n1_desk_2": ("The key is cold. Brass, with the Academy crest worn smooth by forty years of thumbs.", "鍵は冷たい。真鍮製で、学園の紋章は四十年分の親指に擦られて滑らかになっている。"),
"n1_essays_4": ("You put her essay in your inside pocket. It feels like the first decision of the night.", "彼女のレポートを内ポケットに入れる。今夜最初の決断のような気がした。"),
"n1_corr_2": ("Portraits of former deans watch you pass. Every one of them looks like someone who kept a list.", "歴代学部長の肖像画が通り過ぎるあなたを見ている。どれもリストを作っていそうな顔だ。"),
"n1_corr_3": ("The lodge radio is playing the shipping forecast. Somebody is awake down here.", "詰所のラジオが海上気象を流している。ここで誰かが起きている。"),
"n1_cobb_7": ("He sets his mug down on the radiator, very deliberately, like a man laying down a card.", "彼はマグをゆっくりとラジエーターに置く。カードを場に出すような手つきで。"),
"n1_cobb_8": ("He wants something. Most people at this hour do. The trick is finding out what.", "彼は何かを欲しがっている。この時間に起きている人間はたいていそうだ。問題はそれが何かだ。"),
"n1_cobb_9": ("You add the rota to your pocket. Paper has a way of becoming useful after midnight.", "当番表をポケットに入れる。真夜中を過ぎると、紙切れは役に立つものに化ける。"),
"n1_stair_2": ("Somebody has been down here tonight. Wet footprints, small, going one way only.", "今夜、誰かがここを降りた。濡れた小さな足跡が、一方向にだけ続いている。"),
"n1_notice_3": ("Below the stamp, in pencil: 'Lot 14 — see me first. J.P.'", "印の下に鉛筆で：「第14ロット — まず私に。J.P.」"),
"n1_join_7": ("She buttons her coat to the collar. Her hands are not quite steady yet, and she hides it well.", "彼女はコートのボタンを襟元まで留める。手はまだ少し震えているが、うまく隠している。"),
"n1_join_8": ("If we get the ledger out, Professor, you'll have to read page fourteen. You know that.", "台帳を持ち出せたら、教授、あなたは14ページを読むことになる。分かってますよね。"),
"n1_join_9": ("I know.", "分かっている。"),
"n1_join_10": ("No, you don't. Not yet.", "いいえ、まだ分かってない。"),
"n1_crate_2": ("Elena watches you search. \"You do this like a man who has done it before.\" You have not. You let her think so.", "エレナはあなたが探す様子を見ている。「慣れてるみたい」。慣れてなどいない。だが、そう思わせておく。"),
"n1_coat_3": ("She stands closer to the radiator, and therefore closer to you. Neither of you mentions it.", "彼女はラジエーターに近付く。つまり、あなたにも近付く。二人ともそれには触れない。"),
"n1_stacks_2": ("Elena stops dead. She knows the coat before she knows the face.", "エレナがぴたりと止まる。顔より先に、そのコートに見覚えがあったのだ。"),
"n1_pen_8": ("He looks at Elena the way a man checks a figure he has already paid.", "彼はエレナを見る。もう支払いの済んだ数字を確かめるような目で。"),
"n1_pen_9": ("Elena stands very still until his footsteps are gone. Then she sits down on the returns cart, all at once.", "エレナは彼の足音が消えるまで身じろぎもしない。それから、返却カートにすとんと腰を下ろす。"),
"n1_pen_10": ("Who is he to you, Elena?", "彼は君にとって何なんだ、エレナ。"),
"n1_pen_11": ("Ask me after we've read page fourteen.", "14ページを読んでから聞いて。"),
"n1_cellar_3": ("A coal store opens off the passage, black to the ceiling. The service door to the vault is at the far end.", "通路の脇に天井まで真っ黒な石炭庫。突き当たりに書庫へ通じる業務用の扉がある。"),
"n1_cobb2_8": ("Elena hands Cobb his rota back. \"You'll want this for the morning.\" He looks at her as if she had forgiven him.", "エレナはコブに当番表を返す。「朝には必要でしょう」。彼は赦されたような顔で彼女を見る。"),
"n1_cobb2_9": ("You didn't have to give it back.", "返さなくてもよかったのに。"),
"n1_cobb2_10": ("He's sixty-three and he's frightened of the Dean. So am I. It costs nothing to be kind about it.", "彼は六十三で、学部長を怖がってる。私もよ。それに優しくするのはタダだわ。"),
"n1_back_2": ("Elena kneels by the crate. Her fingers find the ledger in the straw without looking, as if she had left a light on for it.", "エレナは木箱の前に膝をつく。見もせずに藁の中の台帳を探り当てる。明かりを点けて待たせておいたみたいに。"),
"n1_back_3": ("It is past three. Two hours of dark left, and one book between you.", "三時を過ぎた。闇はあと二時間。二人の間には一冊の本。"),
"n1_dean_7": ("Elena moves half a step behind you. Not hiding. Choosing where to stand.", "エレナが半歩、あなたの後ろに下がる。隠れたのではない。立つ場所を選んだのだ。"),
"n1_dean_8": ("Her eyes go to the crate, to the straw, to Elena. In that order. Like Elena's did, nine hours ago.", "学部長の目が木箱へ、藁へ、エレナへと動く。その順番で。九時間前のエレナと同じように。"),
"n1_dean_9": ("You pick up the ring. It is warm. She has been turning it on her finger all night.", "指輪を拾う。温かい。彼女は一晩中、これを指で回していたのだ。"),
"n1_dean_10": ("She knew. She knows we have it.", "知ってたのよ。私たちが持ってることを知ってる。"),
"n1_dean_11": ("Then she has decided to let us keep it. For now.", "なら、持たせておくと決めたんだ。今のところは。"),
}
S.update({
"hs_window": ("Landing window", "踊り場の窓"), "hs_shelf": ("Reserved shelf", "予約棚"), "hs_lodge": ("Porter's lodge", "守衛詰所"),
"n1_window_1": ("From the landing window you can see the whole quad, silver with rain. One light is on in the Dean's residence.", "踊り場の窓から雨に銀色の中庭が見渡せる。学部長公邸にひとつだけ灯りがついている。"),
"n1_window_2": ("It goes out while you watch. Somebody up there has decided to sleep. Or to stop being seen awake.", "見ている間に消える。誰かが眠ることにしたのだ。あるいは、起きているところを見られないことに。"),
"n1_shelf_1": ("A shelf of books reserved under one name: PENHALLOW. Donor rolls, board minutes, a history of the Blackwood bequest.", "ひとつの名前で取り置かれた本の棚。ペンハロウ。寄付者名簿、理事会議事録、ブラックウッド遺贈の歴史。"),
"n1_shelf_2": ("Every volume covers 1994 to 1996. Every one has a slip of paper at the same page.", "どれも1994年から1996年を扱っている。どれにも同じページに紙片が挟まれている。"),
"n1_shelf_3": ("He is reading the same years we are. He's just reading the clean copy.", "彼も私たちと同じ年を読んでる。ただ、彼が読んでるのは綺麗な方の写し。"),
"n1_lodge_1": ("The lodge: a kettle, a radio, a crossword with every clue about birds filled in and nothing else.", "詰所。やかん、ラジオ、鳥に関する鍵だけが埋まったクロスワード。"),
"n1_lodge_2": ("On the wall, a photograph of Cobb thirty years younger, shaking hands with a man in a good coat.", "壁には三十年若いコブの写真。上等なコートの男と握手している。"),
})
S.update({
"hs_desk": ("Desk drawer", "机の引き出し"), "hs_essays": ("Essays", "レポートの束"), "hs_tin": ("Petty-cash tin", "小口現金の缶"),
"hs_cabinet": ("Cabinet", "戸棚"), "hs_board": ("Noticeboard", "掲示板"), "hs_notice": ("Notice on the door", "扉の通知"),
"hs_crate": ("The crate", "木箱"), "hs_coat": ("Her coat", "彼女のコート"), "hs_ledger": ("The ledger", "台帳"),
"hs_cart": ("Returns cart", "返却カート"), "hs_boiler": ("Boiler pipes", "ボイラーの配管"),
})
S.update({
"hs_window_study": ("Study window", "研究室の窓"), "hs_shelfbook": ("The ledger, closed", "閉じた台帳"),
"n1_swin_1": ("Rain on the glass, and beyond it the Blackwood wing, dark except for one slit of orange two floors down.", "ガラスを打つ雨。その向こうにブラックウッド棟。二階下の細いオレンジ色の光を除けば、真っ暗だ。"),
"n1_swin_2": ("The vault has no window. The orange is the corridor. Someone has left the night lights on all the way down.", "書庫に窓はない。あのオレンジは廊下だ。誰かが下まで夜間灯を点けっぱなしにしている。"),
"n1_swin_3": ("Or someone wanted to be able to see the way back up.", "あるいは、上へ戻る道が見えるようにしておきたかった誰かがいる。"),
"n1_lbook_1": ("The ledger sits in the straw where she left it. You do not open it. Not yet. It feels like a thing that should be opened with two people present.", "台帳は彼女が置いた藁の中にある。あなたは開かない。まだ。二人がそろってから開くべきもののような気がする。"),
"n1_lbook_2": ("Elena watches you not open it. Something in her shoulders comes down an inch.", "開かないあなたを、エレナが見ている。彼女の肩がほんの少し下がる。"),
"n1_lbook_3": ("Thank you. For waiting.", "ありがとう。待ってくれて。"),
})
S.update({
"ds_adult": ("This game is for adults (18+). All characters are adults. Contains sexual content.", "本作品は成人向け（18歳以上）です。登場人物はすべて成人です。性的な表現を含みます。"),
"about_ai": ("AI disclosure: This work uses generative AI. All character art, backgrounds and event CGs were generated with Animagine XL (an image model) and then selected and composited by the developer. The heroine's spoken lines are synthesised with CosyVoice (a text-to-speech model). The story, dialogue and game code were written with the help of AI language models and edited, directed and tested by the developer.",
             "AI使用について：本作は生成AIを使用しています。キャラクター立ち絵・背景・イベントCGは画像生成AI「Animagine\u2060 \u2060XL」で生成し、開発者が選定・合成しています。ヒロインのボイスは音声合成AI「CosyVoice」による合成音声です。シナリオ・テキストおよびプログラムもAI（大規模言語モデル）の支援を受けて作成し、開発者が編集・監修・テストしています。"),
"tr_end_title": ("This is where the trial ends.", "体験版はここまで"),
"tr_end_body": ("Nights 2 to 5, all three routes and three endings, every standoff and boss, the full gallery and growth to level 20 are in the full version. Your trial save carries over.",
                "第二夜から第五夜、3つのルートと3種のエンディング、すべての対峙とボス、ギャラリー、レベル20までの成長は製品版に収録されています。体験版のセーブデータは製品版に引き継げます。"),
"tr_open_store": ("Open the product page", "製品版のページを開く"), "tr_back": ("Back to the title", "タイトルに戻る"),
})
S.update({
"hs_lamp": ("Green lamp", "緑のランプ"), "hs_coalchute": ("Coal chute", "石炭シュート"),
"n1_lamp_1": ("The green lamp Penhallow read by is still warm. Under it, a ring of wet from a glass he did not leave behind.", "ペンハロウが読書していた緑のランプはまだ温かい。その下に、彼が持ち去ったグラスの濡れた輪。"),
"n1_lamp_2": ("Elena touches the ring with one finger, as if it could tell her what he was drinking to.", "エレナは指先でその輪に触れる。彼が何に乾杯していたのか、それが教えてくれるとでもいうように。"),
"n1_lamp_3": ("He was here for us. Not for the book. For us.", "彼は私たちのためにここにいたのよ。本じゃない。私たちのために。"),
"n1_chute_1": ("The coal chute runs up to a grating in the quad. Through it, rain, and very far away, a car idling with its lights off.", "石炭シュートは中庭の格子まで続いている。その向こうに雨、そしてずっと遠くに、ライトを消してアイドリングする車。"),
"n1_chute_2": ("You watch until it drives away. It does not hurry either.", "走り去るまで見ている。その車も急がない。"),
})
