# Nights 2-5: names, rooms, enemies, room writing (EN, JA).
S = {
# ---- shared
"r_dock": ("Loading dock", "搬入口"), "r_reading_room": ("Main hall", "大講堂"), "r_common_room": ("Faculty common room", "教員談話室"),
"r_deans_corridor": ("Dean's corridor", "学部長室の廊下"), "r_annex": ("The annex", "別館"), "r_deans_office": ("The Dean's file room", "学部長の書類室"),
"r_carrel": ("Elena's carrel", "エレナの閲覧席"),
"n_vey": ("Miss Vey", "ヴェイ"), "n_hollis": ("Hollis", "ホリス"), "n_grice": ("Grice", "グライス"), "n_crane": ("Crane", "クレイン"),
"n_sallis": ("Dr Sallis", "サリス博士"), "n_ambrose": ("Ambrose", "アンブローズ"),
"e_vey": ("Miss Vey, the Dean's secretary", "学部長秘書ヴェイ"), "e_hollis": ("Hollis, Estates security", "施設警備員ホリス"),
"e_grice": ("Grice, the van driver's mate", "運搬車の助手グライス"), "e_crane": ("Crane, the Dean's fixer", "学部長の始末屋クレイン"),
"e_sallis": ("Dr Imogen Sallis, rival archivist", "対抗する書庫学者イモジェン・サリス博士"), "e_ambrose": ("Ambrose, Penhallow's solicitor", "ペンハロウの事務弁護士アンブローズ"),
"e_penhallow_boss": ("Julian Penhallow", "ジュリアン・ペンハロウ"), "e_dean_tea": ("Dean Holloway, at tea", "茶席のホロウェイ学部長"),
"e_penhallow_final": ("Penhallow, in the strongroom", "保管庫のペンハロウ"),
"e_crane_n5": ("Crane, with the bricklayer's hammer", "煉瓦槌を持つクレイン"), "e_grice_n5": ("Grice, on the crypt stair", "地下階段のグライス"),
"e_ambrose_n5": ("Ambrose, with an injunction", "差止命令を持ったアンブローズ"), "e_vey_n4": ("Miss Vey, at her desk", "机に陣取るヴェイ"),
"e_hollis_n4": ("Hollis, at the annex door", "別館の扉のホリス"), "e_crane_n4": ("Crane, in the file room", "書類室のクレイン"),
"e_grice_n3": ("Grice, carrying chairs", "椅子を運ぶグライス"),
"ei_vey": ("Miss Vey has a telephone and a list of who was where.", "ヴェイは電話と、誰がどこにいたかのリストを持っている。"),
"ew_vey": ("Miss Vey writes something down, then crosses it out.", "ヴェイは何かを書き留め、そして線を引いて消した。"),
"ei_hollis": ("Hollis would like to see some identification. And the trolley manifest.", "ホリスは身分証と、台車の積荷目録を見たがっている。"),
"ew_hollis": ("Hollis waves you through and goes to find a coffee.", "ホリスは手を振って通し、コーヒーを探しに行った。"),
"ei_grice": ("Grice has a schedule, and you are standing in it.", "グライスには予定がある。そしてあなたはその邪魔をしている。"),
"ew_grice": ("Grice decides the van can wait ten minutes.", "グライスは、車が十分待っても構わないと決めた。"),
"ei_crane": ("Crane does not raise his voice. He has never needed to.", "クレインは声を荒らげない。その必要があったことがないのだ。"),
"ew_crane": ("Crane lights a cigarette and walks away into the rain.", "クレインは煙草に火を点け、雨の中へ去っていった。"),
"ei_sallis": ("Dr Sallis wants to know what Antiquities is doing in the Blackwood papers.", "サリス博士は、古美術学部がブラックウッド文書で何をしているのか知りたがっている。"),
"ew_sallis": ("Dr Sallis goes to find a better seat.", "サリス博士はもっといい席を探しに行った。"),
"ei_ambrose": ("Ambrose would like a word, on behalf of his client.", "アンブローズは依頼人に代わって、少し話がしたいという。"),
"ew_ambrose": ("Ambrose closes his briefcase. 'Another time.'", "アンブローズは鞄を閉じる。「また今度」"),
"ei_penhallow_boss": ("Penhallow has your hand and is not letting go.", "ペンハロウはあなたの手を握り、離そうとしない。"),
"ew_penhallow_boss": ("Penhallow lets go of your hand, and smiles, and moves on.", "ペンハロウは手を離し、微笑んで、去っていく。"),
"ei_dean_tea": ("Tea with the Dean: twenty minutes if she dislikes you. Make it forty.", "学部長との茶席。嫌われていれば二十分。四十分にしてみせろ。"),
"ew_dean_tea": ("The Dean sets down her cup. 'Enjoy your survey, Professor.'", "学部長はカップを置く。「調査を楽しんで、教授」"),
"ei_penhallow_final": ("Penhallow fills the doorway. He has brought money, and he has brought men.", "ペンハロウが戸口を塞ぐ。金も、男たちも連れてきている。"),
"ew_penhallow_final": ("Penhallow has nothing left to offer. Everyone in the room can see it.", "ペンハロウにはもう差し出すものがない。部屋の誰の目にもそれは明らかだった。"),
"bark_vey_1": ("\"The Dean's diary is full until Thursday.\"", "「学部長の予定は木曜まで埋まっております」"),
"bark_vey_2": ("\"Two cups, Professor. Cobb mentioned two cups.\"", "「カップが二つ、と教授。コブがそう申しておりました」"),
"bark_vey_3": ("\"I'll just make a note of that.\"", "「念のため、控えておきますね」"),
"bark_hollis_1": ("\"Manifest says three crates. I count three crates. Why are you here?\"", "「目録では木箱三つ。数えても三つ。なぜあなたがここに？」"),
"bark_hollis_2": ("\"I'll need to radio this in.\"", "「無線で報告しないと」"),
"bark_hollis_3": ("\"My shift ends at nine. Don't make it end late.\"", "「俺のシフトは九時までだ。延長させないでくれ」"),
"bark_grice_1": ("\"Van leaves at nine. Not five past.\"", "「車は九時に出る。九時五分じゃない」"),
"bark_grice_2": ("\"Labels are labels. I don't read 'em.\"", "「ラベルはラベル。読みゃしねえよ」"),
"bark_grice_3": ("\"You lifting or talking, Professor?\"", "「運ぶのか喋るのか、どっちだ教授」"),
"bark_crane_1": ("\"The Dean likes things tidy.\"", "「学部長は整理整頓がお好きでね」"),
"bark_crane_2": ("\"Coal stores flood, Professor. Things get lost.\"", "「石炭庫は水が出るんですよ、教授。物がなくなる」"),
"bark_crane_3": ("\"I have a long memory and a short list.\"", "「私は記憶が長く、リストは短い」"),
"bark_crane_4": ("\"Miss Ashcombe. Your father was tidy too.\"", "「アシュコムさん。お父上も几帳面な方だった」"),
"bark_sallis_1": ("\"The Blackwood bequest is my field, Vance.\"", "「ブラックウッド遺贈は私の専門よ、ヴァンス」"),
"bark_sallis_2": ("\"You cite the 1953 catalogue? Bold.\"", "「1953年の目録を引用するの？大胆ね」"),
"bark_sallis_3": ("\"Your assistant is very quiet. Clever people often are.\"", "「助手さん、静かね。賢い人はたいていそう」"),
"bark_ambrose_1": ("\"My client values discretion above all things.\"", "「依頼人は何よりも慎重さを重んじます」"),
"bark_ambrose_2": ("\"Shall we call it a misunderstanding?\"", "「誤解、ということにしましょうか」"),
"bark_ambrose_3": ("\"I have the paperwork for every outcome.\"", "「どんな結末にも書類は用意してあります」"),
"bark_penhallow_boss_1": ("\"My grandfather's wing. You keep it very well.\"", "「祖父の棟だ。よく手入れしてくれている」"),
"bark_penhallow_boss_2": ("\"Marguerite retires in the spring, you know.\"", "「マルグリットは春に引退するそうだよ」"),
"bark_penhallow_boss_3": ("\"A board seat is a very comfortable chair.\"", "「理事の椅子はとても座り心地がいい」"),
"bark_penhallow_boss_4": ("\"Her father had that look too.\"", "「彼女の父親も、ああいう目をしていた」"),
"bark_dean_tea_1": ("\"Milk, Professor?\"", "「ミルクは、教授？」"),
"bark_dean_tea_2": ("\"The survey. I thought we should talk before you go poking.\"", "「調査の件。あなたが嗅ぎ回る前に話しておこうと思って」"),
"bark_dean_tea_3": ("\"Julian asked about your assistant.\"", "「ジュリアンがあなたの助手のことを聞いていたわ」"),
"bark_dean_tea_4": ("\"I keep everything, Professor. It is my only vice.\"", "「私は何でも取っておくの、教授。唯一の悪癖よ」"),
"bark_penhallow_final_1": ("\"Everybody goes home. That is my offer.\"", "「皆、家に帰る。それが私の提案だ」"),
"bark_penhallow_final_2": ("\"Sixty volumes. Do you know what they cost?\"", "「六十巻。いくらかかったか分かるかね」"),
"bark_penhallow_final_3": ("\"I can make your father's page disappear, Vance.\"", "「君の父親のページを消してやれるぞ、ヴァンス」"),
"bark_penhallow_final_4": ("\"Marguerite. Say something.\"", "「マルグリット。何か言え」"),
"hs_trolley": ("The trolley", "台車"), "hs_coalstore": ("Coal store door", "石炭庫の扉"), "hs_lodge_phone": ("Lodge telephone", "詰所の電話"),
"hs_manifest": ("Manifest board", "積荷目録"), "hs_programme": ("Lecture programme", "講演プログラム"), "hs_portraits": ("Portraits", "肖像画"),
"hs_decanter": ("Sherry decanter", "シェリーのデカンタ"), "hs_lectern": ("The lectern", "演台"), "hs_vey_desk": ("Secretary's desk", "秘書の机"),
"hs_fireplace": ("Fireplace", "暖炉"), "hs_files": ("File boxes", "書類箱"), "hs_bricks": ("The bricked door", "煉瓦で塞がれた扉"),
"hs_wheel": ("Wheel lock", "円形錠"), "hs_shelves": ("The volumes", "台帳の棚"), "hs_window2": ("Window", "窓"), "hs_back": ("Back to the study", "研究室へ戻る"),
"hs_go_lecture": ("Into the hall", "講堂へ"), "hs_return": ("Go back", "戻る"),
"i_survey": ("Survey approval", "調査許可書"), "id_survey": ("Evidence. Approved in eleven hours. Nobody is that fast.", "証拠。十一時間で承認。そんなに早い者はいない。"),
"i_plan_1994": ("1994 cellar plan", "1994年の地下図面"), "id_plan_1994": ("Evidence. A room drawn in red that is on no other plan.", "証拠。他のどの図面にもない、赤で描かれた部屋。"),
"i_gift_pen": ("Fountain pen", "万年筆"), "id_gift_pen": ("Green ink. Hers would be green. Give it to her.", "緑のインク。彼女なら緑だ。贈ろう。"),
"i_brandy": ("Common-room brandy", "談話室のブランデー"), "id_brandy": ("Restores 14 nerve.", "胆力を14回復。"),
"i_biscuits": ("Tin of biscuits", "ビスケット缶"), "id_biscuits": ("Restores 28 composure.", "平静を28回復。"),
"i_gown": ("Academic gown", "学位ガウン"), "id_gown": ("Elena's outfit. Wit +1, Recite stronger.", "エレナの衣装。知力+1、暗誦強化。"),
"i_evening": ("Emerald evening gown", "エメラルドのイブニングドレス"), "id_evening": ("Elena's outfit for the lecture. Charm +2, Flirt stronger.", "講演会用のエレナの衣装。魅力+2、誘惑強化。"),
"i_keyring": ("Porter's keyring", "守衛の鍵束"), "id_keyring": ("Tool. Stealth +2.", "道具。隠密+2。"),
"i_page_two": ("Page two", "2ページ"), "id_page_two": ("Evidence. Your father. Four hundred pounds. 1971.", "証拠。あなたの父。四百ポンド。1971年。"),
# ---- night 2
"n2_title": ("Night Two — The Incinerator List", "第二夜 — 焼却リスト"), "n2_sub": ("5:41 AM. The vault door, and a clipboard.", "午前5時41分。書庫の扉と、クリップボード。"),
"n2_plan_1": ("The plan, then: swap the crate before nine. The lodge, the dock, the coal store. In that order, before the van.", "計画はこうだ。九時までに木箱をすり替える。詰所、搬入口、石炭庫。車が来る前に、この順で。"),
"n2_lodge_1": ("The porter's lodge. Cobb is not here. Someone else is, at his telephone, in a grey cardigan.", "守衛詰所。コブはいない。代わりに灰色のカーディガンの誰かが、彼の電話の前にいる。"),
"n2_vey_1": ("\"Professor Vance. The Dean asked me to confirm the signing officer for lot forty-one. I'm told that's you.\"", "「ヴァンス教授。学部長から第41ロットの署名責任者を確認するよう言われまして。あなただと伺いました」"),
"n2_vey_2": ("She has a pencil behind her ear and a list in front of her. Your name is already on it.", "彼女は耳に鉛筆を挟み、目の前にリストを置いている。あなたの名前はもう載っている。"),
"n2_vey_3": ("\"I'll tell the Dean you were very helpful,\" Miss Vey says. She does not say what she will tell her about Elena.", "「とても協力的だったと学部長に伝えますわ」とヴェイ。エレナについて何を伝えるかは言わない。"),
"n2_phone_1": ("The lodge telephone log. One call at 5:52, to an extension you know: the Dean's residence.", "詰所の通話記録。5時52分に一件、知っている内線へ。学部長公邸だ。"),
"n2_keyring_1": ("Cobb's spare keyring hangs on a nail. He would want you to have it. Probably.", "コブの予備の鍵束が釘に掛かっている。彼ならあなたに持たせたがるだろう。たぶん。"),
"n2_dock_hollis_1": ("Estates security, in a yellow coat, with a clipboard of his own. Everybody has a clipboard today.", "黄色いコートの施設警備員。彼もクリップボードを持っている。今日は誰もがクリップボードを持っている。"),
"n2_dock_hollis_2": ("\"Nobody's on my list for the dock this morning, sir.\"", "「今朝の搬入口の名簿に、どなたも載っていませんが」"),
"n2_dock_grice_1": ("The van is early. The driver's mate jumps down, already counting crates.", "車が早く着いた。運転手の助手が飛び降り、もう木箱を数えている。"),
"n2_dock_grice_2": ("Elena steps between him and the middle crate. \"Five minutes. The labels are wrong.\"", "エレナが彼と真ん中の木箱の間に立つ。「五分ちょうだい。ラベルが違うの」"),
"n2_manifest_1": ("The manifest: three crates, lot forty-one in the middle, signing officer VANCE. Typed, not signed.", "積荷目録：木箱三つ、第41ロットは真ん中、署名責任者ヴァンス。タイプ打ちで、署名はない。"),
"n2_coal_1": ("The coal store under the dock. Somebody has been here since you hid the crate. The door is ajar.", "搬入口下の石炭庫。木箱を隠してから、誰かがここに来ている。扉が少し開いている。"),
"n2_crane_1": ("A thin man in a grey trench coat, sitting on lot forty-one, smoking.", "灰色のトレンチコートの痩せた男が、第41ロットに腰掛けて煙草を吸っている。"),
"n2_crane_2": ("\"Professor. Miss Ashcombe. The Dean sends her thanks for your diligence. She'd like the crate.\"", "「教授。アシュコムさん。学部長があなた方の勤勉さに感謝しています。木箱を頂きたいそうです」"),
"n2_crane_3": ("He flicks the cigarette into the coal and does not look to see where it lands.", "彼は煙草を石炭の上に弾き飛ばし、どこに落ちたかも見ない。"),
"n2_crane_4": ("\"Another time, then.\" Crane steps over the crate on his way out, as if it were a puddle.", "「では、また今度」クレインは水たまりでも跨ぐように木箱を跨いで出ていった。"),
"n2_crane_5": ("Elena sits down on the crate where he sat. Her hands are shaking now, all at once.", "エレナは彼が座っていた木箱に腰を下ろす。今になって、手が一気に震え出す。"),
"n2_back_1": ("Back upstairs. The study, the lamp, the radiator. It feels like a week since last night.", "上の階へ戻る。研究室、ランプ、ラジエーター。昨夜から一週間経ったような気がする。"),
"n2_trust_hint": ("(Her trust is not there yet. At Trust 5 this scene goes further.)", "（まだ信頼が足りない。信頼5でこの場面は先へ進む）"),
"n2_trolley_1": ("The trolley. Three crates. Hollis's back is turned, for now.", "台車。木箱が三つ。ホリスは今のところ背を向けている。"),
"n2_window_1": ("From the dock you can see the incinerator chimney. It is already smoking.", "搬入口から焼却炉の煙突が見える。もう煙が上がっている。"),
"n3_gift_1": ("In your drawer: a fountain pen with green ink, bought in September and never used, and a dress box Elena left here 'for Friday'.", "引き出しの中に、九月に買って使わずにいた緑インクの万年筆と、エレナが「金曜日用」と置いていったドレスの箱。"),
"n4_tin_1": ("The petty-cash tin holds biscuits now. Elena's academic gown hangs on the back of the door.", "小口現金の缶には今やビスケットが入っている。扉の裏にはエレナの学位ガウンが掛かっている。"),
# ---- night 3
"n3_title": ("Night Three — Penhallow", "第三夜 — ペンハロウ"), "n3_sub": ("Three days later. Friday: the Penhallow Lecture.", "三日後。金曜日、ペンハロウ記念講演。"),
"n3_plan_1": ("Seven o'clock. The main hall first, then the sherry in the common room. Elena has put on something she says is armour.", "七時。まず大講堂、それから談話室でシェリー。エレナは「鎧よ」と言って何かに着替えてきた。"),
"n3_corr_1": ("The Dean's corridor is full of chairs being carried somewhere else.", "学部長室の廊下は、どこかへ運ばれていく椅子でいっぱいだ。"),
"n3_grice_1": ("Grice, from the dock, in a borrowed waiter's jacket, with a stack of chairs and a long memory.", "搬入口のグライスが、借り物の給仕服で椅子を積み上げ、長い記憶を携えて立っている。"),
"n3_grice_2": ("\"You're the ten-minute man. Van was late to the incinerator. Somebody noticed.\"", "「あんた、十分待たせた人だな。焼却炉に遅れた。気付いた奴がいる」"),
"n3_grice_3": ("\"Fine. I never saw you. I'm carrying chairs.\"", "「いいさ。何も見てない。俺は椅子を運んでるだけだ」"),
"n3_hall_1": ("The main hall. Four hundred chairs, a lectern, and a portrait of Aldous Penhallow ten feet high.", "大講堂。四百脚の椅子、演台、そして高さ三メートルのオルダス・ペンハロウの肖像画。"),
"n3_sallis_1": ("Dr Imogen Sallis, who wrote the book on the Blackwood bequest and would like you to know it.", "ブラックウッド遺贈について本を書き、それを知らしめたいイモジェン・サリス博士。"),
"n3_sallis_2": ("\"Vance. Antiquities filed a survey request on my wing. Explain.\"", "「ヴァンス。古美術学部が私の棟の調査請求を出したわね。説明して」"),
"n3_sallis_3": ("\"Fine. Fine. But if you find anything, I want the footnote.\"", "「いいわ。でも何か見つけたら、脚注は私のものよ」"),
"n3_programme_1": ("The programme lists the Penhallow donors since 1897. Ashcombe is not among them. The typeface changes in 1996.", "プログラムには1897年以来のペンハロウ寄付者が並ぶ。アシュコムの名はない。1996年で書体が変わっている。"),
"n3_portraits_1": ("Aldous Penhallow, in oils. The painter gave him Julian's hands. Or Julian has his.", "油彩のオルダス・ペンハロウ。画家は彼にジュリアンの手を描いた。あるいはジュリアンが祖父の手を受け継いだのか。"),
"n3_common_1": ("The common room. Sherry, small talk, and a man in a pinstripe suit who has been watching Elena since the door.", "談話室。シェリー、世間話、そして扉からずっとエレナを見ているピンストライプの男。"),
"n3_ambrose_1": ("\"Professor Vance? Ambrose. I act for the Penhallow family. A small matter of a survey.\"", "「ヴァンス教授？アンブローズです。ペンハロウ家の代理人をしております。調査の件で少々」"),
"n3_ambrose_2": ("\"Another time, then. My client is on his way over.\"", "「では、また。依頼人がこちらに向かっております」"),
"n3_decanter_1": ("A decanter of common-room brandy nobody is guarding. Medicinal, again.", "誰も見張っていない談話室のブランデー。またしても薬用だ。"),
"n3_pen_pre_1": ("Julian Penhallow crosses the room toward you. He does not hurry. He has never had to.", "ジュリアン・ペンハロウが部屋を横切ってくる。急がない。急ぐ必要がなかった男だ。"),
"n3_back_1": ("Ten o'clock. You leave the common room without looking back. Elena follows two minutes later, as agreed.", "十時。振り返らずに談話室を出る。エレナは打ち合わせ通り二分後に続く。"),
"n3_trust_hint": ("(Her trust is not there yet. At Trust 7 this scene goes further.)", "（まだ信頼が足りない。信頼7でこの場面は先へ進む）"),
# ---- night 4
"n4_title": ("Night Four — The Dean's Annex", "第四夜 — 学部長の別館"), "n4_sub": ("Two o'clock. Tea. Twenty minutes in the file room.", "二時。茶席。書類室での二十分。"),
"n4_corr_1": ("The Dean's corridor, by daylight. Every door shut. One desk outside the last one.", "昼の学部長室の廊下。扉はすべて閉ざされ、最後の扉の前に机がひとつ。"),
"n4_vey_1": ("Miss Vey looks up. She has a list. Elena is not on it.", "ヴェイが顔を上げる。リストがある。エレナの名は載っていない。"),
"n4_vey_2": ("\"The Dean is expecting you, Professor. Only you.\"", "「学部長がお待ちです、教授。あなただけを」"),
"n4_vey_3": ("Miss Vey goes to fetch the milk. She leaves the file-room key in her drawer, which is open.", "ヴェイはミルクを取りに行く。書類室の鍵は引き出しに入れたまま。引き出しは開いている。"),
"n4_annex_1": ("The annex: panelling, portraits, Penhallow above the fireplace, and a man at the door who is not a porter.", "別館。羽目板、肖像画、暖炉の上のペンハロウ、そして守衛ではない戸口の男。"),
"n4_hollis_1": ("Hollis, from the dock, moved to the annex. Promoted, he says. He does not look pleased about it.", "搬入口のホリスが別館に移っていた。昇進だという。嬉しそうには見えない。"),
"n4_hollis_2": ("\"Fine. Go in. I didn't see her go the other way, either.\"", "「いいですよ、入って。彼女が反対側に行くのも見てません」"),
"n4_fire_1": ("The fireplace. In the grate, the corner of a typed sheet that did not burn: LOT 41 — SIGNING OFFICER —", "暖炉。火格子にタイプ打ちの紙の燃え残り：第41ロット — 署名責任者 —"),
"n4_files_1": ("The file room. Boxes to the ceiling, every one labelled in the Dean's hand. She keeps everything.", "書類室。天井まで箱が積まれ、どれも学部長の字でラベルが貼られている。彼女は何でも取っておく。"),
"n4_crane_1": ("Crane is in the doorway, between you and the corridor, holding nothing at all.", "クレインが戸口に立っている。あなたと廊下の間に。何も持たずに。"),
"n4_crane_2": ("\"The Dean keeps everything, Professor. That includes count of who comes in here.\"", "「学部長は何でも取っておくんですよ、教授。ここに誰が入ったかの数も含めて」"),
"n4_crane_3": ("\"Keep the plan. She has copies.\" Crane steps aside. He sounds almost relieved.", "「図面はどうぞ。写しはあります」クレインは脇へ退く。どこか安堵したような声だった。"),
"n4_trust_hint": ("(Her trust is not there yet. At Trust 7 this scene goes further.)", "（まだ信頼が足りない。信頼7でこの場面は先へ進む）"),
"n4_carrel_1": ("Her carrel in the postgraduate block. One lamp, books in towers, a teacup with a week of rings in it.", "大学院棟の彼女の閲覧席。ランプひとつ、塔のような本の山、一週間分の輪染みのついたティーカップ。"),
"n4_window_1": ("From her window: the chapel roof, and under it, somewhere, a room that is on no plan but one.", "彼女の窓から礼拝堂の屋根が見える。その下のどこかに、ただ一枚の図面にしか載っていない部屋がある。"),
# ---- night 5
"n5_title": ("Night Five — The Strongroom", "第五夜 — 保管庫"), "n5_sub": ("Under the chapel. Brick, mortar, and a wheel lock.", "礼拝堂の下。煉瓦、モルタル、円形錠。"),
"n5_stair_1": ("The crypt stair. The story the first-years tell. It is real, and it is lit, and someone has swept it.", "地下への階段。新入生が語る噂話。それは実在し、灯りがともり、誰かが掃除していた。"),
"n5_grice_1": ("Grice, again, at the bottom of the stair, with a torch and a different jacket.", "またグライスだ。階段の下で、懐中電灯と違う上着で。"),
"n5_grice_2": ("\"Overtime, Professor. Somebody's paying a lot of people to stand in cellars tonight.\"", "「残業ですよ、教授。今夜は誰かが大勢に金を払って地下に立たせてる」"),
"n5_grice_3": ("\"I'm going home. Tell whoever's paying I went home.\"", "「帰りますよ。金を払ってる奴に、俺は帰ったと伝えてくれ」"),
"n5_ambrose_1": ("Ambrose, in a good coat, holding a document with a red seal.", "上等なコートのアンブローズが、赤い封蝋の書類を手にしている。"),
"n5_ambrose_2": ("\"An injunction, Professor. Signed at six. You will want to read it before you touch that door.\"", "「差止命令です、教授。六時に署名されました。その扉に触れる前にお読みになった方がよろしいかと」"),
"n5_ambrose_3": ("\"I did say I had paperwork for every outcome. I did not say it would hold.\"", "「どんな結末にも書類はある、と申し上げました。それが有効だとは申しておりません」"),
"n5_crane_1": ("Crane, at the bricked door, with a bricklayer's hammer he has clearly never used.", "煉瓦で塞がれた扉の前のクレイン。明らかに使ったことのない煉瓦槌を持って。"),
"n5_crane_2": ("\"The Dean said nobody goes in. She didn't say why. She never does.\"", "「学部長は誰も入れるなと。理由は言わなかった。いつもそうだ」"),
"n5_crane_3": ("Crane puts the hammer down very carefully, as if it were the one thing in the cellar that could break.", "クレインは慎重に槌を置く。まるで地下で唯一壊れるものであるかのように。"),
"n5_bricks_1": ("New brick over an old door. Same mortar as the coal store. Same month.", "古い扉を覆う新しい煉瓦。石炭庫と同じモルタル。同じ月のものだ。"),
"n5_pen_pre_1": ("Penhallow does not raise his voice. He names a figure instead.", "ペンハロウは声を荒らげない。代わりに金額を口にする。"),
"n5_pen_post_1": ("The Dean has still not looked at Penhallow. She is looking at the ledger in Elena's arms.", "学部長はまだペンハロウを見ていない。エレナの腕の中の台帳を見ている。"),
"n5_trust_hint": ("(Her trust is not there yet. At Trust 9 this scene goes further.)", "（まだ信頼が足りない。信頼9でこの場面は先へ進む）"),
"end_rewrite": ("Ending: The Record", "エンディング：記録"), "end_expose": ("Ending: Daylight", "エンディング：白日"), "end_abscond": ("Ending: The Sea", "エンディング：海"),
"credits_1": ("Elena: Crimson Archives — RPG edition. Thank you for playing.", "エレナ：深紅の書庫 — RPG版。プレイしていただきありがとうございました。"),
"credits_2": ("Three endings: The Record, Daylight, The Sea. Your save is kept; play the last night again from slot 1 to see another.", "エンディングは三つ：記録、白日、海。セーブは残る。スロット1から最終夜をやり直せば別の結末が見られる。"),
"g_cg_ch3_crypt": ("An hour", "一時間"), "g_cg_annex": ("The file room", "書類室"), "g_cg_ch4_chapel": ("On my instruction", "私の指示で"),
"g_cg_muniment": ("The strongroom", "保管庫"), "g_cg_ch5_muniment": ("Sixty volumes", "六十巻"),
"g_cg_rpg_rain_arrival": ("Rain at the gate", "門の雨"), "g_cg_rpg_map_room": ("The map room", "地図室"), "g_cg_rpg_lockpick": ("Lockwork", "錠前"),
"g_cg_rpg_bell_chamber": ("The bells", "鐘楼"), "g_cg_rpg_roof_dawn": ("Roof, dawn", "屋根の夜明け"), "g_cg_rpg_gala": ("The lecture", "講演会"),
"g_cg_trust3_carrel": ("Her carrel", "閲覧席"), "g_cg_trust5_common_room": ("After the sherry", "シェリーの後"),
"g_cg_trust7_bath": ("Steam", "湯気"), "g_cg_trust9_bed": ("Morning", "朝"),
}
