"""夜读 / Night Reading — the cast, their tracks, and everything they say.

The adult fork's own pool (ops/adult_forks/cyber_fortune_night_reading.md). The parent's
slips and tarot are still the *text of the draw*; this file is the text of what the draw
does to the person you drew it for.

Three women, three tracks each, at 0..3. Per track she has four things to say:

  open_strong   a reading that opens the track by 2 or 3 — she takes it, and it shows
  open_weak     +1, or a negative one she is already far enough into to absorb
  refuse        the consent gate: she does not take it. Nothing is written, and the
                refusal is not remembered. She says why, in her own words.
  locked        the track reaches 3 — she says it back, and it is true now.

Nothing here is explicit: this is the framework's text, tier 1-2 in register. The night
scene's own lines live in `scene` and stop where ART_DIRECTION's tier 3 stops.
"""

# (id, zh, en)
CAST = [
    dict(
        id="mirren",
        name_zh="米伦", name_en="Mirren",
        who_zh="白天替所有人读牌的人。没人读过她。",
        who_en="The one who reads everyone by day. Nobody has ever read her.",
        room="west",
        tracks=[
            dict(
                id="table",
                name_zh="桌子", name_en="the table",
                belief_zh="她从不绕过桌子这一边。",
                belief_en="She never comes round to this side of the table.",
                open_strong_zh="她看了一眼桌角，然后把椅子往旁边挪了半寸——不是让你过去，是她自己动了。",
                open_strong_en="She looks at the corner of the table, then moves her chair half an inch sideways. Not inviting you over; she moved.",
                open_weak_zh="“桌子只是木头。”她说。她自己先听见了这句话。",
                open_weak_en="\"It's only wood,\" she says, and hears herself say it.",
                refuse_zh="“不。”她把牌推回来，手很稳。“这张不是我。今晚也不是。”",
                refuse_en="\"No.\" She pushes the card back, steady. \"That one isn't me. Not tonight.\"",
                locked_zh="她绕过来，坐在桌子的这一边，像这本来就是她的位置。",
                locked_en="She comes round and sits on this side of the table as if it had always been her chair.",
            ),
            dict(
                id="hood",
                name_zh="兜帽", name_en="the hood",
                belief_zh="读牌的人不该被看见。",
                belief_en="The one who reads is not the one who is seen.",
                open_strong_zh="兜帽往后落了一点。她没有扶回去。",
                open_strong_en="The hood slips back. She doesn't fix it.",
                open_weak_zh="“光太暗了，”她说，“你看不清我。”——这句话她说慢了半拍。",
                open_weak_en="\"It's dark in here,\" she says. \"You can't see me anyway.\" She says it half a beat too slowly.",
                refuse_zh="她把兜帽拉严了。“先读你手里的牌，再读我。”",
                refuse_en="She pulls the hood closed. \"Read the card in your hand before you read me.\"",
                locked_zh="兜帽在椅背上。她让烛光照着自己的脸，没有偏头。",
                locked_en="The hood is over the chair back. She lets the candle have her face and doesn't turn away.",
            ),
            dict(
                id="question",
                name_zh="问", name_en="the question",
                belief_zh="她替别人问，从不替自己问。",
                belief_en="She asks for other people. Never for herself.",
                open_strong_zh="“那……替我问一次。”她说得很快，怕自己改主意。",
                open_strong_en="\"Then ask one for me.\" Fast, before she can take it back.",
                open_weak_zh="她笑了一下：“假设——只是假设——我也有一个问题。”",
                open_weak_en="She almost smiles. \"Suppose — only suppose — I had one.\"",
                refuse_zh="“我今天的问题都用完了。”她把牌翻过去。",
                refuse_en="\"I've used up my questions today.\" She turns the card face down.",
                locked_zh="她说出了那个问题，说完就一直看着你，等你抽。",
                locked_en="She asks it out loud, and then just looks at you, waiting for you to draw.",
            ),
        ],
        scene=dict(
            invite_zh="“你读的都应验了，”她说。“那就读最后一件。”",
            invite_en="\"Everything you read came true,\" she says. \"So read the last one.\"",
            beats_zh=[
                "她自己解开斗篷的第一个扣子，停在第二个上，让你看见她停在哪里。",
                "烛火把她锁骨上的影子推上去一寸；她的手撑在桌沿，指节发白。",
                "“说出来，”她说，“像你读签那样说——然后它就是真的。”",
            ],
            beats_en=[
                "She opens the first clasp of the cloak herself, stops at the second, and lets you see where she stopped.",
                "The candle pushes the shadow up an inch past her collarbone; her hand braces on the table edge, knuckles pale.",
                "\"Say it,\" she says, \"the way you read a slip — and then it's true.\"",
            ],
            after_zh="她把那张牌收进自己的牌堆里，正位朝上。",
            after_en="She slides that card into her own deck, upright.",
        ),
    ),
    dict(
        id="qiao",
        name_zh="签姑", name_en="Qiao",
        who_zh="守签筒的人。凌晨两点还穿着那身袍子。",
        who_en="She keeps the slip tube. Two in the morning and still in the robe.",
        room="east",
        tracks=[
            dict(
                id="hour",
                name_zh="香", name_en="the hour",
                belief_zh="香没断，她就还在当值。",
                belief_en="While the incense burns she is on duty.",
                open_strong_zh="她把最后一炷香按灭了，很轻，像关掉一个开关。",
                open_strong_en="She presses out the last stick of incense, lightly, like turning off a switch.",
                open_weak_zh="“……其实这炷也快完了。”她看着它，没有续。",
                open_weak_en="\"This one's nearly out anyway.\" She watches it and doesn't light another.",
                refuse_zh="“香还没完。”她把签筒摆正。这就是回答。",
                refuse_en="\"The incense isn't finished.\" She squares the tube on the table. That is the answer.",
                locked_zh="香灰是冷的。她终于坐下来，像一个下了班的人。",
                locked_en="The ash is cold. She sits down at last, like someone off shift.",
            ),
            dict(
                id="form",
                name_zh="礼", name_en="the form",
                belief_zh="她用庙里的话回答一切。",
                belief_en="She answers everything in the temple's register.",
                open_strong_zh="她说了一句很普通的话，然后自己愣住了——那是她自己的句子。",
                open_strong_en="She says something ordinary, then stops: it was her own sentence, not the temple's.",
                open_weak_zh="“……我不知道这个该怎么讲。”她第一次没有引经。",
                open_weak_en="\"I don't know the line for that.\" The first time she hasn't had one.",
                refuse_zh="她合十，答了四个字，标准得像印上去的。",
                refuse_en="She folds her hands and gives you four characters, as standard as a stamp.",
                locked_zh="她整晚都在用自己的话说话，而且没有再改回去。",
                locked_en="She talks in her own words all night, and doesn't switch back.",
            ),
            dict(
                id="wish",
                name_zh="愿", name_en="the wish",
                belief_zh="她替所有人求过，唯独没替自己。",
                belief_en="She has prayed for everyone who came in, and never once for herself.",
                open_strong_zh="她抽了一支签，是替自己抽的。她的手抖了一下。",
                open_strong_en="She shakes one stick out for herself. Her hand jumps once.",
                open_weak_zh="“如果我求，”她说，“也不算贪心吧。”",
                open_weak_en="\"If I asked,\" she says, \"that wouldn't be greedy. Would it.\"",
                refuse_zh="“这支不是给我的。”她把它放回筒里。",
                refuse_en="\"That one isn't mine.\" She puts it back in the tube.",
                locked_zh="她把自己的那支签系在架子上，名字朝外。",
                locked_en="She ties her own slip to the rack with her name facing out.",
            ),
        ],
        scene=dict(
            invite_zh="“你读的那些，都成了真的。”她说。“那这一支呢。”",
            invite_en="\"The ones you read came true,\" she says. \"So what about this one.\"",
            beats_zh=[
                "袍子的第一层搭在案上，第二层还穿着；她自己把袖子推到肘上。",
                "签筒空了一半。她扶着案沿，背对烛光，肩线在袍子底下很清楚。",
                "“念出来，”她说，“照签上的念——念了就算数。”",
            ],
            beats_en=[
                "The outer robe goes over the desk; the second layer stays on. She pushes her own sleeve to the elbow.",
                "The tube is half empty. She braces on the desk edge, back to the candle, the line of her shoulders plain under the robe.",
                "\"Read it out,\" she says, \"the way it's written — and then it counts.\"",
            ],
            after_zh="她把那支签收进袖子里，没有系上架子。",
            after_en="She keeps that slip in her sleeve instead of tying it to the rack.",
        ),
    ),
    dict(
        id="dagny",
        name_zh="达妮", name_en="Dagny",
        who_zh="楼下街机厅的老板。进来就是为了证明这是骗人的。",
        who_en="She runs the arcade downstairs. She came in to prove this is nonsense.",
        room="west",
        tracks=[
            dict(
                id="joke",
                name_zh="玩笑", name_en="the joke",
                belief_zh="什么都能当笑话讲过去。",
                belief_en="Everything can be laughed off on the way past.",
                open_strong_zh="她笑到一半停了，把手按在牌上。“再说一遍。”",
                open_strong_en="She stops halfway through the laugh and puts her hand flat on the card. \"Say that again.\"",
                open_weak_zh="“好笑。”她说。她没有笑。",
                open_weak_en="\"Funny,\" she says. She doesn't laugh.",
                refuse_zh="她笑了，很大声，然后换了个话题。你听得出来那是门关上的声音。",
                refuse_en="She laughs, loudly, and changes the subject. You can hear the door closing in it.",
                locked_zh="她不笑了。她就这么坐着，看着你，让句子留在桌上。",
                locked_en="She doesn't laugh. She just sits there and lets the sentence stay on the table.",
            ),
            dict(
                id="lock",
                name_zh="打烊", name_en="the lock",
                belief_zh="她一个人关门，从来不等人。",
                belief_en="She closes up alone. She has never waited for anyone.",
                open_strong_zh="她把钥匙放在桌上，推过来一点，没说为什么。",
                open_strong_en="She puts the keys on the table and pushes them an inch toward you without saying why.",
                open_weak_zh="“反正机器要冷两个小时。”这是她给自己的理由。",
                open_weak_en="\"The machines take two hours to cool down anyway.\" That is the reason she gives herself.",
                refuse_zh="“我十分钟后关门。”她已经站起来了。",
                refuse_en="\"I'm locking up in ten.\" She is already standing.",
                locked_zh="她没关门。她把牌子翻成“营业中”，然后坐回来。",
                locked_en="She doesn't lock up. She flips the sign back to OPEN and sits down again.",
            ),
            dict(
                id="tell",
                name_zh="破绽", name_en="the tell",
                belief_zh="她有一个小动作，她自己知道。",
                belief_en="She has a tell, and she knows she has it.",
                open_strong_zh="她的拇指在杯沿上停住了——正是那个动作，而且她知道你看见了。",
                open_strong_en="Her thumb stops on the rim of the glass — that exact movement, and she knows you saw it.",
                open_weak_zh="她把手放到桌子底下去了。",
                open_weak_en="She puts that hand under the table.",
                refuse_zh="“猜的。”她说。“接着猜。”手没动。",
                refuse_en="\"Guess,\" she says. \"Keep guessing.\" The hand doesn't move.",
                locked_zh="她把两只手都放在桌上，摊开。“行。你读到了。”",
                locked_en="She puts both hands on the table, open. \"Fine. You read it.\"",
            ),
        ],
        scene=dict(
            invite_zh="“三次都对。”她说。“那你现在说什么我就信什么——所以说点值得的。”",
            invite_en="\"Three for three,\" she says. \"So whatever you say now, I'll believe. Make it worth it.\"",
            beats_zh=[
                "外套还挂在椅背上，衬衫的扣子她自己解到第三颗就停了，抬眼看你。",
                "街机的光从楼下透上来，一条一条扫过她的背；她把头发拨到一边。",
                "“读吧，”她说，“读完我就不还嘴了。”",
            ],
            beats_en=[
                "The jacket stays on the chair back; she opens her own shirt to the third button and stops there, eyes up.",
                "Arcade light comes up through the floor in bars across her back; she pushes her hair off one side.",
                "\"Read it,\" she says. \"After that I won't argue.\"",
            ],
            after_zh="她把牌翻过来压在杯底下。“明天我还来。”",
            after_en="She turns the card face down under her glass. \"I'm coming back tomorrow.\"",
        ),
    ),
]

# The fork's own UI strings, merged over the parent's pool/ui.json.
UI_NIGHT = {
    "title": {"zh": "夜读", "en": "Night Reading"},
    "series": {"zh": "blazeCore Play · 18+", "en": "blazeCore Play · 18+"},
    "night.rule": {"zh": "白天你读人。入夜之后，你读出来的就成真。",
                   "en": "By day you read people. After dark, what you read becomes true."},
    "night.who": {"zh": "今晚读谁？", "en": "Who are you reading tonight?"},
    "night.tracks": {"zh": "{n}/9", "en": "{n}/9"},
    "night.done": {"zh": "已读完", "en": "read"},
    "night.ready": {"zh": "她在等", "en": "she is waiting"},
    "night.instrument": {"zh": "用什么读", "en": "Read her with"},
    "inst.slip": {"zh": "签", "en": "The tube"},
    "inst.card": {"zh": "牌", "en": "The deck"},
    "inst.force": {"zh": "读心", "en": "Mentalism"},
    "night.draw": {"zh": "读", "en": "Read"},
    "night.draw.free": {"zh": "读 · 今日免费", "en": "Read · free today"},
    "night.need": {"zh": "还差 {n} 功德", "en": "{n} merit to go"},
    "night.tap": {"zh": "敲木鱼", "en": "Tap the fish"},
    "night.speak": {"zh": "读给她听", "en": "Say it to her"},
    "night.hold": {"zh": "不说", "en": "Keep it"},
    "night.held": {"zh": "你把这一签收起来了（+{n} 功德）", "en": "You keep it to yourself (+{n} merit)"},
    "night.took": {"zh": "{track} +{n}", "en": "{track} +{n}"},
    "night.back": {"zh": "{track} {n}", "en": "{track} {n}"},
    "night.refused": {"zh": "她没有接。这一签作废了。", "en": "She didn't take it. The draw is spent."},
    "night.locked": {"zh": "{track}：现在是真的了。", "en": "{track}: true now."},
    "night.all": {"zh": "她三条都是真的了。", "en": "All three are true now."},
    "night.scene": {"zh": "留下来", "en": "Stay"},
    "night.scene.locked": {"zh": "看广告解锁 · 18+", "en": "Watch an ad to unlock · 18+"},
    "night.scene.denied": {"zh": "没解锁——什么都没有变。", "en": "Not unlocked — nothing changed."},
    "night.next": {"zh": "回到桌边", "en": "Back to the table"},
    "night.clear": {"zh": "三个人，三个夜晚。", "en": "Three women. Three nights."},
    "night.clear.sub": {"zh": "你读出来的，都成真了。", "en": "Everything you read came true."},
    "night.more": {"zh": "还有别的", "en": "More like this"},
    "night.placeholder": {"zh": "占位图 · 未完成", "en": "PLACEHOLDER ART"},
    "night.consent": {"zh": "她接了，才算数。", "en": "It only counts if she takes it."},
    "rank.strength": {"zh": "力度 {n}", "en": "strength {n}"},
    # The parent's toasts talk about the rack and the 签筒; on this side of the table a
    # draw is something you did to someone, so it says what happened to her instead.
    "kept.toast": {"zh": "你把这一签读给了她", "en": "You read it to her"},
    "burned.toast": {"zh": "你没有说出口（+{n} 功德）", "en": "You did not say it (+{n} merit)"},
}
