# The slip pool, written by hand (2026-09-18). One entry per line:
#   (rank, subject, 签文 zh, verse en, reading zh, reading en, do zh, do en)
# Ranks: daji 大吉, zhongji 中吉, xiaoji 小吉, moji 末吉, xiong 凶, daxiong 大凶.
# Subjects: work 事业, money 财, love 情, body 身体, study 学业, traveler 行人.
# House rules (ops/adult_forks/cyber_merit_fortune.md §3): classical register for the
# verse, plain for the reading, one concrete thing to do; no medical, financial or
# named-person claims; 凶 slips speak about effort and timing, never harm.

SLIPS = [
# ---------------------------------------------------------------- 大吉 · work
("daji","work","云开见日","Clouds part; the sun is out",
 "压了很久的事，这几天会松开。你做过的准备，别人现在看得见了。",
 "What has been pressed down for weeks loosens now. The preparation you did is finally visible to other people.",
 "今天把你最想推进的那件事，主动开口说出来。","Say the thing you most want to move forward, out loud, to the person who can move it."),
("daji","work","长风破浪","A long wind breaks the waves",
 "顺风的日子不多，这算一个。放手去争，不必等人点头。",
 "Days with the wind behind you are rare. This is one. Go for it without waiting to be nodded at.",
 "把那个你一直想提的方案，今天写成一页纸。","Turn the proposal you keep rehearsing into one page, today."),
("daji","work","凤鸣高冈","The phoenix calls from the high ridge",
 "你的名字会被提到，而且是在你不在场的时候。这是最好的那种被提到。",
 "Your name gets mentioned, in a room you are not in. That is the best kind of mention.",
 "回复一个你拖了很久的人，越短越好。","Reply to someone you have kept waiting. Keep it short."),
("daji","work","春雷动地","Spring thunder moves the ground",
 "一件停滞的事忽然有了动静。趁它还在响，把你想要的说清楚。",
 "Something stalled suddenly moves. While it is still moving, say clearly what you want from it.",
 "把今天的第一个小时留给最重要的事，不看消息。","Give the first hour of today to the most important thing, before you open any messages."),
# ---------------------------------------------------------------- 大吉 · money
("daji","money","泉源不竭","The spring does not run dry",
 "进来的比出去的多，这一阵会持续。不是横财，是你手艺的回报。",
 "More comes in than goes out, and it holds for a while. Not a windfall; the return on your craft.",
 "今天记下这个月所有固定支出，一行一项。","Write down every fixed expense this month, one line each."),
("daji","money","仓廪丰实","The granary is full",
 "该收的钱会到。这是个把底子打厚的好时候。",
 "The money you are owed arrives. It is a good moment to make the floor under you thicker.",
 "把一笔钱放到你三个月内动不了的地方。","Put one sum somewhere you cannot touch it for three months."),
("daji","money","金玉满堂","Gold and jade fill the hall",
 "你之前种下的会开始结果。不用急着扩张，先把手里的握稳。",
 "Something you planted earlier starts to bear. No need to expand; hold what is in your hand steady first.",
 "给自己买一样小的、用得上的东西，不超过一顿饭的钱。","Buy yourself one small useful thing, for less than the price of a meal."),
("daji","money","春水满塘","Spring water fills the pond",
 "手头宽了一点，心也会宽。宽的时候最容易乱花，记得这一点。",
 "The hand is a little fuller, and so the heart. A full hand spends loosely; remember that.",
 "今天不下单。想买的东西写进清单，三天后再看。","Buy nothing today. Put what you want on a list and look at it in three days."),
# ---------------------------------------------------------------- 大吉 · love
("daji","love","花好月圆","The flowers full, the moon round",
 "你惦记的那个人，也在惦记你。不必试探，直接一点。",
 "The person on your mind has you on theirs. Do not test them. Be direct.",
 "今天给那个人发一条不问问题的消息，只说一件你想到的事。","Send them one message today that asks nothing, just says one thing you thought of."),
("daji","love","并蒂莲开","Two lotuses on one stem",
 "两个人正在往同一个方向走。这很少见，值得慢下来看一眼。",
 "Two people are walking in the same direction. That is rare; worth slowing down to notice.",
 "约一顿没有手机的饭。","Plan one meal together with the phones in another room."),
("daji","love","琴瑟和鸣","Zither and lute in tune",
 "该说的话说出来会被接住。你不是在冒险，你是在被等。",
 "What needs saying will be caught. You are not taking a risk; you are being waited for.",
 "把你最近一次感谢的话，今天说给本人听。","Say the thanks you have been thinking, to the person, today."),
("daji","love","东风解冻","The east wind thaws the ice",
 "一段僵住的关系有了松动。不是谁认输，是天气变了。",
 "A frozen relationship gives a little. Nobody lost; the weather changed.",
 "主动先打一个招呼，不必解释为什么。","Say hello first. No explanation needed."),
# ---------------------------------------------------------------- 大吉 · body
("daji","body","松柏长青","Pine and cypress stay green",
 "身体这段时间跟得上你。别拿它当理所当然，好日子也要养。",
 "The body keeps up with you for now. Do not take it as given; the good days also need tending.",
 "今天走路的时候，把耳机拿下来十分钟。","Take the earphones out for ten minutes of today's walk."),
("daji","body","气清神爽","Clear breath, bright spirit",
 "精神比前几周好。趁这个状态，把那个一直拖的习惯立起来。",
 "You have more in you than in recent weeks. Use it to set up the habit you keep putting off.",
 "定一个明天起床的固定时间，然后今晚按时睡。","Pick a fixed time to get up tomorrow, then go to bed on time tonight."),
("daji","body","晨光入户","Morning light comes in the door",
 "休息是有回报的，你现在正拿到它。别急着把它花掉。",
 "Rest pays, and you are being paid now. Do not spend it all at once.",
 "午后离开椅子一次，出门站三分钟。","Leave the chair once this afternoon and stand outside for three minutes."),
("daji","body","泰山安坐","Sitting steady as the mountain",
 "你的底子比你以为的好。稳住节奏，比冲刺更重要。",
 "Your foundation is better than you think. Holding the pace matters more than a sprint.",
 "今天喝够水，把杯子放在看得见的地方。","Drink enough today. Keep the cup where you can see it."),
# ---------------------------------------------------------------- 大吉 · study
("daji","study","文光射斗","Light of letters reaches the stars",
 "读进去的东西正在连成片。你会忽然明白一件之前不懂的事。",
 "What you have read is joining up. Something you did not understand will suddenly make sense.",
 "把今天学到的一点讲给一个人听，讲不通就再读。","Explain one thing you learned today to someone. If it will not explain, read it again."),
("daji","study","一鸣惊人","One call, and all turn to look",
 "考核、面试、发表，这一轮你的准备够了。剩下的是睡眠。",
 "Exam, interview, presentation: for this round your preparation is enough. What is left is sleep.",
 "今晚提前一小时关灯。","Lights off an hour early tonight."),
("daji","study","读书破卷","Read until the binding breaks",
 "你现在的专注力难得。用它对付最难的那一章，不要用来刷题。",
 "The focus you have now is rare. Spend it on the hardest chapter, not on easy drills.",
 "选最怕的那一节，读二十分钟，不做别的。","Pick the section you dread most and read it for twenty minutes, nothing else."),
("daji","study","水到渠成","Water arrives, the channel forms",
 "过去的积累会在这一轮显出来。别怀疑自己，去做题。",
 "The old accumulation shows this round. Do not second-guess; sit down and work.",
 "把一份旧笔记翻出来，只看划过线的部分。","Open one old notebook and read only what you underlined."),
# ---------------------------------------------------------------- 大吉 · traveler
("daji","traveler","雁归有信","The geese come back with word",
 "你等的消息在路上，而且是好的。手机可以放下了。",
 "The word you are waiting for is on its way, and it is good. You can put the phone down.",
 "今天不去看那个对话框。让它来找你。","Do not open that chat today. Let it come to you."),
("daji","traveler","归舟已近","The returning boat is near",
 "那个人比你以为的近。不是回来了，是快了。",
 "That person is nearer than you think. Not back yet; soon.",
 "准备一样小的、见面时能递过去的东西。","Get one small thing ready to hand over when you meet."),
("daji","traveler","风送好音","The wind carries good news",
 "会有一个回复，比你预期的暖。你可以先把心放宽一格。",
 "A reply is coming, warmer than you expect. You can loosen your grip by one notch.",
 "今天把一件为等消息推迟的小事做掉。","Do one small thing you have been postponing while you waited."),
("daji","traveler","故人在门","An old friend at the door",
 "一个久未联系的人会出现。不是要你什么，是想起你了。",
 "Someone you lost touch with will appear. They want nothing; they remembered you.",
 "先主动联系一个你想起来的人，一句话就行。","Reach out first to someone you have been thinking of. One line is enough."),
# ---------------------------------------------------------------- 中吉 · work
("zhongji","work","顺水行舟","A boat going with the current",
 "事情会往前走，但走的是它自己的速度。你推它不会更快。",
 "Things move forward, at their own pace. Pushing does not speed them.",
 "把今天要做的三件事写在纸上，做完一件划掉一件。","Write today's three things on paper. Cross each one off as it is done."),
("zhongji","work","登高望远","Climb high and look far",
 "退一步能看到整体。这周适合规划，不适合硬干。",
 "A step back shows the whole. This week suits planning, not brute effort.",
 "花二十分钟画一张下个月的路线图，画得丑没关系。","Spend twenty minutes drawing next month's map. Ugly is fine."),
("zhongji","work","小舟得渡","The small boat gets across",
 "手上的事能交差，虽然不会惊艳。交出去，再补。",
 "What you have in hand will pass, if not dazzle. Hand it in, then refine.",
 "今天定一个交付时间，告诉一个人。","Set a delivery time today and tell one person."),
("zhongji","work","雨后新晴","Fresh sky after rain",
 "上一阵的乱正在收尾。别急着开新局，把地扫干净。",
 "The recent mess is ending. Do not open a new front; sweep the floor first.",
 "关掉三个用不上的文档或标签页。","Close three documents or tabs you are not using."),
# ---------------------------------------------------------------- 中吉 · money
("zhongji","money","细水长流","A thin stream that never stops",
 "钱不多，但稳。稳比多难得，值得你把它守住。",
 "Not much, but steady. Steady is rarer than plenty; worth guarding.",
 "取消一个你已经不用的订阅。","Cancel one subscription you no longer use."),
("zhongji","money","勤耕有获","Diligent tilling brings harvest",
 "这阵子的收入和付出成正比。想多拿，就得多做，没有捷径，也没有陷阱。",
 "For now income tracks effort. To have more, do more. No shortcuts, but also no traps.",
 "今天把一件能变成收入的技能，练三十分钟。","Practice one skill that can become income for thirty minutes today."),
("zhongji","money","有余可积","There is a little to set aside",
 "月底会剩下一点。剩下的部分决定你下个月的心情。",
 "There will be a little left at month end. What you do with it decides next month's mood.",
 "把剩下的先转走，再决定这个月怎么花。","Move the surplus away first; then decide how the month is spent."),
("zhongji","money","旧账得清","The old ledger gets settled",
 "一笔拖着的账会有结果。不是全部，但够你松一口气。",
 "A lingering debt or payment resolves. Not all of it, but enough to breathe.",
 "今天去催一笔该收的钱，语气平和。","Chase one payment you are owed today, calmly."),
# ---------------------------------------------------------------- 中吉 · love
("zhongji","love","月下相逢","A meeting under the moon",
 "会有一次不错的相处，不必特别安排。别用力过猛就好。",
 "A good stretch of company is coming, no planning needed. Just do not try too hard.",
 "把手机反扣在桌上一次，看看对方在说什么。","Turn your phone face down once and listen to what they are actually saying."),
("zhongji","love","春风渐暖","The spring wind slowly warms",
 "关系在往好处走，只是慢。慢不是问题，急才是。",
 "The relationship is improving, slowly. Slow is not the problem; hurry is.",
 "今天不谈未来。只问一个关于今天的问题。","Do not discuss the future today. Ask one question about their day."),
("zhongji","love","两心相知","Two hearts that know each other",
 "你们比你以为的更了解彼此。少解释，多做事。",
 "You know each other better than you think. Explain less, do more.",
 "帮对方做一件不用问就知道要做的事。","Do one thing for them that you already know needs doing."),
("zhongji","love","明月在天","The bright moon is up",
 "一个人的日子也可以是好日子。今晚的月亮不需要人陪。",
 "A day alone can be a good day. Tonight's moon needs no company.",
 "为自己做一顿像样的饭，摆好盘。","Cook yourself a proper meal and plate it properly."),
# ---------------------------------------------------------------- 中吉 · body
("zhongji","body","饮食有节","Eat and drink with measure",
 "身体在跟你商量，不是抗议。听一听。",
 "The body is negotiating, not protesting. Listen.",
 "今天晚饭比平时少吃两口，早一点吃。","Tonight eat a little less than usual and a little earlier."),
("zhongji","body","动则生阳","Move, and warmth is made",
 "缺的不是休息，是动。动过之后再休息才算数。",
 "What is missing is not rest but movement. Rest counts after you have moved.",
 "出去走二十分钟，不带目的地。","Walk for twenty minutes with no destination."),
("zhongji","body","夜静早眠","Quiet night, early sleep",
 "这阵子的疲惫是睡眠的债，不是别的。债可以还。",
 "This tiredness is a sleep debt, nothing more. Debts can be repaid.",
 "今晚十一点前躺下，手机放到房间外。","Lie down before eleven tonight, phone outside the room."),
("zhongji","body","渐入佳境","Slowly into the good place",
 "恢复正在发生，虽然你自己看不出来。坚持你在做的那件事。",
 "Recovery is happening even if you cannot see it. Keep doing the thing you are doing.",
 "把上周做过的那个好习惯，今天再做一次。","Repeat the good habit from last week once today."),
# ---------------------------------------------------------------- 中吉 · study
("zhongji","study","温故知新","Revisit the old, find the new",
 "往前赶不如往回看。你漏掉的东西在你以为学会的地方。",
 "Going back beats pushing on. What you missed sits where you think you already learned.",
 "重做一道你上次做错的题。","Redo one problem you got wrong last time."),
("zhongji","study","积土成山","Piled earth becomes a mountain",
 "进步是一天一点，看不出来，但在。不要跟别人比进度。",
 "Progress is a little each day, invisible but real. Do not compare pace with anyone.",
 "今天只学二十五分钟，学完就停。","Study for twenty-five minutes today, then stop."),
("zhongji","study","灯下有得","Something gained by lamplight",
 "晚上的一个小时比白天的三个小时值。找到你的那个小时。",
 "One good hour at night is worth three scattered ones by day. Find your hour.",
 "把明天最清醒的时段空出来，什么都不排。","Block tomorrow's clearest hour and put nothing in it."),
("zhongji","study","循序渐进","Step by step, in order",
 "跳过的地方会回来找你。这周把顺序补上。",
 "What you skipped will come back for you. Fill the sequence in this week.",
 "找出你跳过的那一节，今天读它的第一页。","Find the section you skipped and read its first page today."),
# ---------------------------------------------------------------- 中吉 · traveler
("zhongji","traveler","行人在途","The traveler is on the road",
 "对方在动，只是还没到。等待的滋味不好，但不是坏消息。",
 "They are moving; they have not arrived. Waiting tastes bad, but it is not bad news.",
 "今天做一件和这个人无关的事，做完再看手机。","Do one thing today that has nothing to do with them. Then check your phone."),
("zhongji","traveler","书信将至","The letter is about to arrive",
 "会有回音，可能不是你想要的形式。留意短的那条。",
 "A reply comes, maybe not in the form you wanted. Watch for the short one.",
 "把你想说的整理成三句话，先不发。","Boil what you want to say down to three sentences. Do not send yet."),
("zhongji","traveler","近在咫尺","Within a foot of you",
 "消息其实已经到了，只是你没看到那个地方。",
 "The news has actually arrived; you are looking in the wrong place.",
 "翻一下你平时不看的收件箱或文件夹。","Check the inbox or folder you usually ignore."),
("zhongji","traveler","半途有信","Word from halfway",
 "路上会有一个中间消息，不是结果，但让你知道还在走。",
 "There will be a message from the road: not the outcome, but proof it is moving.",
 "给对方一句不要求回复的话。","Send them a line that asks for no reply."),
# ---------------------------------------------------------------- 小吉 · work
("xiaoji","work","小有所成","A small accomplishment",
 "会有一件小事做成。小事做成的手感比大事重要。",
 "One small thing gets done. The feel of a small thing finished matters more than the big one.",
 "选一件二十分钟能完成的事，现在做。","Pick something that takes twenty minutes and do it now."),
("xiaoji","work","守成为上","Holding is the higher art",
 "这周不适合改动。把已经在跑的东西看好。",
 "This week is not for changes. Watch what is already running.",
 "检查一遍上周交出去的东西，改一个错字。","Reread what you handed in last week and fix one typo."),
("xiaoji","work","择木而栖","Choose the tree before you perch",
 "你在考虑的选择还没到时候。多看一个月不会亏。",
 "The choice you are weighing is not ripe. Another month of looking costs nothing.",
 "列出那个选择的三个具体条件，不是感觉。","List three concrete conditions for that choice. Not feelings; conditions."),
("xiaoji","work","静观其变","Sit still and watch it turn",
 "有件事在你看不见的地方变化。你现在动手，只会踩空。",
 "Something is shifting where you cannot see it. Act now and you step on air.",
 "今天不发那封邮件。存草稿。","Do not send that email today. Save the draft."),
# ---------------------------------------------------------------- 小吉 · money
("xiaoji","money","量入为出","Spend within what comes in",
 "钱够用，不够挥霍。这是大多数好日子的样子。",
 "Enough to live on, not enough to waste. That is what most good days look like.",
 "今天用现金或看得见余额的方式付账。","Pay today with cash or something where you can see the balance."),
("xiaoji","money","涓滴成河","Drops become a river",
 "小钱不要嫌小。你这个月最好的决定可能只值一杯咖啡。",
 "Do not scorn small money. Your best decision this month may be worth one coffee.",
 "把零钱或零头转到一个单独的地方。","Move loose change or odd cents into one separate place."),
("xiaoji","money","暂安勿动","Safe for now; do not move",
 "手上的钱别动，也别去追新的机会。这阵子的好机会大多是别人的。",
 "Leave what you have where it is, and chase nothing new. Most of this month's chances belong to others.",
 "把想投进去的那个念头写下来，标上日期。","Write down the thing you feel like putting money into, with today's date."),
("xiaoji","money","粗茶淡饭","Plain tea and simple rice",
 "省下来的比赚到的更实在。这周不需要新东西。",
 "What you save is more real than what you earn. Nothing new is needed this week.",
 "今天在家吃一顿，把外卖的钱记下来。","Eat one meal at home today and note what the delivery would have cost."),
# ---------------------------------------------------------------- 小吉 · love
("xiaoji","love","淡而有味","Light, and still with flavor",
 "关系里没有戏剧，这是好事。别去找戏剧。",
 "No drama in the relationship. That is good. Do not go looking for any.",
 "今天不复盘任何一次对话。","Do not replay any conversation today."),
("xiaoji","love","各安其位","Each in their own place",
 "你和对方现在需要的东西不一样。不是谁错，是时间不同步。",
 "You and they need different things right now. Nobody is wrong; the clocks differ.",
 "说一句「我今天需要的是……」，只说自己的。","Say one sentence starting 'what I need today is', and speak only for yourself."),
("xiaoji","love","静待花开","Wait quietly for the flower",
 "对方还没准备好，而催是最没用的事。你的耐心是有期限的，但还没到。",
 "They are not ready, and pushing is the least useful thing. Your patience has a limit; it is not here yet.",
 "把注意力放回一个自己的爱好上，一小时。","Put an hour back into something that is yours alone."),
("xiaoji","love","一笑相逢","Meeting with a smile",
 "会有一个让你舒服的照面。可能是陌生人，可能是老朋友。",
 "A pleasant encounter is coming. Maybe a stranger, maybe an old friend.",
 "今天对一个人说一句真的赞美。","Give one true compliment today."),
# ---------------------------------------------------------------- 小吉 · body
("xiaoji","body","起居有常","Regular hours",
 "身体不需要新办法，需要老办法。规律比努力管用。",
 "The body needs no new method, only the old one. Regular beats hard.",
 "今天三餐在固定时间吃。","Eat three meals at set times today."),
("xiaoji","body","微恙即愈","A small ailment mends itself",
 "有点不舒服，但会过去。别硬撑，也别过度解读。",
 "Slightly off, and it will pass. Do not push through, and do not over-read it.",
 "今天少排一件事，把空出来的时间用来躺着。","Drop one thing from today and lie down in the time it frees."),
("xiaoji","body","舒筋活络","Loosen the sinews",
 "僵的不是身体，是你坐了太久。站起来就好一半。",
 "It is not stiffness; it is sitting. Standing up fixes half of it.",
 "每工作五十分钟，站起来伸展两分钟。","Every fifty minutes of work, stand and stretch for two."),
("xiaoji","body","心宽体安","A wide heart, an easy body",
 "身体的紧张是从脑子来的。先处理脑子那头。",
 "The body's tension starts in the head. Deal with the head first.",
 "把今天最担心的事写在纸上，然后把纸合上。","Write today's biggest worry on paper, then fold the paper closed."),
# ---------------------------------------------------------------- 小吉 · study
("xiaoji","study","勤能补拙","Effort patches what talent lacks",
 "你不比别人慢，只是没别人熟。熟是可以练的。",
 "You are not slower than others, just less practiced. Practice is available.",
 "把最基础的那一组题再做一遍。","Do the most basic set of exercises once more."),
("xiaoji","study","一日一课","One lesson a day",
 "别贪多。今天弄懂一个概念，比翻十页强。",
 "Do not be greedy. One concept understood today beats ten pages turned.",
 "只学一个概念，能用自己的话说出来就停。","Learn one concept. When you can say it in your own words, stop."),
("xiaoji","study","不进则退","Stand still and you slide back",
 "这周落下一点，但还追得上。别让它变成两周。",
 "You slipped a little this week, still catchable. Do not let it become two weeks.",
 "今天补十五分钟，明天再补十五分钟。","Make up fifteen minutes today, and fifteen tomorrow."),
("xiaoji","study","书山有径","There is a path up the mountain of books",
 "你缺的是方法，不是时间。找一个学过的人问一句。",
 "What you lack is method, not time. Ask one person who has done it before.",
 "给一个学过这门的人发一条具体的问题。","Send one specific question to someone who has studied this."),
# ---------------------------------------------------------------- 小吉 · traveler
("xiaoji","traveler","音信稍迟","Word comes a little late",
 "回复会来，比你想的晚。晚不代表冷。",
 "The reply comes, later than you hoped. Late does not mean cold.",
 "今天定一个「不看手机」的时段，两小时。","Set a two-hour block today when you do not look at your phone."),
("xiaoji","traveler","隔水相望","Looking across the water",
 "对方也在等，只是你们都在等对方先开口。",
 "They are waiting too. You are both waiting for the other to speak first.",
 "先发一句。就一句。","Send the first line. Just one."),
("xiaoji","traveler","且待时日","Give it some days",
 "这件事不该由你催。给它一周。",
 "This is not yours to hurry. Give it a week.",
 "在日历上标一个七天后的日期，到那天再想。","Mark a date seven days from now. Think about it then."),
("xiaoji","traveler","小别重逢","A short parting, then meeting",
 "分开的时间比你以为的短。别把它想成永别。",
 "The separation is shorter than it feels. Do not dress it as a goodbye.",
 "把想给对方看的东西存进一个相册。","Save the things you want to show them into one album."),
# ---------------------------------------------------------------- 末吉 · work
("moji","work","且行且看","Walk, and watch as you walk",
 "没什么大事，也没什么好事。这周做完该做的，就够了。",
 "Nothing big, nothing bright. Doing what must be done is enough this week.",
 "把明天的待办写好再下班。","Write tomorrow's list before you finish today."),
("moji","work","事缓则圆","Slowed, a thing rounds itself",
 "你想赶的那个节点赶不上，但赶不上比赶坏了强。",
 "The deadline you want to hit, you will miss. Missing beats botching.",
 "今天主动说一句「需要多两天」。","Say 'I need two more days' today, before being asked."),
("moji","work","独木难支","One beam cannot hold the roof",
 "你一个人在扛的东西太多了。不是你不行，是不该一个人。",
 "You are carrying too much alone. Not because you are weak; because it was never a one-person job.",
 "把一件事交出去，说清楚交给谁、什么时候要。","Hand one task to someone, with a name and a date."),
("moji","work","前路微明","Faint light on the road ahead",
 "方向大致对，细节还模糊。别急着确认，先走一段。",
 "The direction is roughly right; the details are blurred. Walk a while before you decide.",
 "今天推进一小步，不做决定。","Take one small step today. Decide nothing."),
# ---------------------------------------------------------------- 末吉 · money
("moji","money","收支相抵","Income meets outgo",
 "不亏不赚。这样的月份多的是，别为它焦虑。",
 "Neither gain nor loss. Months like this are common; do not fret over it.",
 "看一眼账户余额，然后关掉，今天不再看。","Look at the balance once, close it, and do not look again today."),
("moji","money","勿贪小利","Do not chase small gains",
 "有个看起来划算的机会，其实是在花你的时间。",
 "A deal that looks good is really spending your time.",
 "今天不点任何「限时」的东西。","Click nothing marked 'limited time' today."),
("moji","money","惜物如金","Treasure things like gold",
 "钱紧一点，但东西够用。修比换省，用比买省。",
 "Money is tight but you have what you need. Repair beats replace; use beats buy.",
 "修好一样坏了的小东西。","Fix one small broken thing."),
("moji","money","有借有还","What is borrowed is returned",
 "一笔小的往来要清一清。数目不大，拖着难受。",
 "A small debt, either way, wants settling. Not much, but it itches.",
 "把欠的或被欠的那笔小钱，今天清掉。","Settle the small sum you owe or are owed today."),
# ---------------------------------------------------------------- 末吉 · love
("moji","love","相看两忘","Looking, and forgetting to speak",
 "你们最近都在忙，没在看对方。不是问题，但要留意。",
 "You have both been busy and not looking at each other. Not a problem yet; worth noticing.",
 "今天问对方一个你不知道答案的问题。","Ask them one question you do not know the answer to."),
("moji","love","缘分未定","The thread not yet tied",
 "现在的这段还看不出去向。去向不由你一个人决定。",
 "Where this goes is not yet visible, and not yours alone to decide.",
 "今天不评估这段关系，只过一天。","Do not evaluate the relationship today. Just live the day."),
("moji","love","各自安好","Each one well, apart",
 "分开的两个人都过得不差。这是你能得到的最好的消息。",
 "Both people, apart, are doing all right. That is the best news available.",
 "把留着的一件对方的东西收进箱子，不扔。","Put one thing of theirs you kept into a box. Do not throw it away."),
("moji","love","话到嘴边","Words at the edge of the mouth",
 "有句话你想说很久了。不是说不说的问题，是怎么说。",
 "There is something you have wanted to say for a long time. The question is not whether; it is how.",
 "把那句话写下来，念一遍，明天再决定。","Write it down, read it aloud once, decide tomorrow."),
# ---------------------------------------------------------------- 末吉 · body
("moji","body","劳逸失度","Work and rest out of measure",
 "累是累了，还没到伤的地步。现在调，就不用后面修。",
 "Tired, yes; not yet worn. Adjust now and there is nothing to repair later.",
 "今天最后一件工作在晚上八点前结束。","Finish the last work of today before eight."),
("moji","body","风寒宜避","Keep out of the cold wind",
 "身体在提醒你换季了。不需要药，需要一件外套。",
 "The body is telling you the season changed. Not medicine; a coat.",
 "出门带一件外套，哪怕看起来不需要。","Take a jacket when you go out, even if it looks unnecessary."),
("moji","body","忧思伤神","Worry wears the spirit",
 "你的疲惫有一半是想出来的。想的那一半，可以放下。",
 "Half your tiredness is thought. The thinking half can be set down.",
 "今晚睡前把明天的三件事写下来，然后不再想。","Before bed, write tomorrow's three things, then stop thinking about them."),
("moji","body","饮食宜清","Eat light",
 "最近吃得杂。不是要节制，是要简单。",
 "You have been eating all over the place. Not restraint; simplicity.",
 "今天一顿饭只做一样菜。","Cook one dish, and only one, for a meal today."),
# ---------------------------------------------------------------- 末吉 · study
("moji","study","心浮气躁","A floating mind, an unsettled breath",
 "坐不住是这几天的常态。别怪自己，换个短一点的目标。",
 "Restlessness is the mood of these days. Do not blame yourself; shorten the goal.",
 "把学习单位改成十分钟，做完一个再说。","Cut the study unit to ten minutes. Do one, then see."),
("moji","study","似懂非懂","Half-understood",
 "你以为学会的地方其实没会。现在发现比考试时发现强。",
 "What you think you know, you do not quite. Finding out now beats finding out in the exam.",
 "合上书，把那一章的要点默写出来。","Close the book and write the chapter's key points from memory."),
("moji","study","事倍功半","Double the work, half the result",
 "方法不对，越努力越累。停一下，换个法子。",
 "The method is wrong, so effort makes tiredness. Stop and change method.",
 "换一种学法，今天用听的，或者用讲的。","Switch mode today: listen instead of read, or explain instead of review."),
("moji","study","小考失意","A small test disappoints",
 "一次不理想的结果，说明的是那一次，不是你。",
 "One poor result speaks about that one time, not about you.",
 "看错题，只看错题，找出错在哪一步。","Look at the wrong answers only, and find the step where each went wrong."),
# ---------------------------------------------------------------- 末吉 · traveler
("moji","traveler","音书未至","No letter yet",
 "还没消息。没消息不是坏消息，是没消息。",
 "No word yet. No news is not bad news; it is no news.",
 "今天把等消息的时间拿去做一件你自己的事。","Spend the waiting time today on something of your own."),
("moji","traveler","路遥且滞","The road is long and slow",
 "对方遇到了拖延，跟你无关。你能做的是别再加一层。",
 "They are delayed by something that is not you. All you can do is not add a layer.",
 "今天不追问。","Do not chase today."),
("moji","traveler","心有所念","Something held in mind",
 "你想那个人的时间，比那个人知道的多。这不是坏事，但别只是想。",
 "You think of them more than they know. Not bad, but do not only think.",
 "写一封不发的信，写完存起来。","Write a letter you will not send. Keep it."),
("moji","traveler","去者不追","Do not chase what has gone",
 "有些人走了就是走了。不是你的错，也不是你的功课。",
 "Some people, once gone, are gone. Not your fault, and not your homework.",
 "把那个对话框置底或归档。不删。","Move that chat to the bottom, or archive it. Do not delete it."),
# ---------------------------------------------------------------- 凶 · work
("xiong","work","逆水行舟","Rowing against the current",
 "这周每一步都费力。不是你错了，是水在往回流。省着劲用。",
 "Every step is heavy this week. You are not wrong; the water is running backward. Spend your strength carefully.",
 "把今天的目标砍掉一半，做完剩下的一半。","Cut today's goal in half and finish the half that is left."),
("xiong","work","时机未至","The hour has not come",
 "你想做的事是对的，只是现在做会白做。等一个信号。",
 "The thing you want to do is right; doing it now wastes it. Wait for one signal.",
 "写下你在等的那个信号是什么，具体到能认出来。","Write down what signal you are waiting for, specifically enough to recognize it."),
("xiong","work","多言招损","Many words invite loss",
 "这周说得越多，越被误会。把话留给该听的人。",
 "The more you say this week, the more you are misread. Keep words for the one who should hear them.",
 "今天开会少说一半。","Say half as much in today's meetings."),
("xiong","work","独行雾中","Walking alone in fog",
 "你看不清方向，而周围的人也没看清。不必假装看清了。",
 "You cannot see the way, and neither can the people around you. No need to pretend.",
 "今天问一个人「你怎么看」，然后只听。","Ask one person 'how do you see it', then only listen."),
# ---------------------------------------------------------------- 凶 · money
("xiong","money","入不敷出","Outgo exceeds income",
 "这个月的钱往外走得比进来快。这是可以算清的事，算清就不可怕。",
 "Money leaves faster than it arrives this month. It is a thing that can be counted, and counted it is not frightening.",
 "今天把这个月的支出列一遍，哪怕不准。","List this month's spending today, even roughly."),
("xiong","money","勿轻许诺","Promise nothing lightly",
 "有人会要你的钱、或你的担保。这周说「让我想想」。",
 "Someone will ask for your money or your name on a promise. This week, say 'let me think'.",
 "对任何金钱上的请求，回答「明天答复你」。","To any money request, answer 'I'll tell you tomorrow'."),
("xiong","money","小失可忍","A small loss can be borne",
 "会丢一笔小钱，或买错一样东西。认了，比追回来省心。",
 "You will lose a small sum or buy the wrong thing. Accepting it costs less than chasing it.",
 "今天不买任何超过一顿饭钱的东西。","Buy nothing today that costs more than a meal."),
("xiong","money","守多于攻","Guard more than you strike",
 "这不是进取的时候。守住底线，比抓住机会重要。",
 "Not a time for gains. Holding your floor matters more than catching a chance.",
 "把「不能动」的那笔钱写下来，放在看得见的地方。","Write down the sum that must not be touched, and keep the note visible."),
# ---------------------------------------------------------------- 凶 · love
("xiong","love","言语相伤","Words cut both ways",
 "这几天容易吵。吵的多半是累，不是这段关系。先处理累。",
 "It is easy to quarrel these days. Most of it is tiredness, not the relationship. Deal with the tiredness first.",
 "今天不谈重要的事。困了就说困了。","Discuss nothing important today. If tired, say tired."),
("xiong","love","独坐空堂","Sitting alone in an empty hall",
 "孤单会在这周变得明显。它是真实的，也是暂时的。",
 "Loneliness gets loud this week. It is real, and it is temporary.",
 "今天约一个朋友，不是那个人，是朋友。","Make plans with a friend today. Not that person; a friend."),
("xiong","love","缘浅莫强","A thin thread should not be pulled",
 "你在用力维持的这段，对方没在用力。用力的一方总是先累。",
 "You are working to hold this, and they are not. The one who works tires first.",
 "这周不主动发起。看看没有你的推动，它会不会自己动。","Do not initiate this week. See if it moves without your push."),
("xiong","love","旧事重提","Old matters brought up again",
 "过去的事会被翻出来。别接那个茬，它不是今天的问题。",
 "Something old gets raised. Do not take the bait; it is not today's problem.",
 "对翻旧账的话，只回一句「我们说今天的事」。","To old grievances, answer only: 'let's talk about today'."),
# ---------------------------------------------------------------- 凶 · body
("xiong","body","强弩之末","An arrow at the end of its flight",
 "你在硬撑。撑得住，不代表该撑。这周必须停一次。",
 "You are running on will. Being able to is not a reason to. Stop once this week.",
 "今天取消一件不是必须的事。","Cancel one thing today that is not essential."),
("xiong","body","夜不能寐","Night without sleep",
 "睡眠这几天会差。不要靠手机熬，靠早一点躺下。",
 "Sleep will be poor for a few days. Do not ride it out on your phone; go to bed earlier.",
 "今晚屏幕十点关，哪怕睡不着也躺着。","Screens off at ten tonight. Lie down even if sleep does not come."),
("xiong","body","身心俱疲","Body and mind both worn",
 "累到一个程度，做什么都没效率。这周的任务是恢复，不是产出。",
 "Past a certain tiredness nothing is efficient. This week's job is recovery, not output.",
 "把今天的任务清单只留一项。","Leave only one item on today's list."),
("xiong","body","忌逞一时","Do not spend the moment's strength",
 "别在这几天做超过平时的运动或熬夜。身体这周只有一份力气。",
 "Do not push exercise or late nights this week. The body has one measure of strength, no more.",
 "今天的运动量减半，时间给拉伸。","Halve today's workout and give the time to stretching."),
# ---------------------------------------------------------------- 凶 · study
("xiong","study","临渴掘井","Digging the well when thirsty",
 "时间已经不够了。承认这一点，然后只学最重要的。",
 "There is not enough time left. Admit it, then learn only what matters most.",
 "列出考试范围里最值分的三块，其他的放掉。","List the three highest-value parts of the exam. Let the rest go."),
("xiong","study","心不在焉","The mind is elsewhere",
 "这几天读不进去，因为你在想别的事。先把别的事放好。",
 "Nothing goes in these days because you are thinking of something else. Set that something down first.",
 "把让你分心的那件事写在纸上，标上「考完再说」。","Write the distraction on paper and label it 'after the exam'."),
("xiong","study","欲速不达","Hurry, and you do not arrive",
 "赶进度只会让你忘得更快。慢下来的一周，比赶的一周记得多。",
 "Rushing makes you forget faster. A slow week remembers more than a rushed one.",
 "今天只复习，不学新的。","Today, review only. Nothing new."),
("xiong","study","独学无友","Learning alone, without a friend",
 "你困在一个地方太久了，因为没人告诉你困在哪。",
 "You have been stuck too long because nobody told you where you are stuck.",
 "把卡住的地方发给一个人，哪怕只是问「这个正常吗」。","Send the stuck part to someone, even if only to ask 'is this normal?'"),
# ---------------------------------------------------------------- 凶 · traveler
("xiong","traveler","杳无音信","No word at all",
 "这周不会有消息。不是永远，是这周。别把这周当成永远。",
 "No word this week. Not never; this week. Do not confuse the two.",
 "今天把等消息的时间用来收拾一个抽屉。","Use the waiting time today to clear one drawer."),
("xiong","traveler","归期未定","The date of return is not fixed",
 "对方回不回、什么时候回，现在没人知道，包括对方。",
 "Whether they return, and when, nobody knows right now, including them.",
 "把「等」换成一个有截止日的计划，写下来。","Replace 'waiting' with a plan that has an end date. Write it down."),
("xiong","traveler","错过一程","Missed by one stretch",
 "会有一次错过——一个电话、一个时间。不是命，是巧。",
 "There will be one miss: a call, a time. Not fate; coincidence.",
 "留一条清楚的话给对方，说你什么时候方便。","Leave them a clear message saying when you are free."),
("xiong","traveler","风波在途","Rough water on the road",
 "对方那边不顺，所以没顾上你。这不是关于你的。",
 "Things are rough on their side, so they have not had room for you. This is not about you.",
 "发一句「不用回，只是想到你」。","Send one line: 'no need to reply, just thinking of you'."),
# ---------------------------------------------------------------- 大凶 · work
("daxiong","work","山穷水尽","The mountain ends, the water ends",
 "这条路走到头了。走到头不是失败，是该换路的地方。",
 "This road has run out. Running out is not failure; it is where the road changes.",
 "写下三条其他的路，哪怕都不喜欢。","Write down three other roads, even if you like none of them."),
("daxiong","work","覆水难收","Spilt water cannot be gathered",
 "一件事已经错了，改不回来。你能改的只有下一件。",
 "Something has already gone wrong and cannot be undone. All you can change is the next thing.",
 "对那件事说一句「我知道了」，然后开始下一件。","Say 'noted' to the thing that went wrong, then start the next one."),
("daxiong","work","四面楚歌","Songs of the enemy on every side",
 "这周会觉得所有人都在反对你。多半不是所有人，是三个。找到那三个。",
 "This week it will feel like everyone is against you. It is probably three people. Find the three.",
 "写下具体谁、具体什么事。不写「所有人」。","Write who, and what, specifically. Never write 'everyone'."),
("daxiong","work","百事不宜","Nothing is favored",
 "这几天做什么都不顺。那就什么都别开新的，只收尾。",
 "Nothing goes right these days. Then start nothing; only finish.",
 "今天只做「收尾」类的事：回复、归档、关闭。","Do only closing work today: replies, filing, shutting things down."),
# ---------------------------------------------------------------- 大凶 · money
("daxiong","money","破财在前","A loss lies ahead",
 "会有一笔不小的支出，多半是躲不掉的那种。提前知道，就不是意外。",
 "A sizable expense is coming, likely the unavoidable kind. Known ahead, it is not a shock.",
 "今天把应急的那笔钱确认一遍在哪、有多少。","Confirm today where your emergency money is and how much."),
("daxiong","money","贪则必失","Greed guarantees loss",
 "这周任何「稳赚」的东西都不要碰。越稳越危险。",
 "Touch nothing this week that promises a sure gain. The surer, the worse.",
 "对任何人提出的赚钱机会，一律说不。","Say no to every money opportunity anyone offers this week."),
("daxiong","money","债台高筑","Debt piled high",
 "欠的比你愿意看的多。不看它不会少。看了，它就开始少。",
 "You owe more than you want to look at. Not looking does not shrink it. Looking does.",
 "把所有欠款列在一张纸上，总数写在最下面。","List every debt on one page, total at the bottom."),
("daxiong","money","空囊难行","An empty purse cannot travel",
 "这个月钱到不了你想去的地方。那就先不去。",
 "The money will not reach where you want to go this month. Then do not go yet.",
 "把那个计划推迟三十天，写上新日期。","Postpone the plan thirty days and write the new date."),
# ---------------------------------------------------------------- 大凶 · love
("daxiong","love","镜破难圆","A broken mirror does not round again",
 "有一段关系到了尽头。承认它比修它更需要勇气。",
 "A relationship has reached its end. Admitting that takes more courage than mending it.",
 "今天对自己说一遍：它结束了。只说一遍。","Tell yourself once today: it is over. Just once."),
("daxiong","love","形单影只","One body, one shadow",
 "这周你会非常想要一个人，而那个人不会出现。这是要熬的，不是要解决的。",
 "This week you will badly want someone, and they will not appear. This is to be endured, not solved.",
 "今晚早点睡。孤单在睡着的时候最短。","Go to bed early tonight. Loneliness is shortest asleep."),
("daxiong","love","错付真心","A true heart, misplaced",
 "你给的比对方要的多。这不是对方的错，也不是你的。是配错了。",
 "You gave more than they wanted. Not their fault, not yours. A mismatch.",
 "这周不送任何东西，不请任何客。","Give nothing and treat no one this week."),
("daxiong","love","各奔东西","Each goes their own way",
 "分开正在发生。你能决定的，只是分开的样子。",
 "The parting is happening. All you decide is what the parting looks like.",
 "写下你希望对方记得你的一句话。不发。","Write the one line you want them to remember you by. Do not send it."),
# ---------------------------------------------------------------- 大凶 · body
("daxiong","body","油尽灯枯","The oil spent, the lamp dry",
 "你已经透支很久了。这周不休息，下周就由不得你。",
 "You have been overdrawn a long time. If you do not rest this week, next week will rest you.",
 "今天请一个假，或者取消整个晚上。","Take a day off today, or cancel the whole evening."),
("daxiong","body","积劳成疾","Long labor makes illness",
 "疲劳在往一个方向积累。它不是一天造成的，也不能一天解决，但今天可以是第一天。",
 "Tiredness is piling in one direction. Not made in a day, not undone in one; today can be the first.",
 "今晚睡满八小时，其他什么都不做。","Sleep a full eight hours tonight and do nothing else."),
("daxiong","body","心力交瘁","Heart and strength both spent",
 "撑到这里已经很不容易了。放下一件事，不是放弃，是换手。",
 "Getting this far took a lot. Setting one thing down is not quitting; it is changing hands.",
 "对一个人说「我这周撑不住了」。","Tell one person: 'I can't hold this up this week'."),
("daxiong","body","忌动宜静","Stillness, not motion",
 "这周身体不听你的。不要跟它较劲，输的是你。",
 "The body is not taking orders this week. Do not fight it; you lose.",
 "今天不运动，不熬夜，不喝多。三件事，做到两件。","No exercise, no late night, no heavy drinking today. Three things; manage two."),
# ---------------------------------------------------------------- 大凶 · study
("daxiong","study","名落孙山","The name falls below the list",
 "这一轮的结果不会好。它决定的是这一轮，你的下一轮从今天开始。",
 "This round will not go well. It decides this round only; your next one starts today.",
 "把这次学到的三条教训写下来，贴在墙上。","Write three lessons from this round and put them on the wall."),
("daxiong","study","荒废时日","Days let go to waste",
 "过去几周确实丢了。丢了就丢了，不用为它再丢一周。",
 "The past weeks are really lost. Lost is lost; do not lose another one to regret.",
 "今天只做一件事：把书打开，读一页。","Do one thing today: open the book and read one page."),
("daxiong","study","力有不逮","Strength falls short",
 "这门课的难度暂时超过你现在的准备。暂时。",
 "This subject is beyond your current preparation. Currently.",
 "找到这门课的先修内容，从那里开始。","Find the prerequisite for this subject and start there."),
("daxiong","study","孤灯难明","One lamp cannot light the hall",
 "一个人硬学是学不过来的。这周要找人，不是找书。",
 "Grinding alone will not cover it. This week, find people, not books.",
 "报一个学习小组，或者约一个人一起自习。","Join a study group, or arrange to study alongside one person."),
# ---------------------------------------------------------------- 大凶 · traveler
("daxiong","traveler","人去楼空","The person gone, the house empty",
 "你等的人不会回来了，至少不会以你等的方式。",
 "The one you wait for is not coming back, at least not in the way you are waiting.",
 "把那个人的东西收起来一样。只一样。","Put away one thing of theirs. Only one."),
("daxiong","traveler","音尘断绝","Even the dust of news has stopped",
 "消息断了，而且这次不是延迟。你的等待可以结束了。",
 "The line has gone quiet, and this time it is not a delay. Your waiting can end.",
 "今天把等待写成一句话，然后去做别的。","Write the waiting down as one sentence today, then do something else."),
("daxiong","traveler","天各一方","Each at a far corner of the sky",
 "距离已经不是路程，是生活。两个生活很难再重叠。",
 "The distance is no longer miles; it is lives. Two lives rarely overlap again.",
 "给对方一句祝福，不问近况。","Send one line of good wishes. Ask nothing."),
("daxiong","traveler","独行远路","Walking the long road alone",
 "接下来的一段你要一个人走。你走得了，只是没人告诉你可以。",
 "The next stretch you walk alone. You can; nobody told you so, that is all.",
 "今天为自己做一件平时是别人替你做的事。","Do one thing for yourself today that someone else used to do for you."),
# ---------------------------------------------------------------- extras
("daji","work","否极泰来","After the worst, the turn",
 "最难的那段已经过去了。你没注意到，因为你还在用最难时的力气。",
 "The hardest part is already behind you. You did not notice because you are still spending the strength it took.",
 "今天把工作时间缩短一小时，看看会不会有事。","Cut today's working hours by one, and see if anything breaks."),
("zhongji","money","日进有度","Gains that come in measure",
 "钱在按你的节奏进来。别为了快一点，把节奏打乱。",
 "Money arrives at your pace. Do not break the pace to make it faster.",
 "今天不看任何理财的内容。","Read nothing about investing today."),
("xiaoji","love","旧友来访","An old friend visits",
 "会有人主动找你聊天，不是恋爱的那种。那种也很好。",
 "Someone will reach out to talk. Not the romantic kind. That kind is also good.",
 "把这段对话当成今天最重要的事。","Treat that conversation as the most important thing today."),
("moji","body","乍暖还寒","Warm, then cold again",
 "身体状态忽好忽坏，是季节，不是你。",
 "Good days and bad days alternate. That is the season, not you.",
 "今天按最坏的那天安排，好的话算赚到。","Plan today as if it were a bad day. If it is good, you are ahead."),
("xiong","study","书到用时","Books needed when they are not read",
 "你会发现某个基础没打好。现在补，比装作有强。",
 "You will find a foundation that was never laid. Laying it now beats pretending it is there.",
 "找到那个基础，今天只学它。","Find that foundation and study only it today."),
("daxiong","work","釜底抽薪","The fire pulled from under the pot",
 "支撑你的那样东西会被拿走：预算、人、时间。这是最坏的消息，也是最清楚的。",
 "The thing holding you up gets taken: a budget, a person, time. The worst news, and the clearest.",
 "列出没有那样东西的话，你还能做什么。写三条。","List what you can still do without it. Three lines."),
]
