# The 78-card pool, written by hand (2026-09-18). Per card:
#   (slug, name_en, name_zh, numeral, glyph, tier,
#    up_zh, up_en, up_do_zh, up_do_en,
#    rev_zh, rev_en, rev_do_zh, rev_do_en)
# tier: bright | major | court | pip | hard — the rank ladder picks a tier and an
# orientation (scripts/fortune.gd RANK_TIERS). Same house rules as the slips: a reversed
# card speaks about effort, timing and attention; nothing about strangers, harm or money
# advice. The art slots in later by slug: assets/tarot/<slug>.webp.

MAJORS = [
("the-fool","The Fool","愚者","0","❀","major",
 "一个开始，什么都还没定。不知道是正常的，走就是了。","A beginning, with nothing decided. Not knowing is normal. Walk.",
 "今天做一件没做过的小事。","Do one small thing you have never done."),
("the-magician","The Magician","魔术师","I","∴","bright",
 "你手上的工具够了。缺的不是资源，是开始。","You have the tools you need. Not resources; a start.",
 "把想做的事拆成第一步，今天只做这一步。","Cut the thing you want to do down to a first step, and do only that."),
("the-high-priestess","The High Priestess","女祭司","II","☯","major",
 "答案你已经知道，只是还没承认。安静一会儿。","You already know the answer; you have not admitted it. Be quiet a while.",
 "今天有十分钟不看任何屏幕，只坐着。","Spend ten minutes today with no screen, just sitting."),
("the-empress","The Empress","皇后","III","♀","bright",
 "东西在长。不用催，给它水和时间。","Something is growing. Do not hurry it; give it water and time.",
 "照顾一样活的东西：植物、人、或者你自己。","Tend one living thing: a plant, a person, or yourself."),
("the-emperor","The Emperor","皇帝","IV","♂","major",
 "该定规矩了。不是对别人，是对自己的一天。","Time to set rules. Not for others; for your own day.",
 "给今天定一个开始和结束的时间，照做。","Give today a start time and an end time, and keep both."),
("the-hierophant","The Hierophant","教皇","V","✚","major",
 "老办法这次是对的。别急着创新，先学会规矩。","The old way is right this time. Learn the rules before you bend them.",
 "找一份现成的方法或教程，照着做一次。","Find an existing method or tutorial and follow it once."),
("the-lovers","The Lovers","恋人","VI","♡","bright",
 "一个选择，和一个人有关。选你能和它一起过一年的那个。","A choice, with a person in it. Pick the one you could live with for a year.",
 "把两个选项各写三行，看哪个写得顺。","Write three lines for each option. See which one writes easily."),
("the-chariot","The Chariot","战车","VII","⌘","major",
 "方向定了，就别再犹豫。速度来自不回头。","The direction is set; stop reconsidering. Speed comes from not looking back.",
 "今天推进那件事一小时，不查别的。","Push that one thing for an hour today, checking nothing else."),
("strength","Strength","力量","VIII","∞","bright",
 "你比这件事强，只是方式要软。硬来就输。","You are stronger than this thing, but the way is soft. Force loses.",
 "对今天最难的那个人，说一句好话。","Say one kind thing to the hardest person in your day."),
("the-hermit","The Hermit","隐者","IX","☆","major",
 "需要一个人待一会儿。这不是逃避，是补给。","You need to be alone a while. Not escape; resupply.",
 "今晚一个人吃饭，不带手机。","Eat alone tonight, without your phone."),
("wheel-of-fortune","Wheel of Fortune","命运之轮","X","◉","bright",
 "在转。你没法控制转向，但能选站的位置。","It is turning. You cannot steer it, but you can choose where to stand.",
 "把你能控制的三件事写下来，只管这三件。","Write down three things you control. Manage only those."),
("justice","Justice","正义","XI","♁","major",
 "会得到一个公平的结果。公平不等于满意。","You will get a fair outcome. Fair is not the same as pleasing.",
 "今天把一件欠人的事补上。","Settle one thing you owe someone today."),
("the-hanged-man","The Hanged Man","倒吊人","XII","⊙","major",
 "卡住了，而卡住是有用的。换个角度看，别挣扎。","Stuck, and the stuckness is useful. Look from another angle; do not thrash.",
 "把问题倒过来问：如果我什么都不做，会怎样？","Ask the question backward: what happens if I do nothing?"),
("death","Death","死神","XIII","†","hard",
 "有件事结束了。真的结束了，不是暂停。腾出来的地方，是给下一件的。","Something has ended. Truly ended, not paused. The space it leaves is for the next thing.",
 "扔掉一样你留着但已经没用的东西。","Throw out one thing you have kept that no longer serves."),
("temperance","Temperance","节制","XIV","≈","bright",
 "调一调比例。不是多或少，是两样东西的比例。","Adjust the ratio. Not more or less; the proportion of two things.",
 "今天工作和休息各安排一半，看哪一半做到了。","Plan half work and half rest today, and see which half you actually keep."),
("the-devil","The Devil","恶魔","XV","⊗","hard",
 "有个习惯在管你。它不可怕，但它在管你。看清就好。","A habit is running you. Not frightening, but it is in charge. Seeing it is enough.",
 "把你今天最不想承认的那个习惯写下来。","Write down the habit you least want to admit to today."),
("the-tower","The Tower","高塔","XVI","♯","hard",
 "有个结构要塌。它本来就撑不住，塌是清算，不是惩罚。","A structure is falling. It was never going to hold; the fall is a reckoning, not a punishment.",
 "今天不修那个东西。看它塌完。","Do not patch that thing today. Let it finish falling."),
("the-star","The Star","星星","XVII","★","bright",
 "最难的过去了。现在是一小段安静的好日子，用来恢复。","The hardest part is over. A short quiet stretch is here, for recovery.",
 "做一件对未来的自己好的小事，不求回报。","Do one small thing for your future self, expecting nothing."),
("the-moon","The Moon","月亮","XVIII","〇","hard",
 "看不清，而且你的想象在填空。别在夜里做决定。","You cannot see clearly, and imagination is filling the gaps. Decide nothing at night.",
 "把今天的判断推到明早再下。","Push today's judgement to tomorrow morning."),
("the-sun","The Sun","太阳","XIX","☉","bright",
 "简单的好日子。不需要解读，出去晒。","A simple good day. Nothing to interpret; go outside.",
 "在太阳底下待二十分钟。","Spend twenty minutes in the sun."),
("judgement","Judgement","审判","XX","♪","major",
 "有个声音在叫你做某件事。你听见了，装没听见没用。","Something is calling you to a task. You heard it; pretending otherwise does not work.",
 "回应那件你一直知道该做的事，迈第一步。","Answer the thing you have always known needs doing. Take the first step."),
("the-world","The World","世界","XXI","◎","bright",
 "一个圈画完了。庆祝一下，再开始下一个。","A circle is complete. Celebrate before you start the next.",
 "写下这一段你做成的三件事。","Write down three things you finished in this stretch."),
]

# minors: (rank_word, glyph_suffix) built per suit
SUITS = {
 "wands":     ("Wands",     "权杖", "♧", "work and will"),
 "cups":      ("Cups",      "圣杯", "♥", "feeling"),
 "swords":    ("Swords",    "宝剑", "‡",  "thought"),
 "pentacles": ("Pentacles", "星币", "⊕", "the material"),
}
RANKS = ["ace","two","three","four","five","six","seven","eight","nine","ten","page","knight","queen","king"]
RANK_EN = {"ace":"Ace","two":"Two","three":"Three","four":"Four","five":"Five","six":"Six","seven":"Seven","eight":"Eight","nine":"Nine","ten":"Ten","page":"Page","knight":"Knight","queen":"Queen","king":"King"}
RANK_ZH = {"ace":"一","two":"二","three":"三","four":"四","five":"五","six":"六","seven":"七","eight":"八","nine":"九","ten":"十","page":"侍从","knight":"骑士","queen":"王后","king":"国王"}
RANK_NUM = {"ace":"A","two":"2","three":"3","four":"4","five":"5","six":"6","seven":"7","eight":"8","nine":"9","ten":"10","page":"P","knight":"Kn","queen":"Q","king":"K"}

# (suit, rank): (tier, up_zh, up_en, do_zh, do_en)
MINOR_UP = {
("wands","ace"):("pip","一个新念头，热的。趁热写下来。","A new idea, still hot. Write it down while it is.","把那个念头写成一句话，发给自己。","Write the idea as one sentence and send it to yourself."),
("wands","two"):("pip","站在门口看外面。计划可以做了，先别出发。","Standing at the door, looking out. Plan now; do not leave yet.","画一张三个月的路线图。","Draw a three-month map."),
("wands","three"):("pip","船已经出去了。现在是等，等的时候做别的。","The ships are out. Now you wait, and while waiting, do other things.","把等结果的时间用在第二件事上。","Put the waiting time into a second project."),
("wands","four"):("bright","一个小的落成。可以停一晚庆祝。","A small completion. Stop for an evening and mark it.","今晚和人一起吃饭。","Have dinner with someone tonight."),
("wands","five"):("pip","吵，但没人真的在打。是练习，不是战争。","Noise, but nobody is really fighting. Practice, not war.","今天的争论只提一个观点，然后听。","Offer one point in today's argument, then listen."),
("wands","six"):("bright","被看见了。接受它，别解释。","You are seen. Accept it; do not explain it away.","有人夸你的时候，只说「谢谢」。","When praised, say only 'thank you'."),
("wands","seven"):("pip","站得住，但要一直站。这周是防守周。","You can hold, but you must keep holding. A defensive week.","对一件要占你时间的事说不。","Say no to one thing that wants your time."),
("wands","eight"):("pip","事情忽然快了。跟上，别问为什么。","Things speed up suddenly. Keep up; do not ask why.","今天回复所有等着的消息，每条一句。","Answer every waiting message today, one line each."),
("wands","nine"):("pip","累，但还在。最后一段是最难的，也是最短的。","Tired, and still standing. The last stretch is the hardest and the shortest.","把终点写下来，贴在看得见的地方。","Write down the finish line and put it where you can see it."),
("wands","ten"):("hard","背的太多了。不是不能背，是不该。","Too much on your back. Not that you cannot; you should not.","放下一件，今天就放。","Set one thing down. Today."),
("wands","page"):("court","一个消息，让你想动。可以动，动小一点。","A message that makes you want to move. Move, but small.","把那个冲动写成一个二十分钟的实验。","Turn the impulse into a twenty-minute experiment."),
("wands","knight"):("court","冲劲很足，方向不太清。先定方向。","Plenty of drive, unclear direction. Set the direction first.","出发前写下你要去哪，一句话。","Before you start, write where you are going. One line."),
("wands","queen"):("court","你现在是那个让人愿意跟着的人。用好这个。","Right now you are someone people want to follow. Use it well.","今天带一个人做一件事，不是指挥，是一起。","Bring one person along on something today. Not orders; together."),
("wands","king"):("court","有远见的时候。定一个大方向，细节交给别人。","A far-sighted moment. Set the big direction; leave details to others.","写下一年后你希望的样子，一段话。","Write one paragraph on where you want to be in a year."),
("cups","ace"):("bright","一种新的感觉在冒出来。别分析，先感受。","A new feeling is surfacing. Do not analyze; feel it first.","今天对一个人表达一次真实的感谢。","Thank one person, truly, today."),
("cups","two"):("bright","两个人对上了。不管是什么关系，都值得珍惜。","Two people meet in the middle. Whatever the relationship, treasure it.","约一次见面，不带议程。","Arrange a meeting with no agenda."),
("cups","three"):("bright","和朋友在一起的好日子。不要推掉。","A good day with friends. Do not cancel.","联系一个你想见的朋友，定日子。","Reach out to a friend you miss and set a date."),
("cups","four"):("pip","有东西递到你面前，你没看。抬头。","Something is being offered and you are not looking. Look up.","今天认真回一个你本来想忽略的邀请。","Properly answer one invitation you meant to ignore."),
("cups","five"):("hard","失去了三样，还剩两样。你看的是三样。","Three lost, two remain. You are looking at the three.","写下还在的两样东西。","Write down the two things still here."),
("cups","six"):("pip","一件旧事让你软下来。可以怀念，别搬回去住。","Something old softens you. Remember; do not move back in.","翻一张旧照片，然后合上。","Look at one old photo, then put it away."),
("cups","seven"):("pip","选项太多，都是幻想。挑一个能明天开始的。","Too many options, all of them fantasies. Pick the one you can start tomorrow.","把选项列出来，划掉明天开始不了的。","List the options and strike out any you cannot start tomorrow."),
("cups","eight"):("pip","该走了。留下的东西不坏，只是不是你的了。","Time to leave. What you leave is not bad; it is no longer yours.","今天正式退出一个你早已不参与的群或事。","Formally leave one group or commitment you have already stopped attending."),
("cups","nine"):("bright","满足。这是你要的，你得到了。承认它。","Satisfaction. This is what you wanted and you have it. Admit it.","写下今天让你满意的一件事。","Write down one thing today that satisfied you."),
("cups","ten"):("bright","家里的好日子。什么都不用做，在场就行。","A good day at home. Nothing to do but be present.","今晚不加班，回家吃饭。","No overtime tonight. Go home for dinner."),
("cups","page"):("court","一个小的、有点幼稚的感觉。它是对的。","A small, slightly childish feeling. It is right.","做一件小时候喜欢做的事，十分钟。","Do something you loved as a child, for ten minutes."),
("cups","knight"):("court","浪漫的提议，或者你想提一个。提，但看清对方的日程。","A romantic offer, or you want to make one. Make it, but check their calendar.","约一次具体的时间地点，不说「改天」。","Propose a specific time and place. Never 'sometime'."),
("cups","queen"):("court","你在替别人接住情绪。可以，但今天也接一下自己的。","You are catching other people's feelings. Fine; catch your own today too.","问自己一次「我现在怎么样」，认真答。","Ask yourself once 'how am I', and answer honestly."),
("cups","king"):("court","有情绪但不被情绪带走。这周你是稳的那个。","Feeling, without being carried by it. This week you are the steady one.","有人激动的时候，你慢半拍再回。","When someone gets heated, wait half a beat before answering."),
("swords","ace"):("pip","看清了一件事。清楚有时候不舒服，但清楚是好的。","One thing comes clear. Clarity can sting, but clarity is good.","把想清楚的那件事写成一句话。","Write the clear thing as one sentence."),
("swords","two"):("pip","两难，你在拖。拖也是选择，而且是最差的那个。","Two options, and you are stalling. Stalling is a choice, the worst one.","定一个截止日，到那天必须选。","Set a deadline by which you must choose."),
("swords","three"):("hard","心里有一处疼，是真的。不用解释，允许它疼一天。","There is a real hurt. No explanation needed; let it hurt for a day.","今天对一个人说「我今天不太好」。","Tell one person today: 'I'm not great today'."),
("swords","four"):("pip","该休息了。不是懒，是修复。","Rest now. Not laziness; repair.","下午留一个小时什么都不排。","Leave one afternoon hour empty."),
("swords","five"):("hard","赢了一场不值得赢的架。或者输了。都一样。","You won a fight not worth winning. Or lost it. Same thing.","今天不再提那件事。","Do not bring that up again today."),
("swords","six"):("pip","在往平静的地方走。慢，但方向对。","Moving toward calmer water. Slow, but the right way.","做一件让明天更顺的准备。","Prepare one thing that makes tomorrow smoother."),
("swords","seven"):("hard","有人在绕着走，可能是你。直一点省力。","Someone is going around instead of through. Possibly you. Straight is cheaper.","把一件你一直绕着说的事，直说一次。","Say straight one thing you have been talking around."),
("swords","eight"):("hard","觉得被困住，绳子其实是松的。动一下试试。","You feel trapped; the rope is actually loose. Try moving.","做一件你「不能做」的小事，看看真不能吗。","Do one small thing you 'can't do' and see if that is true."),
("swords","nine"):("hard","半夜的担心，白天看会小很多。等天亮。","Night worries shrink in daylight. Wait for morning.","担心的事写在纸上，明早再读。","Write the worry down; read it tomorrow morning."),
("swords","ten"):("hard","到底了。到底的好处是不会再往下。","Rock bottom. The good news about bottom is it does not go lower.","今天只做一件事：吃一顿好的。","Do one thing today: eat one good meal."),
("swords","page"):("court","好奇心很旺。用来问问题，别用来偷看。","Curiosity is high. Use it to ask questions, not to snoop.","今天问三个「为什么」。","Ask three 'why's today."),
("swords","knight"):("court","冲得太快，话说得太狠。慢半拍。","Charging too fast, speaking too sharp. Slow by half a beat.","发出去之前，把每条消息重读一遍。","Reread every message before sending."),
("swords","queen"):("court","看得清，说得准。今天适合做决定、说实话。","Clear sight, exact speech. A day for decisions and truth.","做一个拖了很久的决定，今天说出来。","Make the decision you have been delaying and say it today."),
("swords","king"):("court","逻辑很硬，情绪很少。有用，但别对人。","Logic hard, feeling scarce. Useful, but not on people.","处理事用逻辑，处理人先问一句「你还好吗」。","Use logic on tasks. With people, first ask 'are you okay'."),
("pentacles","ace"):("bright","一个实在的机会：一份工作、一笔钱、一块地。接住。","A concrete chance: a job, a sum, a piece of ground. Catch it.","回复那个机会，今天。","Answer that opportunity today."),
("pentacles","two"):("pip","两头在平衡。可以撑，但撑不了三头。","Two things in balance. You can hold two; not three.","这周不接新的事。","Take on nothing new this week."),
("pentacles","three"):("pip","手艺被认可了。和人合作会比单干好。","Your craft is recognized. Working with others beats working alone.","今天找一个人一起做一件事。","Find one person to work with on one thing today."),
("pentacles","four"):("pip","抓得太紧。钱、人、时间，都一样。","Holding too tight. Money, people, time; all the same.","今天松开一样东西：花一点、给一点、放一点。","Loosen one thing today: spend a little, give a little, let a little go."),
("pentacles","five"):("hard","觉得穷，觉得冷，觉得没人管。门就在旁边，进去。","Feeling poor, cold, unseen. The door is right there. Go in.","向一个人开口要一次帮助。","Ask one person for help, once."),
("pentacles","six"):("pip","给和拿都在发生。看清你是哪一边，然后接受。","Giving and taking, both happening. See which side you are on, and accept it.","今天给出一样东西，或者接受一样东西，不客气。","Give one thing today, or accept one, without fuss."),
("pentacles","seven"):("pip","种下去了，还没长。看，不要挖。","Planted, not yet grown. Watch; do not dig it up.","不查那件事的进度，今天不查。","Do not check on that project's progress today."),
("pentacles","eight"):("pip","练。同一件事做第八遍。第八遍才是开始。","Practice. The same thing for the eighth time. The eighth is where it starts.","把一个技能重复练三十分钟。","Repeat one skill for thirty minutes."),
("pentacles","nine"):("bright","靠自己得来的舒适。享受，不用道歉。","Comfort earned by your own hand. Enjoy it without apology.","今天给自己一个小奢侈，独自享受。","Allow yourself one small luxury today, alone."),
("pentacles","ten"):("bright","长远的稳。家、积蓄、根。","Long-term steadiness: home, savings, roots.","为半年后的自己做一件事。","Do one thing for yourself six months from now."),
("pentacles","page"):("court","一个学新东西的机会。去学，哪怕没用。","A chance to learn something. Learn it, even if it is useless.","报名一样东西，今天。","Sign up for something today."),
("pentacles","knight"):("court","慢而稳。这周不会有惊喜，但会有进度。","Slow and steady. No surprises this week, but progress.","每天同一时间做同一件事，连做五天。","Do the same thing at the same time for five days."),
("pentacles","queen"):("court","把家照顾好。家也包括你自己的身体。","Look after the home. The home includes your body.","做一顿饭，或者整理一个房间。","Cook a meal or tidy one room."),
("pentacles","king"):("court","财务上稳，可以帮人了。帮，但别管。","Financially steady; you can help others now. Help; do not manage.","帮一个人一次，不问后续。","Help one person once and do not follow up."),
}

# (suit, rank): (rev_zh, rev_en, do_zh, do_en)
MINOR_REV = {
("wands","ace"):("念头有了，火没点着。不是没能力，是没时间表。","The idea is there; the fire is not lit. Not ability; a missing schedule.","给那个念头定一个开始日期。","Give the idea a start date."),
("wands","two"):("计划做了三遍，没出发过一次。","Planned three times, never left once.","把计划关上，做第一步。","Close the plan and do step one."),
("wands","three"):("等的东西不来，因为没发出去。","What you wait for is not coming, because it was never sent.","检查你以为发出去的那件事。","Check the thing you think you sent."),
("wands","four"):("庆祝早了，或者根本没庆祝。补上。","The celebration came too early, or not at all. Make it up.","为一件已经做成的事，今天补一顿饭。","Mark one finished thing with a meal today."),
("wands","five"):("吵得没有意义，而且越吵越累。","The argument has no point and it is wearing you down.","今天退出一场争论，不需要赢。","Leave one argument today. No need to win."),
("wands","six"):("想被看见，没被看见。这一次的功劳会晚到。","Wanting to be seen, and not being. The credit comes late this time.","把你做的事写在一个自己的记录里。","Record what you did in a log that is yours."),
("wands","seven"):("防守太久，忘了为什么守。","Defending so long you forgot what for.","问自己：这件事值得再守一周吗？","Ask: is this worth another week of holding?"),
("wands","eight"):("太快了，飞过头了。有东西没跟上。","Too fast; overshot. Something did not keep up.","把今天的速度减半。","Halve today's speed."),
("wands","nine"):("累到怀疑值不值得。答案不在今天。","Tired enough to doubt it is worth it. The answer is not today's.","今天不做判断，只休息。","No judgement today. Only rest."),
("wands","ten"):("压垮了。放下一件是不够的，放下三件。","Crushed. One thing down is not enough; put down three.","写下你背的所有事，划掉三件。","List everything you carry and cross out three."),
("wands","page"):("消息来了，你没当回事。回头看一眼。","The message came and you dismissed it. Look again.","重新读一遍你昨天忽略的那条消息。","Reread the message you ignored yesterday."),
("wands","knight"):("冲了，撞了，没方向。停一天。","Charged, hit the wall, no direction. Stop for a day.","今天不推进任何事，只定方向。","Push nothing today. Only set direction."),
("wands","queen"):("你在带的人没跟上，因为你没回头看。","The people you lead are behind, because you did not look back.","今天问一个跟你做事的人：你需要什么？","Ask someone who works with you: what do you need?"),
("wands","king"):("看得远，做得少。方向说了三次，还没动。","Far sight, little action. The direction said three times, nothing moved.","把大方向的第一步，今天亲手做。","Do the first step of the big direction yourself, today."),
("cups","ace"):("感觉堵住了。不是没有，是出不来。","The feeling is blocked. Not absent; unable to get out.","今天对一个人说一句心里话，小的。","Tell one person one true thing today. A small one."),
("cups","two"):("两个人错开了。不是分开，是没对上。","Two people out of step. Not apart; just not aligned.","约一次只聊天、不解决问题的见面。","Arrange a meeting that is only talk, no problem-solving."),
("cups","three"):("朋友太多，或者太少。你需要的是一个。","Too many friends, or too few. What you need is one.","给一个朋友打电话，不发消息。","Call one friend. Do not text."),
("cups","four"):("拒绝了太多次，别人不递了。","You refused so often that people stopped offering.","主动约一个人，别等被约。","Invite someone. Stop waiting to be invited."),
("cups","five"):("终于转身看到剩下的两样了。可以走了。","You have finally turned and seen the two remaining. You can go now.","带着那两样东西，做一件小的新事。","Take those two things and do one small new thing."),
("cups","six"):("困在过去。怀念变成了住址。","Stuck in the past. Nostalgia became an address.","今天做一件只属于现在的事。","Do one thing today that belongs only to now."),
("cups","seven"):("幻想散了，看到了实际。有点失望，但能用。","The fantasies clear and the real shows. Disappointing, but usable.","从实际的选项里挑一个，今天做第一步。","Pick one real option and take its first step today."),
("cups","eight"):("该走没走。留下来不是忠诚，是怕。","Should have left, did not. Staying is not loyalty; it is fear.","写下你留下的真实原因。","Write down the real reason you are staying."),
("cups","nine"):("满足是假的，是撑的。少要一点。","The satisfaction is faked, or forced. Want less.","今天取消一样你其实不需要的东西。","Cancel one thing today that you do not actually need."),
("cups","ten"):("家里的问题，没人说。你先说。","A problem at home nobody names. You name it.","今天在家问一句「最近怎么样」，然后等。","Ask at home 'how are things lately', then wait."),
("cups","page"):("情绪像小孩，不讲道理。哄一下，别讲道理。","The feeling is a child and will not reason. Soothe it; do not argue.","今天允许自己不讲道理一小时。","Allow yourself one unreasonable hour today."),
("cups","knight"):("承诺得太快。不是撒谎，是没算。","Promised too fast. Not a lie; just uncounted.","收回一个你兑现不了的承诺，今天说。","Withdraw one promise you cannot keep. Say so today."),
("cups","queen"):("接了太多别人的情绪，自己的漏了。","Caught too many other people's feelings; your own leaked out.","今天对一个人说「我今天接不住」。","Tell one person today: 'I can't take that on today'."),
("cups","king"):("稳过头，变冷了。稳和冷差一句话。","Steady to the point of cold. The difference is one sentence.","对一个人说一句有温度的话。","Say one warm thing to one person."),
("swords","ace"):("想清楚了，说错了。清楚不等于说得出来。","Thought clearly, said it wrong. Clear is not the same as sayable.","把那件事重新说一遍，换一种说法。","Say it again, another way."),
("swords","two"):("拖到别人替你选了。下次早一点。","Stalled until someone chose for you. Earlier next time.","把下一个要做的决定的截止日写下来。","Write the deadline for your next decision."),
("swords","three"):("疼在过去，慢慢在好。别去揭。","The hurt is easing. Do not pick at it.","今天不看那个人的动态。","Do not look at that person's feed today."),
("swords","four"):("休息不下来，因为你在假装休息。","You cannot rest because you are performing rest.","关掉所有通知一小时，真的关。","Turn off every notification for an hour. Actually off."),
("swords","five"):("一场架的余波。放它过去。","The aftershock of a fight. Let it pass.","不给那件事补最后一句。","Add no last word to that argument."),
("swords","six"):("想走，走不了。不是路的问题，是行李。","Want to leave, cannot. Not the road; the luggage.","写下你不能走的真实原因，只写一条。","Write the real reason you cannot leave. One line."),
("swords","seven"):("绕的路被看穿了。直说吧，还来得及。","The detour has been seen through. Say it straight; there is still time.","今天主动承认一件绕开的小事。","Own up to one small thing you went around."),
("swords","eight"):("绳子松了。你现在可以动了，只是还不习惯。","The rope has loosened. You can move now; you are just not used to it.","今天做一件上周「不能做」的事。","Do one thing today that was 'impossible' last week."),
("swords","nine"):("焦虑过了最高点。睡一觉，明天小一号。","The worry passed its peak. Sleep; tomorrow it is a size smaller.","今晚早睡半小时。","Sleep half an hour earlier tonight."),
("swords","ten"):("最坏的过去了。你还在。","The worst is over. You are still here.","今天做一件微小的、向上的事。","Do one tiny thing today that points up."),
("swords","page"):("话说太多，事做太少。","Too many words, too little done.","今天少说一半，多做一件。","Say half as much today and do one more thing."),
("swords","knight"):("冲动的话已经说出去了。补一句，不解释。","The sharp words are already out. Add one line; do not explain.","给那个人发一句「我说重了」。","Send them: 'I put that too hard'."),
("swords","queen"):("准，但冷。这周有人需要你的温度，不是判断。","Exact, but cold. Someone needs your warmth this week, not your verdict.","忍住一次纠正别人的冲动。","Hold back one urge to correct someone."),
("swords","king"):("逻辑被拿来当武器了。放下。","Logic is being used as a weapon. Put it down.","今天输一次辩论。","Lose one argument today."),
("pentacles","ace"):("机会来了，你没接。可能还能捡。","The chance came and you did not catch it. It may still be on the floor.","回那条你没回的机会，今天。","Answer the opportunity you left unanswered. Today."),
("pentacles","two"):("两头都掉了。先捡一头。","Both things dropped. Pick up one.","今天只处理一件事。","Handle one thing today."),
("pentacles","three"):("合作卡住了。不是人不对，是分工不清。","The collaboration is stuck. Not the people; the division of work.","写下谁做什么，发给所有人。","Write who does what and send it to everyone."),
("pentacles","four"):("松了，或者松过头了。看看账。","Loosened, maybe too far. Look at the ledger.","今天看一眼支出。","Look at your spending once today."),
("pentacles","five"):("终于进门了。冷的部分过去了，别再站回外面。","You finally went in. The cold part is over; do not step back out.","接受一次已经给你的帮助。","Accept one piece of help already offered."),
("pentacles","six"):("给的和拿的不平衡。有人在欠，可能是你。","Giving and taking, out of balance. Someone owes, possibly you.","今天还一样东西，或者要回一样。","Return one thing today, or ask for one back."),
("pentacles","seven"):("挖出来看了，苗还小。种回去。","You dug it up to check; the shoot is small. Put it back.","这周不再看进度。","Do not check progress again this week."),
("pentacles","eight"):("练腻了，或者练错了方向。换一种练法。","Bored of practice, or practicing the wrong thing. Change the drill.","把练习换一种形式做一次。","Do the practice once in a different form."),
("pentacles","nine"):("舒服，但一个人。舒服不等于够。","Comfortable, but alone. Comfortable is not the same as enough.","今天约一个人分享你的舒服。","Share your comfort with one person today."),
("pentacles","ten"):("家里的稳在松。不是塌，是要维护。","The home's steadiness is loosening. Not falling; needs maintenance.","修好家里一样坏了的东西。","Fix one broken thing at home."),
("pentacles","page"):("报了名没去。去一次就行。","Signed up, never went. Go once.","去上你报了的那一节课。","Attend the one class you signed up for."),
("pentacles","knight"):("慢成了停。加一格速度。","Slow became stopped. Add one notch of speed.","今天比昨天多做一件。","Do one more thing today than yesterday."),
("pentacles","queen"):("照顾所有人，没照顾家和自己。","Caring for everyone except home and self.","今天为自己做一顿饭。","Cook one meal for yourself today."),
("pentacles","king"):("帮人帮成了管人。退一步。","Helping turned into managing. Step back.","今天不给任何人建议，除非被问。","Give no advice today unless asked."),
}

# majors reversed: slug: (rev_zh, rev_en, do_zh, do_en)
MAJOR_REV = {
"the-fool":("开始得太随便，或者根本不敢开始。","Started too carelessly, or not at all.","把第一步写下来，做它，只做它。","Write the first step. Do it. Only it."),
"the-magician":("工具都在，手停着。缺的是一个动作。","The tools are all there and the hands are idle. One motion is missing.","今天做十分钟，不管做得好不好。","Work ten minutes today, quality irrelevant."),
"the-high-priestess":("你在忽略自己知道的事。停止问别人。","You are ignoring what you know. Stop asking others.","今天不征求任何意见。","Ask nobody's opinion today."),
"the-empress":("给太多，或者给错了对象。先给自己。","Giving too much, or to the wrong one. Give to yourself first.","今天为自己做一件平时替别人做的事。","Do for yourself today what you usually do for others."),
"the-emperor":("规矩定得太死，或者一条没有。找中间。","Rules too rigid, or none at all. Find the middle.","今天只守一条规矩。","Keep exactly one rule today."),
"the-hierophant":("老办法这次不管用。可以破，先知道你在破什么。","The old way does not work this time. Break it; know what you are breaking.","写下你不再遵守的那条规矩和理由。","Write down the rule you are dropping, and why."),
"the-lovers":("选择做了，心没跟上。或者一直没选。","Chosen, but the heart did not follow. Or never chosen at all.","给那个选择再一周，然后不再拖。","Give the choice one more week, then no more delay."),
"the-chariot":("方向没定，油门踩着。先停车。","No direction, foot on the gas. Stop first.","今天不推进，只写下你要去哪。","Push nothing today. Write only where you are going."),
"strength":("硬来了，或者没敢来。软，不是弱。","Forced it, or did not dare. Soft is not weak.","对一件难事，今天用最温和的方式碰一下。","Touch one hard thing today in the gentlest way."),
"the-hermit":("躲太久了。补给完了该出来。","Hidden too long. Resupply is done; come out.","今天联系一个人。","Contact one person today."),
"wheel-of-fortune":("转得不顺，你在跟它较劲。松手。","The wheel turns against you and you are fighting it. Let go.","把不受你控制的事写下来，然后合上。","Write down what you do not control, then close the page."),
"justice":("觉得不公平。可能是，也可能只是不满意。分清。","It feels unfair. Maybe it is; maybe it is just unwelcome. Tell them apart.","写下这件事里哪一部分真的不公平。","Write which part of this is actually unfair."),
"the-hanged-man":("挂太久，成了借口。可以下来了。","Hung too long; it became an excuse. Come down.","今天做一个小决定，结束一次悬而未决。","Make one small decision today and end one hanging matter."),
"death":("该结束的没结束。你在给它做人工呼吸。","What should end has not. You are keeping it breathing.","停止维护一件早该结束的事。","Stop maintaining one thing that should already be over."),
"temperance":("比例失衡。全是工作，或全是躺。","Out of proportion: all work, or all lying down.","今天加回缺的那一半，哪怕只有半小时。","Add back the missing half today, even for thirty minutes."),
"the-devil":("你看见那个习惯了。看见就是松动的开始。","You have seen the habit. Seeing is where it starts to loosen.","今天少做那个习惯一次。","Do the habit one time fewer today."),
"the-tower":("塌完了。灰尘落定，可以看地基了。","It has finished falling. The dust settles; you can see the foundation.","写下塌掉的东西里，哪一块还能用。","Write down which piece of what fell can still be used."),
"the-star":("希望有点弱。不是没有，是累。","Hope is thin. Not gone; tired.","今晚早睡，明天再看希望。","Sleep early tonight. Check on hope tomorrow."),
"the-moon":("雾在散。你之前怕的东西，多半没那么大。","The fog is lifting. What you feared is likely smaller than it looked.","把上周害怕的事重新看一眼。","Look again at what frightened you last week."),
"the-sun":("好日子，但你没在场。抬头。","A good day, and you were not present for it. Look up.","今天在外面待十分钟，什么都不做。","Spend ten minutes outside today doing nothing."),
"judgement":("听见了叫声，没应。或者应了别人的。","You heard the call and did not answer. Or answered someone else's.","问自己一次：这是我要的，还是别人要的？","Ask once: is this what I want, or what someone else wants?"),
"the-world":("圈没画完，你已经在画下一个。回去补一笔。","The circle is unfinished and you are drawing the next. Go back for one stroke.","把一件差最后一步的事做完。","Finish one thing that is one step from done."),
}


def cards():
    out = []
    for (slug, en, zh, num, glyph, tier, uz, ue, udz, ude) in MAJORS:
        rz, re_, rdz, rde = MAJOR_REV[slug]
        out.append(dict(slug=slug, name_en=en, name_zh=zh, numeral=num, glyph=glyph, tier=tier, suit="major",
                        up_zh=uz, up_en=ue, up_do_zh=udz, up_do_en=ude,
                        rev_zh=rz, rev_en=re_, rev_do_zh=rdz, rev_do_en=rde))
    for suit, (sen, szh, sg, _) in SUITS.items():
        for r in RANKS:
            tier, uz, ue, udz, ude = MINOR_UP[(suit, r)]
            rz, re_, rdz, rde = MINOR_REV[(suit, r)]
            out.append(dict(slug="%s-of-%s" % (r, suit), name_en="%s of %s" % (RANK_EN[r], sen),
                            name_zh="%s%s" % (szh, RANK_ZH[r]), numeral=RANK_NUM[r], glyph=sg, tier=tier, suit=suit,
                            up_zh=uz, up_en=ue, up_do_zh=udz, up_do_en=ude,
                            rev_zh=rz, rev_en=re_, rev_do_zh=rdz, rev_do_en=rde))
    return out


if __name__ == "__main__":
    c = cards()
    print(len(c))
