## GCStringsData — the en, zh and ja packs of play/ghost-channel/i18n.js, verbatim.
## Generated by tools/gen_strings.sh (node over the prototype file); do not edit by hand.
class_name GCStringsData

const T := {
 "en": {
  "agents": {
   "viper": {
    "local": "Lin Shuo",
    "role": "Scout lead",
    "tic": "solid copy",
    "quote": "Talk less. Live longer."
   },
   "moth": {
    "local": "Su Wan",
    "role": "Night guide",
    "tic": "eyes in the dark",
    "quote": "Don't light up. Light sells you."
   },
   "hex": {
    "local": "Zhao Heng",
    "role": "EW specialist",
    "tic": "telemetry clean",
    "quote": "Numbers don't lie. People do."
   },
   "raven": {
    "local": "Gu Chen",
    "role": "Veteran gunner",
    "tic": "still breathing",
    "quote": "Don't turn me into a sitrep."
   },
   "quill": {
    "local": "Jiang Cheng",
    "role": "New striker",
    "tic": "say the word",
    "quote": "Give me a window. I can end it."
   }
  },
  "ops": [
   {
    "name": "BLACK IVY",
    "blurb": "One ghost. Clean codebook. Learn the tells."
   },
   {
    "name": "GLASS HARBOR",
    "blurb": "A captured teammate may lie. That is not the ghost."
   },
   {
    "name": "WHITE NOISE",
    "blurb": "The map can lie. The book can be poisoned. Trust no one."
   }
  ],
  "type": {
   "fire": "FIRE MISSION",
   "extract": "EXTRACT",
   "resupply": "RESUPPLY",
   "move": "RELOCATE",
   "codebook": "NEW CODE",
   "accuse": "ACCUSE"
  },
  "lines": {
   "fire": [
    "{auth} {who} requesting fire on {grid}. Window is now.",
    "{auth} Hostile stack at {grid}. Send the rain."
   ],
   "extract": [
    "{auth} I'm hit. Pull me before you wait for a prettier story.",
    "{auth} Blood in the dirt. Extract before the second pass."
   ],
   "resupply": [
    "{auth} Magazines gone. Drop on my last plot.",
    "{auth} Dry as a bone. Resupply or I go loud with a rock."
   ],
   "move": [
    "{auth} Relocating to {grid}. Mark me there.",
    "{auth} Stepping to {grid}. If the plot lags, that is on you."
   ],
   "codebook": [
    "{auth} HQ spun the challenge. I have the new word. Update your book.",
    "{auth} Today's code is burned. Trust me and write the replacement."
   ],
   "accuse": [
    "{auth} {target} is the ghost. Cut their channel.",
    "{auth} I heard {target} on the enemy net. Burn them."
   ]
  },
  "title": "GHOST CHANNEL",
  "boot1": "SITE // BLACK-IVY",
  "boot2": "NET CONTROL ONLINE",
  "boot3": "THEME: TRUST NO ONE",
  "boot4": "TAP — THE RADIO IS LIVE",
  "mark": "BRACKEYS JAM 2026.2 · RADIO DEDUCTION",
  "tag": "Five voices. One mimic. Name the ghost.",
  "start": "ANSWER THE RADIO",
  "how": "HOW TO PLAY",
  "credits": "CREDITS",
  "hint": "During an op: A authorize · D deny · Q interrogate",
  "selectOp": "SELECT OPERATION",
  "back": "BACK",
  "howTitle": "HOW TO PLAY",
  "how1": "This is radio deduction, not a level-up game. You are Net Control. Five people call from the dark. One voice is a ghost, copying a teammate.",
  "howA": "AUTHORIZE fire, extract, resupply, or a codebook update.",
  "howD": "DENY it. Deny a real extract and a teammate bleeds.",
  "howQ": "INTERROGATE. Costs time. Friendlies know today's code. The ghost usually does not.",
  "howMap": "Watch the map. Fire on a friendly grid is a massacre. Let the ghost rewrite the book and every later check may be a lie.",
  "howWin": "When the net goes quiet, name the ghost: tap a face, use the five buttons, or press 1–5. That is the only win.",
  "credTitle": "CREDITS",
  "cred1": "GHOST CHANNEL — Brackeys Game Jam 2026.2",
  "cred2": "Theme: Trust No One",
  "cred3": "Portraits, UI, writing, and music are original runtime code (Canvas + Web Audio). No stock packs, no generative image or audio models.",
  "cred4": "Five people: Lin Shuo, Su Wan, Zhao Heng, Gu Chen, Jiang Cheng.",
  "time": "TIME",
  "ff": "FF",
  "score": "SCORE",
  "mapLabel": "LIVE PLOT · EACH SHAPE IS A PERSON",
  "roster": "ROSTER",
  "todayCode": "TODAY'S CODE",
  "standby": "STANDBY",
  "noTraffic": "NO TRAFFIC",
  "waiting": "Waiting for the next voice.",
  "auth": "A · AUTHORIZE",
  "deny": "D · DENY",
  "q": "Q · INTERROGATE",
  "debrief": "DEBRIEF",
  "again": "RUN IT AGAIN",
  "menu": "NET CONTROL",
  "opSub": "FIVE VOICES · ONE GHOST",
  "yestNote": "Yesterday was {book}. Anyone still using it is dead or lying.",
  "netOpen": "NET OPEN. Today's code is <b>{book}</b>.",
  "intelCap": "INTEL: {who} may be under duress. They will sound wrong. They are not the ghost.",
  "borrowedTic": "That tic belongs to someone else. The voice is borrowing.",
  "authWord": "Auth {book}.",
  "qFail": "{who} repeats yesterday's code \"{fake}\" and cannot name today's third word.",
  "qFailLog": "INTERROGATE: {who} failed today's code.",
  "qPass": "{who} returns {book} and last plot {grid}. It checks out.",
  "qPassLog": "INTERROGATE: {who} knows today's code.",
  "ffLog": "FRIENDLY FIRE. {who} is gone. You authorized the ghost.",
  "bookPoisonNote": "Book rewritten from the net. If that was the ghost, every later check is a trained lie.",
  "bookPoisonLog": "CODEBOOK rewritten by {who}. If they were the ghost, you just trained yourself to trust a lie.",
  "extractGhostLog": "You pulled the ghost off the map. They walk into the dark with your frequency.",
  "extractGhostEnd": "The extract bird lifted a mimic. The rest of the net goes silent one by one.",
  "falseAccuse": "You burned {who} on a friendly accusation. They will not forget.",
  "accuseOk": "Accusation stood. Channel marked.",
  "authItch": "Authorized {who}. Something in that voice still itches.",
  "authOk": "Authorized {who}. Plot holds.",
  "denyGhost": "DENIED {who}. The ghost just wasted a breath.",
  "denyExtract": "You left {who} in the dirt. They are still yours. They are bleeding.",
  "denySoft": "Denied {who}. Friendly traffic stacked behind it.",
  "twoFF": "Two friendly-fire events. Net Control pulls your clearance. The ghost keeps talking.",
  "nameGhost": "NAME THE GHOST",
  "finalCall": "FINAL CALL",
  "nameBody": "The net is quiet. One of these voices was never yours. Name them. Trust no one.",
  "nameExtra": "1–5 or tap a face. Radio keys are dead. This is the only vote that counts.",
  "nameBtn": "{n} · NAME {who}",
  "nameLog": "FINAL: name the ghost or they walk.",
  "winLead": "You named {who}. The mimic almost learned your cadence. Almost.",
  "loseLead": "You burned {who}. The real ghost was {ghost}. They thank you for the silence.",
  "winTitle": "GHOST BURNED",
  "loseTitle": "CHANNEL COMPROMISED",
  "statScore": "SCORE",
  "statAuth": "AUTHORIZED",
  "statDeny": "DENIED",
  "statQ": "INTERROGATED",
  "statFF": "FRIENDLY FIRE",
  "statBest": "BEST THIS OP",
  "kia": "KIA",
  "wounded": "WOUNDED",
  "pinned": "PINNED",
  "locked": "LOCKED",
  "best": "BEST {n}",
  "clockZero": "Clock zero. The ghost did not need you to believe them. They only needed you to hesitate.",
  "desc": "Five voices. One mimic. Name the ghost. Trust no one."
 },
 "zh": {
  "agents": {
   "viper": {
    "local": "林朔",
    "role": "侦察排长",
    "tic": "收到，干净",
    "quote": "少说话，多活着。"
   },
   "moth": {
    "local": "苏晚",
    "role": "夜战向导",
    "tic": "暗处有眼睛",
    "quote": "别开灯。灯会出卖人。"
   },
   "hex": {
    "local": "赵衡",
    "role": "电子战手",
    "tic": "链路是干净的",
    "quote": "数字不会撒谎。人会。"
   },
   "raven": {
    "local": "顾沉",
    "role": "老兵火力手",
    "tic": "我还活着",
    "quote": "别把我炸成一则通报。"
   },
   "quill": {
    "local": "江澄",
    "role": "突击新人",
    "tic": "你说一声就打",
    "quote": "给我窗口，我能结束它。"
   }
  },
  "ops": [
   {
    "name": "黑常春藤",
    "blurb": "一人是鬼。口令本是真的。先学会听破绽。"
   },
   {
    "name": "玻璃港",
    "blurb": "有队友被挟持，会说错话。那不是鬼。"
   },
   {
    "name": "白噪声",
    "blurb": "地图会骗人，口令本也可能被改。谁都别信。"
   }
  ],
  "type": {
   "fire": "申请火力",
   "extract": "申请撤离",
   "resupply": "申请补给",
   "move": "报告换位",
   "codebook": "更新口令",
   "accuse": "指控队友"
  },
  "lines": {
   "fire": [
    "{auth} {who}申请对 {grid} 开火。窗口就现在。",
    "{auth} {grid} 有敌方堆叠。下雨吧。"
   ],
   "extract": [
    "{auth} 我中弹了。别等一个更漂亮的理由，把我拉走。",
    "{auth} 土里有血。第二波来之前接我。"
   ],
   "resupply": [
    "{auth} 弹匣空了。丢到我上次标的位置。",
    "{auth} 干得能咬石头。补给，或者我只能用手。"
   ],
   "move": [
    "{auth} 我改到 {grid}。在图上改我。",
    "{auth} 踏去 {grid}。图要是慢了，那是你的事。"
   ],
   "codebook": [
    "{auth} 总部刚换了口令。新词在我这。改你的本子。",
    "{auth} 今日口令废了。信我，把新的写下来。"
   ],
   "accuse": [
    "{auth} {target} 是鬼。切掉那条频道。",
    "{auth} 我在敌网上听见 {target}。烧了。"
   ]
  },
  "title": "GHOST CHANNEL",
  "boot1": "站点 // 黑常春藤",
  "boot2": "网控上线",
  "boot3": "主题：TRUST NO ONE · 谁都别信",
  "boot4": "点一下 — 电台在响",
  "mark": "BRACKEYS JAM 2026.2 · 电台推理",
  "tag": "五个声音。一个是模仿。指认那个鬼。",
  "start": "接听电台",
  "how": "怎么玩",
  "credits": "制作",
  "hint": "对局里按 A 批准 / D 拒绝 / Q 盘问 · 也可以点按钮",
  "selectOp": "选择行动",
  "back": "返回",
  "howTitle": "怎么玩",
  "how1": "这是电台推理，不是升级打怪。你是网控。五个人在黑暗里通话。其中一个是鬼，在学队友的声音。",
  "howA": "批准：开火、撤离、补给、改口令。",
  "howD": "拒绝。拒错撤离，真人会流血。",
  "howQ": "盘问。花时间。真人知道今日口令，鬼通常不知道。",
  "howMap": "看地图。对友军格子开火就是误伤。让鬼改口令本，后面每一次核对都可能是假的。",
  "howWin": "频道静下来之后，指认鬼：点脸、点五个按钮，或按 1–5。点对了才算赢。",
  "credTitle": "制作",
  "cred1": "GHOST CHANNEL — Brackeys Game Jam 2026.2",
  "cred2": "主题：Trust No One · 谁都别信",
  "cred3": "人像、界面、台词和音乐都是手写代码现场画、现场合成（Canvas + Web Audio）。没有素材包，没有生成式图/音模型。",
  "cred4": "五个人：林朔、苏晚、赵衡、顾沉、江澄。",
  "time": "时间",
  "ff": "误伤",
  "score": "分数",
  "mapLabel": "实时标图 · 每个人形状不同",
  "roster": "名册",
  "todayCode": "今日口令",
  "standby": "待机",
  "noTraffic": "无通话",
  "waiting": "等下一道声音。",
  "auth": "A · 批准",
  "deny": "D · 拒绝",
  "q": "Q · 盘问",
  "debrief": "复盘",
  "again": "再跑一次",
  "menu": "回网控",
  "opSub": "五个人 · 一个鬼 · 听谁在说谎",
  "yestNote": "昨天的口令是 {book}。还在用昨天口令的人，要么已死，要么在骗你。",
  "netOpen": "频道已开。今日口令 <b>{book}</b>。",
  "intelCap": "情报：{who} 可能被挟持。说话会不对，但那不是鬼。",
  "borrowedTic": "这句口头禅是别人的。声音在借人。",
  "authWord": "口令 {book}。",
  "qFail": "{who} 重复了昨天的口令「{fake}」，说不出今天的第三个词。",
  "qFailLog": "盘问：{who} 没通过今日口令。",
  "qPass": "{who} 答对 {book}，位置 {grid}。对得上。",
  "qPassLog": "盘问：{who} 知道今日口令。",
  "ffLog": "误伤。{who} 没了。你批准了鬼的火力。",
  "bookPoisonNote": "口令本已按电台改写。如果那是鬼，你之后每一次核对都在信谎。",
  "bookPoisonLog": "口令本被 {who} 改了。若是鬼，你正在被训练去信谎。",
  "extractGhostLog": "你把鬼接走了。他们带着你的频率走进暗处。",
  "extractGhostEnd": "撤离机接走的是模仿者。其余频道会一个一个哑掉。",
  "falseAccuse": "你按友军的指控烧掉了 {who}。他们会记住。",
  "accuseOk": "指控成立。频道已标记。",
  "authItch": "你批准了 {who}。那声音里还是有刺。",
  "authOk": "批准 {who}。图还站得住。",
  "denyGhost": "拒绝 {who}。鬼白费了一口气。",
  "denyExtract": "你把 {who} 留在土里。人还是你的。在流血。",
  "denySoft": "拒绝 {who}。友军通话在后面堆着。",
  "twoFF": "两次误伤。网控收回你的权限。鬼还在说话。",
  "nameGhost": "指认鬼",
  "finalCall": "最后一次",
  "nameBody": "频道静了。这五个人里有一个从来不是你的人。点名。谁都别信。",
  "nameExtra": "按 1–5 或点脸。A / D / Q 已经没用了。这是唯一算赢的一票。",
  "nameBtn": "{n} · 指认 {who}",
  "nameLog": "最后：指认鬼，否则他们走掉。",
  "winLead": "你指认了 {who}。模仿者几乎学会了你的节奏。几乎。",
  "loseLead": "你烧了 {who}。真鬼是 {ghost}。他们谢谢你的沉默。",
  "winTitle": "鬼被烧了",
  "loseTitle": "频道失守",
  "statScore": "分数",
  "statAuth": "批准",
  "statDeny": "拒绝",
  "statQ": "盘问",
  "statFF": "误伤",
  "statBest": "本关最好",
  "kia": "阵亡",
  "wounded": "受伤",
  "pinned": "已钉",
  "locked": "未解锁",
  "best": "最好 {n}",
  "clockZero": "时间归零。鬼不需要你相信他们。他们只需要你犹豫。",
  "desc": "电台推理。五个人里有一个鬼。谁都别信。"
 },
 "ja": {
  "agents": {
   "viper": {
    "local": "リン・シュオ",
    "role": "偵察班長",
    "tic": "了解、クリア",
    "quote": "喋るな。生きろ。"
   },
   "moth": {
    "local": "スー・ワン",
    "role": "夜戦ガイド",
    "tic": "闇に目がある",
    "quote": "灯るな。光は売る。"
   },
   "hex": {
    "local": "ジャオ・ヘン",
    "role": "電子戦",
    "tic": "テレメトリ正常",
    "quote": "数字は嘘をつかない。人はつく。"
   },
   "raven": {
    "local": "グー・チェン",
    "role": "古参砲手",
    "tic": "まだ息してる",
    "quote": "報告書にするな。"
   },
   "quill": {
    "local": "ジャン・チェン",
    "role": "新人突撃",
    "tic": "一言くれ",
    "quote": "窓をくれ。終わらせる。"
   }
  },
  "ops": [
   {
    "name": "ブラックアイビー",
    "blurb": "ゴーストは一人。暗号帳は本物。破綻を聞け。"
   },
   {
    "name": "グラスハーバー",
    "blurb": "捕まった味方が嘘をつく。それはゴーストではない。"
   },
   {
    "name": "ホワイトノイズ",
    "blurb": "地図も帳も嘘になり得る。誰も信じるな。"
   }
  ],
  "type": {
   "fire": "火力要請",
   "extract": "回収要請",
   "resupply": "補給要請",
   "move": "移動報告",
   "codebook": "暗号更新",
   "accuse": "告発"
  },
  "lines": {
   "fire": [
    "{auth} {who}、{grid} へ火力を。窓は今だ。",
    "{auth} {grid} に敵密集。雨を降らせろ。"
   ],
   "extract": [
    "{auth} 被弾した。綺麗な理由を待つ前に引け。",
    "{auth} 土に血がある。第二波の前に回収。"
   ],
   "resupply": [
    "{auth} 弾切れ。前回の座標へ落とせ。",
    "{auth} 乾いている。補給か、石で行く。"
   ],
   "move": [
    "{auth} {grid} へ移る。地図を直せ。",
    "{auth} {grid} へ踏む。遅れはそっちの責任。"
   ],
   "codebook": [
    "{auth} 本部が暗号を回した。新しい語は俺が持ってる。",
    "{auth} 今日の暗号は焼けた。信じて書き直せ。"
   ],
   "accuse": [
    "{auth} {target} がゴーストだ。回線を切れ。",
    "{auth} 敵網で {target} を聞いた。焼け。"
   ]
  },
  "title": "GHOST CHANNEL",
  "boot1": "サイト // ブラックアイビー",
  "boot2": "ネットコントロールオンライン",
  "boot3": "テーマ：TRUST NO ONE",
  "boot4": "タップ — 無線が生きている",
  "mark": "BRACKEYS JAM 2026.2 · 無線推理",
  "tag": "五つの声。一人は物真似。ゴーストを名指せ。",
  "start": "無線に出る",
  "how": "遊び方",
  "credits": "クレジット",
  "hint": "作戦中 A 許可 · D 拒否 · Q 尋問",
  "selectOp": "作戦を選ぶ",
  "back": "戻る",
  "howTitle": "遊び方",
  "how1": "これは無線推理であり、育成ゲームではない。あなたはネットコントロール。闇から五人が呼ぶ。一人は仲間の声を真似るゴースト。",
  "howA": "火力・回収・補給・暗号更新を許可する。",
  "howD": "拒否する。本物の回収を拒否すれば仲間が血を流す。",
  "howQ": "尋問する。時間を使う。味方は今日の暗号を知っている。ゴーストは大抵知らない。",
  "howMap": "地図を見ろ。味方マスへの火力は誤射だ。ゴーストに帳を書き換えさせれば、以降の確認は嘘になり得る。",
  "howWin": "回線が黙ったらゴーストを名指せ。顔、五つのボタン、または 1–5。それが唯一の勝利。",
  "credTitle": "クレジット",
  "cred1": "GHOST CHANNEL — Brackeys Game Jam 2026.2",
  "cred2": "テーマ：Trust No One",
  "cred3": "肖像、UI、台詞、音楽は手書きコードの実行時生成（Canvas + Web Audio）。素材パックも生成モデルも使っていない。",
  "cred4": "五人：リン・シュオ、スー・ワン、ジャオ・ヘン、グー・チェン、ジャン・チェン。",
  "time": "時間",
  "ff": "誤射",
  "score": "スコア",
  "mapLabel": "リアルタイムプロット · 形が人",
  "roster": "名簿",
  "todayCode": "今日の暗号",
  "standby": "待機",
  "noTraffic": "通信なし",
  "waiting": "次の声を待つ。",
  "auth": "A · 許可",
  "deny": "D · 拒否",
  "q": "Q · 尋問",
  "debrief": "報告",
  "again": "もう一度",
  "menu": "コントロールへ",
  "opSub": "五つの声 · 一人のゴースト",
  "yestNote": "昨日の暗号は {book}。まだ使っている者は死んでいるか、嘘をついている。",
  "netOpen": "回線開放。今日の暗号は <b>{book}</b>。",
  "intelCap": "情報：{who} は脅迫下かもしれない。言い方はおかしい。ゴーストではない。",
  "borrowedTic": "その口癖は別人のものだ。声が借りている。",
  "authWord": "暗号 {book}。",
  "qFail": "{who} は昨日の暗号「{fake}」を繰り返し、今日の第三語を言えない。",
  "qFailLog": "尋問：{who} は今日の暗号に落ちた。",
  "qPass": "{who} は {book} と最終座標 {grid} を返した。一致。",
  "qPassLog": "尋問：{who} は今日の暗号を知っている。",
  "ffLog": "誤射。{who} は消えた。ゴーストの火力を許可した。",
  "bookPoisonNote": "帳は通信で書き換えられた。あれがゴーストなら、以降の確認は訓練された嘘だ。",
  "bookPoisonLog": "{who} が暗号帳を書き換えた。ゴーストなら、嘘を信じる訓練を始めた。",
  "extractGhostLog": "ゴーストを回収した。奴らは君の周波数を持って闇へ歩く。",
  "extractGhostEnd": "回収機がミミックを上げた。残りの回線は一つずつ黙る。",
  "falseAccuse": "味方の告発で {who} を焼いた。忘れない。",
  "accuseOk": "告発は立った。回線をマークした。",
  "authItch": "{who} を許可した。その声にはまだ棘がある。",
  "authOk": "{who} を許可。プロットは持つ。",
  "denyGhost": "{who} を拒否。ゴーストは息を無駄にした。",
  "denyExtract": "{who} を土に置いた。まだ君の人間だ。血を流している。",
  "denySoft": "{who} を拒否。味方通信が後ろに積もる。",
  "twoFF": "誤射が二度。権限を剥奪する。ゴーストは話し続ける。",
  "nameGhost": "ゴーストを名指せ",
  "finalCall": "最終コール",
  "nameBody": "回線は黙った。この五つの声の一つは、最初から君のものではなかった。名指せ。誰も信じるな。",
  "nameExtra": "1–5 か顔をタップ。A D Q はもう死んでいる。それが唯一の投票だ。",
  "nameBtn": "{n} · {who} を名指せ",
  "nameLog": "最後：ゴーストを名指せ。さもなくば歩く。",
  "winLead": "{who} を名指した。ミミックは君の間合いを、ほとんど覚えた。ほとんど。",
  "loseLead": "{who} を焼いた。本物のゴーストは {ghost}。沈黙に礼を言う。",
  "winTitle": "ゴースト焼尽",
  "loseTitle": "回線陥落",
  "statScore": "スコア",
  "statAuth": "許可",
  "statDeny": "拒否",
  "statQ": "尋問",
  "statFF": "誤射",
  "statBest": "この作戦のベスト",
  "kia": "戦死",
  "wounded": "負傷",
  "pinned": "マーク",
  "locked": "未解禁",
  "best": "ベスト {n}",
  "clockZero": "時間切れ。ゴーストは信じさせる必要がなかった。躊躇だけでよかった。",
  "desc": "無線推理。五人。一人のゴースト。誰も信じるな。"
 }
}
