window.REBOUND_COPY = {
  langs: ["en", "es", "pt", "zh", "ja"],
  en: {
    wordmark: "REBOUND",
    localTitle: "Rebound Tycoon",
    tagline: "Hose the night. Bank the rent.",
    kicker: "GATE 01 · NIGHT EMPIRE",
    pitch: "You are the night-shift guard. Pump the water hose to launch. Every rebound soaks a troublemaker and pays rent. Spend the coins on towers until the booth becomes an empire.",
    start: "TAKE THE GATE",
    again: "NEW NIGHT",
    spray: "PUMP HOSE",
    launchHint: "Hold Space, or tap PUMP HOSE",
    spaceHint: "HOLD SPACE",
    left: "LEFT",
    right: "RIGHT",
    shop: "LEDGER",
    prestige: "REBOUND",
    settings: "BOOTH",
    coins: "COINS",
    rent: "RENT",
    combo: "COMBO",
    night: "NIGHT",
    era: "ERA",
    balls: "HOSES",
    tokens: "TOKENS",
    waiting: "ON DUTY",
    live: "HOSE LIVE",
    ringing: "PUMP",
    nightover: "SHIFT OVER",
    hits: {
      courier: "Courier soaked. Rent collected.",
      party: "Floor 6 shut down. They paid.",
      raccoon: "Raccoon bounced. Fine collected.",
      booth: "Booth intercom. Tip jar.",
      lobby: "Lobby intercom. Late fee.",
      tower: "Penthouse intercom. Bonus.",
      cannon: "Water cannon. Full pressure.",
      sling: "Gate post. Another coin.",
      gate: "All intercoms. Jackpot rent.",
    },
    log: "NIGHT LOG",
    logBody: "How was the table? The empire is listening.",
    sendLog: "FILE THE LOG",
    close: "CLOSE",
    share: "SHARE THE TABLE",
    copied: "Copied the night report.",
    need: "Need more coins",
    needTokens: "Need more tokens",
    prestigeHint: "Reset the table. Keep the tokens. Come back louder.",
    prestigeLocked: "Reach the lobby era, then earn a token.",
    prestigeGo: "REBOUND THE EMPIRE",
    shopHint: "Upgrade the table. Then the towers.",
    perkHint: "Spend tokens. The uniform remembers.",
    sound: "Sound",
    motion: "Motion",
    language: "Language",
    on: "ON",
    off: "OFF",
    reduce: "REDUCED",
    full: "FULL",
    eras: { booth: "Booth", lobby: "Lobby", towers: "Towers", neon: "Neon Empire" },
    groups: { table: "Table", staff: "Staff", property: "Property", amenity: "Amenities" },
    upgrades: {
      springs: "Plunger Springs",
      flippers: "Gold Flippers",
      bumpers: "Hot Bumpers",
      slings: "Slingshots",
      doorman: "Ball Save",
      concierge: "Bonus Hold",
      manager: "Extra Ball",
      studio: "Studio",
      loft: "Loft",
      penthouse: "Penthouse",
      cannon: "Water Cannon",
      neon: "Neon Sign",
    },
    hints: {
      springs: "More pressure in the hose.",
      flippers: "Faster gate arms. Meaner rebounds.",
      bumpers: "Troublemakers pay more when soaked.",
      slings: "The gate posts shove back.",
      doorman: "Saves one missed shot each hose.",
      concierge: "Every rebound pays louder rent.",
      manager: "Start the night with an extra hose.",
      studio: "A window. Then a skyline.",
      loft: "Mid-rise rent multiplier.",
      penthouse: "The reason the uniform went gold.",
      cannon: "The center hose fires harder.",
      neon: "The city admits you own the building.",
    },
    perks: {
      uniform: "Gold-Trim Uniform",
      legend: "Legendary Cannon",
      switchboard: "Ringing Switchboard",
      empire: "Empire Fund",
    },
    perkHints: {
      uniform: "+8% score per rank.",
      legend: "Stronger saucer kick.",
      switchboard: "Lights remember you.",
      empire: "+12% score per rank.",
    },
    lines: {
      booth: "Night shift. Pump the hose. Make them pay.",
      lobby: "The gate is collecting rent now.",
      towers: "The water cannon has a waiting list.",
      neon: "The skyline finally learned your name.",
      bumper: "Soaked. Coin in the till.",
      drain: "Hose ran dry. Next burst.",
      save: "The doorman caught the drip.",
      nightover: "Shift over. Count the coins.",
      launch: "Hose is live.",
      buy: "The building noticed.",
      prestige: "Leave the booth. Keep the gold.",
      gate: "Every intercom lit. Jackpot rent.",
    },
    shareText: "REBOUND — I turned a night-shift pinball table into a neon empire.",
  },
  es: {
    wordmark: "REBOUND", localTitle: "Magnate del Rebote", tagline: "Lanza la bola. Compra el horizonte.",
    kicker: "MESA 01 · IMPERIO NOCTURNO",
    pitch: "Una mesa de pinball vestida de portería nocturna. Lanza, rebota y gasta las monedas en un imperio.",
    start: "PRESIONA START", again: "NUEVA NOCHE", spray: "BOMBA", launchHint: "Mantén Espacio o toca BOMBA", spaceHint: "MANTÉN ESPACIO", left: "IZQ", right: "DER",
    shop: "LIBRO", prestige: "REBOTE", settings: "CASETA", coins: "MONEDAS", rent: "RENTA",
    combo: "COMBO", night: "NOCHE", era: "ERA", balls: "BOLAS", tokens: "FICHAS",
    waiting: "LISTO", live: "BOLA VIVA", ringing: "LANZAR", nightover: "DRAIN",
    log: "BITÁCORA", logBody: "¿Cómo estuvo la mesa? El imperio escucha.", sendLog: "ARCHIVAR",
    close: "CERRAR", share: "COMPARTIR LA MESA", copied: "Parte copiado.",
    need: "Faltan monedas", needTokens: "Faltan fichas",
    prestigeHint: "Reinicia la mesa. Quédate las fichas.", prestigeLocked: "Llega al lobby y gana una ficha.",
    prestigeGo: "REBOTAR EL IMPERIO", shopHint: "Mejora la mesa. Luego las torres.", perkHint: "Gasta fichas.",
    sound: "Sonido", motion: "Movimiento", language: "Idioma", on: "SÍ", off: "NO", reduce: "BAJO", full: "TOTAL",
    eras: { booth: "Caseta", lobby: "Lobby", towers: "Torres", neon: "Imperio neón" },
    groups: { table: "Mesa", staff: "Personal", property: "Propiedad", amenity: "Amenidades" },
    upgrades: { springs: "Resortes", flippers: "Aletas de oro", bumpers: "Bumpers", slings: "Hondas", doorman: "Salvamento", concierge: "Bonus", manager: "Bola extra", studio: "Estudio", loft: "Loft", penthouse: "Ático", cannon: "Cañón de agua", neon: "Neón" },
    hints: { springs: "Lanzamiento más duro.", flippers: "Aletas más rápidas.", bumpers: "Pegan más fuerte.", slings: "Empujan de vuelta.", doorman: "Salva un drain.", concierge: "Cada golpe paga más.", manager: "Una bola extra al empezar.", studio: "Una ventana en el cristal.", loft: "Multiplicador medio.", penthouse: "Por esto las aletas se doraron.", cannon: "El saucer dispara.", neon: "La ciudad admite la mesa." },
    perks: { uniform: "Uniforme con oro", legend: "Cañón legendario", switchboard: "Centralita", empire: "Fondo imperio" },
    perkHints: { uniform: "+8% puntos por rango.", legend: "Saucer más fuerte.", switchboard: "Las luces recuerdan.", empire: "+12% puntos por rango." },
    lines: { booth: "Tres bolas. Una caseta.", lobby: "Las aletas ya pagan renta.", towers: "La mesa tiene lista de espera.", neon: "El horizonte aprendió tu nombre.", bumper: "Rebote.", drain: "Drain. Siguiente bola.", save: "El portero la atrapó.", nightover: "Noche cerrada.", launch: "Bola en juego.", buy: "La mesa se dio cuenta.", prestige: "Deja la caseta. Quédate el oro.", gate: "Puerta encendida." },
    shareText: "REBOUND — Convertí una mesa nocturna en un imperio de neón.",
  },
  pt: {
    wordmark: "REBOUND", localTitle: "Magnata do Rebote", tagline: "Lança a bola. Compra o horizonte.",
    kicker: "MESA 01 · IMPÉRIO NOTURNO",
    pitch: "Uma mesa de pinball vestida de portaria noturna. Lança, rebate e gasta as moedas num império.",
    start: "APERTE START", again: "NOVA NOITE", spray: "MANGUEIRA", launchHint: "Segure Espaço ou toque MANGUEIRA", spaceHint: "SEGURE ESPAÇO", left: "ESQ", right: "DIR",
    shop: "LIVRO", prestige: "REBOTE", settings: "GUARITA", coins: "MOEDAS", rent: "ALUGUEL",
    combo: "COMBO", night: "NOITE", era: "ERA", balls: "BOLAS", tokens: "FICHAS",
    waiting: "PRONTO", live: "BOLA VIVA", ringing: "LANÇAR", nightover: "DRAIN",
    log: "LIVRO DE TURNO", logBody: "Como foi a mesa? O império escuta.", sendLog: "ARQUIVAR",
    close: "FECHAR", share: "COMPARTILHAR A MESA", copied: "Relato copiado.",
    need: "Faltam moedas", needTokens: "Faltam fichas",
    prestigeHint: "Reinicia a mesa. Fica com as fichas.", prestigeLocked: "Chegue ao lobby e ganhe uma ficha.",
    prestigeGo: "REBATER O IMPÉRIO", shopHint: "Melhore a mesa. Depois as torres.", perkHint: "Gaste fichas.",
    sound: "Som", motion: "Movimento", language: "Idioma", on: "SIM", off: "NÃO", reduce: "BAIXO", full: "TOTAL",
    eras: { booth: "Guarita", lobby: "Lobby", towers: "Torres", neon: "Império neon" },
    groups: { table: "Mesa", staff: "Equipe", property: "Imóvel", amenity: "Comodidades" },
    upgrades: { springs: "Molas", flippers: "Flippers de ouro", bumpers: "Bumpers", slings: "Estilingues", doorman: "Ball save", concierge: "Bônus", manager: "Bola extra", studio: "Studio", loft: "Loft", penthouse: "Cobertura", cannon: "Canhão de água", neon: "Neon" },
    hints: { springs: "Lançamento mais forte.", flippers: "Batedores mais rápidos.", bumpers: "Chutam mais.", slings: "Empurram de volta.", doorman: "Salva um drain.", concierge: "Cada hit paga mais.", manager: "Bola extra no início.", studio: "Uma janela no vidro.", loft: "Multiplicador médio.", penthouse: "Por isso os flippers douraram.", cannon: "O saucer dispara.", neon: "A cidade admite a mesa." },
    perks: { uniform: "Uniforme dourado", legend: "Canhão lendário", switchboard: "Mesa telefônica", empire: "Fundo império" },
    perkHints: { uniform: "+8% pontos por nível.", legend: "Saucer mais forte.", switchboard: "As luzes lembram.", empire: "+12% pontos por nível." },
    lines: { booth: "Três bolas. Uma guarita.", lobby: "Os flippers já pagam aluguel.", towers: "A mesa tem fila.", neon: "O horizonte aprendeu seu nome.", bumper: "Rebote.", drain: "Drain. Próxima bola.", save: "O porteiro pegou.", nightover: "Noite encerrada.", launch: "Bola em jogo.", buy: "A mesa percebeu.", prestige: "Deixe a guarita. Fique com o ouro.", gate: "Portão aceso." },
    shareText: "REBOUND — Transformei uma mesa noturna num império de neon.",
  },
  zh: {
    wordmark: "REBOUND", localTitle: "回弹大亨", tagline: "弹球值夜，再买下天际线。",
    kicker: "一号球台 · 夜帝国",
    pitch: "一张装成门岗的弹珠台。发射、回弹、把硬币花成地产帝国。",
    start: "上岗", again: "再值一晚", spray: "压水炮", launchHint: "按住空格，或点压水炮", spaceHint: "按住空格", left: "左挡", right: "右挡",
    shop: "账本", prestige: "翻身", settings: "岗亭", coins: "硬币", rent: "租金",
    combo: "连击", night: "夜班", era: "时代", balls: "球数", tokens: "翻身币",
    waiting: "就绪", live: "球在台上", ringing: "待发", nightover: "漏球",
    log: "值班日志", logBody: "这台球怎么样？帝国在听。", sendLog: "归档",
    close: "关闭", share: "分享球台", copied: "夜报已复制。",
    need: "硬币不够", needTokens: "翻身币不够",
    prestigeHint: "重置球台，留下代币。", prestigeLocked: "先进入大堂时代，再赚到一枚翻身币。",
    prestigeGo: "弹回整个帝国", shopHint: "先改球台，再买塔楼。", perkHint: "花掉代币。",
    sound: "声音", motion: "动效", language: "语言", on: "开", off: "关", reduce: "减弱", full: "全开",
    eras: { booth: "岗亭", lobby: "大堂", towers: "塔楼", neon: "霓虹帝国" },
    groups: { table: "球台", staff: "人手", property: "物业", amenity: "配套" },
    upgrades: { springs: "发射簧", flippers: "金挡板", bumpers: "热碰柱", slings: "弹板", doorman: "救球", concierge: "加成", manager: "加一球", studio: "开间", loft: "复式", penthouse: "顶层", cannon: "水炮穴", neon: "霓虹" },
    hints: { springs: "发射更狠。", flippers: "挡板更快。", bumpers: "踢得更响。", slings: "下沿往回推。", doorman: "漏球时救一次。", concierge: "每次命中更肥。", manager: "开局多一球。", studio: "背板上多一扇窗。", loft: "中层倍率。", penthouse: "挡板镀金的理由。", cannon: "球穴像水管一样喷。", neon: "这座城承认这张台是你的。" },
    perks: { uniform: "金边制服", legend: "传说水炮", switchboard: "总机", empire: "帝国基金" },
    perkHints: { uniform: "每级分数 +8%。", legend: "球穴更猛。", switchboard: "灯会记得你。", empire: "每级分数 +12%。" },
    lines: { booth: "三颗球。一座岗亭。打回去。", lobby: "挡板开始交租了。", towers: "这张台已经有候补。", neon: "天际线学会了你的名字。", bumper: "回弹。", drain: "漏了。下一球。", save: "门童接住了。", nightover: "夜班结束。数硬币。", launch: "球活了。", buy: "球台看见了。", prestige: "离开岗亭，带走金子。", gate: "门岗点亮。彩金。" },
    shareText: "REBOUND — 我把夜班弹珠台做成了霓虹帝国。",
  },
  ja: {
    wordmark: "REBOUND", localTitle: "リバウンド大亨", tagline: "弾いて、空を買う。",
    kicker: "テーブル01 · 夜の帝国",
    pitch: "夜勤の門を着たピンボール。発射し、跳ね返し、コインで帝国を買う。",
    start: "ゲートに立て", again: "次の夜", spray: "ホース", launchHint: "スペースを押すかホースをタップ", spaceHint: "スペース長押し", left: "左", right: "右",
    shop: "台帳", prestige: "転生", settings: "詰所", coins: "コイン", rent: "家賃",
    combo: "コンボ", night: "夜勤", era: "時代", balls: "ボール", tokens: "トークン",
    waiting: "待機", live: "インプレイ", ringing: "発射待ち", nightover: "ドレイン",
    log: "当番日誌", logBody: "テーブルはどうだった？帝国は聞いている。", sendLog: "提出",
    close: "閉じる", share: "テーブルをシェア", copied: "夜報をコピーした。",
    need: "コインが足りない", needTokens: "トークンが足りない",
    prestigeHint: "テーブルをリセットし、トークンは残す。", prestigeLocked: "ロビー時代に達し、トークンを1枚得る。",
    prestigeGo: "帝国を跳ね返す", shopHint: "先にテーブル、次に塔。", perkHint: "トークンを使え。",
    sound: "音", motion: "動き", language: "言語", on: "入", off: "切", reduce: "弱", full: "強",
    eras: { booth: "詰所", lobby: "ロビー", towers: "タワー", neon: "ネオン帝国" },
    groups: { table: "テーブル", staff: "人員", property: "物件", amenity: "設備" },
    upgrades: { springs: "プランジャー", flippers: "金のフリッパー", bumpers: "バンパー", slings: "スリング", doorman: "ボールセーブ", concierge: "ボーナス", manager: "エクストラボール", studio: "スタジオ", loft: "ロフト", penthouse: "ペントハウス", cannon: "水砲", neon: "ネオン" },
    hints: { springs: "より強い発射。", flippers: "速いバット。", bumpers: "強く弾く。", slings: "下段が押し返す。", doorman: "ドレインを一度救う。", concierge: "ヒットが太る。", manager: "夜の始めに+1球。", studio: "バックグラスの窓。", loft: "中層倍率。", penthouse: "フリッパーが金になった理由。", cannon: "ソーサーが噴く。", neon: "街がテーブルを認める。" },
    perks: { uniform: "金縁の制服", legend: "伝説の砲", switchboard: "交換台", empire: "帝国基金" },
    perkHints: { uniform: "各ランクでスコア +8%。", legend: "ソーサーが強い。", switchboard: "ライトが覚える。", empire: "各ランクでスコア +12%。" },
    lines: { booth: "三球。詰所。跳ね返せ。", lobby: "フリッパーが家賃を払い始めた。", towers: "テーブルに順番待ち。", neon: "空が名前を覚えた。", bumper: "リバウンド。", drain: "ドレイン。次の球。", save: "ドアマンが捕った。", nightover: "夜が終わった。", launch: "ボールが生きた。", buy: "テーブルが気づいた。", prestige: "詰所を離れ、金は残す。", gate: "ゲート点灯。" },
    shareText: "REBOUND — 夜勤のピンボールをネオンの帝国にした。",
  },
};
