# The RPG's own narration for the three nights and the epilogue (key: (EN, JA)). The VN's
# text (testimonies, press beats, routes, endings) is referenced from data/story/ and is not
# repeated here. Voice: the VN's voice follows its lines; these new lines are unvoiced.
S = {
# ---------------------------------------------------------------- night 1: The Cold Room
"n1_title": ("Case 1 — The Cold Room", "第一の事件 — 冷蔵室"),
"n1_sub": ("Thursday. The Paloma, back office. One down, three keys.", "木曜。パロマの事務室。死者一人、鍵は三本。"),
"n1_open_1": ("The captain gets in at seven. Until then the Paloma, the three keys and the three people who held them are yours.", "署長は七時に来る。それまでは、パロマも、三本の鍵も、それを持っていた三人も、あなたのものだ。"),
"n1_open_2": ("Three doors off one corridor; two blocks of wet street between here and the club. Start wherever the night tells you to.", "一本の廊下に三つの扉。ここからクラブまでは濡れた通りを二区画。夜が告げる場所から始めろ。"),
"n1_drawer_1": ("Your drawer: a notebook with half its pages gone, a hip flask, and two markers you have been owed since spring.", "机の引き出し。半分ちぎれた手帳、スキットル、春から回収していない貸しが二つ。"),
"n1_alley_1": ("The alley behind the Paloma. Rain in the puddles, a dead neon sign, police tape across the yard door, and a man standing where the tape used to be.", "パロマ裏の路地。水たまりに雨、死んだネオン、裏庭の扉に張られた規制線、そしてテープのあった場所に立つ男。"),
"n1_bouncer_1": ("\"Closed.\"", "「閉店だ」"),
"n1_bouncer_2": ("He peels the tape back for you. Not far.", "彼はテープをめくってくれる。ほんの少しだけ。"),
"n1_dumpster_1": ("Under the lid: a brass lighter with its initials scratched off, and a delivery docket somebody did not want found in the van.", "蓋の下。イニシャルを削った真鍮のライターと、バンの中で見つかりたくなかった誰かの配達伝票。"),
"n1_yard_1": ("The yard door. Steel, a rubber seal round the frame, a drag mark in the paint at knee height.", "裏庭の扉。鋼製、枠にゴムのシール、膝の高さの塗装に引きずった跡。"),
"n1_club_1": ("The Paloma after closing: upturned stools, the smell of a mop, one service light left on by somebody who meant to come back.", "閉店後のパロマ。逆さのスツール、モップの匂い、戻るつもりだった誰かが点けたままのサービスライト。"),
"n1_bar_1": ("Behind the bar, a bottle nobody rang up and a glass with lipstick on it.", "カウンターの裏に、レジを通していない瓶と、口紅のついたグラス。"),
"n1_curtain_1": ("The strip curtain to the back rooms. Plastic slats. They swing when you touch them and keep swinging for a long time.", "奥へ続くストリップカーテン。プラスチックの帯。触れると揺れ、長いこと揺れ続ける。"),
"n1_booth_1": ("The booths. Under one cushion, a marker in Nikolai's handwriting: a name, a sum, a date.", "ボックス席。クッションの下に、ニコライの字の貸し。名前、金額、日付。"),
"n1_office_1": ("The dead man's office. The chalk is gone, the chair is where he was, and the desk has been tidied by somebody who tidies when nervous.", "死んだ男の事務室。チョークの跡は消え、椅子は彼のいた場所にあり、机は不安なときに片付ける誰かの手で整えられている。"),
"n1_desk_1": ("A key list in the drawer: three keys issued, a fourth struck through and never returned.", "引き出しの鍵一覧。三本発行、四本目は線で消され、返却されていない。"),
"n1_safe_1": ("The safe is open and nothing is missing. The alarm log is taped inside the door: set at 02:14 by the manager's code.", "金庫は開いていて、何もなくなっていない。扉の内側に警報記録。店長のコードで2時14分にセット。"),
"n1_blinds_1": ("Through the blinds: the yard, the cooler door, and the camera on Delgado Street that likes Nikolai.", "ブラインドの向こう。裏庭、冷蔵室の扉、ニコライを気に入っているデルガド通りのカメラ。"),
"n1_cooler_1": ("The walk-in cooler. Your breath goes white. Something in here was moved, and the frost remembers the shape.", "冷蔵室。息が白くなる。ここで何かが動かされ、霜がその形を覚えている。"),
"n1_rack_1": ("Under the bottom rack: a left shoe, size ten, and a yellow marker forensics forgot to take with them.", "最下段の棚の下。左の靴、10サイズ、鑑識が持ち帰り忘れた黄色いマーカー。"),
# ---------------------------------------------------------------- night 2: The Second Key
"n2_title": ("Case 2 — The Second Key", "第二の事件 — 二本目の鍵"),
"n2_sub": ("Three weeks later. The loading bay, 05:40. Doors unlocked.", "三週間後。搬入口、5時40分。ドアは開いていた。"),
"n2_open_1": ("Three weeks. The Paloma reopened for nine days and closed again at 05:40 this morning, when a bookkeeper was found in her own car with the doors unlocked.", "三週間。パロマは九日間営業を再開し、今朝5時40分にまた閉まった。帳簿係が自分の車の中で、ドアを開けたまま見つかった。"),
"n2_open_2": ("The same three names on the sheet. Nobody is surprised, which is a kind of evidence too.", "用紙には同じ三つの名前。誰も驚かない。それもまた一種の証拠だ。"),
"n2_locker_1": ("Your locker. The good suit, for court. You have not been to court in a year.", "ロッカー。法廷用の上等なスーツ。この一年、法廷には行っていない。"),
"n2_archive_1": ("The records archive: the Paloma's licence file, six years of Iris Toma's handwriting, and the dust of nobody reading any of it.", "記録保管庫。パロマの営業許可ファイル、六年分のアイリス・トマの手書き、そしてそれを誰も読まなかった埃。"),
"n2_books_1": ("Two sets. The clean one typed; the real one in her hand, with margins full of questions nobody answered.", "二組。清書の方はタイプ打ち。本物は彼女の手書きで、余白は誰も答えなかった問いで埋まっている。"),
"n2_filedrawer_1": ("In the drawer: her fountain pen, and the aspirin she kept for the nights the numbers did not add up.", "引き出しの中。彼女の万年筆と、数字の合わない夜のためのアスピリン。"),
"n2_morgue_1": ("The morgue. Cold the way the cooler was cold. Sergeant Okafor has the log, a chair, and no intention of leaving either.", "遺体安置所。冷蔵室と同じ冷たさ。オカフォー巡査部長は記録簿と椅子を持ち、どちらも離すつもりがない。"),
"n2_sergeant_1": ("\"Day shift signs. You're not day shift.\"", "「署名は日勤がする。あんたは日勤じゃない」"),
"n2_sergeant_2": ("He signs you in under a name that is not yours.", "彼はあなたでない名前であなたを記帳する。"),
"n2_drawer7_1": ("Drawer 7. The note clipped to the sheet: lungs, clean water. No diesel. No rain.", "7番の引き出し。シーツに留められた所見。肺、きれいな水。ディーゼルなし。雨水なし。"),
"n2_alley_1": ("The alley again. No tape this time; the bouncer is at a different door in a different part of town.", "また路地。今回はテープはない。バウンサーは別の街の別の扉にいる。"),
"n2_bay_1": ("The loading bay. The water is down to the ankles now. Her car is still backed in, the way she always parked: ready to leave in one move.", "搬入口。水はもう足首までに引いた。彼女の車はまだ後ろ向きに停められている。いつも通り、一手で出られるように。"),
"n2_car_1": ("Keys in the ignition. Bag on the seat. Nothing taken. Everything about the car says she meant to drive away and never got the chance to try.", "鍵はイグニッションに。バッグは座席に。何も取られていない。車のすべてが、彼女は走り去るつもりで、その機会を得なかったと言っている。"),
"n2_light_1": ("The bay light is on a timer and it is off. It does not fail. The switch for it is inside, in the mop room.", "搬入口の灯りはタイマー式で、消えている。故障しない灯りだ。スイッチは中の、モップ室にある。"),
"n2_mop_1": ("The mop room. One bulb, a bucket on its side, and a deep white sink still full of water you can see the bottom of.", "モップ室。電球一つ、横倒しのバケツ、底まで見える水で満たされた深い白いシンク。"),
"n2_sink_1": ("Deep enough to lose an arm in. Clean. The only clean water in the building.", "腕が沈むほど深い。澄んでいる。この建物で唯一のきれいな水。"),
"n2_bucket_1": ("Under the bucket, a folded twenty with a phone number on it. Somebody's marker, now yours.", "バケツの下に、電話番号を書いた二十ドル札。誰かの貸しが、あなたのものになった。"),
"n2_bar_1": ("The bar. Someone has been drinking the good bottle and not paying.", "バー。誰かが上等な瓶を飲んで、払っていない。"),
"n2_desk_1": ("Her desk now. The lamp still warm — no. Your imagination. It has been three weeks.", "今は彼女の机。ランプがまだ温かい — いや。気のせいだ。三週間経っている。"),
"n2_safe_1": ("The safe. Locked this time. Adaeze changed the code the day after.", "金庫。今回は施錠されている。アダエゼは翌日にコードを変えた。"),
# ---------------------------------------------------------------- night 3: What the Room Heard
"n3_title": ("Case 3 — What the Room Heard", "第三の事件 — 部屋が聞いたもの"),
"n3_sub": ("The last night. The fire stairs, 01:20. A folder with nothing missing.", "最後の夜。非常階段、1時20分。何も欠けていないフォルダー。"),
"n3_open_1": ("The last night. A licensing inspector on the fire stairs, a folder beside him with nothing missing from it, and an inspection booked for nine that nobody will attend.", "最後の夜。非常階段に査察官、横には何も欠けていないフォルダー、そして誰も出席しない九時の査察予定。"),
"n3_open_2": ("Adaeze has a lawyer now. Vee walked in on their own. Nikolai is already in the chair.", "アダエゼには弁護士がついた。ヴィーは自分で歩いてきた。ニコライはもう椅子に座っている。"),
"n3_drawer_1": ("Your drawer, the last night: two coffees gone cold and a marker you had forgotten you held.", "最後の夜の引き出し。冷めたコーヒー二つと、持っていたのを忘れていた貸し。"),
"n3_lawyer_1": ("\"My client will see you when I say so.\"", "「依頼人に会えるのは、私がいいと言ったときです」"),
"n3_lawyer_2": ("Twenty minutes. She means it.", "二十分。本気だ。"),
"n3_club_1": ("The Paloma, the last time. Chairs on the tables for good.", "最後のパロマ。椅子はもう永遠にテーブルの上だ。"),
"n3_safe_1": ("The safe, open. The cash banded and in place. The inner drawer pulled out and empty, and a clean rectangle in the dust the size of a ledger.", "金庫、開いている。現金は帯封のままそこにある。内側の引き出しは引き出されて空、埃に台帳の大きさのきれいな長方形。"),
"n3_desk_1": ("A folder's worth of paper clips and nothing with a name on it. The office has been cleaned by someone who knows what a file looks like.", "フォルダー一冊分のクリップと、名前の書かれたものは何一つない。ファイルの形を知っている誰かが、事務室を掃除した。"),
"n3_stairs_1": ("The fire stairs. Concrete, steel nosing, no handrail on the turn. The building has been trying to kill somebody here for thirty years.", "非常階段。コンクリート、鋼の段鼻、曲がり角に手摺りなし。この建物は三十年、ここで誰かを殺そうとしてきた。"),
"n3_landing_1": ("Bo's folder, where it fell. Open. Nothing missing. Everything in it is about the Paloma, and none of it is about why he was in the office.", "ボーのフォルダー、落ちた場所に。開いている。欠けているものはない。中身はすべてパロマについてで、彼がなぜ事務室にいたかについては何もない。"),
"n3_flat_1": ("Adaeze's flat, over the club. Lights off. A coat on a chair. From the window you can see the yard wall and the square of light the office throws on it.", "クラブの上のアダエゼの部屋。灯りは消えている。椅子にコート。窓からは裏庭の壁と、事務室が投げる四角い光が見える。"),
"n3_window_1": ("The office light. From here you would have watched it go out.", "事務室の灯り。ここからなら、消えるのを見ていられただろう。"),
"n3_sofa_1": ("Between the cushions: a pair of gold cufflinks. Not hers. You know whose.", "クッションの間に、金のカフスボタン。彼女のものではない。誰のものか、あなたは知っている。"),
"n3_yard_1": ("The vent by the yard door. Put your ear to it and the office speaks. Not words. That there are words.", "裏庭の扉の脇の通気口。耳を当てれば事務室が話す。言葉ではない。言葉があるということが。"),
"n3_dumpster_1": ("A bottle, mostly full, thrown away by someone in a hurry.", "ほぼ満杯の瓶。急いでいた誰かが捨てたもの。"),
# ---------------------------------------------------------------- epilogue: the safe house
"ep_title": ("Epilogue — The safe house", "エピローグ — 隠れ家"),
"ep_sub": ("After the last file. One lamp.", "最後のファイルの後。ランプ一つ。"),
"ep_all": ("You got all three. Nobody hands you anything for that. You did not expect them to.", "三件すべて解決した。誰も何も渡してはくれない。期待もしていなかった。"),
"ep_some": ("You did not get all three. The rest sit in a drawer with your name on the tab.", "三件すべてではなかった。残りは、あなたの名前のタブがついた引き出しの中だ。"),
"ep_safe_1": ("The safe house. One lamp. Somebody knocks the way people knock when they have decided something on the stairs.", "隠れ家。ランプ一つ。階段で何かを決めてきた人間のノックが聞こえる。"),
"ep_nikolai_1": ("\"Third time I have come to you. First time nobody sent me.\"", "「お前のところに来るのは三度目だ。誰にも送られずに来たのは初めてだ」"),
"ep_nikolai_2": ("He takes off the signet ring and puts it on the table, which is the only confession he will ever make.", "彼は印章指輪を外してテーブルに置く。それが彼が生涯にする唯一の自白だ。"),
"ep_nikolai_3": ("You do not write it down. For an hour there is no file, no Paloma, and nobody's name on anything.", "あなたは書き留めない。一時間、ファイルも、パロマも、誰の名前も、どこにもない。"),
"ep_nikolai_no": ("Nikolai, at the door. He looks at you a long moment, then goes back down the stairs. Whatever he came to say, there was not enough between you for it.", "扉の前にニコライ。長くあなたを見て、階段を降りていく。言いに来たことが何であれ、二人の間にはそのための十分なものがなかった。"),
"ep_adaeze_1": ("\"I am not on any page tonight. I checked.\"", "「今夜は私はどのページにも載っていない。確かめた」"),
"ep_adaeze_2": ("She hangs her coat on your hook as if the hook were hers.", "彼女はコートをあなたのフックに掛ける。フックが自分のものであるかのように。"),
"ep_adaeze_3": ("Later she spells your name, slowly, to see if you will correct her.", "あとで彼女はあなたの名前をゆっくり綴る。訂正するかどうか、見るために。"),
"ep_adaeze_no": ("Adaeze, at the door. She says your name correctly, once, and leaves. That is all there was room for.", "扉の前にアダエゼ。あなたの名前を一度正しく言って、去る。それだけの余地しかなかった。"),
"ep_vee_1": ("\"Nobody came and got me. I walked. I keep telling you that.\"", "「誰も迎えに来なかった。歩いてきた。ずっとそう言ってる」"),
"ep_vee_2": ("Vee sits on the edge of the mattress and the shaking stops, for once, because of a room instead of in spite of one.", "ヴィーはマットレスの端に座り、震えが止まる。初めて、部屋のせいでではなく、部屋のおかげで。"),
"ep_vee_3": ("Dawn through the broken blinds. Vee is still here. That has to be worth something. It is.", "壊れたブラインドから夜明け。ヴィーはまだここにいる。それは何かの価値があるはずだ。ある。"),
"ep_vee_no": ("Vee, at the door. Vee does not come in, and you do not ask, and both of you know that was the kind thing.", "扉の前にヴィー。入ってこず、あなたも頼まない。それが優しさだったと、二人とも知っている。"),
"ep_lamp_1": ("You turn off the lamp. Somewhere a captain is signing something without reading it.", "ランプを消す。どこかで署長が、読まずに何かに署名している。"),
}
