## Loc — the UI language (autoload "Loc").
##
## STANDARD §7 asks for en + zh minimum, with **ja as the priority** — 507 of the 581
## DLsite works we scraped are Japanese, and without it this game is not on that shelf.
## This file ships **en, zh, zh-Hant and ja**.
##
## ja was added on 2026-09-21, and it was added the way the rest of that rule demands
## rather than as a button. "Never offer a language you did not actually translate" is
## what Floor 13 broke by shipping ja/ko/es whose story files held Chinese prose, and this
## game's text is not its chrome — it is 64 card faces, 225 of her reply lines, five
## scenario rows and ten ending beats. All of it is translated:
##
##   backend/replies_ja.py    her 225 replies, keyed identically to replies.R, one voice
##                            per character (Teodora starts in です／ます and ends in plain
##                            form, which is the character rather than a style choice)
##   backend/cards_ja.py      the 64 printed card faces — DISPLAY ONLY; the engine still
##                            decomposes the English `line`, so a card cannot mean two
##                            different things in two languages
##   backend/scenarios.json   *_ja for title / character / goal / story / the three CG
##                            captions / closing_beat / refusal_beat
##
## The one honest gap, written down rather than hidden: a `wild` line the player types is
## scored by the English decomposer in persuasion_engine, so a Japanese player's own words
## score as a neutral wild instead of being read for signals. Every printed card is
## unaffected. Fixing it needs a Japanese decomposer, which is its own job.
##
## zh and zh-Hant remain what they were — the scenario rows and this chrome — and her
## reply lines are still English there. That is a real gap too, and it is the next one.
extends Node

signal changed(code: String)

# code -> (endonym, does the DATA carry this locale). A language whose data column is
# empty must never appear in the picker, whatever the chrome below says.
## Seven, plus zh-Hant (2026-09-24, memory `seven-languages-default`): every title on
## Nutaku and DLsite ships EN, JA, DE, FR, ES, zh, KO. de/fr/es/ko carry the whole campaign
## (assets/i18n/src/<lang>.json) and this chrome; the order is the language menu's.
const LANGS := [
	{"code": "en", "name": "English"},
	{"code": "ja", "name": "日本語"},
	{"code": "de", "name": "Deutsch"},
	{"code": "fr", "name": "Français"},
	{"code": "es", "name": "Español"},
	{"code": "zh", "name": "中文"},
	{"code": "ko", "name": "한국어"},
	{"code": "zh-Hant", "name": "繁體中文"},
]

const SAVE := "user://locale.cfg"

## The Night Ledger's words (Nutaku F2P): everything the title server sends a player --
## story, stages, her replies, card lines, bond scenes, store items, missions, refusals --
## keyed on the exact English string the server sends, built by
## tools/campaign_i18n.py and checked by ops/nutaku/suasion_f2p/check_i18n.py. The server
## stays English on purpose (card lines are rules the engine reads; replies are picked by
## the replay's seeded rng), so translating on arrival is the only place this can live.
const CAMPAIGN := "res://assets/i18n/campaign.json"
var _campaign := {}
var _num := RegEx.create_from_string("\\d+(?:\\.\\d+)?")

var _code := "en"

# Only the client's own chrome. Keys are the English string, so an untranslated key falls
# through to itself and a missing translation is visible rather than blank.
const T := {
	"ja": {
		# update packs, events, auto-battle, the missing pages (2026-09-24)
		"EVENT: %s": "イベント：%s",
		"THE MISSING PAGES · %d": "失われたページ · %d",
		"THE MISSING PAGES": "失われたページ",
		"AUTO ×1 · 1 CHARM": "オート×1 · 魅力1",
		"AUTO ×5 · 5 CHARM": "オート×5 · 魅力5",
		"Auto: won %d of %d.": "オート：%d勝 / %d戦。",
		"%d CARDS": "カード%d枚",
		"ENDS IN %d DAYS": "残り%d日",
		"REWARD TRACK": "報酬トラック",
		"CLAIM": "受け取る",
		"CLAIMED": "受取済み",
		"+%d CHARM": "魅力+%d",
		"%s'S CARD": "%sのカード",
		"+%d %s · %d in all": "+%d %s · 合計%d",
		"marks": "マーク",
		"ON: %s · %d DAYS LEFT": "開催中：%s · 残り%d日",
		"BANNER: %s · %d DAYS LEFT": "バナー：%s · 残り%d日",
		"TONIGHT": "今夜",
		"DUELS": "対話", "GACHA": "ガチャ", "AFFECTION": "好感度", "DECK": "デッキ",
		"RANK": "難易度", "GENTLE": "やさしい", "SILVER": "シルバー", "GOLD": "ゴールド",
		"GOLD_TAG": "ゴールド",
		"DUEL": "はじめる", "DAILY": "デイリー", "FREE": "無料", "PLAY": "出す", "BACK": "もどる",
		"NERVE": "度胸", "MOMENTUM": "流れ", "TURN": "ターン", "DECK LEFT": "残り",
		"WILD": "自分の言葉で", "FORFEIT": "降参", "CONTINUE": "つづける",
		"PERSUADED": "彼女は応じた", "REFUSED": "彼女は断った",
		"GUARDED": "警戒", "ENGAGED": "傾聴", "WAVERING": "動揺", "BREAKTHROUGH": "陥落",
		"SHE NEEDS": "彼女が求めるもの", "HELPS": "効果あり", "ON THE RECORD": "記録済み",
		"PULL 1": "単発", "PULL 10": "10連", "NEW": "NEW",
		"NO BACKEND — PLAYING OFFLINE": "オフラインでプレイ中",
		"Five people, one evening each. Bring a deck; every card is a sentence. The engine reads it. She answers. A duel costs 3 energy; today's is free and pays double affection.":
			"五人、それぞれに一夜ずつ。デッキを持って行く。カードはどれも一つの台詞で、エンジンがそれを読み、彼女が答える。対話一回につきスタミナ3。今日の一回は無料で、好感度は二倍。",
		"Nothing sold changes the turn count or what she needs.":
			"課金でターン数は変わらないし、彼女が聞きたいことも変わらない。",
		"PRESS ANY KEY": "何かキーを押してください",
		"LANGUAGE": "言語",
		"COMMON": "コモン",
		"RARE": "レア",
		"EPIC": "エピック",
		"WILD · once": "ワイルド · 1回",
		"Say it in your own words.": "自分の言葉で言う。",
		"the engine reads it": "読むのはエンジン",
		"CLOSED · ": "打ち切り · ",
		# the persuasion vocabulary — the chips on a card and in SHE NEEDS
		"respect": "敬意",
		"accountability": "責任",
		"exchange": "取引",
		"evidence": "根拠",
		"safety": "安心",
		"empathy": "共感",
		"precision": "正確さ",
		"authority": "裏づけ",
		"warmth": "あたたかさ",
		"craft": "仕事",
		"specific_praise": "具体的な賞賛",
		"riddle": "なぞかけ",
		"calm_action": "落ち着いた行動",
		"direct_request": "率直な依頼",
		"cooperation": "協力",
		"threat": "脅し",
		"bribe": "買収",
		"insult": "侮辱",
		"entitlement": "当然視",
		"TURNS %d/%d": "ターン %d/%d",
		"DECK %d": "デッキ %d",
		"LEAVE": "やめる",
		"SAY IT": "言う",
		"CLOSED": "打ち切り",
		"OUT OF WORDS": "言葉切れ",
		"BACK TO THE BAR": "カウンターに戻る",
		"SEE THE PLATE": "絵を見る",
		"MORE LIKE THIS": "似た作品",
		"♥ AFFECTION  (+%d)": "♥ 好感度  (+%d)",
		"◆ GOLD": "◆ ゴールド",
		"DROP →": "ドロップ →",
		"You have beaten %d%% of players today.":
			"本日のプレイヤーの %d%% を上回りました。",
		"Say it in your own words — the engine reads it, nobody else does":
			"自分の言葉で言ってください——読むのはエンジンだけで、ほかの誰でもありません",
		"TODAY · FREE · ×2 AFFECTION": "本日 · 無料 · 好感度×2",
		"DUEL · 3⚡": "はじめる · 3⚡",
		"DAILY · FREE": "デイリー · 無料",
		"DAILY DONE": "デイリー完了",
		"GENTLE · 18": "やさしい · 18",
		"SILVER · 15": "シルバー · 15",
		"GOLD · 10": "ゴールド · 10",
		"Common 70 · Rare 25 · Epic 5. A ten-pull always holds a rare; every thirtieth pull is an epic. Cards add sentences you can say. They do not change what she needs.":
			"コモン70 · レア25 · エピック5。10連には必ずレアが入り、30回ごとに必ずエピックが出ます。カードは言えることを増やすだけで、彼女が求めるものは変わりません。",
		"1 PULL · %d": "単発 · %d",
		"10 PULL · %d": "10連 · %d",
		"PULLS %d · EPIC PITY IN %d · CREDITS %d":
			"抽数 %d · エピック天井まで %d · 無料分 %d",
		"DUPE": "重複",
		"PITY": "天井",
		"SAVE DECK": "デッキを保存",
		"AUTO": "おまかせ",
		"Pick up to %d. Copies count. The wild card is always in the deck and never counts.":
			"最大 %d 枚まで。同じカードも枚数に数えます。ワイルドは常にデッキにあり、枚数には数えません。",
		"%d/%d in deck": "デッキに %d/%d",
		"Affection is the count of duels won against her. Plates unlock at 1, 3 and 6 wins; the fourth rung at 10 is a scene of Blaze's own and is a placeholder in this build. Nothing here unlocks from time.":
			"好感度は、その人に勝った対話の回数です。1勝・3勝・6勝で絵が解放されます。10勝の四段目はこのビルドでは仮置きです。時間で解放されるものはありません。",
		# --- Nutaku F2P (SUASION: The Night Ledger) ---
		" — tickets are in the store": "——チケットはストアで",
		"%d CHIPS": "チップ %d",
		"%d DUPES — already in your collection": "%d 枚重複——すでに所持しています",
		"1 DUPE — already in your collection": "1 枚重複——すでに所持しています",
		"%d GOLD": "%d ゴールド",
		"%d TICKETS": "チケット %d 枚",
		"1 TICKET": "チケット 1 枚",
		"%d TURNS": "%d ターン",
		"(She is still waiting.)": "（彼女はまだ待っている。）",
		"(You say nothing.)": "（何も言わない。）",
		"+1 in %d:%02d": "あと %d:%02d で +1",
		"1 PULL · %d CHIPS": "単発 · チップ %d",
		"1 PULL · 1 TICKET": "単発 · チケット 1 枚",
		"10 PULL · %d CHIPS": "10連 · チップ %d",
		"10 PULL · 10 TICKETS": "10連 · チケット 10 枚",
		"A card that adds nothing new costs two turns.": "新しいものを何も足さないカードは2ターンかかる。",
		"AFTER HOURS · CARDS": "アフターアワーズ · カード",
		"BOND": "絆",
		"BOSS": "ボス",
		"RIVAL": "ライバル",
		"BUILD THE DECK FOR THIS NIGHT": "この夜のデッキを組む",
		"Backend unreachable: ": "サーバーに接続できません：",
		"Bond is the count of nights won against her. Her plates open at 3 and 10 bond; the rung at 30 is a scene still being written. Nothing here unlocks from time.": "絆は、彼女に勝った夜の数。絆3と10で絵が開く。30の段はまだ書いている途中の一場面。時間で開くものはここにはない。",
		"CHARM %d (refills to %d)": "チャーム %d（自然回復は %d まで）",
		"CHARM %d/%d": "チャーム %d/%d",
		"CHIPS · %d TICKETS": "チップ · チケット %d 枚",
		"CHIPS · 1 TICKET": "チップ · チケット 1 枚",
		"CLAIM TODAY'S REWARD": "今日の報酬を受け取る",
		"Cancelled.": "キャンセルしました。",
		"Celeste's cut: she took your costliest card.": "セレストの横やり：いちばん重いカードを持っていかれた。",
		"Claimed.": "受け取りました。",
		"Could not save the deck.": "デッキを保存できませんでした。",
		"DAILY DUEL FREE": "今日の対話は無料",
		"Deck saved": "デッキを保存しました",
		"Delivered.": "お届けしました。",
		"Every %d turns she takes your costliest card.": "%d ターンごとに、手札でいちばん重いカードを彼女が取っていく。",
		"HOLD YOUR TONGUE": "黙る",
		"LAST CALL": "ラストコール",
		"LAST CALL (after the boss)": "ラストコール（ボスのあとで）",
		"NIGHT PASS · CLAIM": "ナイトパス · 受け取る",
		"PLAY AGAIN · 1 CHARM": "もう一度 · チャーム 1",
		"PLAY · 1 CHARM": "はじめる · チャーム 1",
		"Paid in Nutaku gold (100 gold = $1). Everything in the story can be won without it; gold only makes it sooner.": "Nutakuゴールドで支払い（100ゴールド＝1ドル）。物語のすべてはゴールドなしで手に入る。ゴールドは早めるだけ。",
		"Plate not available offline.": "オフラインでは絵を表示できません。",
		"Plate not available.": "絵を表示できません。",
		"Purchase failed.": "購入できませんでした。",
		"RESOLVE": "決意",
		"RESOLVE %d": "決意 %d",
		"RESOLVE %d/%d": "決意 %d/%d",
		"SIT DOWN ACROSS FROM HER": "彼女の向かいに座る",
		"WHO YOU HAVE PERSUADED": "口説き落とした人たち",
		"STANDING ★%d": "格 ★%d",
		"STORE": "ストア",
		"STORY SO FAR": "これまでの話",
		"THE STORY SO FAR": "これまでの話",
		"Say nothing: spend a turn, refill your nerve, draw a fresh hand.": "何も言わない：1ターン使い、度胸を戻し、手札を引き直す。",
		"She has every reason to say no.": "断る理由なら、彼女にはいくらでもある。",
		"She talked straight over it.": "彼女はそのまま話をかぶせてきた。",
		"She talks over your first card.": "最初のカードには、彼女が話をかぶせてくる。",
		"THE NIGHT LEDGER": "夜の台帳",
		"THE NIGHTS": "夜ごとの対話",
		"TONIGHT'S REMATCH · FREE": "今夜の再戦 · 無料",
		"The purchase did not go through; Nutaku has refunded the gold.": "購入は完了しませんでした。ゴールドはNutakuが返金済みです。",
		"The server did not accept this duel: ": "サーバーがこの対話を認めませんでした：",
		"VELL, AFTER TWO": "ヴェル、午前二時過ぎ",
		"Wrong order — she closed the door.": "順番が違う——彼女はドアを閉めた。",
		"You": "あなた",
		"You hold %d cards.": "手札は %d 枚。",
		"at %d bond": "絆 %d で",
		"at %d wins": "%d 勝で",
		"locked": "ロック中",
		"needs bond %d with %s (%d)": "絆 %d が必要（%s、現在 %d）",
		"needs standing ★%d (%d)": "格 ★%d が必要（現在 %d）",
		"still to come": "準備中",
		"tap to close": "タップで閉じる",
		"tier %d": "第 %d 段",
		"tier %d · at %d": "第 %d 段 · %d",
		"◆ CHIPS": "◆ チップ",
		"♥ BOND  (+%d)": "♥ 絆  (+%d)",
		"FOR %s (%s) · SHE HEARS: %s · %d OF YOUR CARDS CAN ACT TONIGHT": "今夜：%s（%s）· 彼女に届くもの：%s · 今夜使えるカードは %d 枚",
		"not tonight": "今夜は使えない",
		"She will not hear this card tonight: it carries none of what she wants.": "今夜このカードは彼女に届かない。彼女が求めるものを何も持っていない。",
		"LEDGER": "台帳",
	},
	"zh": {
		# update packs, events, auto-battle, the missing pages (2026-09-24)
		"EVENT: %s": "活动：%s",
		"THE MISSING PAGES · %d": "遗失的书页 · %d",
		"THE MISSING PAGES": "遗失的书页",
		"AUTO ×1 · 1 CHARM": "自动×1 · 1点魅力",
		"AUTO ×5 · 5 CHARM": "自动×5 · 5点魅力",
		"Auto: won %d of %d.": "自动：赢%d场，共%d场。",
		"%d CARDS": "%d张卡",
		"ENDS IN %d DAYS": "还剩%d天",
		"REWARD TRACK": "奖励线",
		"CLAIM": "领取",
		"CLAIMED": "已领取",
		"+%d CHARM": "魅力+%d",
		"%s'S CARD": "%s的卡",
		"+%d %s · %d in all": "+%d %s · 共%d",
		"marks": "印记",
		"ON: %s · %d DAYS LEFT": "已选：%s · 还剩%d天",
		"BANNER: %s · %d DAYS LEFT": "限定卡池：%s · 还剩%d天",
		"TONIGHT": "今夜",
		"DUELS": "对话", "GACHA": "抽卡", "AFFECTION": "好感", "DECK": "牌组",
		"RANK": "难度", "GENTLE": "温和", "SILVER": "白银", "GOLD": "黄金",
		"GOLD_TAG": "金币",
		"DUEL": "开始", "DAILY": "今日", "FREE": "免费", "PLAY": "出牌", "BACK": "返回",
		"NERVE": "胆识", "MOMENTUM": "势头", "TURN": "回合", "DECK LEFT": "剩余",
		"WILD": "自由发言", "FORFEIT": "认输", "CONTINUE": "继续",
		"PERSUADED": "她答应了", "REFUSED": "她拒绝了",
		"GUARDED": "戒备", "ENGAGED": "在听", "WAVERING": "动摇", "BREAKTHROUGH": "松口",
		"SHE NEEDS": "她需要", "HELPS": "有帮助", "ON THE RECORD": "已记录",
		"PULL 1": "单抽", "PULL 10": "十连", "NEW": "新",
		"NO BACKEND — PLAYING OFFLINE": "离线游玩",
		"Five people, one evening each. Bring a deck; every card is a sentence. The engine reads it. She answers. A duel costs 3 energy; today's is free and pays double affection.":
			"五个人，一人一夜。带上你的牌组；每张牌都是一句话。引擎读它，她来回答。一场对话消耗 3 点体力；今日这场免费，好感翻倍。",
		"Nothing sold changes the turn count or what she needs.":
			"任何付费都不会改变回合数，也不会改变她要听到的话。",
		"PRESS ANY KEY": "按任意键",
		"LANGUAGE": "语言",
		"COMMON": "普通",
		"RARE": "稀有",
		"EPIC": "史诗",
		"WILD · once": "自由发言 · 一次",
		"Say it in your own words.": "用你自己的话说。",
		"the engine reads it": "由引擎读取",
		"CLOSED · ": "已结束 · ",
		# the persuasion vocabulary — the chips on a card and in SHE NEEDS
		"respect": "尊重",
		"accountability": "担责",
		"exchange": "交换",
		"evidence": "证据",
		"safety": "安全感",
		"empathy": "共情",
		"precision": "精确",
		"authority": "权威",
		"warmth": "温度",
		"craft": "手艺",
		"specific_praise": "具体的称赞",
		"riddle": "谜题",
		"calm_action": "冷静的举动",
		"direct_request": "直接请求",
		"cooperation": "协作",
		"threat": "威胁",
		"bribe": "收买",
		"insult": "侮辱",
		"entitlement": "理所当然",
		"TURNS %d/%d": "回合 %d/%d",
		"DECK %d": "牌组 %d",
		"LEAVE": "离开",
		"SAY IT": "说出口",
		"CLOSED": "结束",
		"OUT OF WORDS": "无话可说",
		"BACK TO THE BAR": "回到吧台",
		"SEE THE PLATE": "查看插图",
		"MORE LIKE THIS": "更多这样的",
		"♥ AFFECTION  (+%d)": "♥ 好感  (+%d)",
		"◆ GOLD": "◆ 金币",
		"DROP →": "掉落 →",
		"You have beaten %d%% of players today.":
			"你今天超过了 %d%% 的玩家。",
		"Say it in your own words — the engine reads it, nobody else does":
			"用你自己的话说——读它的是引擎，不是别人",
		"TODAY · FREE · ×2 AFFECTION": "今日 · 免费 · 好感×2",
		"DUEL · 3⚡": "开始 · 3⚡",
		"DAILY · FREE": "今日 · 免费",
		"DAILY DONE": "今日已完成",
		"GENTLE · 18": "温和 · 18",
		"SILVER · 15": "白银 · 15",
		"GOLD · 10": "黄金 · 10",
		"Common 70 · Rare 25 · Epic 5. A ten-pull always holds a rare; every thirtieth pull is an epic. Cards add sentences you can say. They do not change what she needs.":
			"普通70 · 稀有25 · 史诗5。十连必出稀有，每三十抽必出史诗。卡牌只增加你能说的话，不会改变她要听的东西。",
		"1 PULL · %d": "单抽 · %d",
		"10 PULL · %d": "十连 · %d",
		"PULLS %d · EPIC PITY IN %d · CREDITS %d":
			"已抽 %d · 史诗保底还差 %d · 免费次数 %d",
		"DUPE": "重复",
		"PITY": "保底",
		"SAVE DECK": "保存牌组",
		"AUTO": "自动",
		"Pick up to %d. Copies count. The wild card is always in the deck and never counts.":
			"最多选 %d 张。重复的也计数。自由发言牌始终在牌组里，且不计入数量。",
		"%d/%d in deck": "牌组中 %d/%d",
		"Affection is the count of duels won against her. Plates unlock at 1, 3 and 6 wins; the fourth rung at 10 is a scene of Blaze's own and is a placeholder in this build. Nothing here unlocks from time.":
			"好感是你赢下的对话次数。1、3、6 胜各解锁一张插图；10 胜的第四级在本版本中是占位。这里没有任何东西靠时间解锁。",
		# --- Nutaku F2P (SUASION: The Night Ledger) ---
		" — tickets are in the store": "——抽卡券在商店里",
		"%d CHIPS": "%d 筹码",
		"%d DUPES — already in your collection": "%d 张重复——你已经有了",
		"1 DUPE — already in your collection": "1 张重复——你已经有了",
		"%d GOLD": "%d 金币",
		"%d TICKETS": "%d 张抽卡券",
		"1 TICKET": "1 张抽卡券",
		"%d TURNS": "%d 回合",
		"(She is still waiting.)": "（她还在等。）",
		"(You say nothing.)": "（你什么也没说。）",
		"+1 in %d:%02d": "%d:%02d 后 +1",
		"1 PULL · %d CHIPS": "单抽 · %d 筹码",
		"1 PULL · 1 TICKET": "单抽 · 1 张抽卡券",
		"10 PULL · %d CHIPS": "十连 · %d 筹码",
		"10 PULL · 10 TICKETS": "十连 · 10 张抽卡券",
		"A card that adds nothing new costs two turns.": "没有新意的牌要花两个回合。",
		"AFTER HOURS · CARDS": "打烊之后 · 卡牌",
		"BOND": "羁绊",
		"BOSS": "首领",
		"RIVAL": "对手",
		"BUILD THE DECK FOR THIS NIGHT": "为这一夜组牌",
		"Backend unreachable: ": "连不上服务器：",
		"Bond is the count of nights won against her. Her plates open at 3 and 10 bond; the rung at 30 is a scene still being written. Nothing here unlocks from time.": "羁绊就是你赢下她的夜数。羁绊 3 和 10 时各解锁一张插图；30 那一级是一场还在写的场景。这里没有任何东西靠时间解锁。",
		"CHARM %d (refills to %d)": "魅力 %d（回复上限 %d）",
		"CHARM %d/%d": "魅力 %d/%d",
		"CHIPS · %d TICKETS": "筹码 · %d 张抽卡券",
		"CHIPS · 1 TICKET": "筹码 · 1 张抽卡券",
		"CLAIM TODAY'S REWARD": "领取今日奖励",
		"Cancelled.": "已取消。",
		"Celeste's cut: she took your costliest card.": "赛莱斯特插话：她拿走了你最贵的那张牌。",
		"Claimed.": "已领取。",
		"Could not save the deck.": "牌组没能保存。",
		"DAILY DUEL FREE": "今日对决免费",
		"Deck saved": "牌组已保存",
		"Delivered.": "已到账。",
		"Every %d turns she takes your costliest card.": "每 %d 回合，她会拿走你手里最贵的牌。",
		"HOLD YOUR TONGUE": "沉默",
		"LAST CALL": "最后一轮",
		"LAST CALL (after the boss)": "最后一轮（击败首领后开放）",
		"NIGHT PASS · CLAIM": "夜间通行证 · 领取",
		"PLAY AGAIN · 1 CHARM": "再来一次 · 1 魅力",
		"PLAY · 1 CHARM": "开始 · 1 魅力",
		"Paid in Nutaku gold (100 gold = $1). Everything in the story can be won without it; gold only makes it sooner.": "用 Nutaku 金币支付（100 金币 = 1 美元）。故事里的一切不花钱也能赢到；金币只是让它来得更快。",
		"Plate not available offline.": "离线时看不到插图。",
		"Plate not available.": "插图暂时无法显示。",
		"Purchase failed.": "购买失败。",
		"RESOLVE": "决心",
		"RESOLVE %d": "决心 %d",
		"RESOLVE %d/%d": "决心 %d/%d",
		"SIT DOWN ACROSS FROM HER": "在她对面坐下",
		"WHO YOU HAVE PERSUADED": "你说服过的人",
		"STANDING ★%d": "声望 ★%d",
		"STORE": "商店",
		"STORY SO FAR": "前情",
		"THE STORY SO FAR": "前情回顾",
		"Say nothing: spend a turn, refill your nerve, draw a fresh hand.": "什么也不说：用掉一个回合，胆识回满，换一手新牌。",
		"She has every reason to say no.": "她有一万个理由拒绝。",
		"She talked straight over it.": "她直接把你的话盖了过去。",
		"She talks over your first card.": "你的第一张牌，她会直接盖过去。",
		"THE NIGHT LEDGER": "夜之账簿",
		"THE NIGHTS": "夜晚",
		"TONIGHT'S REMATCH · FREE": "今晚重赛 · 免费",
		"The purchase did not go through; Nutaku has refunded the gold.": "购买没有完成；Nutaku 已退还金币。",
		"The server did not accept this duel: ": "服务器没有认可这场对决：",
		"VELL, AFTER TWO": "维尔，凌晨两点后",
		"Wrong order — she closed the door.": "顺序错了——她关上了门。",
		"You": "你",
		"You hold %d cards.": "你手里只有 %d 张牌。",
		"at %d bond": "羁绊 %d",
		"at %d wins": "%d 胜时",
		"locked": "未解锁",
		"needs bond %d with %s (%d)": "需要羁绊 %d（与%s，现有 %d）",
		"needs standing ★%d (%d)": "需要声望 ★%d（现有 %d）",
		"still to come": "敬请期待",
		"tap to close": "点按关闭",
		"tier %d": "第 %d 级",
		"tier %d · at %d": "第 %d 级 · %d",
		"◆ CHIPS": "◆ 筹码",
		"♥ BOND  (+%d)": "♥ 羁绊  (+%d)",
		"FOR %s (%s) · SHE HEARS: %s · %d OF YOUR CARDS CAN ACT TONIGHT": "今夜：%s（%s）· 她听得进：%s · 你有 %d 张牌今晚能起作用",
		"not tonight": "今晚用不上",
		"She will not hear this card tonight: it carries none of what she wants.": "今晚她听不进这张牌：它不带她想要的任何东西。",
		"LEDGER": "账簿",
	},
	"zh-Hant": {
		# update packs, events, auto-battle, the missing pages (2026-09-24)
		"EVENT: %s": "活動：%s",
		"THE MISSING PAGES · %d": "遺失的書頁 · %d",
		"THE MISSING PAGES": "遺失的書頁",
		"AUTO ×1 · 1 CHARM": "自動×1 · 1點魅力",
		"AUTO ×5 · 5 CHARM": "自動×5 · 5點魅力",
		"Auto: won %d of %d.": "自動：贏%d場，共%d場。",
		"%d CARDS": "%d張卡",
		"ENDS IN %d DAYS": "還剩%d天",
		"REWARD TRACK": "獎勵線",
		"CLAIM": "領取",
		"CLAIMED": "已領取",
		"+%d CHARM": "魅力+%d",
		"%s'S CARD": "%s的卡",
		"+%d %s · %d in all": "+%d %s · 共%d",
		"marks": "印記",
		"ON: %s · %d DAYS LEFT": "已選：%s · 還剩%d天",
		"BANNER: %s · %d DAYS LEFT": "限定卡池：%s · 還剩%d天",
		"TONIGHT": "今夜",
		"DUELS": "對話", "GACHA": "抽卡", "AFFECTION": "好感", "DECK": "牌組",
		"RANK": "難度", "GENTLE": "溫和", "SILVER": "白銀", "GOLD": "黃金",
		"GOLD_TAG": "金幣",
		"DUEL": "開始", "DAILY": "今日", "FREE": "免費", "PLAY": "出牌", "BACK": "返回",
		"NERVE": "膽識", "MOMENTUM": "勢頭", "TURN": "回合", "DECK LEFT": "剩餘",
		"WILD": "自由發言", "FORFEIT": "認輸", "CONTINUE": "繼續",
		"PERSUADED": "她答應了", "REFUSED": "她拒絕了",
		"GUARDED": "戒備", "ENGAGED": "在聽", "WAVERING": "動搖", "BREAKTHROUGH": "鬆口",
		"SHE NEEDS": "她需要", "HELPS": "有幫助", "ON THE RECORD": "已記錄",
		"PULL 1": "單抽", "PULL 10": "十連", "NEW": "新",
		"NO BACKEND — PLAYING OFFLINE": "離線遊玩",
		"Five people, one evening each. Bring a deck; every card is a sentence. The engine reads it. She answers. A duel costs 3 energy; today's is free and pays double affection.":
			"五個人，一人一夜。帶上你的牌組；每張牌都是一句話。引擎讀它，她來回答。一場對話消耗 3 點體力；今日這場免費，好感翻倍。",
		"Nothing sold changes the turn count or what she needs.":
			"任何付費都不會改變回合數，也不會改變她要聽到的話。",
		"PRESS ANY KEY": "按任意鍵",
		"LANGUAGE": "語言",
		"COMMON": "普通",
		"RARE": "稀有",
		"EPIC": "史詩",
		"WILD · once": "自由發言 · 一次",
		"Say it in your own words.": "用你自己的話說。",
		"the engine reads it": "由引擎讀取",
		"CLOSED · ": "已結束 · ",
		# the persuasion vocabulary — the chips on a card and in SHE NEEDS
		"respect": "尊重",
		"accountability": "擔責",
		"exchange": "交換",
		"evidence": "證據",
		"safety": "安全感",
		"empathy": "共情",
		"precision": "精確",
		"authority": "權威",
		"warmth": "溫度",
		"craft": "手藝",
		"specific_praise": "具體的稱讚",
		"riddle": "謎題",
		"calm_action": "冷靜的舉動",
		"direct_request": "直接請求",
		"cooperation": "協作",
		"threat": "威脅",
		"bribe": "收買",
		"insult": "侮辱",
		"entitlement": "理所當然",
		"TURNS %d/%d": "回合 %d/%d",
		"DECK %d": "牌組 %d",
		"LEAVE": "離開",
		"SAY IT": "說出口",
		"CLOSED": "結束",
		"OUT OF WORDS": "無話可說",
		"BACK TO THE BAR": "回到吧台",
		"SEE THE PLATE": "查看插圖",
		"MORE LIKE THIS": "更多這樣的",
		"♥ AFFECTION  (+%d)": "♥ 好感  (+%d)",
		"◆ GOLD": "◆ 金幣",
		"DROP →": "掉落 →",
		"You have beaten %d%% of players today.":
			"你今天超過了 %d%% 的玩家。",
		"Say it in your own words — the engine reads it, nobody else does":
			"用你自己的話說——讀它的是引擎，不是別人",
		"TODAY · FREE · ×2 AFFECTION": "今日 · 免費 · 好感×2",
		"DUEL · 3⚡": "開始 · 3⚡",
		"DAILY · FREE": "今日 · 免費",
		"DAILY DONE": "今日已完成",
		"GENTLE · 18": "溫和 · 18",
		"SILVER · 15": "白銀 · 15",
		"GOLD · 10": "黃金 · 10",
		"Common 70 · Rare 25 · Epic 5. A ten-pull always holds a rare; every thirtieth pull is an epic. Cards add sentences you can say. They do not change what she needs.":
			"普通70 · 稀有25 · 史詩5。十連必出稀有，每三十抽必出史詩。卡牌只增加你能說的話，不會改變她要聽的東西。",
		"1 PULL · %d": "單抽 · %d",
		"10 PULL · %d": "十連 · %d",
		"PULLS %d · EPIC PITY IN %d · CREDITS %d":
			"已抽 %d · 史詩保底還差 %d · 免費次數 %d",
		"DUPE": "重複",
		"PITY": "保底",
		"SAVE DECK": "保存牌組",
		"AUTO": "自動",
		"Pick up to %d. Copies count. The wild card is always in the deck and never counts.":
			"最多選 %d 張。重複的也計數。自由發言牌始終在牌組裡，且不計入數量。",
		"%d/%d in deck": "牌組中 %d/%d",
		"Affection is the count of duels won against her. Plates unlock at 1, 3 and 6 wins; the fourth rung at 10 is a scene of Blaze's own and is a placeholder in this build. Nothing here unlocks from time.":
			"好感是你贏下的對話次數。1、3、6 勝各解鎖一張插圖；10 勝的第四級在本版本中是占位。這裡沒有任何東西靠時間解鎖。",
		# --- Nutaku F2P (SUASION: The Night Ledger) ---
		" — tickets are in the store": "——抽卡券在商店裡",
		"%d CHIPS": "%d 籌碼",
		"%d DUPES — already in your collection": "%d 張重複——你已經有了",
		"1 DUPE — already in your collection": "1 張重複——你已經有了",
		"%d GOLD": "%d 金幣",
		"%d TICKETS": "%d 張抽卡券",
		"1 TICKET": "1 張抽卡券",
		"%d TURNS": "%d 回合",
		"(She is still waiting.)": "（她還在等。）",
		"(You say nothing.)": "（你什麼也沒說。）",
		"+1 in %d:%02d": "%d:%02d 後 +1",
		"1 PULL · %d CHIPS": "單抽 · %d 籌碼",
		"1 PULL · 1 TICKET": "單抽 · 1 張抽卡券",
		"10 PULL · %d CHIPS": "十連 · %d 籌碼",
		"10 PULL · 10 TICKETS": "十連 · 10 張抽卡券",
		"A card that adds nothing new costs two turns.": "沒有新意的牌要花兩個回合。",
		"AFTER HOURS · CARDS": "打烊之後 · 卡牌",
		"BOND": "羈絆",
		"BOSS": "首領",
		"RIVAL": "對手",
		"BUILD THE DECK FOR THIS NIGHT": "為這一夜組牌",
		"Backend unreachable: ": "連不上伺服器：",
		"Bond is the count of nights won against her. Her plates open at 3 and 10 bond; the rung at 30 is a scene still being written. Nothing here unlocks from time.": "羈絆就是你贏下她的夜數。羈絆 3 和 10 時各解鎖一張插圖；30 那一級是一場還在寫的場景。這裡沒有任何東西靠時間解鎖。",
		"CHARM %d (refills to %d)": "魅力 %d（回覆上限 %d）",
		"CHARM %d/%d": "魅力 %d/%d",
		"CHIPS · %d TICKETS": "籌碼 · %d 張抽卡券",
		"CHIPS · 1 TICKET": "籌碼 · 1 張抽卡券",
		"CLAIM TODAY'S REWARD": "領取今日獎勵",
		"Cancelled.": "已取消。",
		"Celeste's cut: she took your costliest card.": "賽萊斯特插話：她拿走了你最貴的那張牌。",
		"Claimed.": "已領取。",
		"Could not save the deck.": "牌組沒能儲存。",
		"DAILY DUEL FREE": "今日對決免費",
		"Deck saved": "牌組已儲存",
		"Delivered.": "已到賬。",
		"Every %d turns she takes your costliest card.": "每 %d 回合，她會拿走你手裡最貴的牌。",
		"HOLD YOUR TONGUE": "沉默",
		"LAST CALL": "最後一輪",
		"LAST CALL (after the boss)": "最後一輪（擊敗首領後開放）",
		"NIGHT PASS · CLAIM": "夜間通行證 · 領取",
		"PLAY AGAIN · 1 CHARM": "再來一次 · 1 魅力",
		"PLAY · 1 CHARM": "開始 · 1 魅力",
		"Paid in Nutaku gold (100 gold = $1). Everything in the story can be won without it; gold only makes it sooner.": "用 Nutaku 金幣支付（100 金幣 = 1 美元）。故事裡的一切不花錢也能贏到；金幣只是讓它來得更快。",
		"Plate not available offline.": "離線時看不到插圖。",
		"Plate not available.": "插圖暫時無法顯示。",
		"Purchase failed.": "購買失敗。",
		"RESOLVE": "決心",
		"RESOLVE %d": "決心 %d",
		"RESOLVE %d/%d": "決心 %d/%d",
		"SIT DOWN ACROSS FROM HER": "在她對面坐下",
		"WHO YOU HAVE PERSUADED": "你說服過的人",
		"STANDING ★%d": "聲望 ★%d",
		"STORE": "商店",
		"STORY SO FAR": "前情",
		"THE STORY SO FAR": "前情回顧",
		"Say nothing: spend a turn, refill your nerve, draw a fresh hand.": "什麼也不說：用掉一個回合，膽識回滿，換一手新牌。",
		"She has every reason to say no.": "她有一萬個理由拒絕。",
		"She talked straight over it.": "她直接把你的話蓋了過去。",
		"She talks over your first card.": "你的第一張牌，她會直接蓋過去。",
		"THE NIGHT LEDGER": "夜之賬簿",
		"THE NIGHTS": "夜晚",
		"TONIGHT'S REMATCH · FREE": "今晚重賽 · 免費",
		"The purchase did not go through; Nutaku has refunded the gold.": "購買沒有完成；Nutaku 已退還金幣。",
		"The server did not accept this duel: ": "伺服器沒有認可這場對決：",
		"VELL, AFTER TWO": "維爾，凌晨兩點後",
		"Wrong order — she closed the door.": "順序錯了——她關上了門。",
		"You": "你",
		"You hold %d cards.": "你手裡只有 %d 張牌。",
		"at %d bond": "羈絆 %d",
		"at %d wins": "%d 勝時",
		"locked": "未解鎖",
		"needs bond %d with %s (%d)": "需要羈絆 %d（與%s，現有 %d）",
		"needs standing ★%d (%d)": "需要聲望 ★%d（現有 %d）",
		"still to come": "敬請期待",
		"tap to close": "點按關閉",
		"tier %d": "第 %d 級",
		"tier %d · at %d": "第 %d 級 · %d",
		"◆ CHIPS": "◆ 籌碼",
		"♥ BOND  (+%d)": "♥ 羈絆  (+%d)",
		"FOR %s (%s) · SHE HEARS: %s · %d OF YOUR CARDS CAN ACT TONIGHT": "今夜：%s（%s）· 她聽得進：%s · 你有 %d 張牌今晚能起作用",
		"not tonight": "今晚用不上",
		"She will not hear this card tonight: it carries none of what she wants.": "今晚她聽不進這張牌：它不帶她想要的任何東西。",
		"LEDGER": "賬簿",
	},
	"de": {
		# update packs, events, auto-battle, the missing pages (2026-09-24)
		"EVENT: %s": "EVENT: %s",
		"THE MISSING PAGES · %d": "DIE FEHLENDEN SEITEN · %d",
		"THE MISSING PAGES": "DIE FEHLENDEN SEITEN",
		"AUTO ×1 · 1 CHARM": "AUTO ×1 · 1 CHARME",
		"AUTO ×5 · 5 CHARM": "AUTO ×5 · 5 CHARME",
		"Auto: won %d of %d.": "Auto: %d von %d gewonnen.",
		"%d CARDS": "%d KARTEN",
		"ENDS IN %d DAYS": "ENDET IN %d TAGEN",
		"REWARD TRACK": "BELOHNUNGSLEISTE",
		"CLAIM": "ABHOLEN",
		"CLAIMED": "ABGEHOLT",
		"+%d CHARM": "+%d CHARME",
		"%s'S CARD": "KARTE VON %s",
		"+%d %s · %d in all": "+%d %s · %d insgesamt",
		"marks": "Marken",
		"ON: %s · %d DAYS LEFT": "AKTIV: %s · NOCH %d TAGE",
		"BANNER: %s · %d DAYS LEFT": "BANNER: %s · NOCH %d TAGE",
		"TONIGHT": "HEUTE NACHT",
		"DUELS": "DUELLE",
		"GACHA": "GACHA",
		"AFFECTION": "ZUNEIGUNG",
		"DECK": "DECK",
		"RANK": "RANG",
		"GENTLE": "SANFT",
		"SILVER": "SILBER",
		"GOLD": "GOLD",
		"GOLD_TAG": "GOLD",
		"DUEL": "DUELL",
		"DAILY": "TÄGLICH",
		"FREE": "GRATIS",
		"PLAY": "SPIELEN",
		"BACK": "ZURÜCK",
		"NERVE": "NERVEN",
		"MOMENTUM": "SCHWUNG",
		"TURN": "ZUG",
		"DECK LEFT": "IM STAPEL",
		"WILD": "JOKER",
		"FORFEIT": "AUFGEBEN",
		"CONTINUE": "WEITER",
		"PERSUADED": "ÜBERZEUGT",
		"REFUSED": "ABGELEHNT",
		"GUARDED": "VERSCHLOSSEN",
		"ENGAGED": "INTERESSIERT",
		"WAVERING": "SCHWANKEND",
		"BREAKTHROUGH": "DURCHBRUCH",
		"SHE NEEDS": "SIE BRAUCHT",
		"HELPS": "HILFT",
		"ON THE RECORD": "PROTOKOLL",
		"PULL 1": "1× ZIEHEN",
		"PULL 10": "10× ZIEHEN",
		"NEW": "NEU",
		"NO BACKEND — PLAYING OFFLINE": "KEIN BACKEND — OFFLINE-MODUS",
		"Five people, one evening each. Bring a deck; every card is a sentence. The engine reads it. She answers. A duel costs 3 energy; today's is free and pays double affection.": "Fünf Menschen, je ein Abend. Bring ein Deck mit; jede Karte ist ein Satz. Die Engine liest ihn. Sie antwortet. Ein Duell kostet 3 Energie; das heutige ist gratis und bringt doppelte Zuneigung.",
		"Nothing sold changes the turn count or what she needs.": "Nichts, was man kaufen kann, ändert die Zugzahl oder das, was sie braucht.",
		"PRESS ANY KEY": "TASTE DRÜCKEN",
		"LANGUAGE": "SPRACHE",
		"COMMON": "GEWÖHNLICH",
		"RARE": "SELTEN",
		"EPIC": "EPISCH",
		"WILD · once": "JOKER · einmal",
		"Say it in your own words.": "Sag es mit deinen eigenen Worten.",
		"the engine reads it": "die Engine liest es",
		"CLOSED · ": "ZU · ",
		"respect": "Respekt",
		"accountability": "Verantwortung",
		"exchange": "Tausch",
		"evidence": "Beweis",
		"safety": "Sicherheit",
		"empathy": "Empathie",
		"precision": "Präzision",
		"authority": "Autorität",
		"warmth": "Wärme",
		"craft": "Handwerk",
		"specific_praise": "gezieltes Lob",
		"riddle": "Rätsel",
		"calm_action": "ruhiges Handeln",
		"direct_request": "direkte Bitte",
		"cooperation": "Zusammenarbeit",
		"threat": "Drohung",
		"bribe": "Bestechung",
		"insult": "Beleidigung",
		"entitlement": "Anspruchsdenken",
		"TURNS %d/%d": "ZÜGE %d/%d",
		"DECK %d": "DECK %d",
		"LEAVE": "GEHEN",
		"SAY IT": "SAG ES",
		"CLOSED": "ZU",
		"OUT OF WORDS": "KEINE WORTE MEHR",
		"BACK TO THE BAR": "ZUR BAR",
		"SEE THE PLATE": "ZUM BILD",
		"MORE LIKE THIS": "MEHR DAVON",
		"♥ AFFECTION  (+%d)": "♥ ZUNEIGUNG  (+%d)",
		"◆ GOLD": "◆ GOLD",
		"DROP →": "BEUTE →",
		"You have beaten %d%% of players today.": "Du hast heute %d%% der Spieler geschlagen.",
		"Say it in your own words — the engine reads it, nobody else does": "Sag es mit deinen eigenen Worten — die Engine liest es, sonst niemand",
		"TODAY · FREE · ×2 AFFECTION": "HEUTE · GRATIS · ×2 ZUNEIGUNG",
		"DUEL · 3⚡": "DUELL · 3⚡",
		"DAILY · FREE": "TÄGLICH · GRATIS",
		"DAILY DONE": "TÄGLICH ERLEDIGT",
		"GENTLE · 18": "SANFT · 18",
		"SILVER · 15": "SILBER · 15",
		"GOLD · 10": "GOLD · 10",
		"Common 70 · Rare 25 · Epic 5. A ten-pull always holds a rare; every thirtieth pull is an epic. Cards add sentences you can say. They do not change what she needs.": "Gewöhnlich 70 · Selten 25 · Episch 5. Zehn Ziehungen enthalten immer eine seltene Karte; jede dreißigste Ziehung ist episch. Karten geben dir neue Sätze. Sie ändern nicht, was sie braucht.",
		"1 PULL · %d": "1× ZIEHEN · %d",
		"10 PULL · %d": "10× ZIEHEN · %d",
		"PULLS %d · EPIC PITY IN %d · CREDITS %d": "ZIEHUNGEN %d · EPISCH-GARANTIE IN %d · CREDITS %d",
		"DUPE": "DOPPELT",
		"PITY": "GARANTIE",
		"SAVE DECK": "DECK SICHERN",
		"AUTO": "AUTO",
		"Pick up to %d. Copies count. The wild card is always in the deck and never counts.": "Wähle bis zu %d. Kopien zählen. Der Joker ist immer im Deck und zählt nie.",
		"%d/%d in deck": "%d/%d im Deck",
		"Affection is the count of duels won against her. Plates unlock at 1, 3 and 6 wins; the fourth rung at 10 is a scene of Blaze's own and is a placeholder in this build. Nothing here unlocks from time.": "Zuneigung ist die Zahl der gegen sie gewonnenen Duelle. Bilder werden bei 1, 3 und 6 Siegen frei; die vierte Stufe bei 10 ist eine eigene Szene von Blaze und in diesem Build ein Platzhalter. Nichts hier wird durch Zeit freigeschaltet.",
		" — tickets are in the store": " — Tickets gibt es im Shop",
		"%d CHIPS": "%d CHIPS",
		"%d DUPES — already in your collection": "%d DOPPELTE — schon in deiner Sammlung",
		"1 DUPE — already in your collection": "1 DOPPELTE — schon in deiner Sammlung",
		"%d GOLD": "%d GOLD",
		"%d TICKETS": "%d TICKETS",
		"1 TICKET": "1 TICKET",
		"%d TURNS": "%d ZÜGE",
		"(She is still waiting.)": "(Sie wartet immer noch.)",
		"(You say nothing.)": "(Du sagst nichts.)",
		"+1 in %d:%02d": "+1 in %d:%02d",
		"1 PULL · %d CHIPS": "1× ZIEHEN · %d CHIPS",
		"1 PULL · 1 TICKET": "1× ZIEHEN · 1 TICKET",
		"10 PULL · %d CHIPS": "10× ZIEHEN · %d CHIPS",
		"10 PULL · 10 TICKETS": "10× ZIEHEN · 10 TICKETS",
		"A card that adds nothing new costs two turns.": "Eine Karte, die nichts Neues bringt, kostet zwei Züge.",
		"AFTER HOURS · CARDS": "NACH FEIERABEND · KARTEN",
		"BOND": "BINDUNG",
		"BOSS": "BOSS",
		"RIVAL": "RIVALIN",
		"BUILD THE DECK FOR THIS NIGHT": "STELL DAS DECK FÜR DIESE NACHT ZUSAMMEN",
		"Backend unreachable: ": "Backend nicht erreichbar: ",
		"Bond is the count of nights won against her. Her plates open at 3 and 10 bond; the rung at 30 is a scene still being written. Nothing here unlocks from time.": "Bindung ist die Zahl der gegen sie gewonnenen Nächte. Ihre Bilder öffnen sich bei 3 und 10 Bindung; die Stufe bei 30 ist eine Szene, die noch geschrieben wird. Nichts hier wird durch Zeit freigeschaltet.",
		"CHARM %d (refills to %d)": "CHARME %d (lädt bis %d)",
		"CHARM %d/%d": "CHARME %d/%d",
		"CHIPS · %d TICKETS": "CHIPS · %d TICKETS",
		"CHIPS · 1 TICKET": "CHIPS · 1 TICKET",
		"CLAIM TODAY'S REWARD": "HEUTIGE BELOHNUNG ABHOLEN",
		"Cancelled.": "Abgebrochen.",
		"Celeste's cut: she took your costliest card.": "Celestes Anteil: Sie hat deine teuerste Karte genommen.",
		"Claimed.": "Abgeholt.",
		"Could not save the deck.": "Deck konnte nicht gespeichert werden.",
		"DAILY DUEL FREE": "DUELL HEUTE GRATIS",
		"Deck saved": "Deck gesichert",
		"Delivered.": "Zugestellt.",
		"Every %d turns she takes your costliest card.": "Alle %d Züge nimmt sie deine teuerste Karte.",
		"HOLD YOUR TONGUE": "SCHWEIGEN",
		"LAST CALL": "LETZTE RUNDE",
		"LAST CALL (after the boss)": "LETZTE RUNDE (nach dem Boss)",
		"NIGHT PASS · CLAIM": "NACHTPASS · ABHOLEN",
		"PLAY AGAIN · 1 CHARM": "NOCHMAL · 1 CHARME",
		"PLAY · 1 CHARM": "SPIELEN · 1 CHARME",
		"Paid in Nutaku gold (100 gold = $1). Everything in the story can be won without it; gold only makes it sooner.": "Bezahlt mit Nutaku-Gold (100 Gold = 1 $). Alles in der Geschichte lässt sich ohne Gold gewinnen; Gold macht es nur schneller.",
		"Plate not available offline.": "Bild offline nicht verfügbar.",
		"Plate not available.": "Bild nicht verfügbar.",
		"Purchase failed.": "Kauf fehlgeschlagen.",
		"RESOLVE": "WIDERSTAND",
		"RESOLVE %d": "WIDERSTAND %d",
		"RESOLVE %d/%d": "WIDERSTAND %d/%d",
		"SIT DOWN ACROSS FROM HER": "SETZ DICH IHR GEGENÜBER",
		"WHO YOU HAVE PERSUADED": "WEN DU ÜBERZEUGT HAST",
		"STANDING ★%d": "ANSEHEN ★%d",
		"STORE": "SHOP",
		"STORY SO FAR": "BISHER",
		"THE STORY SO FAR": "DIE GESCHICHTE BISHER",
		"Say nothing: spend a turn, refill your nerve, draw a fresh hand.": "Schweigen: einen Zug opfern, Nerven auffüllen, neue Hand ziehen.",
		"She has every reason to say no.": "Sie hat allen Grund, Nein zu sagen.",
		"She talked straight over it.": "Sie hat einfach darüber hinweggeredet.",
		"She talks over your first card.": "Sie redet über deine erste Karte hinweg.",
		"THE NIGHT LEDGER": "DAS NACHTBUCH",
		"THE NIGHTS": "DIE NÄCHTE",
		"TONIGHT'S REMATCH · FREE": "REVANCHE HEUTE · GRATIS",
		"The purchase did not go through; Nutaku has refunded the gold.": "Der Kauf ist nicht durchgegangen; Nutaku hat das Gold erstattet.",
		"The server did not accept this duel: ": "Der Server hat dieses Duell nicht angenommen: ",
		"VELL, AFTER TWO": "VELL, NACH ZWEI",
		"Wrong order — she closed the door.": "Falsche Reihenfolge — sie hat die Tür zugemacht.",
		"You": "Du",
		"You hold %d cards.": "Du hältst %d Karten.",
		"at %d bond": "bei %d Bindung",
		"at %d wins": "bei %d Siegen",
		"locked": "gesperrt",
		"needs bond %d with %s (%d)": "braucht Bindung %d mit %s (%d)",
		"needs standing ★%d (%d)": "braucht Ansehen ★%d (%d)",
		"still to come": "folgt noch",
		"tap to close": "Tippen zum Schließen",
		"tier %d": "Stufe %d",
		"tier %d · at %d": "Stufe %d · bei %d",
		"◆ CHIPS": "◆ CHIPS",
		"♥ BOND  (+%d)": "♥ BINDUNG  (+%d)",
		"FOR %s (%s) · SHE HEARS: %s · %d OF YOUR CARDS CAN ACT TONIGHT": "FÜR %s (%s) · SIE HÖRT: %s · %d DEINER KARTEN WIRKEN HEUTE NACHT",
		"not tonight": "nicht heute",
		"She will not hear this card tonight: it carries none of what she wants.": "Diese Karte hört sie heute nicht: Nichts davon ist, was sie will.",
		"LEDGER": "BUCH",
	},
	"fr": {
		# update packs, events, auto-battle, the missing pages (2026-09-24)
		"EVENT: %s": "ÉVÉNEMENT : %s",
		"THE MISSING PAGES · %d": "LES PAGES MANQUANTES · %d",
		"THE MISSING PAGES": "LES PAGES MANQUANTES",
		"AUTO ×1 · 1 CHARM": "AUTO ×1 · 1 CHARME",
		"AUTO ×5 · 5 CHARM": "AUTO ×5 · 5 CHARME",
		"Auto: won %d of %d.": "Auto : %d victoires sur %d.",
		"%d CARDS": "%d CARTES",
		"ENDS IN %d DAYS": "FIN DANS %d JOURS",
		"REWARD TRACK": "PISTE DE RÉCOMPENSES",
		"CLAIM": "RÉCUPÉRER",
		"CLAIMED": "RÉCUPÉRÉ",
		"+%d CHARM": "+%d CHARME",
		"%s'S CARD": "CARTE DE %s",
		"+%d %s · %d in all": "+%d %s · %d en tout",
		"marks": "marques",
		"ON: %s · %d DAYS LEFT": "ACTIF : %s · %d JOURS RESTANTS",
		"BANNER: %s · %d DAYS LEFT": "BANNIÈRE : %s · %d JOURS RESTANTS",
		"TONIGHT": "CE SOIR",
		"DUELS": "DUELS",
		"GACHA": "GACHA",
		"AFFECTION": "AFFECTION",
		"DECK": "DECK",
		"RANK": "RANG",
		"GENTLE": "DOUX",
		"SILVER": "ARGENT",
		"GOLD": "OR",
		"GOLD_TAG": "OR",
		"DUEL": "DUEL",
		"DAILY": "DU JOUR",
		"FREE": "GRATUIT",
		"PLAY": "JOUER",
		"BACK": "RETOUR",
		"NERVE": "SANG-FROID",
		"MOMENTUM": "ÉLAN",
		"TURN": "TOUR",
		"DECK LEFT": "PIOCHE",
		"WILD": "JOKER",
		"FORFEIT": "ABANDONNER",
		"CONTINUE": "CONTINUER",
		"PERSUADED": "CONVAINCUE",
		"REFUSED": "REFUS",
		"GUARDED": "SUR SES GARDES",
		"ENGAGED": "INTÉRESSÉE",
		"WAVERING": "HÉSITANTE",
		"BREAKTHROUGH": "PERCÉE",
		"SHE NEEDS": "IL LUI FAUT",
		"HELPS": "AIDE",
		"ON THE RECORD": "AU DOSSIER",
		"PULL 1": "1 TIRAGE",
		"PULL 10": "10 TIRAGES",
		"NEW": "NOUVEAU",
		"NO BACKEND — PLAYING OFFLINE": "PAS DE SERVEUR — JEU HORS LIGNE",
		"Five people, one evening each. Bring a deck; every card is a sentence. The engine reads it. She answers. A duel costs 3 energy; today's is free and pays double affection.": "Cinq personnes, une soirée chacune. Apportez un deck ; chaque carte est une phrase. Le moteur la lit. Elle répond. Un duel coûte 3 énergie ; celui du jour est gratuit et rapporte le double d'affection.",
		"Nothing sold changes the turn count or what she needs.": "Rien de ce qui est vendu ne change le nombre de tours ni ce qu'il lui faut.",
		"PRESS ANY KEY": "APPUYEZ SUR UNE TOUCHE",
		"LANGUAGE": "LANGUE",
		"COMMON": "COMMUNE",
		"RARE": "RARE",
		"EPIC": "ÉPIQUE",
		"WILD · once": "JOKER · une fois",
		"Say it in your own words.": "Dites-le avec vos mots.",
		"the engine reads it": "le moteur la lit",
		"CLOSED · ": "FERMÉ · ",
		"respect": "respect",
		"accountability": "responsabilité",
		"exchange": "échange",
		"evidence": "preuve",
		"safety": "sécurité",
		"empathy": "empathie",
		"precision": "précision",
		"authority": "autorité",
		"warmth": "chaleur",
		"craft": "métier",
		"specific_praise": "éloge précis",
		"riddle": "énigme",
		"calm_action": "calme",
		"direct_request": "demande directe",
		"cooperation": "coopération",
		"threat": "menace",
		"bribe": "pot-de-vin",
		"insult": "insulte",
		"entitlement": "prétention",
		"TURNS %d/%d": "TOURS %d/%d",
		"DECK %d": "DECK %d",
		"LEAVE": "PARTIR",
		"SAY IT": "LE DIRE",
		"CLOSED": "FERMÉ",
		"OUT OF WORDS": "À COURT DE MOTS",
		"BACK TO THE BAR": "RETOUR AU BAR",
		"SEE THE PLATE": "VOIR LA PLANCHE",
		"MORE LIKE THIS": "PLUS COMME ÇA",
		"♥ AFFECTION  (+%d)": "♥ AFFECTION  (+%d)",
		"◆ GOLD": "◆ OR",
		"DROP →": "TIRAGE →",
		"You have beaten %d%% of players today.": "Vous avez battu %d%% des joueurs aujourd'hui.",
		"Say it in your own words — the engine reads it, nobody else does": "Dites-le avec vos mots — le moteur le lit, personne d'autre",
		"TODAY · FREE · ×2 AFFECTION": "AUJOURD'HUI · GRATUIT · ×2 AFFECTION",
		"DUEL · 3⚡": "DUEL · 3⚡",
		"DAILY · FREE": "DU JOUR · GRATUIT",
		"DAILY DONE": "DU JOUR FAIT",
		"GENTLE · 18": "DOUX · 18",
		"SILVER · 15": "ARGENT · 15",
		"GOLD · 10": "OR · 10",
		"Common 70 · Rare 25 · Epic 5. A ten-pull always holds a rare; every thirtieth pull is an epic. Cards add sentences you can say. They do not change what she needs.": "Commune 70 · Rare 25 · Épique 5. Dix tirages contiennent toujours une rare ; chaque trentième tirage est une épique. Les cartes ajoutent des phrases à dire. Elles ne changent pas ce qu'il lui faut.",
		"1 PULL · %d": "1 TIRAGE · %d",
		"10 PULL · %d": "10 TIRAGES · %d",
		"PULLS %d · EPIC PITY IN %d · CREDITS %d": "TIRAGES %d · ÉPIQUE GARANTIE DANS %d · CRÉDITS %d",
		"DUPE": "DOUBLON",
		"PITY": "GARANTIE",
		"SAVE DECK": "SAUVER DECK",
		"AUTO": "AUTO",
		"Pick up to %d. Copies count. The wild card is always in the deck and never counts.": "Choisissez jusqu'à %d cartes. Les copies comptent. Le joker est toujours dans le deck et ne compte jamais.",
		"%d/%d in deck": "%d/%d dans le deck",
		"Affection is the count of duels won against her. Plates unlock at 1, 3 and 6 wins; the fourth rung at 10 is a scene of Blaze's own and is a placeholder in this build. Nothing here unlocks from time.": "L'affection est le nombre de duels gagnés contre elle. Les planches se débloquent à 1, 3 et 6 victoires ; le quatrième palier, à 10, est une scène propre à Blaze et reste provisoire dans cette version. Rien ici ne se débloque avec le temps.",
		" — tickets are in the store": " — les tickets sont en boutique",
		"%d CHIPS": "%d JETONS",
		"%d DUPES — already in your collection": "%d DOUBLONS — déjà dans votre collection",
		"1 DUPE — already in your collection": "1 DOUBLON — déjà dans votre collection",
		"%d GOLD": "%d OR",
		"%d TICKETS": "%d TICKETS",
		"1 TICKET": "1 TICKET",
		"%d TURNS": "%d TOURS",
		"(She is still waiting.)": "(Elle attend toujours.)",
		"(You say nothing.)": "(Tu ne dis rien.)",
		"+1 in %d:%02d": "+1 dans %d:%02d",
		"1 PULL · %d CHIPS": "1 TIRAGE · %d JETONS",
		"1 PULL · 1 TICKET": "1 TIRAGE · 1 TICKET",
		"10 PULL · %d CHIPS": "10 TIRAGES · %d JETONS",
		"10 PULL · 10 TICKETS": "10 TIRAGES · 10 TICKETS",
		"A card that adds nothing new costs two turns.": "Une carte qui n'apporte rien de neuf coûte deux tours.",
		"AFTER HOURS · CARDS": "APRÈS MINUIT · CARTES",
		"BOND": "LIEN",
		"BOSS": "BOSS",
		"RIVAL": "RIVALE",
		"BUILD THE DECK FOR THIS NIGHT": "PRÉPARER LE DECK POUR CETTE NUIT",
		"Backend unreachable: ": "Serveur injoignable : ",
		"Bond is the count of nights won against her. Her plates open at 3 and 10 bond; the rung at 30 is a scene still being written. Nothing here unlocks from time.": "Le lien est le nombre de nuits gagnées contre elle. Ses planches s'ouvrent à 3 et 10 de lien ; le palier à 30 est une scène encore en cours d'écriture. Rien ici ne se débloque avec le temps.",
		"CHARM %d (refills to %d)": "CHARME %d (remonte à %d)",
		"CHARM %d/%d": "CHARME %d/%d",
		"CHIPS · %d TICKETS": "JETONS · %d TICKETS",
		"CHIPS · 1 TICKET": "JETONS · 1 TICKET",
		"CLAIM TODAY'S REWARD": "RÉCUPÉRER LE CADEAU DU JOUR",
		"Cancelled.": "Annulé.",
		"Celeste's cut: she took your costliest card.": "La part de Celeste : elle a pris ta carte la plus chère.",
		"Claimed.": "Récupéré.",
		"Could not save the deck.": "Impossible de sauver le deck.",
		"DAILY DUEL FREE": "DUEL DU JOUR GRATUIT",
		"Deck saved": "Deck sauvé",
		"Delivered.": "Livré.",
		"Every %d turns she takes your costliest card.": "Tous les %d tours, elle prend ta carte la plus chère.",
		"HOLD YOUR TONGUE": "SE TAIRE",
		"LAST CALL": "DERNIÈRE TOURNÉE",
		"LAST CALL (after the boss)": "DERNIÈRE TOURNÉE (après le boss)",
		"NIGHT PASS · CLAIM": "PASS NUIT · RÉCUPÉRER",
		"PLAY AGAIN · 1 CHARM": "REJOUER · 1 CHARME",
		"PLAY · 1 CHARM": "JOUER · 1 CHARME",
		"Paid in Nutaku gold (100 gold = $1). Everything in the story can be won without it; gold only makes it sooner.": "Payé en or Nutaku (100 or = 1 $). Tout dans l'histoire peut être gagné sans ; l'or ne fait qu'aller plus vite.",
		"Plate not available offline.": "Planche indisponible hors ligne.",
		"Plate not available.": "Planche indisponible.",
		"Purchase failed.": "Échec de l'achat.",
		"RESOLVE": "RÉSISTANCE",
		"RESOLVE %d": "RÉSISTANCE %d",
		"RESOLVE %d/%d": "RÉSISTANCE %d/%d",
		"SIT DOWN ACROSS FROM HER": "S'ASSEOIR EN FACE D'ELLE",
		"WHO YOU HAVE PERSUADED": "CELLES QUE VOUS AVEZ CONVAINCUES",
		"STANDING ★%d": "RÉPUTATION ★%d",
		"STORE": "BOUTIQUE",
		"STORY SO FAR": "L'HISTOIRE",
		"THE STORY SO FAR": "L'HISTOIRE JUSQU'ICI",
		"Say nothing: spend a turn, refill your nerve, draw a fresh hand.": "Se taire : passer un tour, retrouver ton sang-froid, piocher une nouvelle main.",
		"She has every reason to say no.": "Elle a toutes les raisons de dire non.",
		"She talked straight over it.": "Elle a parlé par-dessus.",
		"She talks over your first card.": "Elle parle par-dessus ta première carte.",
		"THE NIGHT LEDGER": "LE REGISTRE DE NUIT",
		"THE NIGHTS": "LES NUITS",
		"TONIGHT'S REMATCH · FREE": "REVANCHE DE CE SOIR · GRATUITE",
		"The purchase did not go through; Nutaku has refunded the gold.": "L'achat n'a pas abouti ; Nutaku vous a remboursé l'or.",
		"The server did not accept this duel: ": "Le serveur a refusé ce duel : ",
		"VELL, AFTER TWO": "VELL, APRÈS DEUX HEURES",
		"Wrong order — she closed the door.": "Mauvais ordre — elle a fermé la porte.",
		"You": "Toi",
		"You hold %d cards.": "Tu as %d cartes en main.",
		"at %d bond": "à %d de lien",
		"at %d wins": "à %d victoires",
		"locked": "verrouillé",
		"needs bond %d with %s (%d)": "il faut %d de lien avec %s (%d)",
		"needs standing ★%d (%d)": "il faut ★%d de réputation (%d)",
		"still to come": "à venir",
		"tap to close": "Toucher pour fermer",
		"tier %d": "palier %d",
		"tier %d · at %d": "palier %d · à %d",
		"◆ CHIPS": "◆ JETONS",
		"♥ BOND  (+%d)": "♥ LIEN  (+%d)",
		"FOR %s (%s) · SHE HEARS: %s · %d OF YOUR CARDS CAN ACT TONIGHT": "POUR %s (%s) · ELLE ENTEND : %s · %d DE TES CARTES PEUVENT AGIR CE SOIR",
		"not tonight": "pas ce soir",
		"She will not hear this card tonight: it carries none of what she wants.": "Elle n'entendra pas cette carte ce soir : elle ne porte rien de ce qu'elle veut.",
		"LEDGER": "REGISTRE",
	},
	"es": {
		# update packs, events, auto-battle, the missing pages (2026-09-24)
		"EVENT: %s": "EVENTO: %s",
		"THE MISSING PAGES · %d": "LAS PÁGINAS PERDIDAS · %d",
		"THE MISSING PAGES": "LAS PÁGINAS PERDIDAS",
		"AUTO ×1 · 1 CHARM": "AUTO ×1 · 1 ENCANTO",
		"AUTO ×5 · 5 CHARM": "AUTO ×5 · 5 ENCANTO",
		"Auto: won %d of %d.": "Auto: %d victorias de %d.",
		"%d CARDS": "%d CARTAS",
		"ENDS IN %d DAYS": "TERMINA EN %d DÍAS",
		"REWARD TRACK": "PISTA DE PREMIOS",
		"CLAIM": "RECLAMAR",
		"CLAIMED": "RECLAMADO",
		"+%d CHARM": "+%d ENCANTO",
		"%s'S CARD": "CARTA DE %s",
		"+%d %s · %d in all": "+%d %s · %d en total",
		"marks": "marcas",
		"ON: %s · %d DAYS LEFT": "ACTIVO: %s · QUEDAN %d DÍAS",
		"BANNER: %s · %d DAYS LEFT": "BANNER: %s · QUEDAN %d DÍAS",
		"TONIGHT": "ESTA NOCHE",
		"DUELS": "DUELOS",
		"GACHA": "GACHA",
		"AFFECTION": "AFECTO",
		"DECK": "MAZO",
		"RANK": "RANGO",
		"GENTLE": "SUAVE",
		"SILVER": "PLATA",
		"GOLD": "ORO",
		"GOLD_TAG": "ORO",
		"DUEL": "DUELO",
		"DAILY": "DIARIO",
		"FREE": "GRATIS",
		"PLAY": "JUGAR",
		"BACK": "VOLVER",
		"NERVE": "TEMPLE",
		"MOMENTUM": "IMPULSO",
		"TURN": "TURNO",
		"DECK LEFT": "EN MAZO",
		"WILD": "COMODÍN",
		"FORFEIT": "RENDIRSE",
		"CONTINUE": "SEGUIR",
		"PERSUADED": "CONVENCIDA",
		"REFUSED": "RECHAZADO",
		"GUARDED": "RECELOSA",
		"ENGAGED": "INTERESADA",
		"WAVERING": "DUDANDO",
		"BREAKTHROUGH": "AVANCE",
		"SHE NEEDS": "NECESITA",
		"HELPS": "AYUDA",
		"ON THE RECORD": "EN ACTA",
		"PULL 1": "1 TIRADA",
		"PULL 10": "10 TIRADAS",
		"NEW": "NUEVO",
		"NO BACKEND — PLAYING OFFLINE": "SIN SERVIDOR — JUEGO SIN CONEXIÓN",
		"Five people, one evening each. Bring a deck; every card is a sentence. The engine reads it. She answers. A duel costs 3 energy; today's is free and pays double affection.": "Cinco personas, una noche cada una. Trae un mazo; cada carta es una frase. El motor la lee. Ella responde. Un duelo cuesta 3 de energía; el de hoy es gratis y da el doble de afecto.",
		"Nothing sold changes the turn count or what she needs.": "Nada de lo que se vende cambia los turnos ni lo que ella necesita.",
		"PRESS ANY KEY": "PULSA UNA TECLA",
		"LANGUAGE": "IDIOMA",
		"COMMON": "COMÚN",
		"RARE": "RARA",
		"EPIC": "ÉPICA",
		"WILD · once": "COMODÍN · una vez",
		"Say it in your own words.": "Dilo con tus propias palabras.",
		"the engine reads it": "el motor lo lee",
		"CLOSED · ": "CERRADO · ",
		"respect": "respeto",
		"accountability": "responsabilidad",
		"exchange": "intercambio",
		"evidence": "pruebas",
		"safety": "seguridad",
		"empathy": "empatía",
		"precision": "precisión",
		"authority": "autoridad",
		"warmth": "calidez",
		"craft": "oficio",
		"specific_praise": "elogio concreto",
		"riddle": "acertijo",
		"calm_action": "acción serena",
		"direct_request": "petición directa",
		"cooperation": "cooperación",
		"threat": "amenaza",
		"bribe": "soborno",
		"insult": "insulto",
		"entitlement": "prepotencia",
		"TURNS %d/%d": "TURNOS %d/%d",
		"DECK %d": "MAZO %d",
		"LEAVE": "SALIR",
		"SAY IT": "DECIRLO",
		"CLOSED": "CERRADO",
		"OUT OF WORDS": "SIN PALABRAS",
		"BACK TO THE BAR": "AL BAR",
		"SEE THE PLATE": "VER LA LÁMINA",
		"MORE LIKE THIS": "MÁS COMO ESTA",
		"♥ AFFECTION  (+%d)": "♥ AFECTO  (+%d)",
		"◆ GOLD": "◆ ORO",
		"DROP →": "BOTÍN →",
		"You have beaten %d%% of players today.": "Hoy has superado al %d%% de los jugadores.",
		"Say it in your own words — the engine reads it, nobody else does": "Dilo con tus palabras — lo lee el motor, nadie más",
		"TODAY · FREE · ×2 AFFECTION": "HOY · GRATIS · ×2 AFECTO",
		"DUEL · 3⚡": "DUELO · 3⚡",
		"DAILY · FREE": "DIARIO · GRATIS",
		"DAILY DONE": "DIARIO HECHO",
		"GENTLE · 18": "SUAVE · 18",
		"SILVER · 15": "PLATA · 15",
		"GOLD · 10": "ORO · 10",
		"Common 70 · Rare 25 · Epic 5. A ten-pull always holds a rare; every thirtieth pull is an epic. Cards add sentences you can say. They do not change what she needs.": "Común 70 · Rara 25 · Épica 5. Una tirada de diez siempre trae una rara; cada trigésima tirada es épica. Las cartas añaden frases que puedes decir. No cambian lo que ella necesita.",
		"1 PULL · %d": "1 TIRADA · %d",
		"10 PULL · %d": "10 TIRADAS · %d",
		"PULLS %d · EPIC PITY IN %d · CREDITS %d": "TIRADAS %d · ÉPICA GARANTIZADA EN %d · CRÉDITOS %d",
		"DUPE": "REPE",
		"PITY": "GARANTÍA",
		"SAVE DECK": "GUARDAR MAZO",
		"AUTO": "AUTO",
		"Pick up to %d. Copies count. The wild card is always in the deck and never counts.": "Elige hasta %d. Las copias cuentan. El comodín siempre está en el mazo y nunca cuenta.",
		"%d/%d in deck": "%d/%d en el mazo",
		"Affection is the count of duels won against her. Plates unlock at 1, 3 and 6 wins; the fourth rung at 10 is a scene of Blaze's own and is a placeholder in this build. Nothing here unlocks from time.": "El afecto es el número de duelos que le has ganado. Las láminas se desbloquean con 1, 3 y 6 victorias; el cuarto peldaño, a las 10, es una escena propia de Blaze y en esta versión es provisional. Aquí nada se desbloquea con el tiempo.",
		" — tickets are in the store": " — los boletos están en la tienda",
		"%d CHIPS": "%d FICHAS",
		"%d DUPES — already in your collection": "%d REPES — ya en tu colección",
		"1 DUPE — already in your collection": "1 REPE — ya en tu colección",
		"%d GOLD": "%d ORO",
		"%d TICKETS": "%d BOLETOS",
		"1 TICKET": "1 BOLETO",
		"%d TURNS": "%d TURNOS",
		"(She is still waiting.)": "(Ella sigue esperando.)",
		"(You say nothing.)": "(No dices nada.)",
		"+1 in %d:%02d": "+1 en %d:%02d",
		"1 PULL · %d CHIPS": "1 TIRADA · %d FICHAS",
		"1 PULL · 1 TICKET": "1 TIRADA · 1 BOLETO",
		"10 PULL · %d CHIPS": "10 TIRADAS · %d FICHAS",
		"10 PULL · 10 TICKETS": "10 TIRADAS · 10 BOLETOS",
		"A card that adds nothing new costs two turns.": "Una carta que no aporta nada nuevo cuesta dos turnos.",
		"AFTER HOURS · CARDS": "DE MADRUGADA · CARTAS",
		"BOND": "VÍNCULO",
		"BOSS": "JEFA",
		"RIVAL": "RIVAL",
		"BUILD THE DECK FOR THIS NIGHT": "ARMA EL MAZO PARA ESTA NOCHE",
		"Backend unreachable: ": "Servidor inaccesible: ",
		"Bond is the count of nights won against her. Her plates open at 3 and 10 bond; the rung at 30 is a scene still being written. Nothing here unlocks from time.": "El vínculo es el número de noches que le has ganado. Sus láminas se abren con 3 y 10 de vínculo; el peldaño de 30 es una escena que aún se está escribiendo. Aquí nada se desbloquea con el tiempo.",
		"CHARM %d (refills to %d)": "ENCANTO %d (se recarga a %d)",
		"CHARM %d/%d": "ENCANTO %d/%d",
		"CHIPS · %d TICKETS": "FICHAS · %d BOLETOS",
		"CHIPS · 1 TICKET": "FICHAS · 1 BOLETO",
		"CLAIM TODAY'S REWARD": "RECLAMAR PREMIO DE HOY",
		"Cancelled.": "Cancelado.",
		"Celeste's cut: she took your costliest card.": "La tajada de Celeste: se quedó tu carta más cara.",
		"Claimed.": "Reclamado.",
		"Could not save the deck.": "No se pudo guardar el mazo.",
		"DAILY DUEL FREE": "DUELO DIARIO GRATIS",
		"Deck saved": "Mazo guardado",
		"Delivered.": "Entregado.",
		"Every %d turns she takes your costliest card.": "Cada %d turnos se lleva tu carta más cara.",
		"HOLD YOUR TONGUE": "CALLAR",
		"LAST CALL": "ÚLTIMA RONDA",
		"LAST CALL (after the boss)": "ÚLTIMA RONDA (tras la jefa)",
		"NIGHT PASS · CLAIM": "PASE NOCTURNO · RECLAMAR",
		"PLAY AGAIN · 1 CHARM": "OTRA VEZ · 1 ENCANTO",
		"PLAY · 1 CHARM": "JUGAR · 1 ENCANTO",
		"Paid in Nutaku gold (100 gold = $1). Everything in the story can be won without it; gold only makes it sooner.": "Se paga con oro de Nutaku (100 de oro = 1 $). Todo lo de la historia se puede ganar sin él; el oro solo lo adelanta.",
		"Plate not available offline.": "Lámina no disponible sin conexión.",
		"Plate not available.": "Lámina no disponible.",
		"Purchase failed.": "La compra falló.",
		"RESOLVE": "RESISTENCIA",
		"RESOLVE %d": "RESISTENCIA %d",
		"RESOLVE %d/%d": "RESISTENCIA %d/%d",
		"SIT DOWN ACROSS FROM HER": "SIÉNTATE FRENTE A ELLA",
		"WHO YOU HAVE PERSUADED": "A QUIÉN HAS CONVENCIDO",
		"STANDING ★%d": "PRESTIGIO ★%d",
		"STORE": "TIENDA",
		"STORY SO FAR": "LA HISTORIA",
		"THE STORY SO FAR": "LA HISTORIA HASTA AHORA",
		"Say nothing: spend a turn, refill your nerve, draw a fresh hand.": "Callar: gastas un turno, recuperas el temple y robas una mano nueva.",
		"She has every reason to say no.": "Tiene todos los motivos para decir que no.",
		"She talked straight over it.": "Habló por encima sin inmutarse.",
		"She talks over your first card.": "Habla por encima de tu primera carta.",
		"THE NIGHT LEDGER": "EL LIBRO DE LA NOCHE",
		"THE NIGHTS": "LAS NOCHES",
		"TONIGHT'S REMATCH · FREE": "REVANCHA DE ESTA NOCHE · GRATIS",
		"The purchase did not go through; Nutaku has refunded the gold.": "La compra no se completó; Nutaku ha devuelto el oro.",
		"The server did not accept this duel: ": "El servidor no aceptó este duelo: ",
		"VELL, AFTER TWO": "VELL, PASADAS LAS DOS",
		"Wrong order — she closed the door.": "Orden equivocado: te cerró la puerta.",
		"You": "Tú",
		"You hold %d cards.": "Tienes %d cartas.",
		"at %d bond": "vínculo %d",
		"at %d wins": "con %d victorias",
		"locked": "bloqueado",
		"needs bond %d with %s (%d)": "requiere vínculo %d con %s (%d)",
		"needs standing ★%d (%d)": "requiere prestigio ★%d (%d)",
		"still to come": "próximamente",
		"tap to close": "Toca para cerrar",
		"tier %d": "nivel %d",
		"tier %d · at %d": "nivel %d · con %d",
		"◆ CHIPS": "◆ FICHAS",
		"♥ BOND  (+%d)": "♥ VÍNCULO  (+%d)",
		"FOR %s (%s) · SHE HEARS: %s · %d OF YOUR CARDS CAN ACT TONIGHT": "PARA %s (%s) · ELLA ESCUCHA: %s · %d DE TUS CARTAS SIRVEN ESTA NOCHE",
		"not tonight": "esta noche no",
		"She will not hear this card tonight: it carries none of what she wants.": "Esta noche no escuchará esta carta: no lleva nada de lo que ella quiere.",
		"LEDGER": "LIBRO",
	},
	"ko": {
		# update packs, events, auto-battle, the missing pages (2026-09-24)
		"EVENT: %s": "이벤트: %s",
		"THE MISSING PAGES · %d": "사라진 페이지 · %d",
		"THE MISSING PAGES": "사라진 페이지",
		"AUTO ×1 · 1 CHARM": "자동 ×1 · 매력 1",
		"AUTO ×5 · 5 CHARM": "자동 ×5 · 매력 5",
		"Auto: won %d of %d.": "자동: %d승 / %d판.",
		"%d CARDS": "카드 %d장",
		"ENDS IN %d DAYS": "%d일 남음",
		"REWARD TRACK": "보상 트랙",
		"CLAIM": "받기",
		"CLAIMED": "받음",
		"+%d CHARM": "매력 +%d",
		"%s'S CARD": "%s의 카드",
		"+%d %s · %d in all": "+%d %s · 총 %d",
		"marks": "마크",
		"ON: %s · %d DAYS LEFT": "선택됨: %s · %d일 남음",
		"BANNER: %s · %d DAYS LEFT": "배너: %s · %d일 남음",
		"TONIGHT": "오늘 밤",
		"DUELS": "대결",
		"GACHA": "뽑기",
		"AFFECTION": "호감",
		"DECK": "덱",
		"RANK": "랭크",
		"GENTLE": "순한",
		"SILVER": "실버",
		"GOLD": "골드",
		"GOLD_TAG": "골드",
		"DUEL": "대결",
		"DAILY": "일일",
		"FREE": "무료",
		"PLAY": "플레이",
		"BACK": "뒤로",
		"NERVE": "배짱",
		"MOMENTUM": "기세",
		"TURN": "턴",
		"DECK LEFT": "남은 덱",
		"WILD": "와일드",
		"FORFEIT": "포기",
		"CONTINUE": "계속",
		"PERSUADED": "설득 성공",
		"REFUSED": "거절",
		"GUARDED": "경계",
		"ENGAGED": "관심",
		"WAVERING": "흔들림",
		"BREAKTHROUGH": "돌파",
		"SHE NEEDS": "그녀가 원하는 것",
		"HELPS": "도움",
		"ON THE RECORD": "기록",
		"PULL 1": "1회 뽑기",
		"PULL 10": "10연 뽑기",
		"NEW": "신규",
		"NO BACKEND — PLAYING OFFLINE": "서버 없음 — 오프라인 플레이 중",
		"Five people, one evening each. Bring a deck; every card is a sentence. The engine reads it. She answers. A duel costs 3 energy; today's is free and pays double affection.": "다섯 사람, 한 사람당 하룻저녁. 덱을 챙겨라. 카드 한 장이 문장 하나다. 엔진이 읽고, 그녀가 답한다. 대결은 에너지 3을 쓴다. 오늘의 대결은 무료이고 호감이 두 배다.",
		"Nothing sold changes the turn count or what she needs.": "무엇을 사든 턴 수도, 그녀가 원하는 것도 바뀌지 않습니다.",
		"PRESS ANY KEY": "아무 키나 누르세요",
		"LANGUAGE": "언어",
		"COMMON": "일반",
		"RARE": "레어",
		"EPIC": "에픽",
		"WILD · once": "와일드 · 1회",
		"Say it in your own words.": "네 말로 해 봐.",
		"the engine reads it": "엔진이 읽는다",
		"CLOSED · ": "종료 · ",
		"respect": "존중",
		"accountability": "책임",
		"exchange": "거래",
		"evidence": "증거",
		"safety": "안전",
		"empathy": "공감",
		"precision": "정확성",
		"authority": "권위",
		"warmth": "온기",
		"craft": "솜씨",
		"specific_praise": "구체적 칭찬",
		"riddle": "수수께끼",
		"calm_action": "차분한 행동",
		"direct_request": "직접 요청",
		"cooperation": "협력",
		"threat": "협박",
		"bribe": "뇌물",
		"insult": "모욕",
		"entitlement": "특권의식",
		"TURNS %d/%d": "턴 %d/%d",
		"DECK %d": "덱 %d",
		"LEAVE": "떠나기",
		"SAY IT": "말하기",
		"CLOSED": "종료",
		"OUT OF WORDS": "할 말 없음",
		"BACK TO THE BAR": "바로 돌아가기",
		"SEE THE PLATE": "그림 보기",
		"MORE LIKE THIS": "비슷한 작품",
		"♥ AFFECTION  (+%d)": "♥ 호감  (+%d)",
		"◆ GOLD": "◆ 골드",
		"DROP →": "드롭 →",
		"You have beaten %d%% of players today.": "오늘 플레이어의 %d%%를 이겼습니다.",
		"Say it in your own words — the engine reads it, nobody else does": "네 말로 해 봐 — 엔진만 읽고, 다른 누구도 읽지 않는다",
		"TODAY · FREE · ×2 AFFECTION": "오늘 · 무료 · 호감 ×2",
		"DUEL · 3⚡": "대결 · 3⚡",
		"DAILY · FREE": "일일 · 무료",
		"DAILY DONE": "일일 완료",
		"GENTLE · 18": "순한 · 18",
		"SILVER · 15": "실버 · 15",
		"GOLD · 10": "골드 · 10",
		"Common 70 · Rare 25 · Epic 5. A ten-pull always holds a rare; every thirtieth pull is an epic. Cards add sentences you can say. They do not change what she needs.": "일반 70 · 레어 25 · 에픽 5. 10연 뽑기에는 레어가 반드시 하나 들어 있고, 30번째 뽑기마다 에픽이 나옵니다. 카드는 할 수 있는 말을 늘려 줄 뿐, 그녀가 원하는 것은 바꾸지 않습니다.",
		"1 PULL · %d": "1회 뽑기 · %d",
		"10 PULL · %d": "10연 뽑기 · %d",
		"PULLS %d · EPIC PITY IN %d · CREDITS %d": "뽑기 %d · 에픽 천장까지 %d · 크레딧 %d",
		"DUPE": "중복",
		"PITY": "천장",
		"SAVE DECK": "덱 저장",
		"AUTO": "자동",
		"Pick up to %d. Copies count. The wild card is always in the deck and never counts.": "최대 %d장까지 고르세요. 같은 카드도 따로 셉니다. 와일드 카드는 항상 덱에 있으며 장수에 포함되지 않습니다.",
		"%d/%d in deck": "덱에 %d/%d",
		"Affection is the count of duels won against her. Plates unlock at 1, 3 and 6 wins; the fourth rung at 10 is a scene of Blaze's own and is a placeholder in this build. Nothing here unlocks from time.": "호감은 그녀와의 대결에서 이긴 횟수입니다. 1승, 3승, 6승에 그림이 열리고, 10승의 네 번째 단계는 Blaze가 직접 만드는 장면으로 이 빌드에서는 임시입니다. 시간이 지난다고 열리는 것은 없습니다.",
		" — tickets are in the store": " — 티켓은 상점에 있습니다",
		"%d CHIPS": "%d 칩",
		"%d DUPES — already in your collection": "중복 %d장 — 이미 보유 중",
		"1 DUPE — already in your collection": "중복 1장 — 이미 보유 중",
		"%d GOLD": "%d 골드",
		"%d TICKETS": "티켓 %d장",
		"1 TICKET": "티켓 1장",
		"%d TURNS": "%d턴",
		"(She is still waiting.)": "(그녀는 아직 기다리고 있다.)",
		"(You say nothing.)": "(아무 말도 하지 않는다.)",
		"+1 in %d:%02d": "%d:%02d 후 +1",
		"1 PULL · %d CHIPS": "1회 뽑기 · %d 칩",
		"1 PULL · 1 TICKET": "1회 뽑기 · 티켓 1장",
		"10 PULL · %d CHIPS": "10연 뽑기 · %d 칩",
		"10 PULL · 10 TICKETS": "10연 뽑기 · 티켓 10장",
		"A card that adds nothing new costs two turns.": "새로운 것이 없는 카드는 턴 두 개를 잡아먹는다.",
		"AFTER HOURS · CARDS": "애프터 아워즈 · 카드",
		"BOND": "인연",
		"BOSS": "보스",
		"RIVAL": "라이벌",
		"BUILD THE DECK FOR THIS NIGHT": "오늘 밤을 위한 덱 짜기",
		"Backend unreachable: ": "서버에 연결할 수 없습니다: ",
		"Bond is the count of nights won against her. Her plates open at 3 and 10 bond; the rung at 30 is a scene still being written. Nothing here unlocks from time.": "인연은 그녀와의 밤에서 이긴 횟수입니다. 인연 3과 10에 그림이 열리고, 30의 단계는 아직 쓰고 있는 장면입니다. 시간이 지난다고 열리는 것은 없습니다.",
		"CHARM %d (refills to %d)": "매력 %d (%d까지 회복)",
		"CHARM %d/%d": "매력 %d/%d",
		"CHIPS · %d TICKETS": "칩 · 티켓 %d장",
		"CHIPS · 1 TICKET": "칩 · 티켓 1장",
		"CLAIM TODAY'S REWARD": "오늘의 보상 받기",
		"Cancelled.": "취소했습니다.",
		"Celeste's cut: she took your costliest card.": "셀레스트의 몫: 가장 비싼 카드를 가져갔다.",
		"Claimed.": "받았습니다.",
		"Could not save the deck.": "덱을 저장하지 못했습니다.",
		"DAILY DUEL FREE": "일일 대결 무료",
		"Deck saved": "덱 저장 완료",
		"Delivered.": "지급되었습니다.",
		"Every %d turns she takes your costliest card.": "%d턴마다 그녀가 가장 비싼 카드를 가져간다.",
		"HOLD YOUR TONGUE": "입 다물기",
		"LAST CALL": "라스트 콜",
		"LAST CALL (after the boss)": "라스트 콜 (보스 이후)",
		"NIGHT PASS · CLAIM": "나이트 패스 · 받기",
		"PLAY AGAIN · 1 CHARM": "다시 · 매력 1",
		"PLAY · 1 CHARM": "플레이 · 매력 1",
		"Paid in Nutaku gold (100 gold = $1). Everything in the story can be won without it; gold only makes it sooner.": "Nutaku 골드로 결제합니다(100골드 = $1). 스토리의 모든 것은 골드 없이도 얻을 수 있으며, 골드는 시간을 앞당길 뿐입니다.",
		"Plate not available offline.": "오프라인에서는 그림을 볼 수 없습니다.",
		"Plate not available.": "그림을 볼 수 없습니다.",
		"Purchase failed.": "구매에 실패했습니다.",
		"RESOLVE": "결의",
		"RESOLVE %d": "결의 %d",
		"RESOLVE %d/%d": "결의 %d/%d",
		"SIT DOWN ACROSS FROM HER": "그녀의 맞은편에 앉기",
		"WHO YOU HAVE PERSUADED": "설득한 사람들",
		"STANDING ★%d": "명성 ★%d",
		"STORE": "상점",
		"STORY SO FAR": "지난 이야기",
		"THE STORY SO FAR": "지금까지의 이야기",
		"Say nothing: spend a turn, refill your nerve, draw a fresh hand.": "입 다물기: 턴 하나를 쓰고, 배짱을 채우고, 패를 새로 뽑는다.",
		"She has every reason to say no.": "그녀에게는 거절할 이유가 충분하다.",
		"She talked straight over it.": "그녀는 그 말을 그냥 끊고 넘어갔다.",
		"She talks over your first card.": "그녀는 첫 카드를 말을 끊고 넘긴다.",
		"THE NIGHT LEDGER": "밤의 장부",
		"THE NIGHTS": "밤들",
		"TONIGHT'S REMATCH · FREE": "오늘 밤 재대결 · 무료",
		"The purchase did not go through; Nutaku has refunded the gold.": "구매가 완료되지 않았습니다. Nutaku에서 골드를 환불했습니다.",
		"The server did not accept this duel: ": "서버가 이 대결을 받아들이지 않았습니다: ",
		"VELL, AFTER TWO": "벨, 새벽 두 시 이후",
		"Wrong order — she closed the door.": "순서가 틀렸다 — 그녀가 문을 닫았다.",
		"You": "나",
		"You hold %d cards.": "카드 %d장을 들고 있다.",
		"at %d bond": "인연 %d에서",
		"at %d wins": "%d승에서",
		"locked": "잠김",
		"needs bond %d with %s (%d)": "인연 %d 필요: %s (%d)",
		"needs standing ★%d (%d)": "명성 ★%d 필요 (%d)",
		"still to come": "공개 예정",
		"tap to close": "탭하여 닫기",
		"tier %d": "%d단계",
		"tier %d · at %d": "%d단계 · %d에서",
		"◆ CHIPS": "◆ 칩",
		"♥ BOND  (+%d)": "♥ 인연  (+%d)",
		"FOR %s (%s) · SHE HEARS: %s · %d OF YOUR CARDS CAN ACT TONIGHT": "%s (%s) 상대 · 그녀가 듣는 것: %s · 오늘 밤 쓸 수 있는 카드 %d장",
		"not tonight": "오늘은 안 돼",
		"She will not hear this card tonight: it carries none of what she wants.": "이 카드는 오늘 밤 그녀에게 닿지 않는다. 그녀가 원하는 것이 하나도 없다.",
		"LEDGER": "장부",
	},
}


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_code = _restore()
	if FileAccess.file_exists(CAMPAIGN):
		var f := FileAccess.open(CAMPAIGN, FileAccess.READ)
		var d = JSON.parse_string(f.get_as_text())
		if typeof(d) == TYPE_DICTIONARY:
			_campaign = d


func code() -> String:
	return _code


## Server-sent translations for words newer than this build (F2P.strings): added under
## what the build already has, never over it.
func merge(c: String, table: Dictionary) -> void:
	if not _campaign.has(c):
		_campaign[c] = {}
	var mine: Dictionary = _campaign[c]
	for k in table:
		if not mine.has(k):
			mine[k] = table[k]


func set_code(c: String) -> void:
	if c == _code:
		return
	for row in LANGS:
		if row["code"] == c:
			_code = c
			_persist(c)
			changed.emit(c)
			return


func next() -> void:
	var i := 0
	for n in LANGS.size():
		if LANGS[n]["code"] == _code:
			i = n
	set_code(str(LANGS[(i + 1) % LANGS.size()]["code"]))


func name_of(c: String) -> String:
	for row in LANGS:
		if row["code"] == c:
			return str(row["name"])
	return c


## Translate one chrome string. English falls through, and so does any key a language has
## not got — which shows up on screen as English rather than as an empty label.
func t(s: String) -> String:
	if _code == "en" or s == "":
		return s
	var chrome: Dictionary = T.get(_code, {})
	if chrome.has(s):
		return str(chrome[s])
	var camp: Dictionary = _campaign.get(_code, _campaign.get("zh", {}) if _code == "zh-Hant" else {})
	if camp.has(s):
		return str(camp[s])
	# a server line with numbers in it ("too fast (0.4s for 6 plays)"): its template
	var nums := _num.search_all(s)
	if not nums.is_empty():
		var tmpl := _num.sub(s, "%s", true)
		var tr = chrome.get(tmpl, camp.get(tmpl, null))
		if tr != null:
			var args := []
			for m in nums:
				args.append(m.get_string())
			return str(tr) % args
	return s


## Server text (anything the title server sent): the same table. A separate name only so
## the call sites say what they are translating.
func s(text) -> String:
	return t(str(text))


func _restore() -> String:
	var cfg := ConfigFile.new()
	if cfg.load(SAVE) == OK:
		var c := str(cfg.get_value("loc", "code", ""))
		for row in LANGS:
			if row["code"] == c:
				return c
	# No choice yet: follow the browser or the OS, but only into a language we have.
	var sys := OS.get_locale()
	if OS.has_feature("web"):
		var r = JavaScriptBridge.eval("(navigator.language||\"en\")")
		if r != null:
			sys = str(r)
	sys = sys.replace("_", "-")
	var low := sys.to_lower()
	if low.begins_with("zh"):
		return "zh-Hant" if (low.contains("hant") or low.contains("tw") or low.contains("hk") or low.contains("mo")) else "zh"
	for c in ["ja", "de", "fr", "es", "ko"]:
		if low.begins_with(c):
			return c
	return "en"


func _persist(c: String) -> void:
	var cfg := ConfigFile.new()
	cfg.set_value("loc", "code", c)
	cfg.save(SAVE)
