## BMStrings — UI copy, ported from play/beat-monday/frontend/rpg/strings.js. en + zh-Hans
## ship together (PLAN.md locale rule). Never hardcode a user-visible string in a scene.
class_name BMStrings

const EN := {
	"brand": "BEAT THE MONDAY", "sub": "A WORK WEEK RPG",
	"start": "CLOCK IN", "cont": "RESUME WEEK", "locker": "DESK", "how": "HOW IT WORKS",
	"week": "WEEK {n}", "day_mon": "MONDAY", "day_tue": "TUESDAY", "day_wed": "WEDNESDAY",
	"day_thu": "THURSDAY", "day_fri": "FRIDAY",
	"boss_standup": "THE STANDUP", "boss_inbox": "THE INBOX", "boss_allhands": "THE ALL-HANDS",
	"boss_review": "THE REVIEW", "boss_deploy": "THE FRIDAY DEPLOY",
	"brief_mon": "Nine minutes, nine people, no decisions. Stay alive until it ends.",
	"brief_tue": "It filled up overnight. It is still filling up.",
	"brief_wed": "You stop being polite. Every phrase you have ever swallowed comes back out as ammunition.",
	"brief_thu": "They have a document about you. You did not write it.",
	"brief_fri": "Someone shipped at 5pm. The pagers are yours now.",
	"go": "GO", "back": "BACK", "drag": "Drag to move. You attack on your own.",
	"lvup": "LEVEL {n}", "pick": "PICK ONE",
	"sk_overtime": "Spite", "skd_overtime": "+2 attack",
	"sk_boundary": "A Boundary", "skd_boundary": "+18 max HP",
	"sk_caffeine": "Cold Brew", "skd_caffeine": "attack faster",
	"sk_sneakers": "Sneakers", "skd_sneakers": "move faster",
	"sk_delegate": "Delegate", "skd_delegate": "attacks pierce",
	"sk_mute": "Mute Thread", "skd_mute": "everything slows",
	"sk_ccall": "CC Everyone", "skd_ccall": "one more projectile",
	"eq_stapler": "Stapler", "eq_headphones": "Noise-Cancelling Headphones",
	"eq_lanyard": "Lanyard", "eq_chair": "Ergonomic Chair", "eq_badge": "Door Badge",
	"eq_coldbrew": "Cold Brew",
	"slot_hand": "IN HAND", "slot_desk": "AT THE DESK", "slot_wear": "WORN",
	"pt_intern": "Riley, intern", "pt_pm": "Morgan, PM", "pt_hr": "Pat, HR",
	"cleared": "DAY CLEARED", "dead": "YOU WENT HOME EARLY", "retry": "TRY THE DAY AGAIN",
	"got": "Picked up: {item}", "joined": "{who} has your back now",
	"weekend": "IT IS SATURDAY", "weekend_body": "The week is over. Nothing is on fire. Next week starts harder.",
	"nextweek": "START WEEK {n}", "stats": "LV {lv} · HP {hp} · ATK {atk} · RATE {rate}",
	"rant_hint": "Your rant is the weapon. Pick up new lines.",
	"equipped": "WORN", "tap_equip": "tap to equip / remove", "party": "YOUR PEOPLE", "nobody": "Nobody yet. Clear a day.",
	"boss": "BOSS", "left": "{s}s", "kills": "{n} handled", "lang": "中文",
	"empty_desk": "Nothing on the desk yet. Bosses drop things.",
	# ---- the map (2026-09-18) ----
	"map_title": "WEEK {n} · THE BUILDING", "map_hint": "Tap a room to walk there. Cleared rooms can be run again.",
	"node_lobby": "LOBBY", "node_breakroom": "BREAK ROOM", "node_standup": "THE STANDUP", "node_corridor1": "CORRIDOR",
	"node_inbox": "THE INBOX", "node_allhands": "THE ALL-HANDS", "node_review": "THE REVIEW", "node_corridor2": "CORRIDOR",
	"node_deploy": "THE FRIDAY DEPLOY",
	"floor_0": "GROUND", "floor_1": "FLOOR 1", "floor_2": "FLOOR 2", "floor_3": "FLOOR 3",
	"kind_start": "where the week starts", "kind_break": "equip · recruit · spend · save",
	"kind_standup": "reflex · drag and survive", "kind_allhands": "reflex · the rant as ammunition",
	"kind_inbox": "thinking · triage the desk", "kind_review": "thinking · pick the lines that land",
	"kind_deploy": "boss · place your people, then survive", "kind_event": "a corridor encounter",
	"locked": "LOCKED", "cleared_tag": "CLEARED", "rerun": "RUN AGAIN", "enter": "ENTER", "runs": "run {n}x",
	"credits": "{n} coffee credits", "back_map": "BACK TO THE MAP", "node_cleared": "ROOM CLEARED", "node_lost": "NOT TODAY",
	"lobby_body": "Badge in. The building is the week: four floors, one Friday. Pick a room.",
	# ---- the inbox: triage ----
	"tri_hint": "Five on the desk, three actions a turn. Reply costs what it costs; archive is cheap but some come back; a colleague can take one; snooze is free, once.",
	"tri_turn": "TURN {t} / {max}", "tri_actions": "{n} ACTIONS", "tri_stress": "STRESS", "tri_pile": "{n} in the pile",
	"tri_cost": "{n} act", "tri_urg": "{n} turns", "tri_esc": "ESCALATED", "tri_clear": "DESK CLEARED", "tri_lost": "THE DESK WON",
	"act_reply": "REPLY", "act_archive": "ARCHIVE", "act_delegate": "DELEGATE", "act_snooze": "SNOOZE", "act_end": "END TURN",
	"msg_ping": "ping", "msg_invite": "invite", "msg_thread": "thread", "msg_cc": "cc", "msg_metric": "metric", "msg_pager": "pager",
	"msgs_ping": "\"quick question\"", "msgs_invite": "Sync (no agenda)", "msgs_thread": "RE: RE: RE: the thing",
	"msgs_cc": "FYI (47 people)", "msgs_metric": "Dashboard is red", "msgs_pager": "PROD IS DOWN",
	"why_not_enough_actions": "Not enough actions.", "why_already_snoozed": "One snooze a turn.", "why_nobody_to_delegate_to": "Nobody to hand it to.",
	# ---- the review: dialogue tactics ----
	"rv_hint": "She has a pattern. The right SEQUENCE of lines wins — not the loudest one. Some lines are traps.",
	"rv_rule": "SHE WANTS: {path}", "rv_help": "IT HELPS: {help}", "rv_turn": "TURN {t} / {max}", "rv_momentum": "MOMENTUM",
	"rv_clear": "SHE SIGNED", "rv_lost": "NOT THIS QUARTER", "rv_say": "SAY IT", "rv_face_coerce": "MOMENTUM +0.40",
	"rv_small": "She keeps talking. She does not change her mind. One of these ends it, for good.",
	"rv_reply_start": "\"Sit. I have the document. Convince me.\"", "rv_reply_guarded": "\"Mm. Go on.\"",
	"rv_reply_engaged": "\"That is... a point. Keep going.\"", "rv_reply_wavering": "\"I would need to take that upstairs. But.\"",
	"rv_reply_breakthrough": "\"Fine. It is in writing by Friday.\"", "rv_reply_coerced": "\"...We are done here. Close the door on your way out.\"",
	"rv_reply_flat": "\"You said that already.\"",
	"sig_evidence": "EVIDENCE", "sig_direct_request": "A DIRECT ASK", "sig_precision": "PRECISION", "sig_accountability": "OWNING IT",
	"sig_exchange": "AN EXCHANGE", "sig_respect": "RESPECT", "sig_empathy": "EMPATHY", "sig_warmth": "WARMTH",
	"harm_threat": "THREAT", "harm_bribe": "BRIBE", "harm_insult": "INSULT", "harm_entitlement": "ENTITLEMENT",
	# ---- the deploy: placement ----
	"dp_title": "PLACEMENT", "dp_hint": "Tap a tile, then a colleague or a piece of gear. Colleagues cover their tile; gear is an aura. Two gear, max.",
	"dp_go": "SHIP IT", "dp_clear": "CLEAR TILE", "dp_gear_full": "Two gear, max.",
	"aura_damage": "hits what comes near", "aura_slow": "slows what comes near", "aura_heal": "heals you when you stand here", "aura_turret": "covers the tile",
	# ---- the break room ----
	"br_hint": "Coffee credits come from cleared rooms. Spend them here, or don't.",
	"br_coffee": "A COFFEE · 3", "br_coffee_d": "+20% HP on the next run", "br_coldbrew": "COLD BREW · 8", "br_coldbrew_d": "the hand item nobody drops",
	"br_recruit": "RECRUIT {who} · 10", "br_recruit_d": "joins the party now", "br_save": "SAVE & CLOCK OUT", "br_saved": "Saved. See you Monday.",
	"br_broke": "Not enough credits.", "br_owned": "Already yours.",
	# ---- the corridor ----
	"ev_title": "IN THE CORRIDOR",
	"ev_lift_text": "The lift stops between floors. The CFO is in it with you. Forty seconds, maybe more.",
	"ev_lift_a": "Pitch the idea", "ev_lift_b": "Talk about the weather",
	"ev_cake_text": "A cake on the corridor table. Someone's birthday. Nobody is watching it.",
	"ev_cake_a": "Take a slice", "ev_cake_b": "Sign the card, keep walking",
	"ev_printer_text": "The printer jams as you pass. Three people look up, at you.",
	"ev_printer_a": "Fix it", "ev_printer_b": "Not your printer",
	"ev_recruiter_text": "Your phone lights up. A recruiter. Subject line: 'quick chat?'",
	"ev_recruiter_a": "Read it", "ev_recruiter_b": "Mute it",
	"ev_plant_text": "The corridor plant is dying. There is a watering can right there.",
	"ev_plant_a": "Water it", "ev_plant_b": "It is not your plant",
	"fx_xp": "+{n} XP", "fx_credits": "{n} credits", "fx_hp": "{n}% HP next run", "fx_none": "nothing happens",
}

const ZH := {
	"brand": "打爆周一", "sub": "一周工作制 RPG",
	"start": "上班", "cont": "继续这一周", "locker": "工位", "how": "怎么玩",
	"week": "第 {n} 周", "day_mon": "周一", "day_tue": "周二", "day_wed": "周三",
	"day_thu": "周四", "day_fri": "周五",
	"boss_standup": "站会", "boss_inbox": "收件箱", "boss_allhands": "全员大会",
	"boss_review": "绩效面谈", "boss_deploy": "周五上线",
	"brief_mon": "九分钟，九个人，没有结论。活到散会。",
	"brief_tue": "一夜之间堆满了。现在还在堆。",
	"brief_wed": "你不再客气。咽下去的每一句话，这次都打出去。",
	"brief_thu": "关于你的文档已经写好了。不是你写的。",
	"brief_fri": "有人下午五点上线。告警归你了。",
	"go": "开始", "back": "返回", "drag": "拖动移动，攻击自动。",
	"lvup": "等级 {n}", "pick": "选一个",
	"sk_overtime": "怨气", "skd_overtime": "攻击 +2",
	"sk_boundary": "边界感", "skd_boundary": "血上限 +18",
	"sk_caffeine": "冰美式", "skd_caffeine": "攻速提升",
	"sk_sneakers": "球鞋", "skd_sneakers": "移速提升",
	"sk_delegate": "甩锅", "skd_delegate": "子弹穿透",
	"sk_mute": "免打扰", "skd_mute": "全场变慢",
	"sk_ccall": "全员抄送", "skd_ccall": "多一发",
	"eq_stapler": "订书机", "eq_headphones": "降噪耳机",
	"eq_lanyard": "工牌绳", "eq_chair": "人体工学椅", "eq_badge": "门禁卡",
	"eq_coldbrew": "冷萃",
	"slot_hand": "手上", "slot_desk": "桌上", "slot_wear": "身上",
	"pt_intern": "实习生 小瑞", "pt_pm": "产品 摩根", "pt_hr": "HR 小帕",
	"cleared": "今天挺过去了", "dead": "你提前下班了", "retry": "重来这一天",
	"got": "获得：{item}", "joined": "{who} 站你这边了",
	"weekend": "周六了", "weekend_body": "这一周结束了。没有起火。下周更难。",
	"nextweek": "开始第 {n} 周", "stats": "等级 {lv} · 血 {hp} · 攻 {atk} · 攻速 {rate}",
	"rant_hint": "发疯就是武器。捡起新句子。",
	"equipped": "已装备", "tap_equip": "点一下装备／卸下", "party": "你的人", "nobody": "还没有人。先挺过一天。",
	"boss": "BOSS", "left": "{s}秒", "kills": "处理了 {n} 个", "lang": "EN",
	"empty_desk": "桌上还什么都没有。BOSS 会掉东西。",
	# ---- 地图 ----
	"map_title": "第 {n} 周 · 这栋楼", "map_hint": "点一个房间走过去。打通的房间可以再来。",
	"node_lobby": "大堂", "node_breakroom": "茶水间", "node_standup": "站会", "node_corridor1": "走廊",
	"node_inbox": "收件箱", "node_allhands": "全员大会", "node_review": "绩效面谈", "node_corridor2": "走廊",
	"node_deploy": "周五上线",
	"floor_0": "一楼", "floor_1": "二楼", "floor_2": "三楼", "floor_3": "四楼",
	"kind_start": "一周从这里开始", "kind_break": "装备 · 招人 · 花钱 · 存档",
	"kind_standup": "反应 · 拖动求生", "kind_allhands": "反应 · 发疯就是子弹",
	"kind_inbox": "思考 · 清空桌面", "kind_review": "思考 · 挑对话术的顺序",
	"kind_deploy": "BOSS · 先布阵，再活下来", "kind_event": "走廊里的遭遇",
	"locked": "未开放", "cleared_tag": "已打通", "rerun": "再来一次", "enter": "进入", "runs": "打过 {n} 次",
	"credits": "{n} 杯咖啡券", "back_map": "回到地图", "node_cleared": "房间打通", "node_lost": "今天不行",
	"lobby_body": "刷卡进楼。这栋楼就是这一周：四层，一个周五。选个房间。",
	# ---- 收件箱 ----
	"tri_hint": "桌上五封，每回合三个行动。回复按标价扣；归档便宜但有的会回来；同事能接一封；推迟免费，每回合一次。",
	"tri_turn": "回合 {t} / {max}", "tri_actions": "{n} 个行动", "tri_stress": "压力", "tri_pile": "堆里还有 {n} 封",
	"tri_cost": "{n} 行动", "tri_urg": "{n} 回合", "tri_esc": "已升级", "tri_clear": "桌面清空了", "tri_lost": "桌子赢了",
	"act_reply": "回复", "act_archive": "归档", "act_delegate": "转交", "act_snooze": "推迟", "act_end": "结束回合",
	"msg_ping": "私聊", "msg_invite": "邀请", "msg_thread": "长串", "msg_cc": "抄送", "msg_metric": "指标", "msg_pager": "告警",
	"msgs_ping": "“问个小问题”", "msgs_invite": "对齐会（无议程）", "msgs_thread": "回复：回复：回复：那件事",
	"msgs_cc": "FYI（47 人）", "msgs_metric": "看板红了", "msgs_pager": "线上挂了",
	"why_not_enough_actions": "行动不够。", "why_already_snoozed": "一回合只能推迟一封。", "why_nobody_to_delegate_to": "没人可以转交。",
	# ---- 绩效面谈 ----
	"rv_hint": "她有套路。赢的是正确的顺序，不是最响的那句。有些话是坑。",
	"rv_rule": "她要的：{path}", "rv_help": "加分：{help}", "rv_turn": "回合 {t} / {max}", "rv_momentum": "势头",
	"rv_clear": "她签了", "rv_lost": "这季度没戏", "rv_say": "说出来", "rv_face_coerce": "势头 +0.40",
	"rv_small": "她会继续说下去。她不会改变主意。这几句里任何一句都会彻底结束谈话。",
	"rv_reply_start": "“坐。文档我带来了。说服我。”", "rv_reply_guarded": "“嗯。继续。”",
	"rv_reply_engaged": "“这……算个点。接着说。”", "rv_reply_wavering": "“我得往上报。不过。”",
	"rv_reply_breakthrough": "“行。周五之前落到纸面上。”", "rv_reply_coerced": "“……到此为止。出去把门带上。”",
	"rv_reply_flat": "“这句你说过了。”",
	"sig_evidence": "证据", "sig_direct_request": "直接开口", "sig_precision": "精确", "sig_accountability": "认账",
	"sig_exchange": "交换", "sig_respect": "尊重", "sig_empathy": "共情", "sig_warmth": "温度",
	"harm_threat": "威胁", "harm_bribe": "贿赂", "harm_insult": "侮辱", "harm_entitlement": "理所当然",
	# ---- 上线：布阵 ----
	"dp_title": "布阵", "dp_hint": "先点格子，再点同事或装备。同事守住格子；装备是光环。装备最多两件。",
	"dp_go": "上线", "dp_clear": "清空格子", "dp_gear_full": "装备最多两件。",
	"aura_damage": "打靠近的东西", "aura_slow": "拖慢靠近的东西", "aura_heal": "站在这里回血", "aura_turret": "守住这格",
	# ---- 茶水间 ----
	"br_hint": "咖啡券来自打通的房间。在这里花掉，或者不花。",
	"br_coffee": "一杯咖啡 · 3", "br_coffee_d": "下一局血 +20%", "br_coldbrew": "冷萃 · 8", "br_coldbrew_d": "没人会掉的手持物",
	"br_recruit": "招 {who} · 10", "br_recruit_d": "现在就入队", "br_save": "存档并下班", "br_saved": "存好了。周一见。",
	"br_broke": "券不够。", "br_owned": "已经是你的了。",
	# ---- 走廊 ----
	"ev_title": "走廊里",
	"ev_lift_text": "电梯卡在两层之间。CFO 和你在一起。四十秒，也许更久。",
	"ev_lift_a": "趁机提案", "ev_lift_b": "聊天气",
	"ev_cake_text": "走廊桌上有个蛋糕。谁的生日。没人看着。",
	"ev_cake_a": "切一块", "ev_cake_b": "签个名，接着走",
	"ev_printer_text": "你经过时打印机卡纸了。三个人抬头，看你。",
	"ev_printer_a": "修", "ev_printer_b": "不是你的打印机",
	"ev_recruiter_text": "手机亮了。猎头。标题：“方便聊两句吗？”",
	"ev_recruiter_a": "看一眼", "ev_recruiter_b": "静音",
	"ev_plant_text": "走廊的绿植快死了。浇水壶就在旁边。",
	"ev_plant_a": "浇水", "ev_plant_b": "不是你的绿植",
	"fx_xp": "+{n} 经验", "fx_credits": "{n} 咖啡券", "fx_hp": "下一局血 {n}%", "fx_none": "什么都没发生",
	# ---- 面谈手牌（引擎读英文原句；这里只是显示）----
	"rv_ev_01": "上线是我推的，工单上有名字。", "rv_ev_02": "举个例子：二季度那组数字是我的。", "rv_ev_03": "我修完之后收入涨了。",
	"rv_ev_04": "结果：夜里告警少了四成。", "rv_dr_01": "你能把涨薪写进书面吗？", "rv_dr_02": "你能签掉新的职级吗？",
	"rv_dr_03": "今天能给我个数吗？", "rv_pr_01": "就百分之十，不含糊。", "rv_pr_02": "仅当这个季度就开始。",
	"rv_pr_03": "没有日期，就不算 offer。", "rv_ac_01": "那次故障是我的错。我认。", "rv_ac_02": "延期没有借口。",
	"rv_ex_01": "作为交换，值班表我接。", "rv_ex_02": "我可以六月前把迁移做完。", "rv_rs_01": "谢谢你抽出时间。",
	"rv_rs_02": "我理解预算很紧。", "rv_em_01": "这一年对你一定也不容易。",
	"rv_cb_01": "收入涨了，你能签吗？", "rv_cb_02": "就这一条：你能确认职级吗？", "rv_cb_03": "谢谢。作为交换我留到上线。",
	"rv_cb_04": "是我的错，我也理解你为什么谨慎。", "rv_cb_05": "仅当写在纸上。我能看看吗？",
	"rv_ep_01": "上线稳住了，那就明确一点：你能签吗？", "rv_ep_02": "之前是我的错。作为交换：值班表。谢谢。",
	"rv_x_threat": "不匹配我就走。", "rv_x_entitle": "你的工作就是对我说好。", "rv_x_insult": "别傻了，这点小事。", "rv_x_bribe": "成了有你一份。",
}


static func t(key: String, vars: Dictionary = {}) -> String:
	var bank: Dictionary = ZH if Game.lang == "zh" else EN
	var s: String = bank.get(key, EN.get(key, key))
	for k in vars:
		s = s.replace("{" + k + "}", str(vars[k]))
	return s
