## BMStrings — After Six's copy. Same key names as the day game (main.gd is a fork and
## reads the same keys), re-meant for the night: a node is a person and what they want;
## the inbox is her desk; the review is the confrontation; the standup is the security
## round. en + zh-Hans ship together (PLAN.md locale rule). Never hardcode a user-visible
## string in a scene.
##
## The fiction keeps the DLsite golden tags where they fit (ops/adult_forks/beat_monday_map.md
## §2): the scene is part of the node system (戦闘エロ), the night rule rewrites what is
## normal (常識改変), colleagues with history (同居/幼なじみ), her offer (色仕掛け), the
## building after hours (退廃/背徳), the state she comes back in (トランス/暗示). Everyone is
## an adult and everything is consensual in the fiction — she comes back on her own.
class_name BMStrings

const EN := {
	"brand": "AFTER SIX", "sub": "AFTER SIX, THEY ANSWER TO YOU.",
	"rating": "18+ · FLAT 404",
	"start": "TAKE THE CHAIR", "cont": "BACK INTO THE BUILDING", "locker": "WHAT YOU KEPT ON THEM", "how": "HOW IT WORKS",
	"week": "NIGHT {n}", "day_mon": "THE SECURITY ROUND", "day_tue": "HER DESK", "day_wed": "THE LAST TRAIN",
	"day_thu": "THE CONFRONTATION", "day_fri": "THE SERVER ROOM, 2AM",
	"boss_standup": "THE NIGHT GUARD", "boss_inbox": "HER DESK", "boss_allhands": "THE LAST TRAIN",
	"boss_review": "MIRA, FINANCE", "boss_deploy": "THE CFO",
	"brief_mon": "The guard does his round at 6:40. Torch, radio, every door. Stay out of the beam until he is back in the lobby.",
	"brief_tue": "Mira's desk. She left at six like everyone else. The drawer did not.",
	"brief_wed": "The last train is 23:52. Everyone who stayed is on the platform. Nobody is polite at 23:52.",
	"brief_thu": "She knows you have it. She is in the glass room, and she asked for you by name.",
	"brief_fri": "The CFO is on the seventh floor at 2am with the server-room badge. Take it, and the floor is yours.",
	"go": "GO", "back": "BACK", "drag": "Drag to move. You attack on your own.",
	"lvup": "LEVEL {n}", "pick": "PICK ONE",
	"sk_overtime": "Grudge", "skd_overtime": "+2 attack",
	"sk_boundary": "A Locked Door", "skd_boundary": "+18 max HP",
	"sk_caffeine": "Espresso, Double", "skd_caffeine": "attack faster",
	"sk_sneakers": "Soft Soles", "skd_sneakers": "move faster",
	"sk_delegate": "Someone Else's Badge", "skd_delegate": "attacks pierce",
	"sk_mute": "Radio Silence", "skd_mute": "everything slows",
	"sk_ccall": "Two Phones", "skd_ccall": "one more projectile",
	"eq_stapler": "Letter Opener", "eq_headphones": "Earpiece",
	"eq_lanyard": "Someone's Lanyard", "eq_chair": "Her Chair", "eq_badge": "Server-Room Badge",
	"eq_coldbrew": "Espresso, Double",
	"slot_hand": "IN HAND", "slot_desk": "IN THE DRAWER", "slot_wear": "WORN",
	"pt_intern": "Riley, the intern who stays", "pt_pm": "Morgan, who owes you", "pt_hr": "Pat, who keeps the files",
	"cleared": "THE FLOOR IS CLEAR", "dead": "THE GUARD WALKED YOU OUT", "retry": "TRY THE ROUND AGAIN",
	"got": "Picked up: {item}", "joined": "{who} is in it with you now",
	"weekend": "IT IS 6AM", "weekend_body": "The cleaners are in. Nobody knows. Tomorrow night the building runs on your rules a little more.",
	"nextweek": "NIGHT {n}", "stats": "LV {lv} · HP {hp} · ATK {atk} · RATE {rate}",
	"rant_hint": "Everything you swallowed today is ammunition tonight.",
	"equipped": "WORN", "tap_equip": "tap to equip / remove", "party": "WHO IS IN IT WITH YOU", "nobody": "Nobody yet. Clear a room.",
	"boss": "BOSS", "left": "{s}s", "kills": "{n} handled", "lang": "中文",
	"empty_desk": "Nothing in the drawer yet. The night drops things.",
	# ---- the map: the same building, relit ----
	"map_title": "NIGHT {n} · 18:40", "map_hint": "Only a few windows are on. Tap a lit room: someone is still in it.",
	"map_here": "STILL IN THE BUILDING",
	"node_lobby": "LOBBY", "node_breakroom": "BREAK ROOM", "node_standup": "THE SECURITY ROUND", "node_corridor1": "CORRIDOR",
	"node_inbox": "HER DESK · THE CASE", "node_allhands": "THE LAST TRAIN", "node_review": "THE SEVENTH FLOOR", "node_corridor2": "CORRIDOR",
	"node_deploy": "THE SERVER ROOM, 2AM",
	"who_lobby": "the guard, at the desk", "who_breakroom": "Riley, not going home", "who_standup": "the guard, on his round",
	"who_corridor1": "nobody · a door ajar", "who_inbox": "Mira's lamp is on", "who_allhands": "everyone who stayed",
	"who_review": "the CFO, still here", "who_corridor2": "a phone ringing in an empty office", "who_deploy": "the CFO, with the badge",
	"floor_0": "GROUND", "floor_1": "FLOOR 1", "floor_2": "FLOOR 2", "floor_3": "FLOOR 3",
	"kind_start": "where the night starts", "kind_break": "equip · recruit · spend · save",
	"kind_standup": "reflex · stay out of the beam", "kind_allhands": "reflex · the platform at 23:52",
	"kind_inbox": "the case · search, assemble, confront", "kind_review": "thinking · aim it at the real target",
	"kind_deploy": "boss · place your people, then survive", "kind_event": "a corridor encounter",
	"locked": "DARK", "cleared_tag": "DONE", "rerun": "GO BACK IN", "enter": "ENTER", "runs": "run {n}x",
	"credits": "{n} favours", "back_map": "BACK TO THE BUILDING", "node_cleared": "ROOM CLEARED", "node_lost": "NOT TONIGHT",
	"lobby_body": "18:40. Badge out, lights half off. By day you survive them. After six you get even. Pick a lit window.",
	# ---- the case, part one: her desk (triage, pointed at evidence) ----
	"tri_hint": "Five things on her desk, three moves before the guard passes. BAG what proves it; SHRED what proves nothing; some things come back angrier; a friend can carry one; LATER is free, once.",
	"tri_turn": "PASS {t} / {max}", "tri_actions": "{n} MOVES", "tri_stress": "NOISE", "tri_pile": "{n} still in the drawer",
	"tri_cost": "{n} moves", "tri_urg": "{n} passes", "tri_esc": "FLAGGED", "tri_clear": "LEVERAGE ASSEMBLED", "tri_lost": "THE GUARD HEARD YOU",
	"act_reply": "BAG IT", "act_archive": "SHRED", "act_delegate": "HAND OFF", "act_snooze": "LATER", "act_end": "LET HIM PASS",
	"msg_ping": "receipt", "msg_invite": "calendar", "msg_thread": "thread", "msg_cc": "cc", "msg_metric": "ledger", "msg_pager": "burner",
	"msgs_ping": "A hotel receipt, company card", "msgs_invite": "\"Dinner — vendor\" · every Thursday", "msgs_thread": "RE: RE: the invoice that isn't",
	"msgs_cc": "CC: nobody who should be", "msgs_metric": "A second ledger, in pencil", "msgs_pager": "A phone that is not her phone",
	"why_not_enough_actions": "Not enough moves.", "why_already_snoozed": "One LATER a pass.", "why_nobody_to_delegate_to": "Nobody to hand it to.",
	# ---- the case, part two: the confrontation (the tactics engine pointed at exposure) ----
	"rv_hint": "She has a pattern. The right SEQUENCE exposes her — not the loudest line. Threats and bribes end it: you would just be them.",
	"rv_rule": "WHAT LANDS: {path}", "rv_help": "IT HELPS: {help}", "rv_turn": "TURN {t} / {max}", "rv_momentum": "PRESSURE",
	"rv_clear": "SHE KNOWS YOU HAVE IT", "rv_lost": "SHE WALKED", "rv_say": "SAY IT", "rv_face_coerce": "PRESSURE +0.40",
	"rv_small": "She keeps talking. She does not fold. One of these ends it, for good — and makes you the one who did it to her.",
	"rv_reply_start": "\"You asked for the glass room. Fine. Say what you think you have.\"", "rv_reply_guarded": "\"Mm. Go on.\"",
	"rv_reply_engaged": "\"...That is a real number. Where did you get that number.\"", "rv_reply_wavering": "\"If that goes upstairs I am finished. You know that.\"",
	"rv_reply_breakthrough": "\"Okay. Okay. What do you want.\"", "rv_reply_coerced": "\"...There it is. You are exactly like him. Get out.\"",
	"rv_reply_flat": "\"You said that already.\"",
	"sig_evidence": "EVIDENCE", "sig_direct_request": "THE ASK", "sig_precision": "PRECISION", "sig_accountability": "OWNING IT",
	"sig_exchange": "AN EXCHANGE", "sig_respect": "RESPECT", "sig_empathy": "EMPATHY", "sig_warmth": "WARMTH",
	"harm_threat": "THREAT", "harm_bribe": "BRIBE", "harm_insult": "INSULT", "harm_entitlement": "ENTITLEMENT",
	# ---- the offer scene (beat_monday_map.md §2.2) ----
	"of_title": "THE OFFER", "of_her": "Mira",
	"of_line": "She closes the blinds. \"I know what a second ledger looks like to Legal. So. You have never once looked at me by day; I have noticed you not looking. Keep it in the bag and I stay. Tonight. Any night. That is the deal.\"",
	"of_small": "Would she still come if you had nothing on her? Right now the honest answer is no.",
	"of_accept": "TAKE THE DEAL", "of_refuse": "REFUSE — THE LEDGER IS THE CFO'S", "of_drop": "PUT IT DOWN",
	"of_accept_res": "You took it. She gave it. Nothing in the room changed hands but fear, and you have become the man whose name is on the ledger. The building goes dark. No scene.",
	"of_refuse_res": "\"It isn't your ledger. The handwriting is his. I am taking it to the seventh floor, and I am taking you out of it.\" She does not say thank you. She unlocks the door and leaves it open.",
	"of_drop_res": "You put the bag on her desk and walk out. She does not understand it yet. She will.",
	"of_accept_tag": "THE WEAKER FANTASY", "of_refuse_tag": "THE RIGHT MOVE", "of_drop_tag": "THE QUIET MOVE",
	# ---- the return (the scene the rule makes visible) ----
	"rt_title": "23:40 · YOUR DESK", "rt_body": "The building is nearly empty. She comes down the dark stairwell on her own, no bag, no ledger, and stops at your desk. \"You held the knife and you did not use it. Nobody does that here.\" She is not asking for anything. She is not offering a deal. That is the whole point of her being here.",
	"rt_cg": "cg_return_x · TIER 3", "rt_unlock": "SEE IT", "rt_locked": "THE PLATE IS CENSORED ON THE FREE TRACK", "rt_unavail": "NO SPONSOR SERVED — STILL CENSORED", "rt_skip": "LATER",
	"rt_after": "She leaves before the cleaners come. She will be back tomorrow night, and not because of anything in the bag.",
	"rt_note": "Consensual, in the fiction and in the mechanics: the scene arrives after the leverage is put down, never because of it.",
	# ---- clear / the board ----
	"cl_title": "THE NIGHT IS YOURS", "cl_body": "The guard is back at the desk, the case is on the seventh floor, and someone came down the stairs on her own. The building runs on your rules until six.",
	"cl_more": "MORE NIGHTS LIKE THIS", "cl_go": "CLOSE THE NIGHT", "cl_hint": "Case done and the round survived: the building is yours. Close the night when you are ready.",
	# ---- the seventh floor: the second confrontation, the real target ----
	"sv_hint": "The CFO. Same engine, harder rule: precision lands, threats end it.",
	"sv_clear": "HE SIGNED HIS OWN NAME", "sv_lost": "HE CALLED SECURITY",
	# ---- the deploy: placement ----
	"dp_title": "PLACEMENT", "dp_hint": "Tap a tile, then a colleague or a piece of gear. Colleagues cover their tile; gear is an aura. Two gear, max.",
	"dp_go": "GO IN", "dp_clear": "CLEAR TILE", "dp_gear_full": "Two gear, max.",
	"aura_damage": "hits what comes near", "aura_slow": "slows what comes near", "aura_heal": "heals you when you stand here", "aura_turret": "covers the tile",
	# ---- the break room ----
	"br_hint": "Favours come from cleared rooms. Spend them here, or don't.",
	"br_coffee": "A COFFEE · 3", "br_coffee_d": "+20% HP on the next run", "br_coldbrew": "ESPRESSO · 8", "br_coldbrew_d": "the hand item nobody drops",
	"br_recruit": "BRING IN {who} · 10", "br_recruit_d": "in it with you now", "br_save": "SAVE & SLIP OUT", "br_saved": "Saved. Tomorrow night.",
	"br_broke": "Not enough favours.", "br_owned": "Already yours.",
	# ---- the corridor ----
	"ev_title": "IN THE CORRIDOR",
	"ev_lift_text": "The lift stops between floors. The CFO is in it with you. He does not know you yet. Forty seconds.",
	"ev_lift_a": "Say his ledger's name", "ev_lift_b": "Talk about the weather",
	"ev_cake_text": "Someone's leaving cake on the corridor table. Nobody is watching it. Nobody is watching anything.",
	"ev_cake_a": "Take a slice", "ev_cake_b": "Keep walking",
	"ev_printer_text": "The printer wakes as you pass and prints one page. Not yours. Three names on it.",
	"ev_printer_a": "Take the page", "ev_printer_b": "Not your printer",
	"ev_recruiter_text": "Your phone lights up. A recruiter. Subject line: 'quick chat?' It is 22:10.",
	"ev_recruiter_a": "Read it", "ev_recruiter_b": "Mute it",
	"ev_plant_text": "The corridor plant is dying under one strip light. There is a watering can right there.",
	"ev_plant_a": "Water it", "ev_plant_b": "It is not your plant",
	"fx_xp": "+{n} XP", "fx_credits": "{n} favours", "fx_hp": "{n}% HP next run", "fx_none": "nothing happens",
}

const ZH := {
	"brand": "六点之后", "sub": "六点之后，他们听你的。",
	"rating": "18+ · FLAT 404",
	"start": "坐上那把椅子", "cont": "回到楼里", "locker": "你攥着的东西", "how": "怎么玩",
	"week": "第 {n} 夜", "day_mon": "保安巡楼", "day_tue": "她的桌子", "day_wed": "末班车",
	"day_thu": "对质", "day_fri": "凌晨两点的机房",
	"boss_standup": "夜班保安", "boss_inbox": "她的桌子", "boss_allhands": "末班车",
	"boss_review": "米拉，财务", "boss_deploy": "CFO",
	"brief_mon": "保安六点四十巡楼。手电，对讲机，每一扇门。躲开光束，直到他回到大堂。",
	"brief_tue": "米拉的桌子。她六点走的，和所有人一样。抽屉没走。",
	"brief_wed": "末班车 23:52。留下来的人都在站台上。23:52 没人客气。",
	"brief_thu": "她知道你拿到了。她在玻璃房里，点名要见你。",
	"brief_fri": "凌晨两点，CFO 在七楼，机房门禁在他身上。拿到它，这层就是你的。",
	"go": "开始", "back": "返回", "drag": "拖动移动，攻击自动。",
	"lvup": "等级 {n}", "pick": "选一个",
	"sk_overtime": "记仇", "skd_overtime": "攻击 +2",
	"sk_boundary": "反锁的门", "skd_boundary": "血上限 +18",
	"sk_caffeine": "双份浓缩", "skd_caffeine": "攻速提升",
	"sk_sneakers": "软底鞋", "skd_sneakers": "移速提升",
	"sk_delegate": "别人的工牌", "skd_delegate": "子弹穿透",
	"sk_mute": "无线电静默", "skd_mute": "全场变慢",
	"sk_ccall": "两部手机", "skd_ccall": "多一发",
	"eq_stapler": "拆信刀", "eq_headphones": "耳机",
	"eq_lanyard": "别人的工牌绳", "eq_chair": "她的椅子", "eq_badge": "机房门禁",
	"eq_coldbrew": "双份浓缩",
	"slot_hand": "手上", "slot_desk": "抽屉里", "slot_wear": "身上",
	"pt_intern": "小瑞，不回家的实习生", "pt_pm": "摩根，欠你的", "pt_hr": "小帕，管档案的",
	"cleared": "这层清了", "dead": "保安把你送出去了", "retry": "再来一轮",
	"got": "获得：{item}", "joined": "{who} 现在和你一起了",
	"weekend": "早上六点", "weekend_body": "保洁进来了。没人知道。明晚这栋楼会更听你的一点。",
	"nextweek": "第 {n} 夜", "stats": "等级 {lv} · 血 {hp} · 攻 {atk} · 攻速 {rate}",
	"rant_hint": "白天咽下去的每一句，今晚都是子弹。",
	"equipped": "已装备", "tap_equip": "点一下装备／卸下", "party": "和你一起的人", "nobody": "还没有人。先清一个房间。",
	"boss": "BOSS", "left": "{s}秒", "kills": "处理了 {n} 个", "lang": "EN",
	"empty_desk": "抽屉里还什么都没有。夜里会掉东西。",
	"map_title": "第 {n} 夜 · 18:40", "map_hint": "只有几扇窗亮着。点亮着的房间：里面还有人。",
	"map_here": "还在楼里",
	"node_lobby": "大堂", "node_breakroom": "茶水间", "node_standup": "保安巡楼", "node_corridor1": "走廊",
	"node_inbox": "她的桌子 · 案子", "node_allhands": "末班车", "node_review": "七楼", "node_corridor2": "走廊",
	"node_deploy": "凌晨两点的机房",
	"who_lobby": "保安，在前台", "who_breakroom": "小瑞，不回家", "who_standup": "保安，在巡楼",
	"who_corridor1": "没人 · 一扇虚掩的门", "who_inbox": "米拉的台灯亮着", "who_allhands": "所有留下来的人",
	"who_review": "CFO，还在", "who_corridor2": "空办公室里电话在响", "who_deploy": "CFO，带着门禁",
	"floor_0": "一楼", "floor_1": "二楼", "floor_2": "三楼", "floor_3": "四楼",
	"kind_start": "夜从这里开始", "kind_break": "装备 · 拉人 · 花钱 · 存档",
	"kind_standup": "反应 · 躲开光束", "kind_allhands": "反应 · 23:52 的站台",
	"kind_inbox": "案子 · 搜、拼、对质", "kind_review": "思考 · 对准真正的目标",
	"kind_deploy": "BOSS · 先布阵，再活下来", "kind_event": "走廊里的遭遇",
	"locked": "黑着", "cleared_tag": "完成", "rerun": "再进去", "enter": "进入", "runs": "打过 {n} 次",
	"credits": "{n} 个人情", "back_map": "回到楼里", "node_cleared": "房间清了", "node_lost": "今晚不行",
	"lobby_body": "18:40。工牌收起来，灯关了一半。白天你熬过他们，六点之后你讨回来。选一扇亮着的窗。",
	"tri_hint": "她桌上五样东西，保安路过前三步。装袋能证明的；撕掉证明不了的；有些会更凶地回来；朋友能带走一样；稍后免费，一次。",
	"tri_turn": "第 {t} / {max} 趟", "tri_actions": "{n} 步", "tri_stress": "动静", "tri_pile": "抽屉里还有 {n} 样",
	"tri_cost": "{n} 步", "tri_urg": "{n} 趟", "tri_esc": "被盯上", "tri_clear": "把柄拼齐了", "tri_lost": "保安听见了",
	"act_reply": "装袋", "act_archive": "撕掉", "act_delegate": "交出去", "act_snooze": "稍后", "act_end": "让他过去",
	"msg_ping": "收据", "msg_invite": "日程", "msg_thread": "长串", "msg_cc": "抄送", "msg_metric": "账本", "msg_pager": "黑手机",
	"msgs_ping": "酒店收据，公司卡", "msgs_invite": "“晚餐——供应商”· 每周四", "msgs_thread": "回复：回复：那张不存在的发票",
	"msgs_cc": "抄送：一个该在的人都没有", "msgs_metric": "第二本账，铅笔写的", "msgs_pager": "一部不是她的手机",
	"why_not_enough_actions": "步数不够。", "why_already_snoozed": "一趟只能稍后一次。", "why_nobody_to_delegate_to": "没人可以交。",
	"rv_hint": "她有套路。对的顺序才揭得开她——不是最响的那句。威胁和贿赂会结束一切：你就成了他们。",
	"rv_rule": "有用的：{path}", "rv_help": "加分：{help}", "rv_turn": "回合 {t} / {max}", "rv_momentum": "压力",
	"rv_clear": "她知道你拿到了", "rv_lost": "她走了", "rv_say": "说出来", "rv_face_coerce": "压力 +0.40",
	"rv_small": "她会继续说。她不会认。这几句里任何一句都会彻底结束——也让你变成对她下手的那个人。",
	"rv_reply_start": "“你要玻璃房。好。说说你以为你有什么。”", "rv_reply_guarded": "“嗯。继续。”",
	"rv_reply_engaged": "“……这个数是真的。你从哪拿到这个数。”", "rv_reply_wavering": "“这要是上去了我就完了。你知道的。”",
	"rv_reply_breakthrough": "“好。好。你想要什么。”", "rv_reply_coerced": "“……就是这样。你和他一模一样。出去。”",
	"rv_reply_flat": "“这句你说过了。”",
	"sig_evidence": "证据", "sig_direct_request": "开口要", "sig_precision": "精确", "sig_accountability": "认账",
	"sig_exchange": "交换", "sig_respect": "尊重", "sig_empathy": "共情", "sig_warmth": "温度",
	"harm_threat": "威胁", "harm_bribe": "贿赂", "harm_insult": "侮辱", "harm_entitlement": "理所当然",
	"of_title": "她的提议", "of_her": "米拉",
	"of_line": "她拉上百叶。“我知道第二本账在法务眼里是什么。所以。你白天从来不看我；我注意到你不看。东西留在袋子里，我留下。今晚。哪晚都行。就这么定。”",
	"of_small": "如果你手里什么都没有，她还会来吗？此刻诚实的答案是：不会。",
	"of_accept": "接受", "of_refuse": "拒绝——账本是 CFO 的", "of_drop": "放下",
	"of_accept_res": "你接了。她给了。屋里换手的只有恐惧，而你成了账本上那个名字。楼黑了。没有画面。",
	"of_refuse_res": "“不是你的账本。字迹是他的。我拿去七楼，我把你从里面摘出来。”她没说谢谢。她开了门锁，把门留着。",
	"of_drop_res": "你把袋子放回她桌上，走出去。她现在还不明白。她会明白的。",
	"of_accept_tag": "更弱的幻想", "of_refuse_tag": "对的一步", "of_drop_tag": "安静的一步",
	"rt_title": "23:40 · 你的桌子", "rt_body": "楼快空了。她自己从黑着的楼梯下来，没有袋子，没有账本，停在你桌前。“你握着刀，没用。这里没人这样。”她没在要什么。她没在谈条件。她在这里，就是全部的意思。",
	"rt_cg": "cg_return_x · 三级", "rt_unlock": "看", "rt_locked": "免费版本这张图打了码", "rt_unavail": "没有播出赞助——仍然打码", "rt_skip": "稍后",
	"rt_after": "她在保洁来之前走了。明晚她还会来，和袋子里的东西无关。",
	"rt_note": "剧情与机制都是自愿的：画面在放下把柄之后到来，从不因为把柄。",
	"cl_title": "今晚是你的", "cl_body": "保安回了前台，案子上了七楼，有人自己从楼梯下来了。到六点前这栋楼按你的规矩走。",
	"cl_more": "更多这样的夜", "cl_go": "收工", "cl_hint": "案子结了，巡楼躲过了：楼是你的。准备好了就收工。",
	"sv_hint": "CFO。同一套引擎，更硬的规矩：精确有用，威胁结束一切。",
	"sv_clear": "他签了自己的名字", "sv_lost": "他叫了保安",
	"dp_title": "布阵", "dp_hint": "先点格子，再点同事或装备。同事守住格子；装备是光环。装备最多两件。",
	"dp_go": "进去", "dp_clear": "清空格子", "dp_gear_full": "装备最多两件。",
	"aura_damage": "打靠近的东西", "aura_slow": "拖慢靠近的东西", "aura_heal": "站在这里回血", "aura_turret": "守住这格",
	"br_hint": "人情来自清掉的房间。在这里花，或者不花。",
	"br_coffee": "一杯咖啡 · 3", "br_coffee_d": "下一局血 +20%", "br_coldbrew": "浓缩 · 8", "br_coldbrew_d": "没人会掉的手持物",
	"br_recruit": "拉 {who} · 10", "br_recruit_d": "现在就和你一起", "br_save": "存档溜走", "br_saved": "存好了。明晚。",
	"br_broke": "人情不够。", "br_owned": "已经是你的了。",
	"ev_title": "走廊里",
	"ev_lift_text": "电梯卡在两层之间。CFO 和你在一起。他还不认识你。四十秒。",
	"ev_lift_a": "说出他账本的名字", "ev_lift_b": "聊天气",
	"ev_cake_text": "走廊桌上有离职蛋糕。没人看着。没人看着任何东西。",
	"ev_cake_a": "切一块", "ev_cake_b": "接着走",
	"ev_printer_text": "你经过时打印机醒了，打了一页。不是你的。上面三个名字。",
	"ev_printer_a": "拿走那页", "ev_printer_b": "不是你的打印机",
	"ev_recruiter_text": "手机亮了。猎头。标题：“方便聊两句吗？”现在 22:10。",
	"ev_recruiter_a": "看一眼", "ev_recruiter_b": "静音",
	"ev_plant_text": "走廊绿植在一根灯管下快死了。浇水壶就在旁边。",
	"ev_plant_a": "浇水", "ev_plant_b": "不是你的绿植",
	"fx_xp": "+{n} 经验", "fx_credits": "{n} 人情", "fx_hp": "下一局血 {n}%", "fx_none": "什么都没发生",
	# ---- 对质手牌（引擎读英文原句；这里只是显示）----
	"rv_ev_01": "因为那笔钱走的是你的卡，收据上有名字。", "rv_ev_02": "举个例子：每周四的“供应商晚餐”。", "rv_ev_03": "那张发票之后收入少了一笔。",
	"rv_ev_04": "结果：铅笔写的第二本账，四十页。", "rv_dr_01": "你能告诉我账是谁让你记的吗？", "rv_dr_02": "你能把他的名字说出来吗？",
	"rv_dr_03": "你今晚能把那部手机给我吗？", "rv_pr_01": "就那一本账，别的我不要。", "rv_pr_02": "仅当你今晚说出来。",
	"rv_pr_03": "没有他的名字，这就只是你的账本。", "rv_ac_01": "我白天从来没看过你。我的错。我认。", "rv_ac_02": "我翻你桌子，没有借口。",
	"rv_ex_01": "作为交换，你的名字不进七楼。", "rv_ex_02": "我可以周五前把它交上去——不带你。", "rv_rs_01": "谢谢你留下来。",
	"rv_rs_02": "我理解你为什么记那本账。", "rv_em_01": "你一定很难受，替他记这个。",
	"rv_cb_01": "因为收据在，你能说出他的名字吗？", "rv_cb_02": "就这一条：你能确认字迹是他的吗？", "rv_cb_03": "谢谢。作为交换我把你摘出去。",
	"rv_cb_04": "是我的错，我也理解你为什么怕。", "rv_cb_05": "仅当是他的名字。你能给我看吗？",
	"rv_ep_01": "因为账本是他的字，那就明确一点：你能说吗？", "rv_ep_02": "之前是我的错。作为交换：你不进去。谢谢。",
	"rv_x_threat": "说，否则我举报你。", "rv_x_entitle": "你必须给我，这是你的工作。", "rv_x_insult": "别傻了，你早就完了。", "rv_x_bribe": "成了，塞钱给你。",
}


static func t(key: String, vars: Dictionary = {}) -> String:
	var bank: Dictionary = ZH if Game.lang == "zh" else EN
	var s: String = bank.get(key, EN.get(key, key))
	for k in vars:
		s = s.replace("{" + k + "}", str(vars[k]))
	return s
